### ISSUE TITLE
Debugging Non-Node Language Server

### ISSUE THREAD

**Issue by yxrkt** [microsoft/language-server-protocol#1005]
I'm trying to set up a non-node language server that's being launched as a process. My process is getting the initialize message through stdin, but when I write the response to stdout, nothing happens--no 'initialized' notification, and no more messages coming in through stdin.

Is there a way for me to see what's making it back to the client? Any documentation suggestions for debugging something like this?

**Comment by yxrkt** [comment]
Okay, so it turns out that appending a '\n' character to the stdout in C++ _actually_ sneaks in a '\r' before appending the '\n' (Windows only). So, if you tried to write the string "\r\n\r\n", what you would actually end up writing is "\r\r\n\r\r\n".

Still, if there are any useful logs being produced on the client side somewhere I'd love to know about it.

**Comment by lextm** [comment]
What language do you use to write this language server? By using an existing framework (from another language server), you can avoid troubleshooting such issues.

**Comment by yxrkt** [comment]
I'm using C++. I have some of the C++ language server projects on my machine and I've been using them as a reference, but each one is pretty massive and comes with a lot of dependencies. Right now, I have a single one-header-file dependency (C++ json library) and a bunch of code generated from the lsp spec page + quicktype. Quick and dirty, but it's working pretty well for me so far.
