### ISSUE TITLE
Should workspace/configuration be allowed during initialize?

### ISSUE THREAD

**Issue by bmewburn** [microsoft/language-server-protocol#1006]
My language server sends a `workspace/configuration` request upon receiving the `initialized` notification. For the most part this works well but for a couple of configuration options the server doesn't get the values early enough.

While the server is waiting for the `workspace/configuration` request/response a `didOpen` notification may happen and the server may enter a state based on a default set of options. When the `workspace/configuration` response is received then it can be costly to then correct the server state based on the actual configuration values.

I could put these certain configuration options in `initializationOptions` but it would be good to manage all configuration in one area. Having the ability to pull configuration from the client before declaring that the server is ready would be useful in this case.

**Comment by matklad** [comment]
I think this is the dupe https://github.com/microsoft/language-server-protocol/issues/567. The TL;RD is that there's no good answer for this at the moment. What I do in rust-ananalyzer is that I send the whole `rust-analyzer` section of the config as a part of `initializationOptions` (Ie, I don't distinguish between late and early options).

**Comment by bmewburn** [comment]
Thanks, will close this one then.
