### ISSUE TITLE
Goto Type Definition should probably use range and not just position

### ISSUE THREAD

**Issue by matklad** [microsoft/language-server-protocol#1007]
At the moment, goto type definition is specked to use `TextDocumentPositionParams`:

https://microsoft.github.io/language-server-protocol/specification#textDocument_typeDefinition

I think it is reasonable to use `Range`, and not just position, for this request. I imagine a user might want to use "extend selection" to select an expression (like `foo.bar.baz.foo()`), and then "goto type definition" to get to the type of the result.

**Comment by dbaeumer** [comment]
Dups #1029
