### ISSUE TITLE
Add "additionalData" field to textDocument/completion request

### ISSUE THREAD

**Issue by HaoboGu** [microsoft/language-server-protocol#1009]
In current protocol, the context information in textDocument/completion request param contains only TextDocumentPosition info and optional `CompletionContext`, which specifies the info about trigger. 

However, when the client requests completion result, it can provide context information. Hence, I propose to add `data` field to `CompletionContext`, which provides additional completion context information:

```typescript
/**
 * Contains additional information about the context in which a completion request is triggered.
 */
export interface CompletionContext {
	/**
	 * How the completion was triggered.
	 */
	triggerKind: CompletionTriggerKind;

	/**
	 * The trigger character (a single character) that has trigger code complete.
	 * Is undefined if `triggerKind !== CompletionTriggerKind.TriggerCharacter`
	 */
	triggerCharacter?: string;

	/**
	 * The data that contains more information about the context of completion request
	 */
	data?: any;
}
```

Here is an example about the benefits of this proposal:

Suppose that I am writing an extension for auto-completion, whose backend server is a LSP server. I want to add symbols in current file as the completion result. In current protocol, I have to implement the whole complex calculation process which responses `document/symbol` request in server. 

If I have the `data` field in completion request, we can just use the symbols calculated by other LSP server, and reuse it in my extension by just caching it in extension and pass it to my completion server. This would be great, making me concentrate on my task - the auto completion task.

Any suggestions or questions are welcome :-)

**Comment by mickaelistria** [comment]
I'm skeptical that we should add some `any` field everywhere. Such fields can easily open the door to quadratic N*M integration cost as they would contain server-specific data that each client would need to handle.
Currently, one can implement in the client a generic way to improve the workflow you mention, and that would work for all clients; with your proposal, there is high probability that this starts relying on server-specific id and others and the client implementation becomes server specific.
If we can identify such smart workflows that we can better implement with LSP, and add some more typed and clearly spec'd fields to cover that, it would IMO be much more profitable.

**Comment by puremourning** [comment]
> If we can identify such smart workflows that we can better implement with LSP, and add some more typed and clearly spec'd fields to cover that, it would IMO be much more profitable.

100% agree

**Comment by HaoboGu** [comment]
I agree with you that `any` field brings too many possibilities. How about narrow the range of what can be passed from client to server? In my case, all I need are document symbols, which is actually the result of `document/symbol` request. 

BTW, it is difficult to take advantage of other language servers in current LSP framework.

**Comment by puremourning** [comment]
sending all symbols in a document on every keystroke is a potentially significant amount of additional data. if the server is the one supplying the document/symbols response, then it should already know/be able to calculate this, right?  unclear what the use case is here but its unlikely that many clients would implement this.

**Comment by HaoboGu** [comment]
> if the server is the one supplying the document/symbols response, then it should already know/be able to calculate this, right? 

Yes, you're right. If a server is able to calculate the symbols, this field is redundant. 

But I want to concentrate on my completion task, and do not want to write the complex symbol calculation. Is there any good solution to borrow the result from other language server according to current LSP?
