### ISSUE TITLE
How to invoke a language server from command line? 

### ISSUE THREAD

**Issue by Gauteab** [microsoft/language-server-protocol#1023]
I would like to query a language server from a cli utility, but I am having a hard time making first contact. How can I go about doing this? Are there any examples of "standalone" lsp clients (not part of a editor extension)?

**Comment by rcjsuen** [comment]
> I would like to query a language server from a cli utility, but I am having a hard time making first contact. How can I go about doing this?

@Gauteab Do you know how the language server communicates with the client? Sockets or stdin/stdout or something else?

> Are there any examples of "standalone" lsp clients (not part of a editor extension)?

If you are familiar with TypeScript I have a few (very rudimentary) examples in my language server's [`README.md`](https://github.com/rcjsuen/dockerfile-language-server-nodejs/blob/fa6f8516ebd3afd6f4d1d43e6c118954223656f0/README.md#communicating-with-the-server) file that may get you started.

You can also try looking at my [`server.test.ts` file](https://github.com/rcjsuen/dockerfile-language-server-nodejs/blob/fa6f8516ebd3afd6f4d1d43e6c118954223656f0/test/server.test.ts) I suppose.

**Comment by Gauteab** [comment]
@rcjsuen Thank you! This was very helpful and I have enough to get started now :)
