### ISSUE TITLE
Vi-Việt Nam!

### ISSUE THREAD

**Issue by AMAZALK** [microsoft/language-server-protocol#1026]

**Comment by rcjsuen** [comment]
@AMAZALK I see you have also opened #1015 and #1024. What are you trying to do with these issues and pull requests? Can you elaborate on what you wish to achieve?

**Comment by dbaeumer** [comment]
I am closing the issue for now. @AMAZALK we need an actionable description to consider this as an issue.

**Comment by AMAZALK** [comment]
> Tôi đang đóng vấn đề bây giờ. @AMAZALK chúng tôi cần một mô tả hành động để coi đây là một vấn đề.

Tôi muốn sử dụng github bằng tiếng Việt tôi ko hiểu gi về github tiếng Anh

**Comment by dbaeumer** [comment]
@AMAZALK I don't speak Vietnamese. You need to provide your description in English please.

**Comment by iago-lito** [comment]
Fwiw, [Google translate](https://translate.google.com/?sxsrf=ALeKk01OF108wJtxP7dL62HlsRcsSZWBpg:1592494523523&gs_lcp=CgZwc3ktYWIQAxgAMgcIIxDqAhAnMgcIIxDqAhAnMgcIIxDqAhAnMgcIIxDqAhAnMgcIIxDqAhAnMgcIIxDqAhAnMgcIIxDqAhAnMgcIIxDqAhAnMgcIIxDqAhAnMgcIIxDqAhAnUABYAGDUnQVoAXAAeACAAQCIAQCSAQCYAQCqAQdnd3Mtd2l6sAEK&um=1&ie=UTF-8&hl=fr&client=tw-ob#view=home&op=translate&sl=vi&tl=en&text=T%C3%B4i%20mu%E1%BB%91n%20s%E1%BB%AD%20d%E1%BB%A5ng%20github%20b%E1%BA%B1ng%20ti%E1%BA%BFng%20Vi%E1%BB%87t%20t%C3%B4i%20ko%20hi%E1%BB%83u%20gi%20v%E1%BB%81%20github%20ti%E1%BA%BFng%20Anh)s this as:

> I want to use github in Vietnamese, I don't understand anything about English github.

.. which I'm afraid reveals a problematic communication situation :\
