### ISSUE TITLE
Questions: insert textEdit and additionalTextEdit sequentially in same position

### ISSUE THREAD

**Issue by Eskibear** [microsoft/language-server-protocol#1032]
### Background
Trigger completion in below position:
```java
Runnable foo = new Run|
```
For abstract classes / interfaces, corresponding completion item for annoymous class constructor is provided. But computing **methods to implement** for all the items takes time. With hundreds/thousands candidates, it can take up to ~10s.

Now with `CompletionClientCapabilities.resolveAdditionalTextEditsSupport`, it's natural to think of deferring the calculation to resolve stage. E.g for "Runnable()", we can compute the body later:
**textDocument/complete**: textEdit = "Runnable"
**completionItem/resolve**: additionalTextEdit = "(){\n@Override......}"
```java
Runnable foo = new Runnable(){

    @Override
    public void run() {
        ${0:// TODO Auto-generated method stub}
    }
};
```

### Questions

However, based on current LSP spec, it's not possible to implement in above way. 
1. `insertTextFormat` only appies to `textEdit`, not including `additonalTextEdits`, meaning it's impossible to use placeholder in additional text edits.
2.  `additionalTextEdits` must not overlap with (or even next to) `textEdit`, meaning we cannot simply separate in above way.

For 1) I understand not to support snippet in additionalTextEdits, e.g. in case "${0}" is defined in both textEdit and an additional edit. 
For 2) I agree they must not overlap with each other. But can they be next to each other, i.e. in the same insert position. Maybe they can be inserted in order, first textEdit and then additional ones?

If none of above should change, then what's the suggested way to mitigate performance issue in such case?

**Comment by dbaeumer** [comment]
2) can not easily be relaxed since the communication to the server is async and we don't want to block typing (which we would need to do is we define an order or allow them to be next to it.)

I even think that the user experience will be bad in this case since the body will be inserted lazily and if the user continues typing he will be surprised. He even might start typing `(){...`. This is why we ask that everything is known around the cursor position when the item is inserted.

All I can think about is caching some of the completion items on the client side to not compute them over and over again. 

@jrieken FYI.

**Comment by Eskibear** [comment]
> He even might start typing (){.... This is why we ask that everything is known around the cursor position when the item is inserted.

It makes sense. It looks that, according to current LSP design, maybe we should not include unimplemented methods, but an empty body?  But it's a frequent use case for Java language, and also for other similar languages I believe.
 
>	/**
	 * An optional command that is executed *after* inserting this completion. *Note* that
	 * additional modifications to the current document should be described with the
	 * additionalTextEdits-property.
	 */
	command?: Command;

I'm just thinking of using `command`. The textEdit should be only "Runnable", and the command is to insert unimplemented methods. But just as specified in LSP, additionalTextEdits should be the place to go. And clients will have to implement the command, and be aware of current cursor position after completion. The idea looks not promising, just a brainstorm result fyi.

**Comment by jrieken** [comment]
With TypeScript we have the same challenge and there it is tackled with a source action. E.g whenever you have type that doesn't implement everything its interface mandates you get a quick fix to fill that in.

![Jun-24-2020 12-51-04](https://user-images.githubusercontent.com/1794099/85542478-68fbee00-b619-11ea-8a2e-a8211b0e2993.gif)

**Comment by fbricon** [comment]
@jrieken this is a suboptimal approach from a UX perspective IMHO, definitely a step backward for Java users, but if this is something we can improve in the future at the LSP level, I'm ok doing that.

**Comment by dbaeumer** [comment]
@Eskibear with command you run into the same problem than with additional text edits.
