### ISSUE TITLE
What is the purpose of Exit notification? 

### ISSUE THREAD

**Issue by matklad** [microsoft/language-server-protocol#1036]
I am looking at the `shutdown request-> | shutdown response<- | exit notification->` shutdown sequence and it seems like the last notification is completely unnecessary. So I am wondering if I misunderstand the process :-)

The current docs are:

>The shutdown request is sent from the client to the server. It asks the server to shut down, but to not exit (otherwise the response might not be delivered correctly to the client). There is a separate exit notification that asks the server to exit.

It seems like what they are trying to say is "you must send a valid (trivial) response to the shutdown request", but that's just what JSON RPC requires? Ie, a server that does `process.exit()` immediately after receiving shutdown request, *without* waiting for full response to be send, is just broken. 

OTOH, it seems like it is always valid for the client to send shutdown request and exit notification immediately after each other.

**Comment by puremourning** [comment]
> a server that does process.exit() immediately after receiving shutdown request, without waiting for full response to be send, is just broken.

Yes, broken. It's also a total pain.

https://github.com/ycm-core/ycmd/blob/master/ycmd/completers/language_server/language_server_completer.py#L1001-L1004

**Comment by dbaeumer** [comment]
The reasons is to allow vetoing if we think that is something that is necessary. This is why shutdown is a request right now and no notification.

I am open for ideas to improve with but I don't know how.

**Comment by matklad** [comment]
>The reasons is to allow vetoing if we think that is something that is necessary.

By vetoing you mean that the client is allowed to reject a shutdown request (by returning an error), but it has to terminate after the notification, sort of like sigterm/sigkill work? Agree, this does makes the model more expressive. 

>I am open for ideas to improve with but I don't know how.

What would be simpler is allowing to exit immediately after replying with success to the shutdown request. That is, to reserve exit notifications only for cases where orderly termination via request doesn't work. But we already have existing mechanism, changing that would be bad.

**Comment by puremourning** [comment]
> By vetoing you mean that the client is allowed to reject a shutdown request (by returning an error), 

Assuming you mean server...

Not sure what a client can do if the server rejects the shutdown request. I mean the client is probably shutting down, so it's just doing to forcefully kill you anyway with the notification. Does Vscode do something else on a shutdown request failure?

**Comment by alanz** [comment]
My understanding is

1. Client asks server to shut down.  This may take some time if the server must persist its state, or do other housekeeping.
2. Server responds to say it is done, after an indeterminate time
3. To ensure the reply actually gets to the client, keeping pipes, connections etc up on the transport, server does not immediately exit.
4. This allows the client to terminate the connection on its side in an orderly way.
5. Now the server can exit, hence the notification.

**Comment by matklad** [comment]
>To ensure the reply actually gets to the client, keeping pipes, connections etc up on the transport, server does not immediately exit.

But this doesn't require the final notification, does it? At the bottom layer, you are doing `write` syscall with some bytes to a pipe/socket, and, if that succeeds, you know that the over side will receive the data (even if right now it is in some kind of OS buffer), so you can cleanly exit without waiting for the client to send you exit notification. This is actually symmetric -- if it's impossible for the server to know if shutdown response is fully sent, than it's impossible for the client to know if the exit notification is fully sent!

Now, there certainly might be buggy servers which, eg, schedule async send operations on a socket and fail to await it before exiting, but those bugs can and should be fixed without relying on exit notification.

**Comment by dbaeumer** [comment]
I am actually not in favor of changing this since I don't see the win over the swirl it will cause. 

Regarding 

> than it's impossible for the client to know if the exit notification is fully sent!

valid point. But in general a server needs to handle the case that the client crashes as well without ever sending shutdown or exit. This is why the initialize request contains the client process id. And the VS Code client even passes it as a command line argument.
