### ISSUE TITLE
Clarify how multiple TextEdits should be resolved when given in batch

### ISSUE THREAD

**Issue by rictic** [Microsoft/language-server-protocol#104]
If I have a file with contents `012` and a completion is applied with two text edits:
-  Replace the zeroth character with two characters
-  Deleted the third character

Does that mean that `1` should be deleted, or `2`?

More precisely, after applying these TextEdits:

``` typescript
  [
    {range: {start: {line: 0, column: 0}, end: {line: 0, column: 1}, newText: 'aa'},
    {range: {start: {line: 0, column: 2}, end: {line: 0, column: 3}, newText: ''},
  ]
```

Should the resulting document have contents `aa2` or `aa1`?

**Comment by kaloyan-raev** [comment]
As far as I am familiar with existing language server implementations, all TextEdits are based on the original, yet unmodified document.

So, in you example the resulting document would be `aa1`.

An appropriate order to apply the TextEdits to the document would be backwards. Apply the last one first, then the previous one, and so on... the first one is applied last. This way no shifting of not-yet-applied TextEdits would be necessary.

**Comment by dbaeumer** [comment]
@kaloyan-raev is correct. Updated the protocol.
