### ISSUE TITLE
Feature Request: The CCLS additions imported into the standard

### ISSUE THREAD

**Issue by lanza** [microsoft/language-server-protocol#1041]
The [ccls](https://github.com/maskray/ccls) language server offers numerous very useful extensions to the LSP. Trying it out and testing out the extensions would probably give the best demonstrations, but here's a list of extensions:

* callers/calles -- return a list of callers and callees
* inheriters -- return a nested hierarchy of types that inherit from the type
* inheritance -- return a nested hierarchy of types the current type inherits from
* member vars -- return all member variables of a  type
* member functions -- return a list of all member functions of a type
* member types -- return a list of all member types of a type
* navigate -- navigate the cursor to the next parent scope, child scope, left sibling scope or right sibling scope

Going from ccls to any other LSP is about as noticeable a difference as going from an LSP to a dumb text editor once you learn how to make use of it's extensions. Any thoughts on some of these features?

**Comment by rcjsuen** [comment]
> * callers/calles -- return a list of callers and callees

Call hierarchy will be a new feature in the upcoming 3.16 specification (#468). I don't think the other ones have ever been requested by the community though.

**Comment by kdvolder** [comment]
Type hierarchy is something I really can't live without personally. (Java programming) So until there's a type hiearchy in vscode Java support, I will stick with Eclipse. Does that count as a 'request from the community' for type-hierarchy?

**Comment by rcjsuen** [comment]
> Does that count as a 'request from the community' for type-hierarchy?

Sure. And I suppose this whole #1041 issue from @lanza is a request itself. :)

I was more pointing out that I tried searching for issues but couldn't find any (unlike the call hierarchy case).

**Comment by KamasamaK** [comment]
Type hierarchy is already requested in the poorly named #136 and a proposal exists at microsoft/vscode-languageserver-node#426.
