### ISSUE TITLE
textDocument/open

### ISSUE THREAD

**Issue by krzyzanowskim** [microsoft/language-server-protocol#1042]
specification says

> Client support for `textDocument/open`, `textDocument/change` and `textDocument/close` notifications is mandatory in the protocol

and then `textDocument/didOpen`, `textDocument/didChange` and `textDocument/didClose` is specified.
At this point I'm not sure if `textDocument/open` is just a typo, or there's actual `textDocument/open` notification from server -> client?

**Comment by rcjsuen** [comment]
@krzyzanowskim Good catch. Those do look like typos to me. I have opened #1043 to address this.

**Comment by dbaeumer** [comment]
Yes, very good catch. They are typos

**Comment by dbaeumer** [comment]
PR Merged.
