### ISSUE TITLE
Is the version in the VersionedTextDocumentIdentifier passed to DidChangeTextDocumentParams always a number?

### ISSUE THREAD

**Issue by kjeremy** [microsoft/language-server-protocol#1049]
VersionedTextDocumentIdentifier allows the version to be `null` but if I am reading the spec right the one passed down in `DidChangeTextDocumentParams` will never be `null`. Is that correct?

**Comment by rwols** [comment]
One instance where this version should be `null` is when the client requests textDocument/rename, after which the server sends back a list of [TextDocumentEdit](https://microsoft.github.io/language-server-protocol/specification#textDocumentEdit) where one of the files is not yet opened via a textDocument/didOpen. In that case, the server doesn't know the version (the client dictates what the version is), so it should put `"version": null` for unopened files that need edits.

> if I am reading the spec right the one passed down in DidChangeTextDocumentParams will never be null. Is that correct?

I would say yes, every client has the responsibility to provide a version and have it increment (or generally changed) after edits.

**Comment by kjeremy** [comment]
Right, it makes sense to me that the server could send a `null` back if the document isn't opened. It's the client -> server communication I'm wondering about here.

**Comment by dbaeumer** [comment]
It can never be null in the client -> server communication. I am closing the issue since the protocol current doesn't allow null there. Please ping if you think otherwise.

**Comment by kjeremy** [comment]
I don't think this is clear at all since the *type* allows for `null`. [Server to client](https://microsoft.github.io/language-server-protocol/specifications/specification-3-16/#versionedTextDocumentIdentifier) is mentioned so I think some wording for client -> server should also be added.

**Comment by dbaeumer** [comment]
Made it two interfaces.
