### ISSUE TITLE
Is the client supposed to ignore unknown server caps?

### ISSUE THREAD

**Issue by kjeremy** [microsoft/language-server-protocol#1050]
It appears that the language client for Visual Studio (not Code) fails if we send back server capabilities that it does not recognize. This seems odd to me but I don't think this behavior is explicitly called out in the spec (I haven't seen any other client that behaves in this way).

See: https://github.com/rust-analyzer/rust-analyzer/pull/5516

**Comment by olegtk** [comment]
I filed an internal bug to fix this in VS, but it would be great to have the spec to clarify this aspect.

**Comment by rwols** [comment]
> Is the client supposed to ignore unknown server caps?

Yes, that's the whole point of advertising capabilities IMO.

**Comment by kjeremy** [comment]
@rwols agreed but it's not specified.

**Comment by milopezc** [comment]
Hello, I'm currently investigating the issue in Visual Studio and I'm not able to repro the issue. I was able to return some unrecognized server capabilities and the VS LSP client platform is simply ignoring them (which is expected) and correctly initializing the client.

**Comment by dbaeumer** [comment]
Yes a client should ignore unknown server capabilities. It simply doesn't send the request.  I added some clarification to the 3.16 version of the spec.
