### ISSUE TITLE
Align CompletionItemKind, SymbolKind and SemanticTokenType

### ISSUE THREAD

**Issue by floitsch** [microsoft/language-server-protocol#1054]
These kinds (and maybe others) should just be merged.
There is not really a reason that CompletionItemKind has a `Constructor` but SemanticTokenType doesn't.
Similarly (as mentioned in #343), there is a symbol kinds 'package' but that one is missing in the others. The kind "namespace" exists in SymbolKind, and SemanticTokenType, but not in CompletionItemKind.

All in all, it would be extremely helpful if these kinds would just be the same. Clearly there would be some that aren't useful in all circumstances, but that could be explained in a comment.

**Comment by dbaeumer** [comment]
We try to keep these aligned but in general we prefer distinct types. It always makes it easier to evolve them independently.

I will close the issue since we do have issue to add certain values to these types.
