### ISSUE TITLE
LSP native way for pre-filling required fields/arguments

### ISSUE THREAD

**Issue by radeksimko** [microsoft/language-server-protocol#1057]
## Context

I'm unsure how exactly this may apply to other languages, but I'm working on HCL-based language server ([for Terraform](https://github.com/hashicorp/terraform-ls)). HCL can be characterised by blocks such as this one:

```hcl
block_type "label" {
  arg1 = "val1"
  arg2 = 42
}
```
where a particular _combination of `block_type` and label(s)_ can have a _schema_ prescribing arguments supported within the block (between `{` and `}`) and each argument holds its own metadata, including whether it's required.

I think this is comparable to required fields in languages which implement explicit interface association, e.g. TypeScript?

```ts
interface Point {
    x: number;
    y: number;
}

let p1: Point = {};
```

## Pre-fill mechanism

We'd like to provide the user a mechanism for "pre-filling" required arguments. It seems that `textDocument/completion` is the best way to do it, but it's unclear to me how to best provide this functionality to the user as such functionality isn't explicitly documented in LSP spec nor have I seen any precedent in other language servers.

### Option 1 - completion confirmation

It _seems_ like this one fits better into the LSP spec, but I haven't seen `additionalTextEdits` specifically used in this way anywhere.

We can pre-fill arguments on confirmation of the "parent" completion item via `additionalTextEdits`, e.g.

#### Terraform/HCL

![Screenshot 2020-07-29 at 15 05 59](https://user-images.githubusercontent.com/287584/88810708-9eae6c80-d1ad-11ea-82a9-e2246bdf6949.png)
`Enter` ⬇️ 
![Screenshot 2020-07-29 at 15 06 16](https://user-images.githubusercontent.com/287584/88810714-a110c680-d1ad-11ea-85ba-0fd4d96897d7.png)

#### TypeScript

![Screenshot 2020-07-29 at 14 59 47](https://user-images.githubusercontent.com/287584/88809748-5d698d00-d1ac-11ea-8e41-3733dfe25748.png)
`Enter` ⬇️ 
![Screenshot 2020-07-29 at 15 03 24](https://user-images.githubusercontent.com/287584/88810010-b0dbdb00-d1ac-11ea-8d38-85d8c30e5721.png)

### Option 2 - explicit pre-fill "meta item" within the block

![Screenshot 2020-07-29 at 15 16 56](https://user-images.githubusercontent.com/287584/88811515-9145b200-d1ae-11ea-91a9-1f7432e29c79.png)

This one has the added benefit of providing pre-fill mechanism even for pre-existing or copy-pasted code.
Also there seems to be a precedent in Goland for this kind of UX:

![87387090-91518980-c5d4-11ea-9422-6ead35ee741c](https://user-images.githubusercontent.com/287584/88812199-5db75780-d1af-11ea-8191-8aefae9ce260.png)

Related question - would `Snippet` be the right `CompletionItemKind` for this kind of thing?

**Comment by puremourning** [comment]
I think this is what code actions are for. (other languages provide code actions to, e.g. insert overrides for all pure virtual functions, or when implementing some interface, etc.). You can even attach it to a diagnostic that says "Missing mandatory elements..." or whatever.

Doing this on completion is IMO an abuse of what code completion is for.

**Comment by dbaeumer** [comment]
A couple of comments:

- completion items should usually only manipulate the text around the cursor. It should not manipulate other text.
- additional text edits are meant to fix up things like imports that are usually unrelated to the code you are currently editing

In the example of `let p1: Poi<cursor>` this could be done using a snippet. A more comparable situation to what you outlines for your language would be `let p1: Poi<cursor> = { y: 0 }`. which would add an x property if `Point` is selected from the list.

I do agree with @puremourning that the second case is better handled using code actions which are there to fix incorrect code.

Please ping if this doesn't help.

**Comment by radeksimko** [comment]
Understood, thank you for all the extra context both. I will look into code actions.

> additional text edits are meant to fix up things like imports that are usually unrelated to the code you are currently editing

So what you're saying is that `textDocument/completion` with the `additionalTextEdits` would still be reasonable in case the first scenario, but not so much in the second one, am I right?

**Comment by radeksimko** [comment]
Both of your responses were helpful, just hoping for response to my last question above, then I'm happy to close this issue. 😉 

@puremourning I did check out Code Actions and you were right - they look like the best solution for the 2nd problem (prefilling attributes into an existing block). 👍

**Comment by dbaeumer** [comment]
@radeksimko correct. However in general I would prefer the second flow.
