### ISSUE TITLE
Clarify docs on additionalTextEdits

### ISSUE THREAD

**Issue by 333fred** [microsoft/language-server-protocol#1059]
3.16 added support for deferring additionalTextEdits in completions (https://github.com/microsoft/language-server-protocol/issues/1003), but I don't see this mentioned anywhere in the draft 3.16 specification. Can the docs on what is allowed to be lazy be updated?

**Comment by dbaeumer** [comment]
The client capability is in the spec here: https://github.com/microsoft/language-server-protocol/blob/gh-pages/_specifications/specification-3-16.md#L3244

Added a clarifying sentence to https://github.com/microsoft/language-server-protocol/blob/gh-pages/_specifications/specification-3-16.md#L3166

Thanks for pointing this out.
