### ISSUE TITLE
Question about FormattingOptions and WorkspaceEdit types ( `[key: string]:`...)

### ISSUE THREAD

**Issue by bruno-medeiros** [Microsoft/language-server-protocol#106]
In FormattingOptions  there is:

```
    /**
     * Signature for further properties.
     */
    [key: string]: boolean | number | string;
```

What does that mean exactly? That arbitrary properties can be in of FormattingOptions itself, beyond `tabSize` and `insertSpaces` ?

**Comment by bruno-medeiros** [comment]
On the same line, I'm also not sure what the `changes` property is like:
```
interface WorkspaceEdit {
    /**
     * Holds changes to existing resources.
     */
    changes: { [uri: string]: TextEdit[]; };
}
```
Is changes like a map (associate array) whose keys are URIs, and values are an array of TextEdits for the associated key-URI?

**Comment by akosyakov** [comment]
@bruno-medeiros look for **Indexable Types** [here](https://www.typescriptlang.org/docs/handbook/interfaces.html).

1. `FormattingOptions` can have extra properties of boolean, number or string type.
2. You can think that `WorkspaceEdit` is an array with an index of type string and a value of `TextEdit[]` type.

**Comment by dbaeumer** [comment]
It is IMO impossible to standardize formatting options across languages. This is why we left this open. Alternatively one could say that formatting options besides tabSize and indent have to be synced to the server using configuration options. Opinions ?

**Comment by bruno-medeiros** [comment]
Ah, I wasn't trying to standardize formatting options across languages, I agree that would be hard and likely not ideal to do under the scope of LSP. I was just trying to understand that notation, which is essentially Typescript-centric. I already suspected the meaning was like how @akosyakov described, but wanted to confirm.

Although, an issue that comes to mind now is that modelling types in that way makes it a bit harder for LSP implementations that use reflection (or compile-time meta-programming) for automatically generate implementations of JSON serializers/deserializers for that type. (this is the case for RustLSP, and as far as I know also for LSP4j which uses GSON to automatically serialize/deserialize the JSON data)

It basically means that either: 
 * A custom serializer/deserializer has to be written for FormattingOptions, instead of an automatically generated one.
or:
 * the whole FormattingOptions is modelled as a JSON array in the LSP implementation, but then there still has to be manually written code that checks that `tabSize` and `indent` properties are present and are of the correct types (`number` and `boolean` respectively).

FormattingOptions could instead be:
```typescript
interface FormattingOptions {
    tabSize: number;
    insertSpaces: boolean;
    additionalOptions: { [uri: string]: TextEdit[]; };
}
```

It's a relatively minor issue, but I still thought it would be worth mentioning it and keeping it in mind.

**Comment by dbaeumer** [comment]
@bruno-medeiros I agree with the implementation that use reflection and we try to consider this when specifying new protocol. 

To keep the number of issues in our inbox at a manageable level, we’re closing issues that have been on the backlog for a long time but haven’t gained traction: we look at the number of votes the issue has received and the number of duplicate issues filed. Thank you for your time and understanding.

If you disagree and feel that this issue is crucial: we’re happy to listen and to reconsider.
