### ISSUE TITLE
Shutdown request clarification with notifications

### ISSUE THREAD

**Issue by kjeremy** [microsoft/language-server-protocol#1066]
From the 3.16 spec:

> If a server receives requests after a shutdown request those requests should error with InvalidRequest.

Does this apply to notifications received as well?

**Comment by dbaeumer** [comment]
I think the spec is pretty clear since exit is a notification not a request.

> Clients must not send any notifications other than `exit` or requests to a server to which they have sent a shutdown request. If a server receives requests after a shutdown request those requests should error with `InvalidRequest`.
