### ISSUE TITLE
CLI-client using the language-server-protocol for completions

### ISSUE THREAD

**Issue by v217** [microsoft/language-server-protocol#1070]
Couldn't find a better place to post this question.
Do you know of a **terminal**, which provide **completions through lsp**?
A lsp CLI-client?

**Comment by rcjsuen** [comment]
@v217 There are LSP client plug-ins/extensions for editors in a terminal like Vim and Emacs.

Or are you thinking of something else?

**Comment by v217** [comment]
@rcjsuen Yes, I thought about something else.
E.g. the zsh, fish, etc... shell all provide their custom toolkit to provide autocompletion. lsp solved the problem for editors. My question is if (a subset of) lsp would also work for CLIs?
Note I am not too familiar with the lsp protocol, so I guess for someone with more detailed knowledge this suggestion might sound crazy?
Why I am asking this question?
I was thinking about a CLI which integrates several nested programming languages. Think of ipython, with the autocompletions for python AND fish?
Not sure if that makes sense?

**Comment by dbaeumer** [comment]
IMO this is nothing that needs attention from the protocol itself. I think if someone wants to integrate an existing language server into a shell that should be not too complicated. 

@v217 is there anything you expect from the protocol?

**Comment by v217** [comment]
@dbaeumer I agree, I just couldn't find a better place for posting this question.
A similar question wasn't accepted on stackoverflow. So I think this issue can be closed, people can comment on the closed issue as well. Anyway I would be thankful, if anybody knows of a shell client!

**Comment by dbaeumer** [comment]
Closing the issue then.
