### ISSUE TITLE
Is It possible that vs code LSP client can connect with server use tcp or websocket? 

### ISSUE THREAD

**Issue by hasegetc** [microsoft/language-server-protocol#1072]
* just as this page describ: "https://docs.microsoft.com/en-us/visualstudio/extensibility/language-server-protocol?view=vs-2019", The actual transport channel can either be stdio, sockets, named pipes, or node ipc
* this page notice that we can use tcp, "https://docs.microsoft.com/en-us/visualstudio/extensibility/adding-an-lsp-extension?view=vs-2019"
* but I cant find the demo that lsp client transport data with server use tcp (not use ip + port), just use port for note IPC
* is it possible VS Code LSP client can connect with server use tcp or websocket?

**Comment by rcjsuen** [comment]
@hasegetc Your question is specific to Visual Studio Code so I suggest you get help in the [microsoft/vscode-languageserver-node](https://github.com/microsoft/vscode-languageserver-node) repository instead of here.

**Comment by hasegetc** [comment]
@rcjsuen  thank you
