### ISSUE TITLE
Maybe table of contents?

### ISSUE THREAD

**Issue by ShadowDancer** [microsoft/language-server-protocol#1075]
I think that table of contents would relief tortured souls, who are trying to create language servers.

**Comment by rcjsuen** [comment]
> I think that table of contents would relief tortured souls, who are trying to create language servers.

@ShadowDancer Which page are you referring to specifically? Are you talking to the table of contents on the right hand side of the [specification](https://microsoft.github.io/language-server-protocol/specifications/specification-current/)?

**Comment by ShadowDancer** [comment]
@rcjsuen Doh, I had zoomed too much for some reason, and TOC vanished. I thought that specification page had no TOC and I've spent few day working on language server scrolling this page. Typical PEKBAC. Sorry for bothering you :D
