### ISSUE TITLE
Clarify characterDelta and overlapping/intersecting tokens for SemanticTokens

### ISSUE THREAD

**Issue by DanTup** [microsoft/language-server-protocol#1077]
The Dart server's native protocol provides layers highlight regions, for example:

```
print('This is a $variable in a string!').
```

Here, `'This is a $variable in a string!'` would be supplied as one range, with `$variable` being another. I assumed that LSP's semantic tokens supported this, because the spec says `characterDelta` is from the start of the previous token:

https://microsoft.github.io/language-server-protocol/specifications/specification-3-16/

> token start character, relative to the previous token (relative to 0 or **the previous token’s start** if they are on the same line)

However, @simolus3 linked me to https://github.com/microsoft/vscode/issues/86415#issuecomment-587184889 which says

> > Speaking of deltas, since they are relative to the end of the previous token, there can't be any overlapping ranges.
> 
> the choice to have tokens not overlap is intentional

It's not clear to me which of these is incorrect (is the character delta from the start of the end of the previous token?) of whether it was changed to accommodate overlapping tokens. If the delta is intended to be from the end, the spec needs updating. If it's really the start, but nested tokens are not supported, I think this should be explicit in the spec (since it's easy to assume they're supported if deltas are from the start).

**Comment by rcjsuen** [comment]
> It's not clear to me which of these is incorrect (is the character delta from the start of the end of the previous token?) of whether it was changed to accommodate overlapping tokens. If the delta is intended to be from the end, the spec needs updating. If it's really the start, but nested tokens are not supported, I think this should be explicit in the spec (since it's easy to assume they're supported if deltas are from the start).

The delta is from the start of the previous token and overlapping tokens are not supported. That is the current state of the world as I understand it and is how I've implemented it in my language server.

Given that overlapping tokens are not supported, it does feel like the delta could be from the end of the previous token to not give people the impression that overlapping tokens are supported... 🤔

**Comment by DanTup** [comment]
> Given that overlapping tokens are not supported, it does feel like the delta could be from the end of the previous token to not give people the impression that overlapping tokens are supported... 🤔

Yeah, that's my point. If overlapping tokens definitely aren't supported, it should definitely be called out in the spec.

That said - it seems as easy for clients to flatten as servers, so IMO it'd be better to allow it - preventing it is more restrictive. For example, imagine you want to colour comments green, but also make references to classes underlined:

```dart
/// This is a comment with a [type] reference
```

Here, `[type]` would lose its comment formatting (would not be green) because it's not part of a comment anymore.

**Comment by dbaeumer** [comment]
To my defense this is currently in the spec:

> In this case, the second token is on the same line as the first token, so the `startChar` of the second token is made relative to the `startChar` of the first token, so it will be `10 - 5`

I do agree that the overlapping thing needs to be speced. Since this might be editor dependent I am open to make this a capability which be default is `false`.

**Comment by DanTup** [comment]
> To my defense this is currently in the spec

I don't think that clarifies whether nesting is allowed or not - though my intention was not to say that what's spec'd is bad, just to make it more explicit to keep servers/clients all on the same page and without having to scour GH issues for answers :-)

> I do agree that the overlapping thing needs to be speced. Since this might be editor dependent I am open to make this a capability which be default is `false`. Opinions?

Yeah, that seems much better than ruling it out IMO. It should also be clear if this is just nested tokens and not intersecting:

```<comment>text text<variable>text</comment> text</variable>```

I'm not sure anyone would do that, but since the data structure would allow for it, it should be clear if it's allowed (I suspect not - but if it is, I think it should be a separate capability, since it could be more difficult for clients to handle than just nesting).

**Comment by dbaeumer** [comment]
Then lets make this a client capability

**Comment by DanTup** [comment]
@dbaeumer could we also clarify whether tokens may include the newlines on the end of lines? Currently it just says:

> A token cannot be multiline

But it's not clear if I had code where the logical token spans multiple lines:

```dart
  /**
   * comment
   */
```

whether newlines should be included in token ranges.

Though to be honest, I think multiline tokens would be beneficial too - a [comment of over 100 lines](https://github.com/flutter/flutter/blob/f35a8b7470d622f9430e4190b0c4b116fb721c77/packages/flutter/lib/src/widgets/framework.dart#L548-L658) (or long multiline strings) seems better represented as a single token than 110 tokens (both for payload size, potentially work for the client, and knowing this is a single comment and not many separate comments).

**Comment by dbaeumer** [comment]
I see the point. IMO we need to have a client capability for this as well.

@alexdima do you have any insights on this?

**Comment by alexdima** [comment]
Currently, VS Code expects semantic tokens to be non-overlapping and single line.

The reason for this is that we thought semantic tokens come on top and refine tokens generated via TextMate grammars or other client-side parsers (like e.g. Tree-sitter). It was not our goal for semantic tokens to be a complete replacement of client-side tokenization.

IIRC our main concerns for keeping TextMate grammars in VS Code and using semantic tokens to refine things were around possible latency between the client and the language server (e.g. the time between typing `/*` and the text being rendered as a comment), or around language server startup time (i.e. what is the time since opening vscode until the file becomes colored).

**Comment by gundermanc** [comment]
@allisonchou just hit this as part of the work to move Roslyn colorization in CodeSpaces to LSP semantic tokens protocol: https://github.com/dotnet/roslyn/issues/46052.

Though TextMate can be used for syntactic and lexical classification I've heard a lot of interest in having a TextMate-free alternative for colorization, at least in local LSP scenarios.

Certain syntactic constructs are simpler to do in LSP than in TextMate (arrow functions in TypeScript are done as part of ~150 line regex) or more convenient to do with existing in-proc language services ported to LSP (Roslyn overlapping colorization for escape chars in strings).

Latency, in VS at least, doesn't seem to be a limitation of the protocol so much as of the specific server and the connection through which we communicate with it.

>IMO we need to have a client capability for this as well.

+1, for existing VS language services adopting LSP, this will make it easier to adapt their existing code.

**Comment by dbaeumer** [comment]
I added two capabilities to the spec:

```
	/**
	 * Whether the client supports tokens that can overlap each other.
	 */
	overlappingTokenSupport?: boolean;

	/**
	 * Whether the client supports tokens that can span multiple lines.
	 */
	multilineTokenSupport?: boolean;
```
