### ISSUE TITLE
Feature Request: Generate implementation for languages that separate impls from refs

### ISSUE THREAD

**Issue by lanza** [microsoft/language-server-protocol#1080]
In C , for example, you can have

```
// thing.h
void doThing();

// thing.c
void doThing() { printf("Hi\n"); }
```

In C++ you can have
```
// thing.hpp
class Thing {
  void doThing();
};

// thing.cpp
void Thing::doThing() { std::cout << "HI" << '\n'; }
```

and etc

Some IDEs know how to parse the current project and find decls without definitions and offer you to generate a stub in the file that it thinks it belongs in. For example, in clion if `thing.hpp` declared `Thing::doThing();` you could invoke `textDocument/generateDefinition` to get back a list of unimplemented member funcs which, in this case, would be one element long and upon selecting you'd generate a stub in `thing.cpp`. 

C, ObjC, C++, TypeScript, Swift (via protocols) and many other languages offer decl/def separation.

A related idea that could use the same interface with a separate `kind` flag of some sort would be to generate `override` implementations. e.g. in C++ if you had a `class BaseClass` with method `doSomething();` and your cursor was in `class SubClass : public BaseClass` and you queried for `textDocument/generateDef` with the right `kind` parameter it could offer back a list of possible definitions you can override.

**Comment by rcjsuen** [comment]
@lanza I believe this can already be achieved in some way through `textDocument/codeAction`.

**Comment by dbaeumer** [comment]
I agree with @rcjsuen 

I will close the issue. @lanza if you think otherwise please ping.

**Comment by lanza** [comment]
I suppose that's sufficient. The only concern I have about that is that having dedicated packet's for a specific functionality advertises them to LSP writers and LSP users. This is a pretty simple feature to implement from the LSP side (if decl but no def is something, e.g. libclang, will tell you for free) yet isn't very common amongst LSPs. 

I had never even thought of this type of functionality until I was playing around with clion a week ago. Simply being informed of it made me go and implement a toy version in ccls (that I hope to upstream soon). 

I'm guessing the mere existence of `Generate Method Implementation: not implemented` would encourage more LSP authors to add the functionality while also letting users know about it's existence.
