### ISSUE TITLE
Adding a protocol extension to LSP to get LSIF monikers from a text location

### ISSUE THREAD

**Issue by BertanAygun** [microsoft/language-server-protocol#1085]
With introduction of LSIF and indexed repos, there are some scenarios where users might want to do code navigation from the code they are editing right now to other indexed code that is not loaded in their context. This requires index implementations to know the LSIF moniker at the current cursor location. The following protocol extension would add a method to LSP for server implementations to return LSIF monikers applicable to the queried location.

Method name: textDocument/resolveMoniker
Input: TextDocumentPositionParams
Output: Moniker[] (as defined here https://github.com/microsoft/lsif-node/blob/master/protocol/src/protocol.ts#L510)

Server capability: symbolMonikerProvider? : boolean
No client capability would be introduced.

If these sound good, I can submit a PR that implements this as a protocol extension (or let me know if there is a better way)

Thanks, Bertan

**Comment by BertanAygun** [comment]
Pull request added at https://github.com/microsoft/vscode-languageserver-node/pull/670. Tagging @dbaeumer as FYI

**Comment by dbaeumer** [comment]
@BertanAygun now that the 3.16 spec is alreay available it would be great if you could provide the spec changes / additions as a PR as well. You can then remove the markdown part from the implementation in vscode-languageserver-node

**Comment by BertanAygun** [comment]
3.16 spec changes PR is at https://github.com/microsoft/language-server-protocol/pull/1095

**Comment by dbaeumer** [comment]
Merged the PR.
