### ISSUE TITLE
Rename 'member' semantic token type

### ISSUE THREAD

**Issue by 0dinD** [microsoft/language-server-protocol#1087]
I implemented redhat-developer/vscode-java#1488 a while ago, and was very confused as to why aeschli wanted to use the `member` semantic token type instead of `function` for Java methods. As it turns out (took me a while to figure out), the name `member` is misleading since the token type actually refers to ***member functions***.

This is also misleading for theme authors, as you would expect to style ***all members*** (including member variables, for example) using the `member` token type. But in reality, `member` only applies to member functions, not member variables. 

Is it too much trouble to rename the `member` token type to `memberFunction`?  
If it is, I think a note in the documentation is a good idea in order to prevent future misunderstandings.

**Comment by rcjsuen** [comment]
@0dinD If `member` is for member functions then how do I style member variables? 🤔

**Comment by 0dinD** [comment]
@rcjsuen that's done using the semantic token type `property` (as far as I can tell), which now that I think about it is also a bit confusing. I still think `member` is the most confusing and misleading token type out of the two, but I wouldn't complain if `property` was renamed to `memberVariable` while we're at it.

The meaning of the semantic token types are not very well documented in VS Code or LSP, but from [this line](https://github.com/microsoft/vscode/blob/de7bb5b5fe55fe562361df6eeed61d970929c936/src/vs/platform/theme/common/tokenClassificationRegistry.ts#L525) and [this line](https://github.com/microsoft/vscode/blob/de7bb5b5fe55fe562361df6eeed61d970929c936/src/vs/platform/theme/common/tokenClassificationRegistry.ts#L530) you can tell what the token types are supposed to represent based on the assigned TextMate scopes.

**Comment by dbaeumer** [comment]
@aeschli can you please comment / help me.

**Comment by dbaeumer** [comment]
@aeschli ping!

**Comment by sam-mccall** [comment]
I got bitten by this too (https://github.com/clangd/vscode-clangd/issues/105)

#1146 would make the status quo clearer in the spec at least.
Using clearer names would be nice though!

**Comment by dbaeumer** [comment]
@aeschli thanks. I will adopt in LSP.
