### ISSUE TITLE
Possibility of different diagnostic collections based on source

### ISSUE THREAD

**Issue by stamblerre** [microsoft/language-server-protocol#1088]
I was wondering if you had considered allowing language servers to have separate diagnostic collections, much like VS Code extensions. In the case of the Go language server, some types of diagnostics appear as files change and others are computed only when files are saved, etc. Having separate diagnostic collections would allow us to update only the relevant collections, rather than resending all of the current diagnostics + the new diagnostics.

Obviously this is something that the language server can handle without diagnostic collections, so it's certainly not a necessity, but it was something that came up for us in a discussion.

**Comment by dbaeumer** [comment]
I understand the use case but so far now big demand for this. Would you be willing to work on a PR?

**Comment by Razzeee** [comment]
I would love this, as our code to send different diagnostics is very complex at the moment.

**Comment by stamblerre** [comment]
> Would you be willing to work on a PR? 

Unfortunately, I don't think I will be able to take this on--sorry about that!

**Comment by dbaeumer** [comment]
Actually support for this got added with the new pull diagnostic. You can register different identifiers. I will close the request in favor of the support in pull.
