### ISSUE TITLE
LSP Inspector down?

### ISSUE THREAD

**Issue by Wosi** [microsoft/language-server-protocol#1089]
When you go to the LSP Inspector (https://microsoft.github.io/language-server-protocol/inspector/) then you will be redirected to this page: https://microsoft.github.io//language-server-protocol/overviews/lsp/overview/

It used to work a week ago. Did you turn it off on purpose?

**Comment by rchl** [comment]
Disabled on purpose https://github.com/microsoft/language-server-protocol/pull/1082

**Comment by dbaeumer** [comment]
It got disabled on purpose. Maintaining this is a Web/UI is quite difficult. A better approach would actually now be a custom editor inside VS Code now that it supports it.

**Comment by dbaeumer** [comment]
I will close the issue since I currently don't have the bandwidth to bring this back. If someone is interested please ping and I will reopen the issue.

**Comment by bpringe** [comment]
I've been learning the LSP and when I saw this existed I was so excited, then realized it's no longer hosted. So I tried to run it locally, but alas my OS is incompatible with a dependency :frowning_face:.

```sh
Error: Node Sass does not yet support your current environment: Linux 64-bit with Unsupported runtime (88)
``` 

I'm on Manjaro Linux (Arch based). It would be awesome if this could be hosted again, but I understand bandwidth being tight. A VS Code custom editor sounds like a good idea.

**Comment by Razzeee** [comment]
Maybe you can just update the sass-loader locally? https://stackoverflow.com/questions/64645396/node-sass-does-not-yet-support-your-current-environment-linux-64-bit-with-unsup

**Comment by bpringe** [comment]
Thanks for the tip! I did that but then `yarn serve` was hanging at a `vue-cli-service` call, so I updated that dev package as well as related ones and got it running. I'll submit a PR to the inspector repo, if anyone's interested in merging so others don't have this issue.
