### ISSUE TITLE
Support onTypeRename

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/language-server-protocol#1092]
For language like HTML it would be cool to be able to rename a closing tag automatically if a user changes the name of an opening tag. To make this happen we propose a new message `onTypeRename` which is comparable to on type format.

**Comment by angelozerr** [comment]
@dbaeumer is is to support [HTML mirror cursor](https://code.visualstudio.com/updates/v1_41#_html-mirror-cursor) but with standard LSP requests?

If it that, it means that LSP client should support mirror cursor, LSP should provide a client capability for onTypeRename .

I love this idea and I would like to use it for our [XML Language Server.](https://github.com/eclipse/lemminx).

**Comment by dbaeumer** [comment]
Yes, that is the idea also we will not talk about multiple cursor. The idea is to have ranges that must be kept in sync. The client can then decide on how to visualize this.

**Comment by octref** [comment]
@dbaeumer Would love to adopt it 😉
