### ISSUE TITLE
PublishDiagnosticsClientCapabilities and tagSupport

### ISSUE THREAD

**Issue by kaby76** [microsoft/language-server-protocol#1097]
I'm trying to update my server with a replacement that I am writing for [Microsoft.VisualStudio.LanguageServer.Protocol](https://www.nuget.org/packages/Microsoft.VisualStudio.LanguageServer.Protocol/). The replacement brings forward the types from the 3.6-ish/2+ year old version that VS 2019 uses to the 3.16 spec. I need to move forward to something that I can use with VSCode, GNU Emacs and other clients that support semantic highlighting. It works great, but I'm now looking at every detail to make sure ever interface/class/struct/enum is correct even for things that I don't use.

One problem is the "tagSupport" field of the PublishDiagnosticsClientCapabilities interface.

    export interface PublishDiagnosticsClientCapabilities {
        ...
        /**
         * Client supports the tag property to provide meta data about a diagnostic.
         * Clients supporting tags have to handle unknown tags gracefully.
         *
         * @since 3.15.0
         */
         tagSupport?: {
             /**
              * The tags supported by the client.
              */
             valueSet: DiagnosticTag[];
         };
    }

The JSON I received from VS2019 for initialization included the following:

      "publishDiagnostics": {
        "tagSupport": true
      }

This causes an error because "true" cannot be mapped to a struct containing valueSet/DiagnosticTags array. Am I reading the spec this right? If so, I think I need to flag a bug in VS2019.

(Also, this may not be the correct place to raise this, but this might be a problem with the spec, in that it's missing "| boolean" for "tagSupport".)

**Comment by KamasamaK** [comment]
A boolean is not valid for `tagSupport`, so that's a bug in VS2019 (or whatever extension might be providing that).

**Comment by kaby76** [comment]
Thanks. I'll raise the issue with the VS2019 team.
