### ISSUE TITLE
Stream symbols like diagnostics

### ISSUE THREAD

**Issue by mickaelistria** [microsoft/language-server-protocol#110]
It could be relevant to always show the symbols for a file (Eclipse has the outline view which allows that). In such case, an operation that would "stream" symbols like diagnostics would make it easier to implement a reactive list of symbols.

**Comment by dbaeumer** [comment]
I think if we want to have a symbol tree like in Eclipse we need a protocol addition to incrementally update an existing tree like we can incrementally update the content of a text document.

**Comment by mickaelistria** [comment]
The current symbols action do return "range" for a given symbol. Range are enough to show a tree. The Eclipse/LSP integration already managed to show a tree in the outline for a given file according to symbols.

**Comment by dbaeumer** [comment]
Please see also #786

**Comment by dbaeumer** [comment]
Closing the issue. Corresponding support has been speced in dbaeumer/3.15 branch.
