### ISSUE TITLE
How to dynamically register semantic tokens

### ISSUE THREAD

**Issue by stamblerre** [microsoft/language-server-protocol#1107]
I have a few questions about dynamic registration for the semantic tokens methods.

- Should they each be registered individually? When I register `textDocument/semanticTokens/full`, `textDocument/semanticTokens/full/delta`, and `textDocument/semanticTokens/range`, I get errors for `textDocument/semanticTokens/full/delta` and `textDocument/semanticTokens/range`.
- Should the registration options for each method be the same `SemanticTokensOptions`? Should `full` and `range` be configured in those options or left out since they are registered individually?

**Comment by dbaeumer** [comment]
The idea is to have only one registration. This is why `SemanticTokensOptions` has a property for `range` and for `full`. This allows the client to decide which methods it best calls. 

Does that make sense?

**Comment by stamblerre** [comment]
It does, but then how should semantic tokens be registered? `textDocument/semanticTokens` doesn't seem to work when sent in `registerCapability`.

**Comment by dbaeumer** [comment]
Good find. This is actually more a bug in VS Codes implementation which happened when I renamed the requests. Let me have a look there.

**Comment by dbaeumer** [comment]
I fixed this in the LSP libraries. In the upcoming next version you can register using `textDocument/semanticTokens` which will be the correct key. Until then you can use `textDocument/semanticTokens/full` which was incorrectly used before.

**Comment by david-driscoll** [comment]
cc @gundermanc just so you're aware, this will affect the visual studio language client.

**Comment by gundermanc** [comment]
>cc @gundermanc just so you're aware, this will affect the visual studio language client.

What's the change exactly? AFAIK VS IDE does not yet support dynamic registration of capabilities.

**Comment by dbaeumer** [comment]
@gundermanc it only affects dynamic registration. No routes to request semantic tokens are still the same.
