### ISSUE TITLE
Proposal: treat `CompletionItem#description` as markdown

### ISSUE THREAD

**Issue by rictic** [Microsoft/language-server-protocol#111]
In the polymer language server we have the same documentation available for a symbol whether we're autocompleting it or giving the docs on hover. I expect most other servers to be in a similar boat. The markdown rendering for hover documentation is great, and we'd like to have similar rendering for the same content.

**Comment by svenefftinge** [comment]
In general whenever the LSP passes a strings to be displayed to the user (also showMessage for instance) it should allow the same kind of mark up. 
Always assuming markdown seems good enough to me.

**Comment by rictic** [comment]
@dbaeumer Yeah, I'm talking about `documentation`. No opinion on `details`.

**Comment by jrieken** [comment]
Yes - we have request to allow markdown in more places but haven't tackled that yet

**Comment by dbaeumer** [comment]
@jrieken cool. We keep it as a feature request then.

**Comment by felixfbecker** [comment]
The PHP stubs for the PHP standard libraries all contain HTML in their docblocks, which looks awful at the moment. Using markdown in docblocks is very common, and would also solve the HTML case, since markdown can contain HTML.

**Comment by jrieken** [comment]
> and would also solve the HTML case, since markdown can contain HTML.

fyi - we currently don't allow html in markdown

**Comment by felixfbecker** [comment]
Any reason why?

**Comment by jrieken** [comment]
script execution

**Comment by felixfbecker** [comment]
Good point, but I think it would be pretty easy to not allow any `<script>`, `<style>`, `onclick` etc. but only basic elements like `<b>`, `<br>`, `<table>`. If the markdown parser you're using doesn't provide this, [sanitize-html](https://www.npmjs.com/package/sanitize-html) is super easy to use.

**Comment by jrieken** [comment]
I still haven't found a complete list of `onclick` etc attributes...

**Comment by felixfbecker** [comment]
Instead of blacklisting all script execution attributes, you can just whitelist safe attributes. Normally you don't use that many attributes in HTML in markdown, it's mostly basic elements like the ones I mentioned above that could also be represented in markdown.

**Comment by rcjsuen** [comment]
Would also love it if the `documentation` field on `CompletionItem` supported Markdown.

**Comment by dbaeumer** [comment]
See https://github.com/Microsoft/vscode-languageserver-node/pull/276

**Comment by dbaeumer** [comment]
Implemented in the npm node modules as speced in the protocol in a backwards compatible way.

**Comment by dbaeumer** [comment]
Besides CompletionItem, SignatureHelp can provide Markdown as well.
