### ISSUE TITLE
Specification: clickable area for each section link is too large

### ISSUE THREAD

**Issue by utgwkk** [microsoft/language-server-protocol#1114]
Clickable area for each section link of [specification](https://microsoft.github.io/language-server-protocol/specifications/specification-current/) is too large (shown as green and blue areas in below figure).

![image](https://user-images.githubusercontent.com/4530627/97086305-53e1ab00-165d-11eb-8e2c-83e196d5a92a.png)

I think removing `padding-top: 100px;` and `margin-top: 100px;` from `.anchor` selector's style would fix this problem (I tried it with Chrome DevTools as below).

![image](https://user-images.githubusercontent.com/4530627/97086287-40364480-165d-11eb-96d5-0048958b5e16.png)

**Comment by rchl** [comment]
I think the intention of that is that when you have a link that scrolls directly to the header like:
https://microsoft.github.io/language-server-protocol/specifications/specification-current/#requestMessage
it is positioned below the sticky header. Otherwise, it would be covered by it.

**Comment by dbaeumer** [comment]
@utgwkk @rchl is correct. This is the reason for this and how bootstraps works with a navigation header. Closing.
