### ISSUE TITLE
Markdown issue: Backticks missing for $/

### ISSUE THREAD

**Issue by AndreasMatthias** [microsoft/language-server-protocol#1118]
The markdown file of the specification is missing some backticks for constructs like `'$/'`, which actually should be ```'`$/`'```. This is causing issues if you convert markdown to TeX output.

Here is a diff for file 'specification-3-16.md':

```
215c215
< Notification and requests whose methods start with '$/' are messages which are protocol implementation dependent and might not be implementable in all clients or servers. For example if the server implementation uses a single threaded synchronous programming language then there is little a server can do to react to a '$/cancelRequest' notification. If a server or client receives notifications starting with '$/' it is free to ignore the notification. If a server or client receives a requests starting with '$/' it must error the request with error code `MethodNotFound` (e.g. `-32601`).
---
> Notification and requests whose methods start with '`$/`' are messages which are protocol implementation dependent and might not be implementable in all clients or servers. For example if the server implementation uses a single threaded synchronous programming language then there is little a server can do to react to a '`$/cancelRequest`' notification. If a server or client receives notifications starting with '`$/`' it is free to ignore the notification. If a server or client receives a requests starting with '`$/`' it must error the request with error code `MethodNotFound` (e.g. `-32601`).
222c222
< * method: '$/cancelRequest'
---
> * method: '`$/cancelRequest`'
245c245
< * method: '$/progress'
---
> * method: '`$/progress`'
```

**Comment by dbaeumer** [comment]
Hmm, can you explain this. If at all I think it should go from '$/' ``$/``

**Comment by AndreasMatthias** [comment]
Well, I do not know the details of markdown. But here is what I figured out using pandoc like this:

```
pandoc -s -f markdown-raw_tex  specification.md  -o specification.tex
```

Pairwise dollar signs are interpreted as math delimiters
1. if they appear on the same line and
2. if the second $ is preceded by a non-whitespace character

This is why
```
'$/' xxx '$/'
```
will become
```
`\(/' xxx '\)/'
```
in LaTeX code. Note that `\(` and `\)` are the math delimiters in LaTeX. Note too, that this LaTeX-snippet is syntactically correct and thus will *not* produce any errors or warnings, but the result will be at least confusing. There's not a single dollar sign in the final output.

This wrong interpretation of the dollar sign can be corrected by putting it between backticks. Putting something between backticks like
```
`xxx`
```
will produce
```
\texttt{xxx}
```
in LaTeX code. The same for our $ expression:
```
`$/`
```
will become
```
\texttt{\$/}
```
And because a math equation can never start inside a code block (or inside `\texttt`) and end outside of it, pandoc will not interprete this dollar sign as a math delimiter.

BTW, it might be better to use ``` `$/` ``` that ``` '`$/`' ```, since the single quotes are superfluous here.

Please note, that I'm just observing what pandoc (version 2.11.0.4) is doing here. I do not know whether this is correct concerning the specification of markdown.

**Comment by dbaeumer** [comment]
Actually the meaning of a text in backticks in markdown is to treat it as a code span which means the content inside of the backticks is left as is. I have no problems removing the '' and replacing them with a backtick if it helps. Are you willing to prepare a PR?

**Comment by AndreasMatthias** [comment]
Using backticks seemed more intuitive to me. But then I saw that `'\r\n'` is using single quotes as well. So I suppose it would be more consistent to use single quotes for `$`, too. Therefor I will escape the dollar signs, and not use backticks. Escaping dollar signs will prevent them from being misinterpreted as math delimiters, too.

Yes, I'll prepare a PR.

**Comment by AndreasMatthias** [comment]
I'm afraid I messed up this PR. I did the changes on branch "gh-pages" but the PR seems to be agains "master". And I don't know how to fix this ....

**Comment by AndreasMatthias** [comment]
Ok, here's the corrected PR: https://github.com/microsoft/language-server-protocol/pull/1124
