### ISSUE TITLE
Why is rootPath a path and not a URI

### ISSUE THREAD

**Issue by felixfbecker** [Microsoft/language-server-protocol#113]
The whole protocol uses URIs. That is nice because a client can operate over any protocol, be it `file://`, `ftp://`, `git://` or whatever. But the `rootPath` is a path, and this essentially prevents any kind of indexing if the client operates on a protocol that is not `file://` or a remote host. It cannot set the `rootPath` if it is operating over FTP or git protocol, because there is not local root path, and the server can in turn not search that rootPath for source files (may it be through direct file system access or through a protocol extension). It would have to be a URI that points to the remote resource over the same protocol the client uses.

**Comment by felixfbecker** [comment]
This could be done in a backwards-compatible matter by deprecating `rootPath` and introducing a new param `rootUri`

**Comment by dbaeumer** [comment]
Agree. This should be fixed.

**Comment by dbaeumer** [comment]
Addressed for upcoming 3.0
