### ISSUE TITLE
Add table of contents to the specification

### ISSUE THREAD

**Issue by matklad** [Microsoft/language-server-protocol#114]
Hi!

Currently, the spec is a bit hard to read because there is no ToC which lists all methods/notifications and types. It might be a good idea to provide one! Take a look at the index at the bottom of the Dart server spec, for example, it is really convenient: https://htmlpreview.github.io/?https://github.com/dart-lang/sdk/blob/master/pkg/analysis_server/doc/api.html#Index.

**Comment by vladdu** [comment]
Also it would help to make it more visible which messages are client->server and which ones are server->client.

**Comment by vladdu** [comment]
I have added a TOC manually, but it would have been nicer if there was a machine-readable schema that could be used to generate the docs.

**Comment by dbaeumer** [comment]
Agree and I have an item to spec the protocol in JSON schema. Then we can have tools for various outputs. What do you think about using JSON schema for this.
