### ISSUE TITLE
3.16: didSave breaking change with (Versioned)TextDocumentIdentifier

### ISSUE THREAD

**Issue by poliorcetics** [microsoft/language-server-protocol#1147]
In rust-analyzer/rust-analyzer#6603 we found that in 3.15 the [`didSave`](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_didSave) notification has the following format for its parameters:

```typescript
interface DidSaveTextDocumentParams {
	/**
	 * The document that was saved.
	 */
	textDocument: TextDocumentIdentifier;

	/**
	 * Optional the content when saved. Depends on the includeText value
	 * when the save notification was requested.
	 */
	text?: string;
}
```

But in 3.16, the format for [`didSave`](https://microsoft.github.io/language-server-protocol/specifications/specification-3-16/#textDocument_didSave)'s parameters changed with:

```diff
-	textDocument: TextDocumentIdentifier;
+	textDocument: VersionedTextDocumentIdentifier;
```

But [`VersionedTextDocumentIdentifier`](https://microsoft.github.io/language-server-protocol/specifications/specification-3-16/#versionedTextDocumentIdentifier) **requires** a version field, making this a breaking change from 3.15 to 3.16.

Is this intended  or should `OptionalVersionedTextDocumentIdentifier` have been used ?

**Comment by dbaeumer** [comment]
I broke this when introducing `OptionalVersionedTextDocumentIdentifier`. I will correct the spec.
