### ISSUE TITLE
standardize dependency gathering

### ISSUE THREAD

**Issue by ags799** [Microsoft/language-server-protocol#115]
I appreciate that the [vscode-javac language server](https://github.com/georgewfraser/vscode-javac) reads `javaconfig.json` files for parsing a project's dependencies. It nicely separates the language server from the build system (read: it doesn't force you to use Maven).

I think it'd be nice to encourage this behavior with some standard by which a language server recognizes a project's dependencies. Eg, we could have all language servers expect some `language-server.json` configuration file at the root of each source set. This configuration file would include a list of paths to each of the project's dependencies (eg a list of `.jar` files).

If such a standard existed, build systems could offer plugins that generated these files. Eg a gradle plugin could offer a `generateLanguageServerConfiguration` task that created these `language-server.json` files. Maven could offer equivalent functionality, and different build systems and language servers would cooperate in harmony.

**Comment by rictic** [comment]
It seems like there wouldn't be a lot of commonality between different languages providing this functionality. i.e. a java jar is very different from an npm package name and version constraint, which is very different from a golang package url. It's hard to picture a tool that handles all of these kinds of dependencies in a consistent way.

**Comment by ags799** [comment]
That's a good point. But is there one consistency in that all such packages have to be downloaded to disk? Could all language servers read a list of paths to the downloaded dependencies (or their parent directories, to be more concise).

**Comment by rictic** [comment]
For node and golang, that behavior is already covered by existing tooling and conventions, and an additional configuration file would not provide any benefit.

**Comment by gracew** [comment]
agree that it doesn't make sense to define a new configuration format when each language already has conventions that work.

**Comment by bruno-medeiros** [comment]
One could make the case whether a cross-language dependency gathering and/or build system would be of value - maybe integrating with Gradle in some way. But in any case, this is totally independent of the LSP protocol and should remain so.

Remember, LSP is not *a framework for building/implementing language servers*. It's just a common interface for LS clients (IDEs, editors) so that they can handle multiple language servers by just handling one interface/protocol.

**Comment by dbaeumer** [comment]
I agree that the LSP should stay out of this. I will close the issue.
