### ISSUE TITLE
prepareRename: what is defaultBehavior, rationale

### ISSUE THREAD

**Issue by nbfalcon** [microsoft/language-server-protocol#1151]
LSP 3.16 will introduce a new response to `textDocument/prepareRename`: `defaultBehavior`. However, from the spec, I am not 100% sure how to interpret such a response: "if [ ... ] is returned, the rename position is valid and the client should use its default behavior to compute the rename range".

Does this mean that servers could always return `defaultBehavior` when renaming is possible, or only in some yet-unspecified "obvious" cases, like the c-style identifier under the cursor? Renaming might be more complex in certain cases, e.g. for labels in C/Lua, which should include the colon in the rename range. Should a client then implement language-specific behavior to determine rename ranges?

Also, what is the purpose of this response, and what can be gained by implementing it client-side (to conserve traffic, ...)?

Related discussion: https://github.com/emacs-lsp/lsp-mode/pull/2353#issuecomment-732788423.

**Comment by dbaeumer** [comment]
This got added for the following cases: a server only wants to change the range in one case. In all other cases it is happy with the editor's default behavior. In 3.15 the server either needs to handle all cases or none. With the new 3.16. the server can only treat the one case special and let the client use its default to compute the rename range.

**Comment by dbaeumer** [comment]
Does that make sense?

**Comment by nbfalcon** [comment]
Thank you for answering! That clears things up a bit, at least my first question.

However, it is still unclear to me what the default behavior should be, i.e. in what cases the server should *not* respond with `defaultBehavior`? I am implementing this for the `lsp-mode` client, and as such need to provide some sort of default range behavior. Should clients only send the capability for certain language servers where they know that the `defaultBehavior` has been implemented, or can it be implemented generically, perhaps using the identifier at point as defined by the language's syntax? (dashes are allowed in LISPs, while not in C for example). Would you consider renaming a C-style label `defaultBehavior`?

```c
int main() {
    label:/* cursor here, "label:" should be marked */ goto label;
}

Also, what do we stand to gain by implementing this client-side? Wouldn't this just increase the complexity of servers?

Sorry for the many questions.

**Comment by dbaeumer** [comment]
Using the identifier at the point as defined by the language's syntax is what VS Code does as the default behavior. I stayed away from specing this since it will force clients to implement what we in LSP think that is right and therefore blocks innovation on the client side.

**Comment by nbfalcon** [comment]
Thank you! Leaving this unspecified might not be that good though, because clients and servers need to coordinate here: a server needs to know in what cases `defaultBehavior` is acceptable.

**Comment by dbaeumer** [comment]
I see the point and what we usually do if this becomes necessary is that we add a value set capability to the client explaining which default behavior the client uses. But to do so we first need to get some feedback from clients about there different default behaviour.

**Comment by yyoncho** [comment]
@dbaeumer 

> This got added for the following cases: a server only wants to change the range in one case. In all other cases it is happy with the editor's default behavior. In 3.15 the server either needs to handle all cases or none. With the new 3.16. the server can only treat the one case special and let the client use its default to compute the rename range.

What do you mean by "all cases"? Can you give an example when the server would prefer to return defaultBehaviour and when the same server would prefer to return range? 

As a side note, not defining the behaviour usually means that the server developer will test with vscode and then the other clients should mimic what vscode does even for the cases it does not make sense. This happened with completion prefix calculations.

**Comment by dbaeumer** [comment]
> What do you mean by "all cases"? Can you give an example when the server would prefer to return defaultBehaviour and when the same server would prefer to return range?

I think this really depends on the server. One case is for example html where the client can't easily determine how words with a `-` in it should be handled on rename.

> As a side note, not defining the behaviour usually means that the server developer will test with vscode and then the other clients should mimic what vscode does even for the cases it does not make sense. This happened with completion prefix calculations.

I see this but I can't specify something I don't know. As said I am happy to specify different default behaviors and make them a client capability if someone lets me know how other clients handle this.

**Comment by yyoncho** [comment]
> I think this really depends on the server. One case is for example html where the client can't easily determine how words with a `-` in it should be handled on rename.

So the idea is:

The user is on `foo` - the server knows that the client can calculate that `foo` can be calculated by the client and returns defaultBehaviour.
The user is on `foo-bar` - the server knows that the client cannot calculate the proper range and returns it in the response.

**Comment by nbfalcon** [comment]
@dbaeumer is the syntax for identifiers language-specific, or is a c-like language assumed? I.e. could a hypothetical CommonLisp server respond with `defaultBehavior` if the cursor is on a symbol containing hyphens?

Could `defaultBehavior` be returned if the placeholder and thing being renamed are different? (Specific example: cursor is on a C label, the range is the entire label with colon, but the placeholder is only the identifier without the colon; in `lsp-mode`, we underline the thing being renamed, as determined from the rename range)

If I understood you correctly, by "client innovation", you are thinking of something like the client implementing some sort of live-rename based on `textDocument/documentHighlight` if `defaultBehavior`is returned?

A final thought: for specs like these, coordination between servers and clients is needed, and as such the `defaultBehavior` must be specified. Clients need to know how they should handle `defaultBehavior`, and servers need to know when they can send it. If this is left as is, the "do what VSCode does" situation described by @yyoncho will occur. I don't think the issue here is that various clients can do this best in different ways, but that they wouldn't know at all.

**Comment by dbaeumer** [comment]
The syntax is usually language specific. There is an item in the LSP land to make client and server 'agree' on that syntax since it is currently duplicated (on the client side and the server side).

> Could defaultBehavior be returned if the placeholder and thing being renamed are different? 

IMO yes, but it might depend on the client. 

I agree with the specification part. But I don't want to put in VS Code behavior into the specification since it will equally force clients to implement what VS Code is doing. This is why I opt to have a client capability that describes the client behavior. @yyoncho  and @nbfalcon what do you think the clients you know would / should do. Can you specify this for me?

**Comment by dbaeumer** [comment]
I converted the capability to an enum to make it more clear that the default bahavior is expandable. Fell free to spec some if you client does something different than selecting the language identifier.
