### ISSUE TITLE
Is any client using partialResultToken?

### ISSUE THREAD

**Issue by alanz** [microsoft/language-server-protocol#1153]
I have an [issue with the timing of code lens requests](https://github.com/erlang-ls/erlang_ls/issues/808), and want to be able to send additional results through as they come available on the server. The new partial results mechanism seems perfect for this.

But as I understand the spec, they are signalled by each individual request from the client having a [`partialResultToken`](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#partialResults) in it.

A basic search over github and my local installed clients does not show this being set in any client. And is only set in test code, as far as I can tell.

Is there an example anywhere of how to enable it in say a vscode client?

**Comment by rwols** [comment]
It is certainly one of the hardest things to implement for a client (in a general way). It's also a chicken-and-egg problem: if no language servers have support for partial results, then what's the point of implementing it? I was hoping that some language servers would start implementing support for especially textDocument/references, but no dice so far. I would be happy to see a language implementing it for textDocument/codeLens though (or even workspace/symbol).

**Comment by alanz** [comment]
I am happy to do this in two language servers (erlang-ls and haskell-language-server), but it is not clear to me what changes are needed on the vscode client side to enable it to start sending the tokens in the first place.

My understanding is that if the client supports the feature, it can always send the token. Servers that do not use it can ignore it, those that do, or need to for a particular request, can do that.  So it should be a safe default to have on.

**Comment by dbaeumer** [comment]
The client that currently support partial result tokens is the one for Visual Studio (you read correctly :-)).

Adding support for this for VS Code is quite some wrong since none of it's UI is build for this.

**Comment by alanz** [comment]
@dbaeumer Can you please clarify your reply above?

Does it mean that the protocol supports it, but the UI does not (yet)?  In which case we should continue waiting until it does.

**Comment by dbaeumer** [comment]
@alanz the protocol supports it but the VS Code implementation doesn't since VS Code has no partial result support in its API. As soon as something like this becomes available in VS Code I will adopt the VS Code LSP libraries accordingly.

I am closing the issue since there is nothing I can do in the protocol layer.
