### ISSUE TITLE
Server capability `codeActionProvider.resolveSupport` --> `codeActionProvider.resolveProvider`

### ISSUE THREAD

**Issue by rwols** [microsoft/language-server-protocol#1158]
The 3.16 spec for textDocument/codeAction talks about

> The server capability `codeActionProvider.resolveSupport` signals that a server will offer a `codeAction/resolve` route.

It should say

> The server capability `codeActionProvider.resolveProvider` signals that a server will offer a `codeAction/resolve` route.

**Comment by dbaeumer** [comment]
Good catch
