### ISSUE TITLE
Can the client issue window/workDoneProgress/cancel for any progress token?

### ISSUE THREAD

**Issue by kjeremy** [microsoft/language-server-protocol#1159]
Can we expect the client to be able to cancel any tokens (for instance if there's an error) created with `window/workDoneProgress/create` or only those marked as `cancellable` in `WorkDoneProgressBegin` or `WorkDoneProgressReport`?

**Comment by dbaeumer** [comment]
I think for server created progress the server should expect to receive `window/workDoneProgress/cancel` for all progress token. The cancellable is more for the UI to show a cancel button. The client still might to decide to send cancel in other situations as well. Does that make sense?

**Comment by kjeremy** [comment]
Yes that makes complete sense. It just isn't called out in the documentation that that's a possible case.
