### ISSUE TITLE
[textDocument/formatting] FormattingOptions turned explicitely optional

### ISSUE THREAD

**Issue by nicobao** [microsoft/language-server-protocol#1166]
Hi!

The whole point of an external formatter is to have an external source of truth that tells you whether your file is formatted correctly, and enforces its formatting if necessary, so a team can agree on a shared formatting independently of their IDE or text editors.

In vim, as opposed to VSCode, the tabulation/space settings are very special. There is no support for project-specific configuration without plugin.
Besides, there are plugins like https://github.com/tpope/vim-sleuth that dynamically changes the tabulation options, adapting itself to the style of the edited file. 

Currently, coc.nvim is systematically sending vim-specific tabulation configuration via the "options" fields in "textDocument/formatting" messages. Then, what happens when you edit a wrongly edited files while using vim-sleuth plugin? It keeps the wrong indentation!

I think, some language servers may currently not handle well the absence of these options. 

**I suggest a clarification in the specification which states that the `FormattingOptions` parameters for `textDocument/formatting` are all optional. Make it clear that this field can be empty or omitted entirely.**

For more background about the problem, you can refer to these issues that pop up frequently ("formatting does not work") in the vim world:

https://github.com/neoclide/coc-java/issues/132

https://github.com/neoclide/coc-prettier/issues/1#issuecomment-721696534 

I suspect the situation may be similar in emacs or other editors.

**Comment by nicobao** [comment]
I just realized that I forgot to add that the changes would also affect `rangeFormatting` and `onTypeFormatting`.

**Comment by dbaeumer** [comment]
I looked into this and it is very hard to change now since it is a breaking change. I can't simply make the fields optional since in the specification right now `tabSize` and `insertSpaces` are defined mandatory. 

All I can recommend on an implementation side in Vim is to not send the request to a server if the two values are not known and tell the user that these need to be configured (in an VIM specific way).

I will close the issue. Please ping if there is some other solution on how to solve this.

**Comment by nicobao** [comment]
@dbaeumer  Thanks for your answer.
We could create two new fields, with a different name that are optional:
- `optTabSize`,
- `optInsertSpaces`

And deprecate the two old fields `tabSize` and `insertSpaces`. We can keep them for a few minor versions and remove them in a new major version of the spec.

The implementation could be so that `optTabSize` should be considered first if non-null else the old ones.

**Comment by dbaeumer** [comment]
Besides the fact that the protocol uses semver what should a server do if they are missing. These two values are so fundamental to formatting that I would say if they are not know VIM should sent send. VIM could also use an approach were it infers the settings based on the current file (VS Code does the same if not known)

**Comment by puremourning** [comment]
I don't think this is a protocol issue per se. The servers can just ignore the user's editor settings if they know better, e.g. based on filesystem of project configuration.

As an example, I'm pretty certainly that clangd actually just ignore what the client editor supplies and use what's specified in `.clang-format`. The java language server could do the same via a setting.

**Comment by dbaeumer** [comment]
That is true as well.

**Comment by nicobao** [comment]
The Java Language Server uses the Eclipse Formatter standard: https://github.com/redhat-developer/vscode-java/wiki/Formatter-settings

It's an xml file defining the formatting rules.
Currently the server doesn't ignore the rules when fed with the lsp formatting options, contrary to clangd.
This is the server: https://github.com/eclipse/eclipse.jdt.ls
I'll open an issue to ask them if they can ignore the values when a specific formatting file is specified.

Thanks for your inputs.
