### ISSUE TITLE
Explicitly requesting a code snippet

### ISSUE THREAD

**Issue by robertoaloi** [microsoft/language-server-protocol#1174]
_Snippets_ are a great LSP feature, but they are currently tightly coupled with _completions_. In the [Erlang Language Server](https://erlang-ls.github.io/) we would like to allow developers to use snippet even not in combination with completion.

A sample use case is to add `edoc` annotations (The Erlang equivalent of `javadoc`) to functions.

Say you have a `sum/2` function:

```
sum(A, B) ->
  A + B.
``` 

We would like the user to request an "edoc snippet", which would add the following:

```
%%------------------------------------------------------------------------------
%% @doc Function name
%% Write some docs
%% @end
%%------------------------------------------------------------------------------
sum(A, B) ->
  A + B.
```

Today we are _abusing_ a `snippet_` prefix in the snippet label to achieve this (see https://erlang-ls.github.io/articles/snippets-are-here/), but it would be much cleaner for the client to be able to request a specific snippet.

This would also open to more powerful snippets. For example, the _placeholders_ above could be automatically expanded to:

```
%%------------------------------------------------------------------------------
%% @doc sum/2
%% Write some docs
%% @end
%%------------------------------------------------------------------------------
sum(A, B) ->
  A + B.
```

Thoughts?

**Comment by mickaelistria** [comment]
It looks similar to #592 . I have the impression that basically any TextEdit sent from server to client should be able to define some snippets for client to enable after applying the text edit. Would that work in your case?

**Comment by dbaeumer** [comment]
@robertoaloi how would a user trigger this. Via code actions as @mickaelistria pointed to?

**Comment by robertoaloi** [comment]
Hi @dbaeumer a code action would be a good start.

**Comment by dbaeumer** [comment]
In that case I argue that we fold this as a dup of #592
