### ISSUE TITLE
Consider LinkedEditingRange limitation

### ISSUE THREAD

**Issue by hrsh7th** [microsoft/language-server-protocol#1177]
Hi, The new `textDocument/linkedEditingRange` is cool. I hope some language server provides onTypeRename for variable identifier by this feature.

Currently, the LSP spec says `the ranges cannot overlap` but I think it is not enough for clarification.
I think `The ranges cannot adjacent and overlapped` is better.

The linkedEditingRange has no `current range id` unlike snippets so this spec has possibility of undefined behavior.

What do you think about it?

**Comment by dbaeumer** [comment]
@aeschli can you please comment if you think such a constraint is necessary. IMO it is not.

**Comment by hrsh7th** [comment]
If the range is adjacent. The below case will being undefined behavior, I think.

```
IdentifierIdentifier
~~~~~~~~~~__________
```

If the user insert text when the cursor is placed as `Identifier%CURSOR%Identifier`, I don't know the correct results.

1. `Identifier(modified)Identifier(modified)`
2. `(modified)Identifier(modified)Identifier`

The snippet has no problem because it has `current_tabstop` internally.

**Comment by aeschli** [comment]
We spec how languages can provide linked ranges but we have so far avoided to spec how editors should implement linked editing. I personally would prefer to keep it like that. 

@hrsh7th Out of curiosity, is there a real-world example where two identifiers are adjacent with no separator?
We also have the regexp that comes with the ranges that can help the editor to find out which range should be used as the new identifier content.

**Comment by hrsh7th** [comment]
@dbaeumer @aeschli 
Thank you for your response.

> We spec how languages can provide linked ranges but we have so far avoided to spec how editors should implement linked editing. I personally would prefer to keep it like that.

Okay. I've understood.


> Out of curiosity, is there a real-world example where two identifiers are adjacent with no separator?
I have no real-world example.
This question came from my thoughts experiment at the implementing linkedEditingRange as vim-plugin.
As you said, this situation would not appear in the real-world may be so I'm thinking now this is a trivial question.

Thank you very kind response. I will close it.
