### ISSUE TITLE
LSP support on visual studio 2019

### ISSUE THREAD

**Issue by fbredy** [microsoft/language-server-protocol#1184]
Hello,

I’m reporting a problem in Microsoft.VisualStudio.LanguageServer.Client.
i'm working on a Language Extension. I'd like to plug a Language Server.

I try to use the MS.VisualStudio.LanguageServer.Protocol but i have a problem because it does not respect the entire Protocol Specification 3.15 (https://microsoft.github.io/language-server-protocol/specifications/specification-current/).

The enum Microsoft.VisualStudio.LanguageServer.Protocol.CodeActionKind does not have the value "empty". This produce an exception when i initialize my server.

Could you fix this by adding the value Empty on the CodeActionKind enum?

regards, François

**Comment by rcjsuen** [comment]
@fbredy You should take this up through Visual Studio's official support channels. This repository is for discussing the protocol's specification and not really for raising bugs with implementations of clients and servers.

**Comment by dbaeumer** [comment]
@rcjsuen is correct. 

@tinaschrepfer FYI.

**Comment by rwols** [comment]
> This produce an exception when i initialize my server.

Note that a client advertises exactly which code action kinds it supports, or even if it supports code actions in the first place. You should design your server implementation around these "client capabilities" so that your server will work for any client.
