### ISSUE TITLE
Specify supported language in capabilities

### ISSUE THREAD

**Issue by njames93** [microsoft/language-server-protocol#1187]
Hi,

Sometimes language servers may be able to operate on multiple languages, however the supported capabilities of the server may not be implemented or even make sense on all the languages it supports.

A simple example of this is a `c++` language server, As `c++` is nearly a super-set of `c`, it makes sense that the language server should also support `c`.
As `c++` is object orientated, it makes sense to enable the `implementationProvider` in the server capabilities.
Whereas in `c` it doesn't make sense to offer this capability,
This leaves us in a less than ideal situation, we can either lose the ability in `c++` or have a client that thinks we can use `implementationProvider` in `c`.
There could also be a case where the server could be made to support a feature in both languages but, for whatever reason, the maintainers just haven't got round to adding it in yet, in which case we are again left in the same less than ideal situation.

The specifics of implementing this would likely be an array of supported languages for each provider type. An unspecified/empty array would indicate that the provider is enabled for all languages the server supports.

In order for this to work, the client would likely need to broadcast the languages it recognises to the server in its initialisation.
One possible way this could be done is by extending `InitializeParams` with a field `SupportedLanguages?: string[] | null`. It should be up to the server to match those Languages against what it knows. If a value is not passed, then the server 

It would then be up to the client to match each open file with the language it's determined its working on, with the features the server supports for that language.

**Comment by Aerijo** [comment]
Do [dynamic registration](https://microsoft.github.io/language-server-protocol/specifications/specification-3-14/#client_registerCapability) do what you want? The example in that section shows how requests can be limited to a language. I believe the client determines the language though, which could be annoying if people use `.c` for C++ files.

**Comment by rwols** [comment]
Yes, this is exactly what dynamic registration is for.

**Comment by dbaeumer** [comment]
@njames93 please ping if dynamic registration doesn't address your issue.

**Comment by njames93** [comment]
That seems to do what I want, thanks.
