### ISSUE TITLE
What is the purpose of signatureHelp context options?

### ISSUE THREAD

**Issue by ceronman** [microsoft/language-server-protocol#1196]
Hello.

The `SignatureHelpContext` type has been introduced in `3.15.0`.  It's not clear enough from the documentation what are the practical uses for this context or how it should be implemented. I'm looking for more information about what is the purpose for this context information and perhaps see a reference implementation in any language.

Right now, my intuition tells me that this can be used to provide proper signature help in the case of moving the cursor inside a function call using other function calls as parameters. For example:

```
foo(1, 2, bar(x, y, z))
    ^         ^
    |         |
   pos1      pos2
```

If signature help is originally triggered in `pos1` and then the cursor is moved to the right via keyboard until `pos2`, we probably want to continue displaying signature help for `foo` and not for `bar`.

Is this correct? What other use cases did you have in mind when adding `SignatureHelpContext`?

Thanks.

**Comment by dbaeumer** [comment]
SignatureHelp is usually shown on typing not when moving the cursor. The `activeSignatureHelp` property is used to help with method overloads to signal the currently chosen overload in the UI. The `retrigger` is for the case that the user types nested function calls.

**Comment by bstaletic** [comment]
Ll  l.

**Comment by dbaeumer** [comment]
I will close the issue. Hope that above comment has answered it.
