### ISSUE TITLE
snippet syntax: if/else semantics are poorly documented

### ISSUE THREAD

**Issue by leungbk** [microsoft/language-server-protocol#1202]
```
format      ::= '$' int | '${' int '}'
                | '${' int ':' '/upcase' | '/downcase' | '/capitalize' '}'
                | '${' int ':+' if '}'
                | '${' int ':?' if ':' else '}'
                | '${' int ':-' else '}' | '${' int ':' else '}'
```

It's not clear to me when the `if` and the `else` replacements are used. If the corresponding match group fails, then does that mean we use the `else` as replacement text, and if so, where exactly in the transformed string is it placed?

**Comment by dbaeumer** [comment]
Since we aligned this with TextMate a good source is their documentation as well.

**Comment by leungbk** [comment]
This from SO explains it:

https://stackoverflow.com/questions/57381007/vscode-if-else-conditions-in-user-defined-snippet

**Comment by dbaeumer** [comment]
Cool, wasn't aware of that answer.
