### ISSUE TITLE
Add better documentation on how clients should handle file renames

### ISSUE THREAD

**Issue by Kered13** [microsoft/language-server-protocol#1203]
I am in the process of implementing an LSP client, but reading the spec I cannot figure out how I should handle file renames.

* There are the workspace/willRenameFiles and workspace/didRenameFiles methods, but servers are not required to support them.
* The other logical option seems to be to issue a textDocument/didClose followed by a textDocument/didOpen with the new file name.
* If a server does support the workspace operations, should didClose and didOpen still be sent?
* If so, then should they be sent before or after willRenameFiles and didRenameFiles?

**Comment by dbaeumer** [comment]
Good point. The recommended way on a file rename is to sent a close with the old file and a open with the new file.

**Comment by DanTup** [comment]
> The recommended way on a file rename is to sent a close with the old file and a open with the new file.

Slightly related to #1263 - what about if the rename is only changing case?

Right now, VS code does _not_ send a Close/Open in this case for macOS or Windows (regardless of whether the filesystem is actually case-sensitive or not). However it _does_ send rename events (but continues to use the old casing for everything going forwards). This seems inconsistent and makes it difficult for servers to handle these types of renames.

**Comment by dbaeumer** [comment]
I personally think that using whatever name the system started to use on case insensitive file systems is the right thing to do. There is actually no guarantee that the initial name had the casing as stored on disk.
