### ISSUE TITLE
Can the globstar and glob metacharacters appear within braces?

### ISSUE THREAD

**Issue by leungbk** [microsoft/language-server-protocol#1204]
The spec describes the glob syntax as

``` typescript
        /**
	 * Glob patterns can have the following syntax:
	 [...]
	 * - `{}` to group conditions (e.g. `**​/*.{ts,js}` matches all TypeScript
	 *   and JavaScript files)
	 [...]
	 */
```

I see that VSCode's glob syntax permits patterns like `{**/*.c,**/*.h}`. Does the LSP also permit this kind of pattern (it is not obvious what is meant by a "condition")?

**Comment by dbaeumer** [comment]
Patterns are supported in `{}`
