### ISSUE TITLE
How can I disable completion in a client that does not support dynamic registration?

### ISSUE THREAD

**Issue by sumneko** [microsoft/language-server-protocol#1205]
The language service I developed provides a setting that allows users to turn off auto-completion. In VSCode, I do not statically register the auto-completion function during initialization, but after reading the user's settings using `workspace/configuration`, I then dynamically register the auto-completion function. Every time the user modifies this setting, I can also support runtime modification through dynamic registration or unregistration.

In some clients that do not support dynamic registration, it is obviously unable to support runtime modification, so I only plan to support the decision to statically register this function according to the user's settings during initialization. If the user modifies this setting, he must restart the extension for the modification to take effect. However, I found that this cannot be achieved because the server cannot read the user's settings before static registration.

Is there any way to solve this problem?

**Comment by dbaeumer** [comment]
Two options:

- on the client side you can restart the server if that setting changes.
- or you return an empty array or undefined from the request.

Closing. Please ping if there are other ideas.

**Comment by sumneko** [comment]
Maybe I didn't express it clearly.
The main problem is that the server needs to register its auto-completion capabilities in the `initialize` protocol, but at this time the server cannot obtain the user's settings, and the client will return `" error [-32601]: Unhandled method workspace/configuration"` .

**Comment by rwols** [comment]
workspace/configuration is guarded by a client capability I believe. So you can check if the client has that capability and act accordingly.

**Comment by sumneko** [comment]
> workspace/configuration is guarded by a client capability I believe. So you can check if the client has that capability and act accordingly.

see https://microsoft.github.io/language-server-protocol/specifications/specification-3-17/#initialize
It sais: "In addition the server is not allowed to send any requests or notifications to the client until it has responded with an InitializeResult".
Therefore, the client returns an error as expected.

**Comment by sumneko** [comment]
> Two options:
> 
> * on the client side you can restart the server if that setting changes.
> * or you return an empty array or undefined from the request.
> 
> Closing. Please ping if there are other ideas.

Neither of these two options are feasible.

1. After the server restarts, it is impossible to obtain whether the user has auto-completion enabled, because the static registration must be completed in the `initialize` stage, and the server is not allowed to request `workspace/configuration`.
2. The effect of not registering the ability to complete automatically is different from returning an empty array after registering the ability. As shown in the VSCode in the figure below, the left picture shows no registration, and the right picture returns an empty array after registration.

![completion-unregister](https://user-images.githubusercontent.com/5213431/108491961-8afc5c00-72df-11eb-83a4-96b46c52cbd2.gif) ![completion-return-empty-array](https://user-images.githubusercontent.com/5213431/108491982-90f23d00-72df-11eb-98da-aefbcc08a010.gif)

**Comment by dbaeumer** [comment]
OK. I see. The best way to handle is to use the `initializationOptions` (see https://github.com/microsoft/vscode-languageserver-node/blob/master/protocol/src/common/protocol.ts#L983) property on the initialize params to convey the setting on startup to the server. 

However you would still need to restart the server when that setting changes.

**Comment by sumneko** [comment]
The problem with this solution is that the client needs to customize the language service, which violates the design purpose of the LSP.
In addition, restarting the language service is not a problem, we don’t need to pay attention to it.

**Comment by rwols** [comment]
I got confused because you keep mentioning "dynamic registration", but that doesn't seem applicable here at all. You're basically saying: "when a client doesn't understand `workspace/configuration`, or when a client doesn't notify `workspace/didChangeConfiguration`, then my server is not aware of changes to settings". Well yes, that is obviously true. IMO, it is a problem of the client. The best alternative is `initializationOptions`.

**Comment by sumneko** [comment]
> I got confused because you keep mentioning "dynamic registration", but that doesn't seem applicable here at all. You're basically saying: "when a client doesn't understand `workspace/configuration`, or when a client doesn't notify `workspace/didChangeConfiguration`, then my server is not aware of changes to settings". Well yes, that is obviously true. IMO, it is a problem of the client. The best alternative is `initializationOptions`.

It's my bad.
In my opinion this does not really solve the problem. There are currently several clients supporting my language server, and it is difficult for me to ask them all to support `initializationOptions`.
In addition, as I continue to develop, the content of this option will also change, which makes it more difficult to ask them to synchronize updates.

**Comment by dbaeumer** [comment]
I am actually out of ideas. The best would be to convince clients to implement dynamic registration. It got invented exactly for that purpose (e.g. a server can dynamically decide on the providers it wants to regsiter).

**Comment by sumneko** [comment]
> I am actually out of ideas. The best would be to convince clients to implement dynamic registration. It got invented exactly for that purpose (e.g. a server can dynamically decide on the providers it wants to regsiter).

I found that server is allowed to send limit requests like `window/showMessageRequest` during the `initialize`. How about also allowed to send `workspace/configuration` during the `initialize` ?

But this is really not important. The incomplete implementation of some clients causes some features of the server to fail, which is acceptable to users. The best way is indeed to urge them to implement these features.

**Comment by dbaeumer** [comment]
Regarding `window/showMessageRequest` on initialize: this is actually for backwards compatibility since it was allowed in a first version of the spec. If I could start new I would not allow this anymore. This is why I would like to keep messages during initialize at a minimum.
