### ISSUE TITLE
Clarify constraints on resource operations in a WorkspaceEdit

### ISSUE THREAD

**Issue by pisv** [microsoft/language-server-protocol#1206]
Originally, `WorkspaceEdit` was defined as:

```ts
export interface WorkspaceEdit {
	/**
	 * Holds changes to existing resources.
	 */
	changes?: { [uri: DocumentUri]: TextEdit[]; };
}
```

For `TextEdit[]` it is specified that

> All text edits ranges refer to positions in the document they are computed on. They therefore move a document from state S1 to S2 without describing any intermediate state.

It was then clear that a `WorkspaceEdit` (as originally defined) moved each of the `N` different documents from state `S1i` to `S2i` without describing any intermediate state. In other words, a `WorkspaceEdit` as a whole moved the workspace from state `S1` to `S2` (without describing any intermediate state), with all changes computed on and referring to state `S1`.

Now the question is whether this statement is still true when resource operations come into the picture.

Can it be said that each of the resource operations in a single `WorkspaceEdit` is computed on and referring to state `S1`, does not overlap with each other, and thus can be applied in any order, similar to what is specified for `TextEdit[]`? Otherwise, a `WorkspaceEdit` containing resource operations would no longer move the workspace from state `S1` to `S2` without describing any intermediate state.

To make it a bit more concrete, are the following workspace edits (taken individually) valid:

```js
// assuming 'file:/a.txt' does not exist
{
    documentChanges: [
        {
            kind: 'create',
            uri: 'file:/a.txt'
        },
        {
            kind: 'delete',
            uri: 'file:/a.txt'
        }
    ]
}
```

```js
// assuming 'file:/a.txt' exists
{
    documentChanges: [
        {
            kind: 'delete',
            uri: 'file:/a.txt'
        },
        {
            kind: 'create',
            uri: 'file:/a.txt'
        }
    ]
}
```

```js
// assuming 'file:/a.txt' exists, 'file:/b.txt' and 'file:/c.txt' do not exist
{
    documentChanges: [
        {
            kind: 'rename',
            uri: 'file:/a.txt',
            newUri: 'file:/b.txt'
        },
        {
            kind: 'rename',
            uri: 'file:/b.txt',
            newUri: 'file:/c.txt'
        }
    ]
}
```

In case such workspace edits are valid, validating whether a workspace edit can be executed on the client becomes a more difficult task, since it would need to take into account all side effects produced by the preceding operations in the workspace edit (before those operations have actually been executed) besides the current state of the workspace.

I'm sorry if this has already been discussed elsewhere. I could not find it in the specification or issues.

Thanks.

**Comment by pisv** [comment]
By way of example, if the workspace edit

```js
// assuming 'file:/a.txt' does not exist
{
    documentChanges: [
        {
            kind: 'create',
            uri: 'file:/a.txt'
        },
        {
            kind: 'delete',
            uri: 'file:/a.txt'
        }
    ]
}
```

is validated (before it is executed) against the current workspace state (only), it would be invalid (delete operation cannot be performed because 'file:/a.txt' does not exist).

However, if the above workspace edit is actually allowed by LSP, then validation must take into account not only the current workspace space, but also the effect that will be produced by the create operation, when determining validity of the delete operation.

Therefore, there seems to be two different ways in which workspace edits can be validated, and the choice between one way or another depends on whether workspace edits like the one above are considered valid by the specification.

I'm currently implementing resource operation support in a language client SDK, and would greatly appreciate a clarification from those in the know. Please let me know if more information is needed.

**Comment by pisv** [comment]
Just a note that this might affect not only validation but also preview of workspace edits.

Consider the following workspace edit:

```js
{
    documentChanges: [
        {
            kind: 'rename',
            oldUri: 'file:/b.txt',
            newUri: 'file:/a.txt',
            options: {
                overwrite: true
            }
        },
        {
            textDocument: {
                uri: 'file:/a.txt',
                version: null
            },
            edits: [
                {
                    range: {
                        start: {
                            line: 0,
                            character: 0
                        },
                        end: {
                            line: 0,
                            character: 3
                        }
                    },
                    newText: 'abc'
                }
            ]
        }
    ]
}
```

If this workspace edit is allowed according to the specification, then a preview of the text document edit needs to be done against an intermediate future state, rather than the current state. Assuming that `a.txt` is currently empty and `b.txt` currently has `xyz` as its contents, the preview of the text document edit for `a.txt` should display `xyz -> abc` rather than `<empty> -> abc`. And this is just a simple example.

Generally speaking, if workspace edits are actually allowed by the specification to describe intermediate state, supporting their validation/preview will require a rather complex infrastructure on the client, including the ability to 'dry run' changes against a comprehensive model of the workspace. Just as an example, even the Eclipse refactoring framework with its validation/preview infrastructure for changes (which is rather complex already) have no support for this.

So, the question still is: are such workspace edits really allowed?

**Comment by pisv** [comment]
OK. Seemingly, I have found an answer to my questions. Looking at the following comment for `workspace.applyEdit` API of VSCode, it seems clear that a workspace edit can indeed describe intermediate state, which is additionally confirmed by inspecting the actual implementation.

```ts
        /**
         * Make changes to one or many resources or create, delete, and rename resources as defined by the given
         * [workspace edit](#WorkspaceEdit).
         *
         * All changes of a workspace edit are applied in the same order in which they have been added. If
         * multiple textual inserts are made at the same position, these strings appear in the resulting text
         * in the order the 'inserts' were made, unless that are interleaved with resource edits. Invalid sequences
         * like 'delete file a' -> 'insert text in file a' cause failure of the operation.
         *
         * When applying a workspace edit that consists only of text edits an 'all-or-nothing'-strategy is used.
         * A workspace edit with resource creations or deletions aborts the operation, e.g. consecutive edits will
         * not be attempted, when a single edit fails.
         *
         * @param edit A workspace edit.
         * @return A thenable that resolves when the edit could be applied.
         */
        export function applyEdit(edit: WorkspaceEdit): Thenable<boolean>;
```
Probably it would be nice to include a similar comment in the spec. Otherwise, please feel free to close this issue.

**Comment by dbaeumer** [comment]
@pisv thanks for bringing this up and sorry for the late response. Was out of office. Yes, workspace edits with resource operations can describe intermediate states. Since these can fail LSP allows clients to describe how they will recover from this (see `FailureHandlingKind` https://github.com/microsoft/vscode-languageserver-node/blob/main/protocol/src/common/protocol.ts#L3173). I naively assumed that this makes it clear but I do agree that this deserves some clarification in the spec since clients can have different failure recoveries.

**Comment by pisv** [comment]
@dbaeumer Thank you for clarifying this. Yes, certainly `FailureHandlingKind` is a key. Unfortunately, I did not pay enough attention and did not understand its intent initially.

Anyway, I really appreciate the clarification you have added to the spec. Thanks!
