### ISSUE TITLE
Symbol kind for "print", as in the ubiquitous print("hello world") function/method.

### ISSUE THREAD

**Issue by pajatopmr** [microsoft/language-server-protocol#1213]
Of the 20+ symbol kinds in 3.16, I struggle while deciding which one to use when encountering a function call reference. And I struggle to find any guidance for a server developer in mapping specific language constructs onto the general LSP symbol kind options. The use case is in wanting to render a function definition different from a function call. This is clearly a question. Any suggestions or references?

It does occur to me that a server developer could benefit from a SymbolInformation description field where one could say something like: "Function kind is used here to mean a function call, whereas Method kind is used for the declaration", or some such.

**Comment by dbaeumer** [comment]
@pajatopmr symbol information are definitions by design (e.g. they describe the outline). If you want to render things different on usage then you might want to look into semantic tokens.

**Comment by pajatopmr** [comment]
@dbaeumer Thanks for the tip on semantic tokens.

The first part of your message makes no sense to me, probably because I am new to LSP. All I can garner from the spec is that workspace/symbol gets information on "project wide symbols", which to me says call references like "println", etc. But the servers that I look at seem to treat symbols as only named declarations. Confusing. Maybe semantic tokens will make more sense.
