### ISSUE TITLE
Specify whether to insert before or after the cursor during type formatting

### ISSUE THREAD

**Issue by sumneko** [microsoft/language-server-protocol#1214]
For this code (`$` is the cursor):

```lua
if true then$
```

When user press enter, I want to make it to
```lua
if true then
    $
end
```
instead of 
```lua
if true then
    $
```

Currently I tried `textDocument/onTypeFormatting`, and returns `textEdit[]` :
```json
[
    {
        "range": {
            "start": {
                "line": 1,
                "character": 4,
            },
            "end": {
                "line": 1,
                "character": 4,
            },
        },
        "newText": "\nend"
    }
]
```

However it results:
```lua
if true then
    
end$
```

I think this is because the client cannot determine whether the new text is inserted before or after the cursor based on my return information.
Is there a way to provide this information by the server? Or is there any other way to achieve this function?

![auto-end](https://user-images.githubusercontent.com/5213431/109967610-982c3880-7d2c-11eb-9284-d1113d9ee625.gif)

**Comment by rwols** [comment]
> Or is there any other way to achieve this function?

Yes. When the user is at this point in time:

```lua
if true t$
```

then provide a snippet completion that inserts the whole thing: `then\n\t$0\nend`

**Comment by sumneko** [comment]
> > Or is there any other way to achieve this function?
> 
> Yes. When the user is at this point in time:
> 
> ```lua
> if true t$
> ```
> 
> then provide a snippet completion that inserts the whole thing: `then\n\t$0\nend`

you're right. This should be an completion feature, not a type formatting feature. What I thought before was too complicated.
