### ISSUE TITLE
textDocument/documentSymbol result question

### ISSUE THREAD

**Issue by pajatopmr** [microsoft/language-server-protocol#1215]
What is the rationale behind having the textDocument/documentSymbol result being an array of either SymbolInformation or DocumentSymbol types?

**Comment by rwols** [comment]
SymbolInformation is easier to implement. So it's easier to get something out the door. But prefer DocumentSymbol as clients can use the extra structure for a better presentation.

**Comment by KamasamaK** [comment]
The real answer is backward compatibility.  `DocumentSymbol` was added in v3.10.0. If `DocumentSymbolClientCapabilities.hierarchicalDocumentSymbolSupport` is not `true`, then you must provide `SymbolInformation`. If it is `true`, you should prefer `DocumentSymbol`.

**Comment by dbaeumer** [comment]
@KamasamaK thanks for jumping in.
