### ISSUE TITLE
Allowed ways of transmission?

### ISSUE THREAD

**Issue by zilti** [Microsoft/language-server-protocol#122]
What are the allowed ways of transmitting the language server JSON-RPC messages? HTTP? TCP? Sockets?

**Comment by gorkem** [comment]
There is no defined transmission protocol. Sockets and pipes are commonly used on the current implementations.

**Comment by dbaeumer** [comment]
See the discussion in https://github.com/Microsoft/language-server-protocol/issues/86. Closing in favor of that issue.
