### ISSUE TITLE
didChange without didOpen

### ISSUE THREAD

**Issue by mroch** [microsoft/language-server-protocol#1220]
It's been previously clarified in #436 that the client should not send `didChange` without sending `didOpen`.

What is intended if `TextDocumentSyncOptions.openClose` is `false` (or omitted) and `TextDocumentSyncOptions.change` is `Full` or `Incremental`? It seems that if the server says no didOpen/didClose events, then the client is not allowed to obey the `change` option.

**Comment by dbaeumer** [comment]
Yes, that is correct. The reason is that otherwise it is not guaranteed that both client and server start on the same content for the first change event.

Please ping if something is still unclear.

**Comment by mroch** [comment]
Thanks. It could be a little more clear in the spec if the description of `changes` said that `openClose` is required to also be true. 

Is the same true of didSave? Can the client save without didOpen?
