### ISSUE TITLE
Does 'falsy' field accept null?

### ISSUE THREAD

**Issue by rhysd** [microsoft/language-server-protocol#1222]
For example, [LSP v3.1.6](https://microsoft.github.io/language-server-protocol/specifications/specification-current/) says that `insertText` field is falsy.

```
	/**
	 * A string that should be used when filtering a set of
	 * completion items. When `falsy` the label is used as the
	 * filter text for this item.
	 */
	filterText?: string;
```

There is no definition about 'falsy', but I think falsy values are `false`, `0`, `""`, `null`. In above case, does `insertText` accept falsy value `null` which is other than `string`?

I faced this in real implementation of language server. [zls](https://github.com/zigtools/zls) returned `null` as falsy value in `insertText` field. However [vim-lsp](https://github.com/prabirshrestha/vim-lsp) didn't assume `null` value in `insertText`. I want to know which one should be fixed. (Though I've already added fix to vim-lsp this time).

**Comment by Aerijo** [comment]
The types don't match well with JSON, as `foo?` is [shorthand for `foo | undefined`](https://www.typescriptlang.org/docs/handbook/2/functions.html#optional-parameters), but JSON doesn't have an `undefined` keyword. In TS though, undefined is also taken as the field being omitted entirely. So, strictly from the type, it can be `string` omitted entirely.

Falsy would then be the empty string or when the field is not present. `null` would be an incorrect value to use, so the `zls` is not compliant (unless there is some document somewhere with a different definition of `?` for JSON).

**Comment by dbaeumer** [comment]
@rhysd in LSP if a property can be `null` the type will explicitly be listed (e.g. `filterText?: string | null`). So falsy is only for ""  and undefined in this case. 

@Aerijo there is a subtle difference in TS between `prop?: string`  and `prop: string | undefined`. The first one allows to omit `prop` where the second doesn't. A literal explicitly needs to list `prop` with the `undefined`.

I will close the issue. Please ping if anything is unclear.

**Comment by rhysd** [comment]
@Aerijo @dbaeumer Thank you for clarification! I'll try to fix zls.

**Comment by Aerijo** [comment]
Oh yeah, it helps when reading the section on objects use of `?`

> we can mark those properties as optional by adding a question mark (`?`) to the end of their names.

> All optionality really says is that if the property _is_ set, it better have a specific type.
