### ISSUE TITLE
Is a client allowed to send exit notification before it receives the response to the shutdown request

### ISSUE THREAD

**Issue by natebosch** [microsoft/language-server-protocol#1226]
#1036 addresses the need for both the `shutdown` request and `exit` notification, and I think it hints that the client should wait and only send the `exit` after receiving a non-error response to a `shutdown` notification in the comment that talks about [vetoing the shutdown](https://github.com/microsoft/language-server-protocol/issues/1036#issuecomment-650050168).

Can this be explicit in the protocol?

**Comment by dbaeumer** [comment]
I updated the spec.
