### ISSUE TITLE
Spec clarification: Can a server send multiple registration options without unregistering first?

### ISSUE THREAD

**Issue by DavidGoldman** [microsoft/language-server-protocol#1227]
Let's say I'm working on my language server and I've checked and confirmed that the client supports `dynamicRegistration` for [executing a command](https://microsoft.github.io/language-server-protocol/specification#workspace_executeCommand).

1. My server sends a `ExecuteCommandRegistrationOptions` over to the client, containing 1 command, via [registerCapability](https://microsoft.github.io/language-server-protocol/specification#client_registerCapability)
2. Later on, my server dynamically creates/finds a new command to support, so now I have 2 commands that I want to support.
3. What should my server do?
   - Unregister the previous command then send a new `ExecuteCommandRegistrationOptions` containing both commands?
   - Don't unregister the previous command, instead send a new `ExecuteCommandRegistrationOptions` containing only the new command

**Comment by dbaeumer** [comment]
From a specification point of view both flows are valid and should be supported by clients that support dynamic registration.
