### ISSUE TITLE
how to implement LS in another language?

### ISSUE THREAD

**Issue by njamescouk** [microsoft/language-server-protocol#1230]
hi, vscode noob here.
I'm at home with implementing CGI servers in c++ and running them locally (on an air gapped machine).

my understanding is that a vscode language client sends queries to a server.

if I implement a language server and have it running at, say, http://localhost:123456 how does the client get the servers url? is this possible? is that how it works?

tia

**Comment by rcjsuen** [comment]
> if I implement a language server and have it running at, say, http://localhost:123456 how does the client get the servers url?

Not sure what you are trying to ask here. The client would have to know where the language server is and how to connect to it.

When you write your extension/plug-in for your language server in your LSP client of choice, you'll need to feed that information to the client somewhere.

**Comment by njamescouk** [comment]
ok, I was thinking vscode had to connect to my server.

so the situation is that when my client is invoked  it has to connect to my server, do the necessary, then hand back to vscode?

**Comment by rwols** [comment]
In practice, the "server" is usually a subprocess of the editor ("client"). So, the client starts the subprocess (your server binary), and then starts communicating with your subprocess either via stdin/stdout, or via a tcp socket, or via some other streaming method. The client is then also responsible for terminating the subprocess. You could also run your language server separately on another machine (or perhaps in a Docker container), awaiting new client connections, but that adds all sorts of complexity: how are you aware of the client's workspace? Should the client do path translation/mapping? Should the server do path translation? How do you handle more than one client?

**Comment by njamescouk** [comment]
I think I'm getting there!

for my purposes everything will (ok, might) run on a single air gapped machine. the first half of your reply is plenty to go at thanks.
