### ISSUE TITLE
Default insertTextMode

### ISSUE THREAD

**Issue by KamasamaK** [microsoft/language-server-protocol#1233]
In the spec, there's a reference to a default `insertTextMode` defined in the `textDocument.completion.insertTextMode` client capability.

Also, in https://github.com/microsoft/language-server-protocol/issues/83#issuecomment-723071967, it says

> - the client announces now a `insertTextMode` in the completion client capabilities. Currently support are `asIs` and `adjustIndentation`. This value signals the default behavior of the client

Either I'm missing something or that property is not defined where it should be.

**Comment by dbaeumer** [comment]
@KamasamaK the client capability is named `insertTextModeSupport`. Sorry for that. I adjusted the specs.

**Comment by KamasamaK** [comment]
@dbaeumer The only `insertTextModeSupport` is defined under `textDocument.completion.completionItem.insertTextModeSupport`. And it's a value array. Is the implication that the first element in the array is the client default? If so, the description does not make that clear.

**Comment by dbaeumer** [comment]
I misread your original comment. The property is indeed missing. I will add to the 3.17.0 spec since it does make totally sense to have the property.
