### ISSUE TITLE
Data type for `data`

### ISSUE THREAD

**Issue by KamasamaK** [microsoft/language-server-protocol#1235]
The data type for `data` sometimes uses `any` and sometimes uses `unknown`. In one instance, it uses `string | number | boolean | array | object | null`. This should be consistent.

**Comment by dbaeumer** [comment]
Agree.

**Comment by KamasamaK** [comment]
I think a type definition would be a good idea. This was also recommended by @aeschli in https://github.com/microsoft/language-server-protocol/pull/833#discussion_r335145613.

**Comment by dbaeumer** [comment]
Fully agree and Martin's proposal makes sense.
