### ISSUE TITLE
Is the labelDetailsSupport server capability still necessary?

### ISSUE THREAD

**Issue by mroch** [microsoft/language-server-protocol#1236]
in a previous iteration of 3.17, it looks like `CompletionItem.label` was a `string | CompletionItemLabel`, which necessitated the `completionItem.detailedLabelSupport` server capability (now `labelDetailsSupport`). but now it's a separate `labelDetails` field, so there's no longer any harm in the client sending it, is there? and if the completion item sent in the resolve request is just echoed back from the server, it wouldn't have label details if the server didn't send them in the first place.

it seems to me like an unnecessary complexity, but I'm curious if I'm missing additional justification for it.

ref c7874b246944937a3a11e0a3064265be05293ca7

**Comment by dbaeumer** [comment]
Agree. This got unnecessary since we have a separate property now.

**Comment by dbaeumer** [comment]
Removed from implementation and spec.
