### ISSUE TITLE
Why are the graphs in LSIF backwards?

### ISSUE THREAD

**Issue by masaeedu** [microsoft/language-server-protocol#1238]
This is just a matter of convention, but I find it somewhat confusing that an edge between the following data:

```
{ id: 1, type: "vertex", label: "document",
  uri: "file:///Users/dirkb/sample.ts", languageId: "typescript"
}
{ id: 4, type: "vertex", label: "range",
  start: { line: 0, character: 9}, end: { line: 0, character: 12 }
}
```

is represented like this:

```
{ id: 5, type: "edge", label: "contains", outV: 1, inVs: [4] }
```

whereas the illustrations choose the following (sensible) convention:

![image](https://user-images.githubusercontent.com/3674056/113540516-d341b600-95cf-11eb-94cb-baa8b57cb95e.png)

The "in" and "out" vertices of the hyperedge in question are flipped in the illustration and the data. This subverts an intuitive reading of a  `<verb>`-labeled-edge _from_ `<subject>` _to_ `<object>` as "`<subject>` `<verb>`s `<object>`", because it gives the backwards result "range contains text document".

Would it make any sense to make the text document the input edge, or to substitute "contains" with the dual relation "containedBy"?

**Comment by dbaeumer** [comment]
I am not sure I can follow this. The arrow in the diagram goes from outV (outgoing vertex) to inV (incoming vertex) and when read it is: `document contains range`.  This is how Gremlin defines the meaning and that is what we us in LSIF. If we flip the direction we would need to name the edge `belongsTo`. 

Does this clarify things.

**Comment by dbaeumer** [comment]
I will close the issue. Please ping if something is still unclear.
