### ISSUE TITLE
Error messages for go to definition requests?

### ISSUE THREAD

**Issue by yanmofeixi** [microsoft/language-server-protocol#1241]
Currently when there is no definition found for a symbol it shows "no definition found" like this.

![image](https://user-images.githubusercontent.com/2311828/114071560-1ad97380-9856-11eb-8603-3b03befcba6a.png)

I'm trying to display a custom error message about why this go to definition request fails, but DefinitionRequest only takes LocationLink[] | Location[] as response type so any string I returned will be discarded.

This would also be helpful when the language server is busy building compilation database, and we can display a message like "busy". Is it possible to include an error message field in the response of DefinitionRequest (or other textDocument requests)?

**Comment by rwols** [comment]
> Is it possible to include an error message field in the response of DefinitionRequest (or other textDocument requests)?

Yes. **Any** response may also be an ErrorResponse.

https://www.jsonrpc.org/specification#response_object
https://microsoft.github.io/language-server-protocol/specification#responseMessage

Although, it'll depend on the particular client on how errors are presented.

**Comment by dbaeumer** [comment]
@rwols is correct. 

However I am unsure if VS Code will show the message in the UI. I think it only does this for `prepareRename` requests.

You could also look into intercepting this in the middleware to show some status bar indication in that case.

**Comment by dbaeumer** [comment]
I tested it and VS Code doesn't show the message provided in the exception. It uses its own way to denote it. However there is nothing I can do in LSP since the specification already allows to return an error.
