### ISSUE TITLE
When should a client invoke the new moniker API? 

### ISSUE THREAD

**Issue by keyboardDrummer** [microsoft/language-server-protocol#1243]
Since 3.16 there's a moniker API, `textDocument/moniker` ([reference](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_moniker)).

When is the client supposed to call this API? Given a file

```typescript
import { externalMethod } from 'externalPackage'

externalMethod("happyUser")
```

When the user runs `go to definition` on the `externalMethod` call, the client invokes `textDocument.definition` and jumps to the import. If the user runs `go to definition` on the import, what we would like is to open the public source of the external package in a virtual file and show that to the user. However, our client will invoke `textDocument.definition` again which I'm guessing will jump to compiled sources of `externalPackage` in the `node_modules` folder, which isn't what we wanted. 

At what point should the client invoke `textDocument/moniker` to figure out the imported symbol `externalMethod` is from an external repository?

**Comment by dbaeumer** [comment]
For normal development scenarios there is no need for a client to call that method. It is to connect LSP with LSIF (https://microsoft.github.io/language-server-protocol/specifications/lsif/0.5.0/specification/) which will allow to search for a symbol outside the current workspace. However this will always require an external service that accepts an moniker and then returns you LSP results for that moniker.
