### ISSUE TITLE
CodeActionContext.triggerKind

### ISSUE THREAD

**Issue by sam-mccall** [microsoft/language-server-protocol#1244]
From latest VSCode notes: https://code.visualstudio.com/updates/v1_55#_codeactioncontexttriggerkind

I assume this is intended for eventual inclusion in LSP (and needs to become stable in VSCode first), but wanted an issue to track.

This would be really useful for clangd: we've struggled a lot with the signal/noise ratio of code actions and conflation of available vs suggested actions. (Both in VSCode & other editors).

**Comment by KamasamaK** [comment]
This was finalized in VS Code 2 weeks ago, so will be in the next stable release.

https://github.com/microsoft/vscode/commit/16cff9cff93539b87a0a16ccc8dd09ddf542e7d5
