### ISSUE TITLE
Enable retrieving the selection tree of a document or a range of code

### ISSUE THREAD

**Issue by keyboardDrummer** [microsoft/language-server-protocol#1247]
Currently LSP contains the `textDocument/selectionRange` method which allows retrieving one path inside the selection tree of the document. The LSP client I'm working on wants to use the entire selection tree of the document. This tree can be constructed using the `textDocument/selectionRange` method but this has a high bandwidth overhead since a lot of duplicate data is returned.

Here are my use-cases for constructing a selection tree:
- For the "expand selection range" feature of IDEs, which allows developers to quickly select a particular piece of code, a low latency is critical, otherwise developers would be better off making the selection manually. For remote IDEs with a high latency to the development environment, calling `textDocument/selectionRange` can be too slow. Retrieving the selection tree of a range of code allows resolving "expand selection range" requests from the user with cached data.
- Apart from "expand selection range", the selection tree can be used for other forms of navigation such as "jump to previous/next sibling" to hop between functions, function call arguments,  statements, etc.
- The selection tree can help the developer understand the code, and can be visualised in a separate outline panel or using decorations in the editor.

Currently the `textDocument/documentSymbol` method already enables retrieving a hierarchy of document ranges, but only for named ranges. I propose to change `DocumentSymbolParams` to:

```typescript
export interface DocumentSymbolParams extends WorkDoneProgressParams,
	PartialResultParams {
	/**
	 * The text document.
	 */
	textDocument: TextDocumentIdentifier;

        /**
        * Whether to include symbols without a name in the hierarchy
        */    
        includeAnonymousSymbols: boolean,

       /**
        * The range of the document for which to retrieve symbols
        */
       range?: Range
}
```

And to change `DocumentSymbol` to:
``` typescript
export interface Symbol {
	/**
	 * The range enclosing this symbol not including leading/trailing whitespace
	 * but everything else like comments. This information is typically used to
	 * determine if the clients cursor is inside the symbol to reveal in the
	 * symbol in the UI.
	 */
	range: Range;

	/**
	 * Children of this symbol, e.g. properties of a class.
	 */
	children?: Symbol[];
}

export interface DocumentSymbol extends Symbol {

	/**
	 * The name of this symbol. Will be displayed in the user interface and
	 * therefore must not be an empty string or a string only consisting of
	 * white spaces.
	 */
	name: string;

	/**
	 * More detail for this symbol, e.g the signature of a function.
	 */
	detail?: string;

	/**
	 * The kind of this symbol.
	 */
	kind: SymbolKind;

	/**
	 * Tags for this document symbol.
	 *
	 * @since 3.16.0
	 */
	tags?: SymbolTag[];

	/**
	 * Indicates if this symbol is deprecated.
	 *
	 * @deprecated Use tags instead
	 */
	deprecated?: boolean;

	/**
	 * The range that should be selected and revealed when this symbol is being
	 * picked, e.g. the name of a function. Must be contained by the `range`.
	 */
	selectionRange: Range;

	/**
	 * Children of this symbol, e.g. properties of a class.
	 */
	children?: DocumentSymbol[];
}
```

A positive side-effect of this change is that since `textDocument/documentSymbol` request now includes a range parameter, when a document changes, it can be invoked on only the part of the document that has changed.

I'd be happy to create a PR for this change if some agreement on the design can be reached.

**Comment by dbaeumer** [comment]
How do you reconcile this on the client if the user types in a file?

**Comment by keyboardDrummer** [comment]
> How do you reconcile this on the client if the user types in a file?

Good question. On further thought, I think with the changes I proposed, it's not possible to do this in an incremental way.

For example, given the JSON blob `[ [ [ 1 ], 2 ], 3 ]`, removing the first `]` might trigger the parser's error correction to fix the missing `]` by appending one at the end, so it parses `[ [ [ 1 , 2 ], 3 ] ]`, which changes the entire structure of the tree. The removed `]` was nested several levels deep into the tree and the client has no way of knowing that the entire tree must be rebuilt.

One question I have, does the current `textDocument/documentSymbol` not lead to problems for large files? Looking at the `SymbolKind` enum

```
export namespace SymbolKind {
	export const File = 1;
	export const Module = 2;
	export const Namespace = 3;
	export const Package = 4;
	export const Class = 5;
	export const Method = 6;
	export const Property = 7;
	export const Field = 8;
	export const Constructor = 9;
	export const Enum = 10;
	export const Interface = 11;
	export const Function = 12;
	export const Variable = 13;
	export const Constant = 14;
	export const String = 15;
	export const Number = 16;
	export const Boolean = 17;
	export const Array = 18;
	export const Object = 19;
	export const Key = 20;
	export const Null = 21;
	export const EnumMember = 22;
	export const Struct = 23;
	export const Event = 24;
	export const Operator = 25;
	export const TypeParameter = 26;
}
```

It seems quite a large part of the document could be returned by a `textDocument/documentSymbol` request. However, given that `DocumentSymbol` also has a `name: string` field, I'm also confused as to which symbols should be returned as part of the current request. Should only named symbols, things that could be considered a 'definition', be returned?

I think to enable incrementally updating the symbol tree, the server must support sending edits of this tree, where an edit could be:

```typescript
export interface SymbolTreeDelta {
	readonly resultId?: string;
	/**
	 * The symbol edits to transform a previous result into a new
	 * result.
	 */
	edits: SymbolTreeEdit[];
}

interface SymbolTreeEdit {
  nodeRangeBeforeEdit: Range,
  newNode: Symbol
}
```

This is similar to `textDocument/semanticTokens/full/delta`, except the positions are absolute not relative.

Do you have any thoughts on the feasibility on making a change that enables having a synchronised symbol tree on the client?

Regards

**Comment by dbaeumer** [comment]
To support incremental updates on this the data structure need to change. Simple edits don't help since the current format uses absolute positions and to have a nice incremental story you need to use relative position encoding as we do with semantic tokens now.

**Comment by keyboardDrummer** [comment]
> Simple edits don't help since the current format uses absolute positions and to have a nice incremental story you need to use relative position encoding as we do with semantic tokens now.

Can you share something about what assumptions LSP makes about how the client and server store their text buffers and positions?

I imagine the TextBuffer is a balanced binary tree such as described [here](https://code.visualstudio.com/blogs/2018/03/23/text-buffer-reimplementation).

To efficiently update Positions in for example the AST stored on the server side, when a text change occurs, I would imagine having the Positions be part of the TextBuffer, where a Position contains a reference to a Node in the TextBuffer tree and an offset relative to the start of that Node. Each Node stores which Positions are pointing to it and can re-assign the positions to a different Node if the original one is split or removed. 

If clients and servers store positions according to the above, does it still matter whether LSP communicates relative or absolute positions, and whether it communicates offset or line/column based positions?

**Comment by dbaeumer** [comment]
LSP doesn't enforce any kind of implementation of a text buffer. All it defines is that positions are based on a UTF16 encoding. 

The data to be transferred is IMO independent of the implementation used. If you have absolute positions and introduce a new line at the beginning the whole selection tree will change since all its position will change.
