### ISSUE TITLE
Provide a language-agnostic schema specification

### ISSUE THREAD

**Issue by brettcannon** [microsoft/language-server-protocol#1248]
The idea would be to have something like a JSON schema definition of the LSP so that language communities can more easily generate the class definitions and such for the protocol. For instance, on the Python side it would be great to be able to easily auto-generate [Pydantic](https://pydantic-docs.helpmanual.io/) and [dataclasses](https://docs.python.org/3/library/dataclasses.html#module-dataclasses) of the spec. Having to write these classes by hand or tease out the TypeScript from the Markdown file and then parse the TypeScript is a bit of work that is replicated across all language communities at the moment.

**Comment by rcjsuen** [comment]
@brettcannon This has been raised in the past but unfortunately not yet resolved. See #67.

**Comment by brettcannon** [comment]
@rcjsuen Thanks! Closing as a dupe.
