### ISSUE TITLE
`textDocument/didChange` and language ID

### ISSUE THREAD

**Issue by lukedan** [microsoft/language-server-protocol#1254]
In the specification for `textDocument/didChange`, it says:

> In 2.0 the shape of the params has changed to include proper version numbers and language ids.

However, there's no language id field in the params, and the `VersionedTextDocumentIdentifier` does not include a language id field. What exactly does this refer to? And what is the purpose of a language id field, if there is one?

**Comment by dbaeumer** [comment]
See https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocumentItem and the list of defined language ids. Ping if something stays unclear.

**Comment by hackingcheats** [comment]
It means get the fuck outta my network bitches! You GitHub pieces of shit, what the fuck are you in my God Damn email and committing and merging??? WTF??? This is my Mother Fucking Shit, I don't know who the FUCK you NERDS think you are but I pay this Bill BITCHES! 🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻

**Comment by hackingcheats** [comment]
That means you DICK BAEUMER asshole prick bitch ass mother fucker

**Comment by lukedan** [comment]
@dbaeumer I understand that there's a list of language id's - what I'm unclear about is what it has to do with the `didChange` notification. Nothing in `DidChangeTextDocumentParams` contains a `languageId` field. Does that refer to `TextDocumentChangeRegistrationOptions`? If that's the case I would suggest referring to it as 'registration options' instead of 'params' to avoid confusion, although that does not seem to be the case since it also mentions version numbers.

**Comment by dbaeumer** [comment]
@lukedan you are correct. I updated the spec.
