### ISSUE TITLE
Extend protocol so that servers can provide command implementations

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/language-server-protocol#126]
Currently command execution must be implemented in the client side. However the server could return WorkspaceEdits to provide a command implementation from the server side.

**Comment by mickaelistria** [comment]
I see a good opportunity here for Refactorings.
In which case, could it be possible to have a command be
```
Command :
   String clientCommandId |
   WorkspaceEdit* edits
```
?

**Comment by alanz** [comment]
See also #34 and #61

**Comment by felixfbecker** [comment]
Why not implement the "command" as a method instead?

**Comment by dbaeumer** [comment]
@mickaelistria this got speced/implemented the following way:

- the client sends a request executeCommand to the server without any assumption about what the server is doing. So it is a 'handler' invocation.
- in 3.0 the client can offer a applyEdit capability so that the server can apply a workspace edit manipulating n resources on the client side.

IMO this offers the biggest flexibility without specing to much. 

I am closing this issue. If you want to give feedback on the new approach please open another issue.
