### ISSUE TITLE
Behavior of `InsertReplaceEdit` is incompletely specified

### ISSUE THREAD

**Issue by siegel** [microsoft/language-server-protocol#1260]
I'm writing a new LSP client, and trying to implement support for `InsertReplaceEdit` in completions. The sole documentation for `InsertReplaceEdit` is in the interface description, and a few cryptic notes in the completion discussion; as follows:

```
export interface InsertReplaceEdit {
	/**
	 * The string to be inserted.
	 */
	newText: string;

	/**
	 * The range if the insert is requested
	 */
	insert: Range;

	/**
	 * The range if the replace is requested.
	 */
	replace: Range;
}
```

and in `CompletionItem`, this note:

```
	 * Most editors support two different operations when accepting a completion
	 * item. One is to insert a completion text and the other is to replace an
	 * existing text with a completion text. Since this can usually not be
	 * predetermined by a server it can report both ranges. Clients need to
	 * signal support for `InsertReplaceEdit`s via the
	 * `textDocument.completion.insertReplaceSupport` client capability
	 * property.
```

The comments in the declaration of `InsertReplaceEdit` make it sound as though the `insert` and `replace` ranges are mutually exclusive; but neither one is marked optional.

And then, in the `CompletionItem` discussion, the server is permitted to specify _both_ `insert` and `replace` ranges.

This presents a confusing situation for the client developer. If only one of `insert` or `replace` is provided, the course of action is obvious. However, I'm looking at a server implementation (`rust-analyzer`) which provides both. What client behavior is expected in this case?

**Comment by predragnikolic** [comment]
For more info see https://github.com/microsoft/language-server-protocol/issues/846#issuecomment-602685037 .

**Comment by siegel** [comment]
Thanks for the pointer. If I read that correctly, then, `InsertReplaceEdit` is purely to support VS Code's ability to switch between "insert" and "replace" modes for completions? (I don't use VS Code, so that video was helpful.)

**Comment by predragnikolic** [comment]
That is also how I understood it.

**Comment by dbaeumer** [comment]
It is not about VS Code only. Editors like Eclipse have an insert and replace mode as well.

If a completion item has a normal text edit it is always treated as insert. If you want to replace you need to use a `InsertReplaceEdit`

Please ping if things are still unclear.
