### ISSUE TITLE
Can a server independently cancel a request sent by the client with the RequestCancelled error?

### ISSUE THREAD

**Issue by michaelmesser** [microsoft/language-server-protocol#1269]
Can a server independently cancel a request sent by the client with the `RequestCancelled` error if the client did not send a `$/cancelRequest`? In my case the server is receiving a `textDocument/semanticTokens/full` request and I want to tell the client that proper tokens cannot be generated and to keep the existing tokens and move them as needed. This appears to work in VSCode, but I want to make sure it is correct. Is that the best solution?

Currently Idris can only work with files on disk and provides no info for files with errors besides the errors. Is it best to return a `RequestCancelled` error for all requests about files with unsaved modifications or files that have errors?

After sending a `workspace/semanticTokens/refresh` and then responding to the `textDocument/semanticTokens/full` requests with `RequestCancelled` will the  client keep the semantic tokens before the  `workspace/semanticTokens/refresh`? Since Idris can only work with saved files at this time and a `textDocument/semanticTokens/full` request is not sent on save. I was hoping to use that to invalidate only certain files. Is that the best way?

Is there any way to just push?

Can this be clarified in the spec?

**Comment by dbaeumer** [comment]
This works in VS Code but it not part of the 3.16 spec yet. It will come to 3.17 using `ServerCancelled` (see https://github.com/microsoft/vscode-languageserver-node/blob/main/protocol/src/common/api.ts#L32)

**Comment by dbaeumer** [comment]
I added clarification to the spec (https://github.com/microsoft/language-server-protocol/blob/e0f15d54bb21fc520f38f6b907209326b5b33f15/_specifications/specification-3-17.md#L8543).
