### ISSUE TITLE
How should a server respond to `textDocument/selectionRange` if any of the positions have no range?

### ISSUE THREAD

**Issue by DanTup** [microsoft/language-server-protocol#1270]
The response type for `textDocument/selectionRange` is `SelectionRange[] | null` which means it is valid to return `null` or an empty list for the whole request, but it doesn't appear possible to return no results for a single position within the list.

Example:

```dart
^1
class Foo {
  ^2
}
```

Imagine the client sends a request for positions at `^1` and `^2`. There might be no valid ranges for `^1`, but valid ranges for `^2` but as far as I can see, there's no valid way to respond like that.

Should the response instead be `Array<SelectionRange | null> | null`? Or should a server return a range that is just the same as the position? (if so, I think that should be noted in the spec).

**Comment by dbaeumer** [comment]
Actually a good question. I would prefer returning `null` in the array at the given index. @jrieken what is our take on this?

**Comment by DanTup** [comment]
Allow `null` seems best for me too - though now this has shipped and clients (inc current VS Code) don't expect it, changing it seems breaking so if that was done behind a flag, the spec should still describe what should be done if the client doesn't provide the flag.

(For now I'm going ahead with just sending the incoming position back as an empty range, since it seems like the only thing I can do without violating the spec).

**Comment by jrieken** [comment]
> but it doesn't appear possible to return no results for a single position within the list.

You should be able to return a single `SelectionRange`, without parent and for only that position (empty range)

**Comment by dbaeumer** [comment]
@DanTup yes please.

**Comment by DanTup** [comment]
Opened at https://github.com/microsoft/language-server-protocol/pull/1272
