### ISSUE TITLE
favicon is almost invisible in dark mode browsers

### ISSUE THREAD

**Issue by mikesamuel** [microsoft/language-server-protocol#1276]
https://microsoft.github.io/language-server-protocol/specification uses

```html
    <link rel="shortcut icon" href="/language-server-protocol/img/favicon.png">
```

which loads

[![favicon](https://microsoft.github.io/language-server-protocol/img/favicon.png)](https://microsoft.github.io/language-server-protocol/img/favicon.png)

The black on transparent icon in a tab bar is low contrast on dark mode:

<img width="291" alt="tab-bar-screenshot" src="https://user-images.githubusercontent.com/368886/119677414-b32eb600-be0c-11eb-8e26-53a907f9c3eb.png">

This makes the LSP spec hard to find to refer back to.

I can't find `favicon.png` in this repo which is why this isn't a PR, but below is an version with a border imageMagicked on:

![lsp-favicon-edged](https://user-images.githubusercontent.com/368886/119675835-60a0ca00-be0b-11eb-930b-d1b7ae21c481.png)

**Comment by dbaeumer** [comment]
@misolori can you help me with this please?

**Comment by misolori** [comment]
@dbaeumer you should be able to [use svgs for the favicon](https://medium.com/swlh/are-you-using-svg-favicons-yet-a-guide-for-modern-browsers-836a6aace3df), which can have css that can handle dark mode. [Here's a sample of the svg](https://codepen.io/miguelsolorio/pen/OJpvXgb) in use (change to dark mode to see it working).

And the svg source:
```svg
<svg width="180" height="180" viewBox="0 0 180 180" fill="none" xmlns="http://www.w3.org/2000/svg">
    <style>
        path {
            fill: black;
        }
        @media (prefers-color-scheme: dark) {
            path {
                fill: white;
            }
        }
    </style>
    <path d="M29.7605 115H62.2875V105.293H41.7136V65.5455H29.7605V115Z" />
    <path d="M95.2069 80.3722H106.653C106.556 71.1236 99.1912 64.8693 87.6969 64.8693C76.3958 64.8693 68.258 71.027 68.3304 80.2273C68.3063 87.7372 73.5705 91.9631 82.1188 93.919L87.2864 95.1264C92.7196 96.3821 95.1586 97.8551 95.2069 100.632C95.1586 103.651 92.3333 105.751 87.5279 105.751C82.2395 105.751 78.7623 103.288 78.4966 98.5312H67.0506C67.1955 110.098 75.2367 115.628 87.6728 115.628C99.9881 115.628 107.281 110.05 107.329 100.656C107.281 92.7599 101.944 87.9304 92.1884 85.7812L87.9384 84.8153C83.4469 83.8494 80.5975 82.3523 80.6941 79.4062C80.7182 76.7017 83.0364 74.7457 87.6728 74.7457C92.3333 74.7457 94.8929 76.8466 95.2069 80.3722Z" />
    <path d="M113.366 115H125.319V99.642H133.433C144.758 99.642 151.833 92.929 151.833 82.6662C151.833 72.5 144.903 65.5455 133.795 65.5455H113.366V115ZM125.319 90.2244V75.1804H131.211C136.572 75.1804 139.445 78.0781 139.445 82.6662C139.445 87.2301 136.572 90.2244 131.211 90.2244H125.319Z" />
</svg>

```

**Comment by dbaeumer** [comment]
@misolori Works. Thanks. 

<img width="75" alt="capture" src="https://user-images.githubusercontent.com/1931590/120764944-f974cb00-c518-11eb-8dd7-59b07edc1dc8.png">
