### ISSUE TITLE
Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by xg-github-00** [microsoft/language-server-protocol#1279]
vscode-languageclient 7.0.0
vscode-languageserver 7.0.0
I use verson 7.0.0 for a test, and found that:
when server send response to  method: ‘textDocument/prepareCallHierarchy’ with the result CallHierarchyItem[] (CallHierarchyItem.lengh > 1) ,the client will throw error  "Cannot read property 'map' of undefined", and this error is not exist when the result CallHierarchyItem[] (CallHierarchyItem.lengh ==0 CallHierarchyItem.length==1))

please help to check this problem, thanks ~

**Comment by rcjsuen** [comment]
@xg-github-00 Please share the exact JSON of a successful server response and a failed server response.

**Comment by rcjsuen** [comment]
@xg-github-00 Also, you should be open a bug in the [microsoft/vscode-languageserver-node repository](https://github.com/microsoft/vscode-languageserver-node/) instead of here.

**Comment by dbaeumer** [comment]
@rcjsuen thanks for pointing this out. I will close this issue since it looks like an implementation problem in the LSP client.
