### ISSUE TITLE
Semantic tokens for formatting directives in strings

### ISSUE THREAD

**Issue by stamblerre** [microsoft/language-server-protocol#1281]
The Go textmate grammar applies a special coloring to formatting directives (`%s`, `%d`, etc.) in strings. For example:
![Screen Shot 2021-06-01 at 5 25 48 PM](https://user-images.githubusercontent.com/5856771/120392398-6eb88400-c2fe-11eb-8dc3-a50f35a791bf.png)

We were wondering how we can achieve the same behavior through semantic tokens implemented through LSP. Logically, it makes sense to apply one of the SemanticTokenModifiers to the relevant parts of the string, but that did not appear to produce a difference in colorization, and it's not clear which modifier best fits this specific use case.

/cc @pjweinb

**Comment by rcjsuen** [comment]
> The Go textmate grammar applies a special coloring to formatting directives (`%s`, `%d`, etc.) in strings. For example:
> ![Screen Shot 2021-06-01 at 5 25 48 PM](https://user-images.githubusercontent.com/5856771/120392398-6eb88400-c2fe-11eb-8dc3-a50f35a791bf.png)
> 
> We were wondering how we can achieve the same behavior through semantic tokens implemented through LSP. Logically, it makes sense to apply one of the SemanticTokenModifiers to the relevant parts of the string, but that did not appear to produce a difference in colorization, and it's not clear which modifier best fits this specific use case.

1. I would expect this to work. Have you tried making it a completely different token type like `"variable"` or `"function"` to double check that the offsets in the payload is correct?

2. Which client(s) have you tested this on and verified that it is not working?

**Comment by stamblerre** [comment]
> 1. I would expect this to work. Have you tried making it a completely different token type like `"variable"` or `"function"` to double check that the offsets in the payload is correct?

Yes--and different token types do work.

> 2. Which client(s) have you tested this on and verified that it is not working?

This was originally tested with the latest VS Code language client, but the same behavior also reproduces with the 7.1.0-next.4 version. I confirmed that VS Code saw the modifier here:

![Screen Shot 2021-06-01 at 6 57 23 PM](https://user-images.githubusercontent.com/5856771/120400077-39666300-c30b-11eb-8f32-3419c121ff03.png)

**Comment by rcjsuen** [comment]
@stamblerre Maybe try making changes to your theme?

![image](https://user-images.githubusercontent.com/15629116/120402329-f0fd7400-c30f-11eb-8c55-246b97c00326.png)

**Comment by stamblerre** [comment]
Adding that customization does seem to work. I am using the default VS Code dark theme with VS Code Insiders. Is there any way to get these modifications to show up by default? This is preventing us from switching completely to the LSP's semantic tokens in the Go extension.

**Comment by rcjsuen** [comment]
> Adding that customization does seem to work.

That is good to hear.

> I am using the default VS Code dark theme with VS Code Insiders. Is there any way to get these modifications to show up by default? This is preventing us from switching completely to the LSP's semantic tokens in the Go extension.

I suggest opening an issue in the [microsoft/vscode-languageserver-node/ repository](https://github.com/microsoft/vscode-languageserver-node/) or with Visual Studio Code (since you are using the default theme). This seems like a theming issue and/or VS Code doing things differently for TextMate grammars vs LSP semantic tokens.

**Comment by dbaeumer** [comment]
IMO this has nothing to do with the LSP client. 

@aeschli can you comment on why this might not work for semantic tokens but does work for syntax tokens.

**Comment by aeschli** [comment]
Yes, this would have to be filed against VSCode. You want VScode to add a [TextMate scope mapping](https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide#semantic-token-scope-map) for `string.modification`.

`string.modification` is not (yet) an established way to represent placeholders in strings, so I'm not sure we will just add that in VScode. But extensions can also such TextMate scope mappings: https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide#custom-textmate-scope-mappings (second example)
