### ISSUE TITLE
Question: Should willSaveWaitUntil, willSave and save be rejected if the document is not opened?

### ISSUE THREAD

**Issue by stefan-wullems** [microsoft/language-server-protocol#1284]
In the spec there is nothing that states that these messages cannot be sent for a closed document. I would expect that these messages only make sense when a file is opened though. Are there perhaps cases I'm not seeing?

**Comment by dbaeumer** [comment]
A server is technically allowed to opt out of open / close and opt in into willSave. Since this is possible it is hard to enforce this in the spec. But I will add something that clarifies this that if opt into open / close willSave should only happen after an open.
