### ISSUE TITLE
Define behavior for "missing" documents

### ISSUE THREAD

**Issue by ryanbrandenburg** [microsoft/language-server-protocol#1289]
I wasn't able to find anywhere where the LSP specification says what to do in cases where queries are made about documents which aren't yet known. For example, if a `textDocument/semanticTokens/full` request is made for `C:\someDocument.razor`, but no `didOpen` or `didChange` events have arrived/completed for `C:\someDocument.razor` yet, what would the correct response be?

My first instinct (and how I [implemented it for Razor](https://github.com/dotnet/aspnetcore-tooling/blob/main/src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Semantic/Services/DefaultRazorSemanticTokensInfoService.cs#L85)) is that the "correct" response would be a null or empty reply, but [other implementations](https://github.com/dotnet/roslyn/blob/main/src/Features/LanguageServer/Protocol/Handler/SemanticTokens/SemanticTokensHandler.cs#L49) have implemented it as an error. Which approach is "on spec", and can we make the documentation reflect this to ensure the ecosystem is standardized?

**Comment by rcjsuen** [comment]
> I wasn't able to find anywhere where the LSP specification says what to do in cases where queries are made about documents which aren't yet known. For example, if a `textDocument/semanticTokens/full` request is made for `C:\someDocument.razor`, but no `didOpen` or `didChange` events have arrived/completed for `C:\someDocument.razor` yet, what would the correct response be?

@ryanbrandenburg I think your question is addressed by #177. Unopened files are owned by the server and if possible the server should honour the request.

**Comment by dbaeumer** [comment]
@ryanbrandenburg see also https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_didOpen

and the sentence

Note that a server’s ability to fulfill requests is independent of whether a text document is open or closed.

**Comment by dbaeumer** [comment]
Closing. Please ping if something is still unclear.
