### ISSUE TITLE
ShowMessage Request: Unactionable MessageActionItem 

### ISSUE THREAD

**Issue by slemeur** [Microsoft/language-server-protocol#130]
Hi,

We are having some questions to understand the following specification for [ShowMessage Request](https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#showmessage-request)

The message will be displayed to the user as a notification and possible actions will be available to the user. 
In the following issue #69, we understand that the actions are sent back to the server. But in the [specification](https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#showmessage-request), we understand that actions could also be client side (like `Open Log`), which could make sense as well.

If there is a need to actions which could be triggered by the clients (ie: IDE), we wonder if a pre-defined set of typed actions should not be added to the specification?

If the `MessageActionItem` is meant to be resent to the server, then should the specification be clear on that? 

Optionally, could you point us to some existing samples using `MessageActionItem` ?

**Comment by dbaeumer** [comment]
The request is currently specified in a way that the selected MessageActionItem is sent back to the server. The is not way right now to execute a special action on the client. We would need to spec those. An example looks like this:

```ts
	let actions: MessageActionItem[] = [ {title: 'Save'}, {title: 'Cancel'} ];

	connection.sendRequest(ShowMessageRequest.type, {
		type: MessageType.Info,
		message: 'What do you want to do',
		actions: actions
	}).then((selected) => {
		// Handle the selected item
	});
```

**Comment by dbaeumer** [comment]
Any objection to close.

**Comment by slemeur** [comment]
Ok great. Thanks for the answer and the clarification @dbaeumer.
