### ISSUE TITLE
 is there an equivalent of vscode.workspace.textDocuments ? 

### ISSUE THREAD

**Issue by ganezdragon** [microsoft/language-server-protocol#1300]
hi all,

I'm trying to get all my currently opened files using your language-server-procol. But there is no equivalent of `vscode.workspace.textDocuments` that I could find.

I didn't want to use the `vscode` as a dependency, since i want to be able to port my server to other text editors properly.
So it there any equivalent at all? or any work around?

my repo - https://github.com/ganezdragon/perl-language-server

Thanks,
Ganesan

**Comment by dbaeumer** [comment]
Opened documents are signaled to the server using the textDocument/didOpen notification. It is up to a server implementor to decide how he surfaces this to possible clients.
