### ISSUE TITLE
textDocument/didChange throws error

### ISSUE THREAD

**Issue by ganezdragon** [microsoft/language-server-protocol#1301]
hi all,

I'm developing a LSP for perl, with a vscode client now.

repo - https://github.com/ganezdragon/perl-language-server

and when I do a file edit event - `textDocument/didChange` it throws the following error,

```
[Error - 9:10:11 AM] Notification handler 'textDocument/didChange' failed with message: TextDocument.update: document must be created by TextDocument.create
```

Could anyone help me out here?

**Comment by rcjsuen** [comment]
> I'm developing a LSP for perl, with a vscode client now.

@ganezdragon If you are having issues with a specific LSP client, you should open an issue with that project. In this case, it sounds like you need to open an issue in the [microsoft/vscode-languageserver-node repository](https://github.com/microsoft/vscode-languageserver-node/).

This repository is more for:
- questions about the protocol
  - how to implement it as a client or a server
  - discussions about edge cases, clarifications, and so on
- suggestions on new requests and notifications to be added to the protocol

**Comment by ganezdragon** [comment]
@rcjsuen , I just came from there, https://github.com/microsoft/vscode-languageserver-node/issues/777

Let me reopen the issue, and check once.

**Comment by rcjsuen** [comment]
> @rcjsuen , I just came from there, [microsoft/vscode-languageserver-node#777](https://github.com/microsoft/vscode-languageserver-node/issues/777)

Your original question (microsoft/vscode-languageserver-node#777) was about how to solve something in a generic fashion to support multiple LSP clients. That is why I sent you here and I see you opened #1300 for that.

Your new question is about a behaviour you are observing with a specific LSP client, that is why I am sending you over there.

**Comment by dbaeumer** [comment]
@rcjsuen thanks for commenting. I am closing the issue since the questions is implementation specific.

**Comment by ganezdragon** [comment]
yea agreed we could just keep one issue open.

@rcjsuen , the problem is I don't fully understand on how these two npm modules work, so I just have a more generic idea. But let me debug it as you mentioned in the other issue. But it shouldn't stop from closing this issue.

**Comment by ganezdragon** [comment]
@rcjsuen , found the problem after debugging. The problem was that `document.listen(connection)` was called after `connection.listen()`. This caused the behavior.

I have fixed it this way in case someone would coming looking for it - https://github.com/ganezdragon/perl-language-server/commit/c3a160b303f4f4c1fc8ceed860a0619ee5615ea7#diff-4398e3b2ab3e7e7e70a93409fa893abf68608d45a5ad1ac7faaf888dac77005dR104

Thanks for the help and idea :)

**Comment by dbaeumer** [comment]
Great to hear you got it working.

Closing the issue.

**Comment by deakjahn** [comment]
For others who might arrive here searching for the same error message: the main problem seems to be that the LSP sample doesn't really show where and when the various text change events should be subscribed to. Make sure you put all the `documents` change handler subscription calls -- `documents.onDidChangeContent()` and others -- into the handler of `connection.onInitialized()`, not just into the global flow of the file, as the sample would suggest. The error goes away immediately.

It's not obvious at first sight but it's mentioned in the source code comments: decide whether you use the `documents` _or_ the direct `connection.onDidChangeTextDocument()` and other handlers. If you call

    documents.listen(connection);

it will overwrite these other handlers and replace them with its own. Don't try to use both, either one set or the other.
