### ISSUE TITLE
[Feature requst] Allow snippets in code action edits

### ISSUE THREAD

**Issue by ulugbekna** [microsoft/language-server-protocol#1302]
Currently, a language server can send text edits in code actions, but the edits cannot be interpreted as snippets. This is different in completion items, where the item can also be a snippet.

This is useful for example when the edited text still contains some holes that must be filled by a user to get a valid piece of code.

**Comment by dbaeumer** [comment]
Dups https://github.com/microsoft/language-server-protocol/issues/592
