### ISSUE TITLE
What Command in protocol-1-x

### ISSUE THREAD

**Issue by YeomanYe** [microsoft/language-server-protocol#1304]
Thank you very much for providing this tool, it is very useful for me.But I have some doubts about this tool.How many `Command` are in protocol-1-x and what are they.

https://github.com/microsoft/language-server-protocol/blob/main/versions/protocol-1-x.md

![image](https://user-images.githubusercontent.com/18027354/123544408-bb6c6f00-d785-11eb-994d-ad8851821a85.png)

**Comment by rcjsuen** [comment]
> How many `Command` are in protocol-1-x and what are they.

1. Think of "commands" as an "action". This can be "saving the current file", "formatting the current file", or "cast this string to a boolean".
2. The number of commands that a client or a server can have is unbounded. The protocol does not currently have a standardized list of commands. See #432 and #642 (for starters, there are probably some others out there).
3. I would advise against looking at the 1.x protocol personally.

**Comment by dbaeumer** [comment]
@rcjsuen thanks for the great explanation.

I will close the issue. @YeomanYe please ping if there is still something unclear.

**Comment by YeomanYe** [comment]
Thank you for your anwser.But what I want to ask is what are some of the basic commands for an editor, and I think it's very useful for us to design a graphical editor.


> > How many `Command` are in protocol-1-x and what are they.
> 
> 1. Think of "commands" as an "action". This can be "saving the current file", "formatting the current file", or "cast this string to a boolean".
> 2. The number of commands that a client or a server can have is unbounded. The protocol does not currently have a standardized list of commands. See [Clarify the intension of how commands are defined #432](https://github.com/microsoft/language-server-protocol/issues/432) and [What's the correct way for an LSP server to know whether a command is available on the client? #642](https://github.com/microsoft/language-server-protocol/issues/642) (for starters, there are probably some others out there).
> 3. I would advise against looking at the 1.x protocol personally.

**Comment by dbaeumer** [comment]
The LSP doesn't standardize a set of commands right now. There are requests to do so, but no work has started yet.

**Comment by YeomanYe** [comment]
> The LSP doesn't standardize a set of commands right now. There are requests to do so, but no work has started yet.

OK, thank you very much
