### ISSUE TITLE
Sync `CompletionItemLabelDetails` with VS Code?

### ISSUE THREAD

**Issue by KamasamaK** [microsoft/language-server-protocol#1307]
VS Code finalized their API to be more generic (see microsoft/vscode#39441). Should LSP be synced with those changes? Of course this would still need to accommodate the change made for #1193 so not a full sync.

**Comment by dbaeumer** [comment]
Yes, we should adapt this as soon as the new version of VS Code has shipped.

**Comment by KamasamaK** [comment]
It has shipped

**Comment by dbaeumer** [comment]
And it is adapted in the next version of the LSP libs. 

Need to still doc it in the spec.

**Comment by dbaeumer** [comment]
Implemented and added to spec.
