### ISSUE TITLE
No definition of if/how URIs should be encoded in documentation

### ISSUE THREAD

**Issue by fredg1** [microsoft/language-server-protocol#1330]
The documentation (at https://github.com/Microsoft/language-server-protocol/blob/gh-pages/_specifications/specification-3-16.md#uri ) doesn't specify if and/or how URIs should be encoded.

There is a link supposedly talking about their format, but as pointed out in https://github.com/microsoft/language-server-protocol/pull/1329 , this link is no longer valid, and should be replaced.

While I can't actually find any source claiming that any of the characters in a URI should be encoded, I am currently trying to make a language server, and am testing it with IntelliJ (using this plugin: https://github.com/gtache/intellij-lsp/tree/master/intellij-lsp ), which, I just found, is, for some reason, aggressively manually replacing every space with "`%20`" (while not even bothering to encode file names that already have "`%20`" in them. Go figure...), which is what sparked this question.

**Comment by fredg1** [comment]
Update: managed to find a source claiming that whitespaces don't belong in URIs https://docs.marklogic.com/guide/mlcp/import#id_29822

I am not familiar with "marklogic", so I can't assert that it is official/standard.

**Comment by dbaeumer** [comment]
I fixed the link. It is actually https://tools.ietf.org/html/rfc3986

Does this help.

**Comment by fredg1** [comment]
Yes. Thanks
