### ISSUE TITLE
SemanticTokensDelta specification lacks specificity WRT edit ordering and startOffset

### ISSUE THREAD

**Issue by ryanbrandenburg** [microsoft/language-server-protocol#1333]
In discussing differences between the Roslyn and Razor LSP implementations @allisonchou and I came to realize that though neither of our implementation violated the specification they were incompatible because of a lack of specifics on two key points:
1. Does the int in `SemanticTokensEdit.start` represent the start offset pre or post previous edits? For example, consider we have a current int array of `[0, 1, 2, 3, 4]` and then receive this SemanticTokensDelta: `SemanticTOkensDelta: edits = [(start: 4, deleteCount: 0, data: [5, 6, 7, 8, 9]), (start: 7, deleteCount: 0, data: [....])]`. Is that legal (because after the addition of the values in the first edit a position 7 would exist, and start refers to the "current state" of the array), or illegal (because the array to be originally acted upon does not contain that many elements).
2. The above question also has implications on ordering: do the values in the `edits` array need to have constantly increasing `start` value, or could they start from the end of the array and move toward 0, or even move back and forth?

The answer to these questions has implications both for client implementations and for Servers like ours where one server must be consulted from another.

CC @allisonchou to make sure I represented our conversation correctly.

**Comment by allisonchou** [comment]
cc @gundermanc

**Comment by dbaeumer** [comment]
@ryanbrandenburg good question. The semantic token edits behave like text document edits. The are all made for a version Sn of the int array and move the int array to Sn+1. So when executing they are best sorted and executed from the end of the array to the front.

I will clarify that in the spec.

So in you above example the edits are not valid since the `start: 7` doesn't exit in the Sn version of the array.

**Comment by allisonchou** [comment]
@dbaeumer Is the client or the server meant to be responsible for sorting the array from (end -> front)? Today, it seems like servers are able to return the edits in any order and the client will sort them. Would it be possible to make it clear in the spec whether the client is responsible for sorting?

**Comment by dbaeumer** [comment]
The client is responsible for applying them and can't assume that the list is sorted. Whether the client needs to sort them or not depends on its algorithm that applies them. And easy one is to sort and applied from back to front. But there are others as well :-).

I can add a sentence that the client can't assume any order in the edit list.
