### ISSUE TITLE
clarify documentLink meaning

### ISSUE THREAD

**Issue by vladdu** [Microsoft/language-server-protocol#134]
The docs say they "link to an internal or external resource, like another document or a web site". I suppose that the client will handle the resource differently if it's a document or a web site, but how can it know? HTML files can be either...

Shouldn't there be some kind of type label that can help the client choose right? In the future there might be more kinds of resources available, that might need different handling strategies.

**Comment by svenefftinge** [comment]
Could someone also explain what the purpose of `documentLink/resolve` request is?

**Comment by vladdu** [comment]
My understanding is that the documentLink request may return unresolved links, if the effort to compute the target is going to delay the answer, just like for completion items. 

In this case, I suppose that the taget field on DocumentLink should be specified as optional, right?

**Comment by svenefftinge** [comment]
Yes could be I created a PR https://github.com/Microsoft/language-server-protocol/pull/142

**Comment by dbaeumer** [comment]
Yes. it Should be. I updated the protocol.
