### ISSUE TITLE
textDocument/willSaveWaitUntil via the LSP does not wait

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/language-server-protocol#1343]
We hooked up our LSP server to handle the textDocument/willSaveWaitUntil LSP message and it "works", but VS Code (1.59.0) doesn't actually wait until we send our response back. Switching to using vscode.workspace.onWillSaveTextDocument (and sending our own cpptools/willSaveWaitUntil message) fixes the issue, so it seems like the language-server implementation isn't waiting correctly. It repros 100% of the time with a minimal wait duration.

Let me know if you want more info. I assume it'd repro with any sort of test case you have available.

We're using 5.2.1 of the vscode-languageclient.

**Comment by rcjsuen** [comment]
@sean-mcmanus Did you mean to open an issue in the [microsoft/vscode-languageserver-node repository](https://github.com/microsoft/vscode-languageserver-node/)?

**Comment by sean-mcmanus** [comment]
Yeah, that seems better, thanks.
