### ISSUE TITLE
Add support for supportsHtml on markdown strings

### ISSUE THREAD

**Issue by DanTup** [microsoft/language-server-protocol#1344]
VS Code is getting a flag on `MarkdownString` to say whether (some basic subset of) HTML can be rendered in addition to markdown:

https://github.com/microsoft/vscode/issues/40607

I think it would be useful to support in LSP for the same reason it makes sense there. Some languages let users write their docs in Markdown and they might also include some HTML, but right now it renders literally in the tooltips which is unexpected.

**Comment by felixfbecker** [comment]
Note also that both the very original Markdown invention and the CommonMark spec (the de-facto Markdown standard) clearly allow HTML within Markdown, it's a core part of the idea behind Markdown. I.e. this is not a non-standard syntax "extension".
- https://daringfireball.net/projects/markdown/syntax#html
- https://spec.commonmark.org/0.30/#html-blocks

**Comment by dbaeumer** [comment]
It does make sense to add this to LSP. However a client needs to announce the list of supported HTML tags. For VS Code they are defined here: https://github.com/microsoft/vscode/blob/6d2920473c6f13759c978dd89104c4270a83422d/src/vs/base/browser/markdownRenderer.ts#L296

**Comment by dbaeumer** [comment]
PR welcome.

**Comment by dbaeumer** [comment]
Implemented and added to the spec.

**Comment by DanTup** [comment]
@dbaeumer how does this support work? In 14f7c980e35717cdcaf7dce8dd5d2df0881d1e11 I see the client can advertise which tags it supports, but I don't see a way of passing [`supportsHtml` on the `MarkdownString` to VS Code](https://github.com/microsoft/vscode/pull/132182). Does it require changes in the LSP Client to set this?

**Comment by dbaeumer** [comment]
For VS Code this is handled the same way as `isTrusted`. You specify whether this is supported via a setting in the client options. See https://github.dev/microsoft/vscode-languageserver-node/blob/e22c9bdd485d36b77cdf70fd4b34e6928822ebfe/client/src/common/client.ts#L579

**Comment by DanTup** [comment]
Ah, got it - thanks!

**Comment by DanTup** [comment]
@dbaeumer I don't suppose there's an approx ETA for 3.17? I thought I saw it noted in previous VS Code release notes as being published, but the site still shows 3.16 as current.

**Comment by dbaeumer** [comment]
It is not publish. We did publish new next releases with proposed support for notebooks.

**Comment by dbaeumer** [comment]
The plan is to have a new 3.17 release the next ~ 2 month

**Comment by DanTup** [comment]
Got it, thanks! :)

**Comment by thw0rted** [comment]
Just to check as a user who wants to consume documentation that uses inline HTML, when the new release comes out in 2 months, tags should no longer disappear in VSCode Intellisense results?

I'm having trouble finding my original issue, but I came here from https://github.com/microsoft/vscode/issues/40607 -- that was resolved last year but hasn't fixed the rendering problem; I think it was only part of the puzzle.

**Comment by thw0rted** [comment]
Thanks for the link.  Do you know (or know how to tell) when that lands in a VSCode release?  I'm just trying to figure out when [the symptom](https://github.com/microsoft/vscode/issues/110945) (large portions of some docs are completely removed) is going to be resolved for end users, without getting passed around between the Language Service people and the VSCode people and the TypeScript people.

**Comment by KamasamaK** [comment]
@thw0rted As far as I can see, the [`typescript-language-features` extension](https://github.com/microsoft/vscode/tree/main/extensions/typescript-language-features) doesn't even use the LSP client. The issue you're describing would be with that bundled extension and possibly extends to the TypeScript language service it uses. It's not an issue with the LSP spec or that LSP client.

**Comment by DanTup** [comment]
@dbaeumer 

> The plan is to have a new 3.17 release the next ~ 2 month

We're approaching 2mo from this comment - is the plan still to publish 3.17 in the near future? (not after a commitment, but a rough estimate will help me plan, there are a few things in 3.17 that would help with some things I'm working on). Thanks :)

**Comment by dbaeumer** [comment]
Yes, still the plan. I am waiting for 2 APIs to be finalized in VS Code (which already happened in insider) and then I am good to go beginning of Mai..

**Comment by DanTup** [comment]
Great, thanks!
