### ISSUE TITLE
Typo in textDocument/semanticTokens/range causes some confusion

### ISSUE THREAD

**Issue by rcjsuen** [microsoft/language-server-protocol#1348]
> * result: `SemanticTokens | null` where `SemanticTokensDelta`

We have the above typo in the [specification](https://github.com/microsoft/language-server-protocol/blob/05684ac00c252f26075523a2c69f85dead924db0/_specifications/specification-3-16.md) for the `textDocument/semanticTokens/range` request at the moment.

Is the `textDocument/semanticTokens/range` request supposed to just return tokens as-is starting at some arbitrary visible line or is it supposed to create and return `SemanticTokensDelta` based on how far the user has scrolled...? 🤔 I'm going to assume the former because the latter doesn't seem to make any sense?

**Comment by dbaeumer** [comment]
Copy paster error.
