### ISSUE TITLE
Add support for better looking 'documentation' in completion items (i.e. markdown format)

### ISSUE THREAD

**Issue by kdvolder** [Microsoft/language-server-protocol#137]
It looks like completionItem only supports 'plain text' documentation. Well, not sure, the description in LSP protocol just says the documentation is a 'human readable string' without being particularly specific about how the string is interpreted/rendered by a client. I suppose technically, this leaves it totally to the client to decide how to render the doc strings.
 
This is a shame I think, because hoverinfo, which tends to display the same information already explicitly supports markdown.

The markdown in hover infos, when properly rendered, looks (or can look) great. It looks great, for example, in vscode (and so should be able to look great in other lsp client implementations too).

The 'documentation' string however is not being rendered in the same way. In vscode, when completions are shown a single line of 'doc text' is shown 'smashed together' without respecting the newlines. This looks pretty awful when the content is proper markdown.

It is possible in vscode to click a little 'info' icon to see more. Then it shows the markdown text in a new popup view and there it respects newlines (but otherwise does not render markdown specially).

So, I'm not sure totally sure if I should file a bug with vscode (because it displays markdown poorly) or, a issue ticket with LSP to clarify and/or extend the protocol spec to explicitly support markdown for the 'documentation' text snippets in completion items.

**Comment by kaloyan-raev** [comment]
This is definitely a shortcoming in LSP. 

Note that not only the `CompletionItem` has a `documentation` property, but also the `SignatureInformation` and the `ParameterInformation`.

The format of the `documentation` property should be identical to the hover contents, i.e. Markdown.

**Comment by kaloyan-raev** [comment]
I think #111 is about the same issue.

**Comment by dbaeumer** [comment]
Correct. Marking as dup.
