### ISSUE TITLE
VSCode UI freezes intermittently when an extension is using a language server

### ISSUE THREAD

**Issue by lispercat** [microsoft/language-server-protocol#1375]
I wonder if this issue would be more relevant here than the one I opened [here](https://github.com/microsoft/vscode-languageserver-node/issues/845)

The issue is that when I debug [the sample](https://github.com/microsoft/vscode-extension-samples/tree/main/lsp-sample)
or try to implement my own language server using the sample code I experience intermittent UI freezes when fast typing in the editor.

VSCode version 1.62.0 on Windows 10
"vscode-languageclient": "8.0.0-next.3",
"vscode-languageserver": "8.0.0-next.3",

**Comment by rcjsuen** [comment]
> I wonder if this issue would be more relevant here than the one I opened [here](https://github.com/microsoft/vscode-languageserver-node/issues/845)

Not exactly. This repository is for discussing what sort of features a client and server should support. Specific clients and servers are generally only brought up to raise inconsistencies and/or issues that needs to be clarified in the protocol itself when different clients and servers cannot agree on something.

If you're having issues with integrating your language server with Visual Studio Code then the [microsoft/vscode-languageserver-node repository](https://github.com/microsoft/vscode-languageserver-node/) is the place to be.

**Comment by dbaeumer** [comment]
Thanks @rcjsuen for clarifying. Closing the issue.
