### ISSUE TITLE
Add support for `resolveWorkspaceSymbol`

### ISSUE THREAD

**Issue by isc-bsaviano** [microsoft/language-server-protocol#1377]
I would like to add a `WorkspaceSymbolProvider` to my language server but the cost of computing a `Location` for each symbol is prohibitive. There should be support for deferring that computation until the user clicks on the symbol like in the VS Code API.

**Comment by KamasamaK** [comment]
Resolved by fee023f3efbb6fe3cd4ac1f4c16a16d05ce68100

**Comment by dbaeumer** [comment]
Correct. Thanks for pointing out.
