### ISSUE TITLE
Update spec to make range handling a viable solo option

### ISSUE THREAD

**Issue by allisonchou** [microsoft/language-server-protocol#1378]
Currently, the semantic tokens range protocol (3.17) is [described as the following](https://microsoft.github.io/language-server-protocol/specifications/specification-3-17/#textDocument_semanticTokens):

> When a user opens a file it can be beneficial to only compute the semantic tokens for the visible range (faster rendering of the tokens in the user interface). If a server can compute these tokens faster than for the whole file it can provide a handler for the `textDocument/semanticTokens/range` request to handle this special case. Please note that if a client also announces that it will send the `textDocument/semanticTokens/range` server should implement this request as well to allow for flicker free scrolling and semantic coloring of a minimap.

The above makes it sound like range handling can only be used on file open. However, in Roslyn, we're planning on using range handling by itself instead of using all three of full/delta/range. This was found to be much more optimal perf-wise for us and is similar how local non-LSP Roslyn computes semantic tokens today. It would be nice if the spec could be updated to make range handling a viable option for editing.

**Comment by dbaeumer** [comment]
Actually this shouldn't be a problem since we already have this in the spec: https://github.com/microsoft/language-server-protocol/blob/dc493ca1873940130e16b14687edd0da53b9b150/_specifications/specification-3-16.md#L7628
