### ISSUE TITLE
Sequence support for triggerCharacters

### ISSUE THREAD

**Issue by felixfbecker** [Microsoft/language-server-protocol#138]
It appears to me from the property name and the VS Code implementation that `triggerCharacters` only supports single characters in the array. Support for whole sequences would be very helpful for languages like PHP and C++, that have multi-character operators:
```php
TestClass::staticMethod();
$obj->property;
```
I would like to trigger completion on `->` and `::`, but of course not on a single `>` (greater-than operator) or `:` (no meaning).
Currently, sending `["::", "->"]` to VS Code seems to result in VS Code only triggering on the first character, `:` or `-`. I therefor send `:` and `>` instead.
Please document that the array can not only contain characters, but string sequences.

**Comment by felixfbecker** [comment]
The current situation means that completions are triggered inside embedded HTML on every single closing tag because of the `>` trigger character (instead of `->`), see https://github.com/felixfbecker/php-language-server/issues/372

**Comment by dbaeumer** [comment]
@jrieken any comments from you?

**Comment by jrieken** [comment]
> 		 * @param triggerCharacters Trigger completion when the user types one of the characters, like `.` or `:`.

Well, the [docs](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L4406) talk about characters only, but it does not say strings of length 1 (which is roughly the definition of a character). We might be able to implement multi-character triggers but it is not as trivial as it sound. Until then, an extension should use the *last* character in a potential sequence of trigger characters.

**Comment by felixfbecker** [comment]
@jrieken That would be great. Then I can change the trigger characters to `["::", "->"]` and  clients that already support sequences (e.g. https://github.com/eclipse/che/pull/3230/commits/61b2a93c32c7073f05b9f2a0c0a5a73642f356bd) can use that while VS Code would use the current behaviour until fully implemented.

Regarding the name, `triggerCharacters` is plural, so it is not defined whether that means an array where each element is a single character or where each element can also be multiple characters :)

**Comment by felixfbecker** [comment]
@jrieken what's the status of the intermediate solution you proposed? I am planning to switch the trigger characters to string sequences soon as this issue is now also hitting more users through Atom https://github.com/atom/ide-php/issues/47 and it's hard to justify holding on to that behaviour just for VS Code. Of course I don't want to break VS Code users though. Let me know if there is a way I can help.

**Comment by rcjsuen** [comment]
This reminds me of Microsoft/vscode#33697.

**Comment by felixfbecker** [comment]
@rcjsuen thanks for linking that, I've not seen that issue. The proposed solution doesn't work over LSP though.

**Comment by dbaeumer** [comment]
Actually the solution implemented by @jrieken in VS Code makes sense to me since it allows for the most flexibility. I will mirror that into the LSP in a backward compatible way. However it will make the node client implementation in compatible due to the middleware. But extension require this explicitly anyways.

**Comment by jens1o** [comment]
OMG. LOVE YOU!

**Comment by felixfbecker** [comment]
Implemented in https://github.com/felixfbecker/php-language-server/pull/527
