### ISSUE TITLE
Add "deprecated" property to CompletionItem and SymbolInformation

### ISSUE THREAD

**Issue by kaloyan-raev** [Microsoft/language-server-protocol#139]
Some editors might want to decorate deprecated completion items and symbols, e.g. via a strikeout.

Hence, a new `deprecated` property should be added to `CompletionItem` and `SymbolInformation`.

``` typescript
deprecated?: boolean;
```

**Comment by rcjsuen** [comment]
I opened Microsoft/vscode-languageserver-node#332 to add the property to the typings file.

**Comment by rcjsuen** [comment]
Closed by #465...

**Comment by rcjsuen** [comment]
This can be closed now, @dbaeumer. Thanks for merging the PR in!

**Comment by dbaeumer** [comment]
@rcjsuen thanks for reminding. Closing.
