### ISSUE TITLE
Upper bound of `uinteger` is atypical

### ISSUE THREAD

**Issue by michaelpj** [microsoft/language-server-protocol#1394]
The normal maximum value of a 32-bit unsigned integer type is 2^32-1, but the specification states it to be 2^31-1 (the maximum value of a 32-bit _signed_ integer type)

This makes it difficult to simply implement `uinteger` fields using a normal 32-bit unsigned integer value, and makes testing harder, since the maximum allowable value is not the maximum value of the type.

I believe this would be a simple change in the typescript implementation, since `uinteger` is just a range restriction of typescript's unbounded `number` type.

**Comment by dbaeumer** [comment]
That is correct but it was decided to keep that number range the same as the debugger adapter protocol (see https://microsoft.github.io/debug-adapter-protocol/specification)

**Comment by michaelpj** [comment]
Would it not be possible to change the DAP in the same way?

**Comment by dbaeumer** [comment]
I think the swirl will be too big. But you could open an issue against DAP and see if they change it.
