### ISSUE TITLE
VSCode 1.63.2 does not follow LSP Specification of 3.16

### ISSUE THREAD

**Issue by tm1000** [microsoft/language-server-protocol#1406]
I originally posted this on VSCode but since the Microsoft team essentially manages both this and VSCode I am opting to post it in both places since I dont know what side needs to change

The specification states: https://github.com/microsoft/language-server-protocol/blob/gh-pages/_specifications/specification-3-16.md#-diagnostic-

```js
export interface Diagnostic {
	...
	/**
	 * The diagnostic's code, which might appear in the user interface.
	 */
	code?: integer | string;
```

Yet VSCode itself does something entirely out of spec:
https://github.com/microsoft/vscode/blob/1.63.2/src/vscode-dts/vscode.d.ts#L5466

```js
	/**
	 * Represents a diagnostic, such as a compiler error or warning. Diagnostic objects
	 * are only valid in the scope of a file.
	 */
	export class Diagnostic {
		...
		/**
		 * A code or identifier for this diagnostic.
		 * Should be used for later processing, e.g. when providing {@link CodeActionContext code actions}.
		 */
		code?: string | number | {
			/**
			 * A code or identifier for this diagnostic.
			 * Should be used for later processing, e.g. when providing {@link CodeActionContext code actions}.
			 */
			value: string | number;

			/**
			 * A target URI to open with more information about the diagnostic error.
			 */
			target: Uri;
		};
```

Either VSCode should follow the specification or the specification should be adjusted to account for this

**Comment by rcjsuen** [comment]
@tm1000 You're looking at Visual Studio Code's API which can be whatever Microsoft deems. Their API (and any other LSP client's API) is not meant to map 1-to-1 with the language server protocol.

Are you trying to implement an LSP client, a language server, or just someone curious about the language server protocol?

**Comment by tm1000** [comment]
@rcjsuen thanks for the input.

I'm working on improving the implementation of PHP Psalm's usage of the LSP protocol, its not only used by VSCode so I'm trying to match the specification as closely as possible. 

What caught my eye was this code reference:
https://github.com/vimeo/psalm/blob/0eb00e8ae2b0552dd8910aef13c40926cd3fcf54/src/Psalm/Internal/LanguageServer/LanguageServer.php#L411-L426

**Comment by tm1000** [comment]
@rcjsuen can you see the comment from @IllusionMH on https://github.com/microsoft/vscode/issues/141893#issuecomment-1026130062

**Comment by rcjsuen** [comment]
> What caught my eye was this code reference: https://github.com/vimeo/psalm/blob/0eb00e8ae2b0552dd8910aef13c40926cd3fcf54/src/Psalm/Internal/LanguageServer/LanguageServer.php#L411-L426
> 
> ```
>                     if ($this->project_analyzer->language_server_use_extended_diagnostic_codes) {
>                         // Added in VSCode 1.43.0 and will be part of the LSP 3.16.0 standard.
>                         // Since this new functionality is not backwards compatible, we use a
>                         // configuration option so the end user must opt in to it using the cli argument.
>                         // https://github.com/microsoft/vscode/blob/1.43.0/src/vs/vscode.d.ts#L4688-L4699
> 
>                         /** @psalm-suppress InvalidPropertyAssignmentValue */
>                         $diagnostic->code = [
>                             "value" => $code,
>                             "target" => $issue_data->link,
>                         ];
>                     } else {
>                         // the Diagnostic constructor only takes `int` for the code, but the property can be
>                         // `int` or `string`, so we set the property directly because we want to use a `string`
>                         $diagnostic->code = $code;
>                     }
> ```
> 
> And I couldn't find a reference for this in LSP 3.16.0.

That looks like a bug to me. `DiagnosticRelatedInformation` should be used instead. Search for that in the specification instead.

**Comment by IllusionMH** [comment]
I was referring to comment https://github.com/microsoft/language-server-protocol/issues/926#issuecomment-722372942 which says
> documented in the 3.16 spec

So I would expect that 3.16 should already have this change or other changes (if other approach picked or other methods to implement it) related to links, however I haven't found one.

**Comment by rcjsuen** [comment]
> I was referring to comment [#926 (comment)](https://github.com/microsoft/language-server-protocol/issues/926#issuecomment-722372942) which says
> 
> > documented in the 3.16 spec
> 
> So I would expect that 3.16 should already have this change or other changes (if other approach picked or other methods to implement it) related to links, however I haven't found one.

@tm1000 I don't know what specification you are looking at but did you search the [website](https://microsoft.github.io/language-server-protocol/specifications/specification-current/)? `DiagnosticRelatedInformation` is mentioned there. 🤔

**Comment by rcjsuen** [comment]
@tm1000 Whoops, I now see I'm talking to two different people. :P Thank you for chiming in, @IllusionMH.

In any case, it's on the website, just search for `DiagnosticRelatedInformation`.

**Comment by tm1000** [comment]
Sorry about that @rcjsuen.

I posted this to both vscode and here because either the spec is wrong or vscode is wrong. Yes I understand that vscode doesnt have to follow the spec and thats all fine and good but at least now I can see that in #926 `DiagnosticRelatedInformation` was added, which is where I thought it should be in VSCode, so VSCode should actually use that. 

Instead there's projects just doing a hacky workaround for vscode not following the spec that it created (LSP was created for/by microsoft for vscode originally)

**Comment by rcjsuen** [comment]
> I posted this to both vscode and here because either the spec is wrong or vscode is wrong. Yes I understand that vscode doesnt have to follow the spec and thats all fine and good but at least now I can see that in #926 `DiagnosticRelatedInformation` was added, which is where I thought it should be in VSCode, so VSCode should actually use that.

I disagree because editors evolve at their own pace which is orthogonal to the speed at which the LSP specification is formalized. If editors (Eclipse, Visual Studio Code, Vim, Emacs, etc.) wants to add API to support use cases they are going to do that and they are going to name things in whatever naming guidelines they have defined in their API standards. If LSP community come to an agreement on something and decide sto name something one way that is (most definitely) going to be different from what the editors named them in their API layer, those editors can't just change their API names on a whim and break existing clients.

The editor's public API layer is different to the editor's plug-in/extension/module/addon that adds LSP functionality to said editor. Naming should make in the latter case but the former case is not and should not be a hard requirement. For reference, Visual Studio Code's "LSP bridge layer" is the [microsoft/vscode-languageserver-node repository](https://github.com/microsoft/vscode-languageserver-node/).

> Instead there's projects just doing a hacky workaround for vscode not following the spec that it created (LSP was created for/by microsoft for vscode originally)

I get what you are saying in the example you provided. Perhaps at the time things were still in flux before the community finalized on how to add information to the `Diagnostic` type, I do not know. On the other hand, Visual Studio Code 1.43.0 is almost two years old now and presumably not even supported by Microsoft anymore so it seems to me that project should just drop the workaround and implement the 3.16 specification properly.

**Comment by tm1000** [comment]
> For reference, Visual Studio Code's "LSP bridge layer" is the microsoft/vscode-languageserver-node repository.

Oh interesting. Thank you for that!

> On the other hand, Visual Studio Code 1.43.0 is almost two years old now and presumably not even supported by Microsoft anymore so it seems to me that project should just drop the workaround and implement the 3.16 specification properly.

That is what I am expecting to happen. But I will leave that in the court of VSCode as I assume that would also mean modifications for hundreds of LSPs that are just doing the same thing my reference library is doing (PHP Psalm in this case)

**Comment by rcjsuen** [comment]
> > On the other hand, Visual Studio Code 1.43.0 is almost two years old now and presumably not even supported by Microsoft anymore so it seems to me that project should just drop the workaround and implement the 3.16 specification properly.
> 
> That is what I am expecting to happen. But I will leave that in the court of VSCode as I assume that would also mean modifications for hundreds of LSPs that are just doing the same thxing my reference library is doing (PHP Psalm in this case)

I don't know what you are leaving in the court of Visual Studio Code given that VS Code's developers have no say in what happens with this Psalm language server. It is up to the Psalm development team to decide to stop trying to support an old version of Visual Studio Code and to just implement the 3.16 specification as-is.

> As for my code. I will just support both methods. I can technically use ClientInfo to figure out if the client is vscode and then do the magic that VSCode expects in this particular case (good or bad)

I don't follow. Why not just support the 3.16 way? The 3.16 way should work in Visual Studio Code. The bridge will [convert an LSP `Diagnostic` into a VS Code `Diagnostic`](https://github.com/microsoft/vscode-languageserver-node/blob/292dd0d88b6465337e42ba40ad986fdfdeb42d4d/client/src/common/protocolConverter.ts#L275-L305). If the 3.16 way does not work then a bug should be raised in the bridge layer.

**Comment by tm1000** [comment]
I totally missed the part about the bridge again. 

I am the developer working on this for psalm. I'll implement it the 3.16 way

I think I was stuck on the fact that I thought vscode was 1:1 but infact there is the LSP in the middle of which I should have been aware of.

**Comment by dbaeumer** [comment]
@rcjsuen thanks for the good and clarifying answers.
