### ISSUE TITLE
What is the correct way to send a custom Command from client to server with result

### ISSUE THREAD

**Issue by ballcoach12** [microsoft/language-server-protocol#1408]
I am working on a Language Server extension for a custom DSL. In the extension, I need to send a custom (as opposed to built-in) Command from the client to the Language Server to get the language server to execute a task. I also need for the Language Server to return a result. Can anyone explain the expected way to go about this? I'm specifically trying to get the server side implementation nailed down. Do I use the connection to send back a notification? Is a Command even the right way to do this?

**Comment by michaelmesser** [comment]
It would depend on what you are trying to do. What is the result you want to return? My guess would be you want to add your own method like [rust-analyzer does](https://github.com/rust-analyzer/rust-analyzer/blob/master/docs/dev/lsp-extensions.md).

**Comment by ballcoach12** [comment]
In the simplest case, I'd want to return an error message, or a numeric  completion result. In a more  complex case, I'd want to modify the  text that is in the open editor on the vs code client  side.

**Comment by rcjsuen** [comment]
> In the simplest case, I'd want to return an error message, or a numeric completion result. In a more complex case, I'd want to modify the text that is in the open editor on the vs code client side.

I'm not sure I follow. So the user clicks something or hits some hotkey and any of the three can happen depending on the circumstances?
- an error dialog message pops up
- I get a completion result, ergo I have invoked code completion like as if I hit <kbd>Ctrl</kbd>+<kbd>Space</kbd>
- the text where my cursor is at changes

**Comment by ballcoach12** [comment]
I'm pretty new to Extension development, so please feel free to suggest better methods here...

As my code is written right now, the language extension registers a custom command when  it is activated. At  such time as the command is invoked, the client essentially curries it with parameters to the language server via LSP. The language server contains the syntax tree necessary to perform the operation, which is to send a transformed version of the model to an external 
 API. The state of the model must also change if the operation succeeds, and that state change should be reflected in the text that the client editor displays.

I think a [Command ](https://microsoft.github.io/language-server-protocol/specification#command)  fits the description of what I'm trying to do,  although I also see that I could call the client's sendRequest() function.  And I could possibly use the server's connection to call it's sendNotification() function. However,  it seems  like a misuse of the sendNotification() function to request modification of the editor's text.

**Comment by ballcoach12** [comment]
Also, I realize that my question might be starting to drift outside the scope of LSP and into VS Code, which is the platform that I am developing for. Feel free to send me to that project if my question is off topic.

**Comment by rcjsuen** [comment]
@ballcoach12 I think you can get by with a `workspace/executeCommand`. Ideally I would suggest using `textDocument/codeAction` though to help with discoverability of your feature and that should ensure it works with other LSP clients as well.

**Comment by ballcoach12** [comment]
Thanks @rcjsuen. I will go that route.
