### ISSUE TITLE
Documentation - links in the spec document on the website point to a different version

### ISSUE THREAD

**Issue by pedro-w** [microsoft/language-server-protocol#1411]
On the LSP website, internal links for the current (3.16) version point to elements in the 3.17 version. This is minor but it's a bit tiresome when trying to note down references to a stable version. There are no such links in the markdown source so I'm not sure how they get added; apologies if this is the wrong place to report.
For example: https://microsoft.github.io/language-server-protocol/specifications/specification-3-16/#requestMessage is a location in the 3.16 spec, but just below the heading is a block of interface code, containing links to, amongst others, the 3.17 version of [RequestMessage](https://microsoft.github.io/language-server-protocol/specifications/specification-3-17/#requestMessage)
Would it be possible to have the link target be the same as its source, i.e. 3.16 -> 3.16, current -> current and so on?

**Comment by dbaeumer** [comment]
@NTaylorMullen can I ask you to have another look at this.

**Comment by NTaylorMullen** [comment]
> @NTaylorMullen can I ask you to have another look at this.

On my todo list for a while now, promise I'll get to it eventually! 😄

**Comment by pedro-w** [comment]
This still happens but it's not so bad now as the links do point to a stable version (I think they used to point to version 'current' when I reported this), so thanks for your support so far. I had a look myself, I can build the pages locally with Ruby etc. but for the life of me I can't figure out how the hyperlinks get added to the markdown code blocks. How does it work?

**Comment by dbaeumer** [comment]
@NTaylorMullen friendly ping.

**Comment by pedro-w** [comment]
Don't wait for the unfriendly ping :wink:

Seriously though, you guys have got more important things to worry about -  I'd be happy to have a poke around and see if I can fix it myself, but I could just do with a hint to get started !

**Comment by dbaeumer** [comment]
@pedro-w thanks!!

@NTaylorMullen can you help @pedro-w to get started?

**Comment by pedro-w** [comment]
OK, I think it is hard-coded in 

https://github.com/microsoft/language-server-protocol/blob/ff54ee8f15365600ee8c53e00644b231f51c9368/_includes/js_files.html#L40

and links are generated in the browser by JS in that file (that's why I couldn't find it!)
Is that correct?

**Comment by pedro-w** [comment]
I think I've found a way to fix this which needs only small changes. I will put up a PR "For discussion only" and you can maybe comment if it's feasible (you may have other constraints I've not thought of). However it'll take me a couple of days as I am a bit short of time at the moment.

**Comment by NTaylorMullen** [comment]
@pedro-w feel free to mention me in your PR l. Would love to help guide!

**Comment by pedro-w** [comment]
@NTaylorMullen  thanks for your offer of help. Please see #1551 !

**Comment by NTaylorMullen** [comment]
Will look it over today!

**Comment by dbaeumer** [comment]
PR merged. Will close the issue.
