### ISSUE TITLE
Add support for itemDefaults.Data

### ISSUE THREAD

**Issue by NTaylorMullen** [microsoft/language-server-protocol#1423]
Today I've found a common pattern used by completion endpoints of language servers is to cache a completion item's resolve data per-completion list. For instance, here's how a completion list might look:

```json
[
  {
     "insertText": "first item"
      "data": {
          "resultId": 0
      }
  },
  {
     "insertText": "second item"
      "data": {
          "resultId": 0
      }
  }
]
```

Upon resolve a server can then use the `resultId` 0 to lookup the corresponding completion list that the item was produced from and then find the item by label. This pattern tends to be a more consistent way to cache completion data so you're caching on a per-completion list basis instead of an item basis.

With this pattern in mind if we had completionList.itemDefaults.Data this "lookup" could further be optimized to allow a server to say all items from this completion list have a specific result id.

**Comment by dbaeumer** [comment]
Added for 3.17
