### ISSUE TITLE
[folding] custom folding text for folded ranges

### ISSUE THREAD

**Issue by ris58h** [microsoft/language-server-protocol#1426]
Other IDE's like `Visual Studio` or `Intellij IDEA` allow to define custom text for folded regions.

There are a lot of issues that could be solved with this feature: https://github.com/microsoft/vscode/issues/70794 , https://github.com/microsoft/vscode/issues/3352 , https://github.com/microsoft/language-server-protocol/issues/827 and other.

The proposed change is to add `collapsedText` property to [FoldingRange](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#foldingRange) interface:
```
interface FoldingRange {
	startLine: uinteger
	startCharacter?: uinteger
	endLine: uinteger;
	endCharacter?: uinteger;
	kind?: string;

        collapsedText?: string;
}
```

The problem is: what should clients that don't support char-ranges folding (`lineFoldingOnly === true`) do? I've described the problem in https://github.com/microsoft/vscode/issues/70794
Possible options are:
1. Clients must replace the whole first line too.
2. Clients must show the `collapsedText` at the end of the first line.
3. Clients are free to decide how they show it.
4. Add a property to the `FoldingRange` to specify the behavior.

**Comment by aeschli** [comment]
Having a collapsedText makes sense. 
Following the current logic, for lineFoldingOnly === true, by default it will be shown at the end of the line.

To replace the full line, we could allow that the startCharacter can be set to 0, even when lineFoldingOnly === true.

**Comment by ris58h** [comment]
@aeschli it's a great idea to use `startCharacter` 👏
Do we need an additional property in `FoldingRangeClientCapabilities` to specify that client doesn't support `collapsedText`?

**Comment by aeschli** [comment]
Yes, a new capability is needed. It will be false by default.

**Comment by ris58h** [comment]
Ok. What's next? Should I make PR in https://github.com/microsoft/vscode-languageserver-node repository?

**Comment by dbaeumer** [comment]
Yes, first we need to have an implementation for this.

**Comment by ris58h** [comment]
The PR is ready https://github.com/microsoft/vscode-languageserver-node/pull/910

**Comment by ryzngard** [comment]
@ris58h are you able to do a PR against the specification here? Definitely interested in this moving forward.

**Comment by ris58h** [comment]
@ryzngard I'm interested too but I'm on vacation right now, so not in the very near future.

**Comment by ryzngard** [comment]
I went ahead and created a PR in the meantime, which I hope is correct. Please let me know if anything needs to change.

@ris58h if you get back from vacation and want to take over by all means feel free.

**Comment by dbaeumer** [comment]
Added to 3.17.
