### ISSUE TITLE
specify documentation fields as such

### ISSUE THREAD

**Issue by vladdu** [Microsoft/language-server-protocol#143]
The docs for the hover method specify that the contens is to be rendered as markdown. I'm not sure if that should be a part of the protocol, but if it is, there are several more fields that contain the same kind of information and maybe should be specified as such.

CompletionItem has detail and documentation fields. SignatureInformation and ParameterInformation have documentation fields. Even a Diagnostic's message might be seen as such a sort of information (border case, though).

**Comment by rictic** [comment]
Related: #111 and #137

**Comment by vladdu** [comment]
Actually, duplicate of #137.
