### ISSUE TITLE
 language-server-protocol

### ISSUE THREAD

**Issue by Create-For-Fun** [microsoft/language-server-protocol#1434]
[-](https://github.com/microsoft/language-server-protocol/issues/new#) <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
[-](https://github.com/microsoft/language-server-protocol/issues/new#) <System>
  <Provider Name="Microsoft[-](https://github.com/microsoft/language-server-protocol/issues/new#)Windows-Kernel-PnP" Guid="{9c205a39-1250-487d-abd7-e831c6290539}" /> 
  <EventID>410</EventID> 
  <Version>0</Version> 
  <Level>4</Level> 
  <Task>0</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x4000000000000000</Keywords> 
  <TimeCreated SystemTime="2022-04-01T20:34:03.9208426Z" /> 
  <EventRecordID>291</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="4" ThreadID="5428" /> 
  <Channel>Microsoft-Windows-Kernel-PnP/Configuration</Channel> 
  <Computer>DESKTOP-K4GP9E6</Computer> 
  <Security UserID="S-1-5-18" /> 
  </System>
- <EventData>
  <Data Name="DeviceInstanceId">USBSTOR\Disk&Ven_Hitachi&Prod_HTS545050A7E380&Rev_\20211118&0</Data> 
  <Data Name="DriverName">disk.inf</Data> 
  <Data Name="ClassGuid">{4d36e967-e325-11ce-bfc1-08002be10318}</Data> 
  <Data Name="ServiceName">disk</Data> 
  <Data Name="LowerFilters" /> 
  <Data Name="UpperFilters" /> 
  <Data Name="Problem">0x0</Data> 
  <Data Name="Status">0x0</Data> 
  </EventData>
  </Event>

**Comment by dbaeumer** [comment]
I will close the issue as not actionable.
