### ISSUE TITLE
New types instead of interfaces

### ISSUE THREAD

**Issue by KamasamaK** [microsoft/language-server-protocol#1444]
I've noticed for some of the newer features such as [Type Hierarchy](https://github.com/microsoft/language-server-protocol/blob/7201ba1db625708daf3d81bcd0e6433a923e5830/_specifications/lsp/3.17/language/typeHierarchy.md), [Inlay Hint](https://github.com/microsoft/language-server-protocol/blob/deed0a9aca949fe11bd8f7e43b43d8031cb1ab75/_specifications/lsp/3.17/language/inlayHint.md), and [Inline Value](https://github.com/microsoft/language-server-protocol/blob/e31b4a251739e39b9c6728717e3fa2c7f3d743b0/_specifications/lsp/3.17/language/inlineValue.md) that the objects that would have previously been defined as `interface`s are now defined as `type`s. Why the change? Shouldn't this apply consistently throughout the protocol?

**Comment by dbaeumer** [comment]
Although I am a big fan of consistency these things aren't really interfaces (they shouldn't be implemented). They are type definitions (e.g. structs) and type = { .... } expresses this better.  This is why I started to use them in the implementation and also in the spec. The reason why I used interfaces in the past is that TS didn't have support for types when I started LSP.

I am open for suggestions on how to better express this.

**Comment by KamasamaK** [comment]
The TypeScript documentation still seems to refer to `interface`s as types, but if you prefer the new `type` construct then my suggestion would simply be to consistently apply this new paradigm to the previous types in the spec. I'm not sure if there would be compatibility concerns with doing this in your implementation but I don't think that should prevent the spec from having this consistency. And it seems that the new 8.0 implementation would be able to accommodate breaking compatibility in any case.

**Comment by Kinou90100** [comment]
#1457 
#1456 
#1455 
#1454 
#1453 
#1445
#1444
#303 
@Kinou90100
@Christoc90

**Comment by dbaeumer** [comment]
Made them interfaces for now in the specification for 3.17.
