### ISSUE TITLE
Semantic tokens range protocol spec is unclear about how to determine range client should invalidate

### ISSUE THREAD

**Issue by gundermanc** [microsoft/language-server-protocol#1447]
# Background

I recently discovered an issue in Visual Studio for Windows 'Razor LSP' scenario where large ranges of semantic tokens can 'disappear' as the user scrolls when [polling is disabled](https://devdiv.visualstudio.com/DevDiv/_git/VSLanguageServerClient/pullrequest/388715).

This issue seems to arise from different interpretations of a language server protocol spec ambiguity.

# The Ask
Can we please clarify the spec to indicate what is the correct behavior when:

- An LSP server returns tokens in response to `textDocument/semanticTokens/range` that don't fall within the requested range.
and
- The tokens outside the requested range are an incomplete set, for which, a more complete answer has previously been returned.

# Example
Consider this Razor C# case:

```razor
@{
Console.WriteLine();

...

Console.WriteLine();
}
```

In the current Razor LSP server:
- The client can request the range encompassing the first line and the LSP server returns just those tokens.
- The client then requests the range encompassing just the last two lines, and the LSP server returns those tokens _and_ an additional token spanning the `@{` at the start of the C# block, outside of the requested range.
- Note that no semantic tokens between the `@{` and the start of the requested range were returned.

When invalidating the viewport the VS Windows LSP client seemingly innocuously assumes that all semantic tokens 1) in the requested range OR in the range encompassed by the maximum extent of the union of the set of new tokens, and the invalidated range, should be cleared.

Since the Razor response omitted any semantic tokens between `@{` and the start of the requested range, all of those tokens are then cleared erroneously.

![image](https://user-images.githubusercontent.com/5387680/164576393-56d186e8-351d-4e08-b492-93ccb393dc3f.png)

**Comment by gundermanc** [comment]
The candidate fix for VS simply ignores all semantic tokens returned that fall outside of the requested range: https://devdiv.visualstudio.com/DevDiv/_git/VSLanguageServerClient/pullrequest/394818

**Comment by dbaeumer** [comment]
@gundermanc isn't the underlying problem that a server returns a large range however the tokens in that range are  incomplete or incorrect. So I propose that we clarify the spec in a way say:

- if the server extends the range the tokens in that range must be complete and correct. 

This ensures that the client doesn't need to adjust the result.

**Comment by gundermanc** [comment]
Sounds good, thank you
