### ISSUE TITLE
Getting [] & null response from LSP server running in different machine

### ISSUE THREAD

**Issue by ThisIsNSH** [microsoft/language-server-protocol#1449]
**Goal:** 
Separate LSP client and LSP server such that LSP server runs on a different machine where LSP client communicates with it through websockets. 

**Background**
The goal is achieved but LSP server needs to know the location of code and access it while initialize message is sent from client, if not then it throws DIR not found error in logs. So when I add the **code with same path** (as on client) on the LSP server everything works well. 

**Question**
Is there any alternative where we do not have to share the code initially with the LSP server and it still works well for projects with multiple files (and go to definition, etc. work well)? For single file project, having whole code already doesn't make sense because there is no feature like go to definition etc. 

**Problem**
Assuming that there is no alternative, I put the code on LSP server (but not on the same path as on client) lets say file://a/b/c/d.cs. But on client the code is available on file://n/m/o/p.cs. Now during the communication between LSP client & server, I change all the Paths & URIs in the message. 

So, when LSP Client sends a message to LSP server, I use path recognisable by the server (i.e. file://a/b/c/d.cs) and send the message. And when LSP client sends a message, before processing it I change the path that client knows (i.e. file://n/m/o/p.cs). 

But doing this gives me either [] or null as response for all the messages client sends to the server like documentSymbol, definition etc. 

Is having server on different machine even supported? If yes then is there any resource available for it? Or how can I fix the [] or null issue?

**Comment by dbaeumer** [comment]
This is currently not supported (mainly because of the reasons you pointed out). There is support though in the VS Code LSP client for URI mappings to help with such a setup, but no official support there either.

**Comment by ThisIsNSH** [comment]
@dbaeumer thanks for the reply. 

I am actually performing the URI mapping from the LSP client and that's when I am getting null responses. My guess is that I am missing some hidden mapping somewhere. 

Because I logged the JSON RPC communications and manually checked that the URI mapping is right where LSP server is sent a message with path that it knows and LSP client gets a message with path that it knows. 

Are you aware of any issue where someone tried something similar and made it work?

**Comment by ThisIsNSH** [comment]
Yup! The communication happens properly. It's just that the response I get is null or empty. This only happens during URI mapping. If I put the code on LSP server on the same path as client then everything works normally! 

Any hint what could be wrong here?

**Comment by ThisIsNSH** [comment]
@dbaeumer well there was a problem with the LSP-server I was using. Fixed that and URI mappings fine. Thanks :)
