### ISSUE TITLE
TextDocumentSyncKind detailed behaviour

### ISSUE THREAD

**Issue by alanz** [Microsoft/language-server-protocol#145]
The documentation for `TextDocumentSyncKind` offers `None`, `Full`, or `Incremental`.

In vscode this behaves such that omitting the parameter from the server capabilities returned to the client is effectively a fourth  option, where `DidSave` events are generated without sending document contents.

And `DidChangeTextDocument` notifications are not sent either.

This should be documented in the protocol if this is expected behaviour in all clients.

**Comment by dbaeumer** [comment]
@alanz thanks. I made this more clear in the upcoming 3.0 version. In addition there is now an option to ask for the content on save notifications and to more fine gain control what events are sent (for example you can only get open/close without save). 

Omitting the value ===  TextDocumentSyncKind.None (which is defined as 0, a falsy value).
