### ISSUE TITLE
Expose a proper tokenization/colorization VSCode API for LSP implementing Syntax Highlighting

### ISSUE THREAD

**Issue by raid2light** [microsoft/language-server-protocol#1454]
Currently syntax highlighting is done using TextMate grammars for VSCode LSP extensions. However there is no way to retrieve color of individual text or words in documents using VSCode API. Propose adding such API to be able to get colors for individial tokens within document (and possibly change them as well).

**Comment by michaelmesser** [comment]
This is the LSP spec repository. I think you meant to make this on one of the VSCode repositories.

**Comment by dbaeumer** [comment]
@michaelmesser thanks for chiming in. Will close the issue since it should be opened against VS Code.
