### ISSUE TITLE
TextDocumentContentChangeEvent#range required

### ISSUE THREAD

**Issue by KamasamaK** [microsoft/language-server-protocol#1455]
Re: #9

Was it intentional to change `TextDocumentContentChangeEvent#range` from optional to required between v3.14 and v3.15? I would expect that to be a compatibility issue.

**Comment by dbaeumer** [comment]
Yes, that was intentionally and discussed. LSP adoption was still fairly young, and it was the best way forward given the confusion range and rangeLength caused.

**Comment by KamasamaK** [comment]
Ok. I didn't see that discussed in #9. Then I think the description of `TextDocumentContentChangeEvent` needs to be modified. Right now it says "If range and rangeLength are omitted the new text is considered to be the full content of the document", but range cannot be omitted now.

**Comment by dbaeumer** [comment]
It can because it is an or type with

```{
	/**
	 * The new text of the whole document.
	 */
	text: string;
}
```

But I will formulate that in a positive manner.

**Comment by KamasamaK** [comment]
I see now. I wasn't looking at that correctly.

**Comment by dbaeumer** [comment]
Yes, but it is interpreted as a full replace. That was the case as well in 3.14 but very hard to understand with both being optional.
