### ISSUE TITLE
tests: compliance tests

### ISSUE THREAD

**Issue by mbana** [Microsoft/language-server-protocol#146]
i know this is being heavily worked on, however, i am wondering if there is a set of automated tests like there is with [amdjs-tests](https://github.com/amdjs/amdjs-tests). it could be tied to a specific language and server so long as it's defacto and kept in-sync with the protocol.

if so, any ETA?

**Comment by dbaeumer** [comment]
I fully agree that something like this would be awesome. We have work in the pipeline to add support for this to our node modules we maintain.

Besides executing the test we would need a standardize set of test to run. This would be something someone could work in parallel on.

**Comment by dbaeumer** [comment]
This got addressed by providing a pure npm module of the protocol. It is vscode-lanaguagserver-protocol. This can be used in JS based test frameworks. We have no plans to provide this for other languages right now.
