### ISSUE TITLE
how to fold the single line?

### ISSUE THREAD

**Issue by amoxuk** [microsoft/language-server-protocol#1460]
I want to fold a long line with the prefix word. 

example:
the long line with so many words is like base64 characters:
```text
![](data:image/*;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0aHBwgJC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx)
```
how to folding to like this:
```text
![](data:image/*;base64... 
```
I tried to write ext like this in LSP but it didn't work as my expected:
```js
function getFoldingInfo(textDocument: TextDocumentIdentifier) {
	const folding: FoldingRange[] = [];
	//folding my long character line.
	folding.push({
		startLine: 26,
		startCharacter: 14,
		endLine: 26,
		endCharacter: 1,
		kind: 'imports',  // region
	});
	return folding;
}
```

**Comment by dbaeumer** [comment]
@aeschli can you help me with this?

**Comment by amoxuk** [comment]
do you have any plan to support this feature?

**Comment by aeschli** [comment]
@amoxuk No, we currently have no plans to support folding regions that cover only part of a line.
https://github.com/microsoft/vscode/issues/50840 is the issue.

**Comment by dbaeumer** [comment]
The capability that defines whether a client supports this or not is: https://github.com/microsoft/vscode-languageserver-node/blob/4aec18d2b1ef3d029cd2e135492c41a42d86ed8f/protocol/src/common/protocol.foldingRange.ts#L38

I will close the issue since general support exists in LSP.
