### ISSUE TITLE
Getting all files in the workspace

### ISSUE THREAD

**Issue by MetalSlime0** [microsoft/language-server-protocol#1465]
(Originally posted at https://github.com/microsoft/vscode-languageserver-node/issues/928 but they pointed me here.)

It seems to me that my language server needs to have its own code for scanning the workspace folders for relevant files that are necessary to get proper diagnostics in the open files. (As a side note, I'm curious whether this is the wrong approach or how other languages manage this sort of thing. If I'm "doing it wrong" let me know.) On the other hand, there is the workspace/didChangeWatchedFiles notification, which is really convenient for determining when those files have changed.

Is there a way to just get the list of files in the workspace (matching a pattern) from the client, instead of writing my own code for it? It is challenging that my server code has to handle different platforms and can't use the same "glob pattern" syntax when searching for files. If this doesn't exist, might I suggest adding an optional "found" event to didChangeWatchedFiles that simply reports all of the files matching the pattern when the capability is registered? (I suppose it would also need a "lost" event so it could handle changes to the registered globPattern and/or changes to the workspace folders.)

Sorry if this is the wrong place for a question like this; please let me know if there's somewhere more appropriate.

**Comment by dbaeumer** [comment]
There is work under way to add such a support. But it is more targeted to virtual file system. In general the design of LSP is that the server runs where the files are. Making a request to the client to find all files will result in unnecessary client / server round trips which especially hurt in a remote setup. So it is currently common pratice that a server accesses the file system directly (minus the files for which the server received an open event since this transfers the file's ownership to the client)

**Comment by MetalSlime0** [comment]
OK, at least I'm doing it right. Out of curiosity, how does didChangeWatchedFiles work at all in a remote setup?

**Comment by dbaeumer** [comment]
There is a special watcher in the extension host that runs in the remote.

**Comment by nbrugger-tgm** [comment]
How would this work in a remote scenario. As far as i understand it, except for this use case, the LSP is designed that it can run fully isolated from everything as long as an input/output stream is there to communicate. With the exception of loading non opened files it is entirely possible to write LSPs in a way that they can run in a container, remote ... somewhere else. I assume that's also the reason why didOpen sends the entire content of the file to the LSP and not just the URI and expecting the server to access the local file system.

**Comment by MetalSlime0** [comment]
I'm not familiar with how things work in a remote scenario in general, but this question is about the didChangeWatchedFiles notification which _already_ involves the client editor watching files for changes that can happen from outside the client.
