### ISSUE TITLE
VersionedNotebookDocumentIdentifier is referenced (but not defined) in the v3.17 spec

### ISSUE THREAD

**Issue by DanTup** [microsoft/language-server-protocol#1468]
In the current 3.17 version of the spec at https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/

```typescript
export interface DidChangeNotebookDocumentParams {
	notebookDocument: VersionedNotebookDocumentIdentifier;
```

However there's no other occurrence of `VersionedNotebookDocumentIdentifier` in that page defining what `VersionedNotebookDocumentIdentifier` is.

**Comment by dbaeumer** [comment]
Fixed in branch.
