### ISSUE TITLE
Add context information to MarkedString

### ISSUE THREAD

**Issue by felixfbecker** [microsoft/language-server-protocol#147]
# Issue

See https://github.com/Microsoft/vscode/issues/14166

Sending a `MarkedString { language: 'php', value: 'public function myFunction()' }` will not result in any syntax highlighting, because important context is missing - most notably the `<?php` it is contained in.

From https://github.com/Microsoft/vscode/pull/16503#issuecomment-265226860

> It is clear that we need a way for hover messages to render differently than we render in the editor because the code is, by definition, incomplete, and doesn't necessarily include all of the contextual information that's required to properly tokenize the string

A hover code is never a syntactically valid document that can be tokenized like one, it's an excerpt. This is _not_ just a PHP problem, but it's an issue that happens to be most visible in PHP. It affects all languages where a declaration can only be tokenized correctly with knowledge of the context.
For example: take this TypeScript / Javascript / JSON document:
```ts
const x = {
  "a": 1,
  "b": 2,
  "c": 3
}
```
The property keys inside the object are rendered blue:

![image](https://cloud.githubusercontent.com/assets/10532611/20937126/e250cf5a-bbe5-11e6-81aa-0c3444eed42d.png)

Now lets say we access the `b` property somewhere and hover over it, and the language server wants to respond with the declaration line:
```ts
"b": 2
```
this is an excerpt from the document, it is incomplete and syntactically invalid. Because it doesn't know about the context of being in an object literal, the key will now be colored orange, like a string literal:

![image](https://cloud.githubusercontent.com/assets/10532611/20937196/20de5652-bbe6-11e6-9dcc-80fd63ca7ee1.png)

Another example: We define this class in TypeScript / JavaScript:

![image](https://cloud.githubusercontent.com/assets/10532611/20937301/a607f112-bbe6-11e6-8050-19dc97edfd41.png)

Now we use `sayHello` somewhere, and hover over it. The language server will want to show the declaration line. But because it doesn't include the `class` context around it, it is colored like a function _call_, not a function _declaration_ - which means it gets some highlighting, but there is no proper coloring for the parameter and return types:

![image](https://cloud.githubusercontent.com/assets/10532611/20937335/d375734a-bbe6-11e6-9c46-9b3ce634d4ce.png)

In these examples, the syntax highlighting is wrong, the highlighter always highlights the line as something it is not (property key vs string, method definition vs method call). This is the exact case in PHP - instead of highlighting a string like `class X extends Y` as a class declaration, it is highlighting it as HTML, because it is missing the context. It is only very visible in PHP, because while in the other cases there is at least _some_ broken coloring, in PHP it's simply all white (except if you happened to use something that looks like an HTML tag).

# Proposal

So I think the only real solution to this issue would be to extend the `MarkedString` of the LSP with context information, e.g. properties for "invisible" pre- and suffixes that the LS can provide to make the string get tokenized correctly. This would be backwards-compatible since current clients would simply ignore the properties.

```ts
interface MarkedString {

  language: string;

  /**
   * An optional prefix that provides context to the editor.
   * It is prepended to `value` only for tokenization and not shown to the user.
   */
  prefix?: string;

  /**
   * the code shown to the user
   */
  value: string;

  /**
   * An optional suffix that provides context to the editor.
   * It is appended to `value` only for tokenization and not shown to the user.
   */
  suffix?: string;
}
```

Example usage, fixing the above examples:
```ts
{
  language: 'ts',
  prefix: 'const x = {',
  value: '"b": 2',
  suffix: '}'
}
{
  language: 'ts',
  prefix: 'class X {',
  value: 'sayHello(param: string): void',
  suffix: ' {} }'
}
{
  language: 'php',
  prefix: '<?php ',
  value: 'class X extends Y implements Z',
  suffix: ' {}'
}
```

/cc @mousetraps @jrieken

**Comment by dbaeumer** [comment]
Needs some thinking...

**Comment by felixfbecker** [comment]
Sure. I suggest you read through the linked issue and PR, this is the result of a lengthy discussion :)

**Comment by felixfbecker** [comment]
@dbaeumer anything that speaks against this?

**Comment by mousetraps** [comment]
Looking over this once more, this proposal could be simplified by removing the suffix property because in most cases, the prefix should be sufficient to determine context.

**Comment by felixfbecker** [comment]
Depends on whether the syntax highlighter used by the client can detect partial structures.

**Comment by felixfbecker** [comment]
I would say allow the LS to provide it. It's optional, it can leave it out.

**Comment by dbaeumer** [comment]
@jrieken have you thought about this? You own a PR https://github.com/Microsoft/vscode/pull/16503 to change this.

I do see the need to provide some context information. However I do think that we need to validate something like with an implementation.
