### ISSUE TITLE
[Meta Model] Indicate message source/destination

### ISSUE THREAD

**Issue by KamasamaK** [microsoft/language-server-protocol#1472]
> it would be nice if Notifications and Requests said whether they were sent
> by the client, the server, or both.

_Originally posted by @pjweinbgo in https://github.com/microsoft/language-server-protocol/issues/67#issuecomment-1093409730_

Since that issue was closed, making this its own issue.

**Comment by michaelpj** [comment]
cf https://github.com/microsoft/vscode-languageserver-node/issues/998

**Comment by KamasamaK** [comment]
Fixed by #1549
