### ISSUE TITLE
How to get/work with not opened in the editor text document (for rename refactoring)

### ISSUE THREAD

**Issue by wclr** [microsoft/language-server-protocol#1477]
This is kind of question how to correctly work with LSP when implementing rename refactoring.

To get refactoring done we should prepare WorspaceEdits. To do this we need to handle content of files that need to be changed. 

We use initialized `TextDocuments` store to get `TextDocument` by uri to get text content and perform some specific operations like `getTextRange`. 

But if the document was not opened in the editor, it doesn't get in TextDocuments store, so we can not get this doc form the store and work with it as a `TextDocument`.

So, what is the advice how should we deal with documents that are not in `TextDocuments` store? Should we perform FS ops (to load text file content) and custom content related operations (like search), or it is posible somehow to load it and use it as a `TextDocument` (I didn't see this capability in the API)?

**Comment by dbaeumer** [comment]
The language server owns the files. The open notification transfers that ownership to the client. So, for files that are not open the server can read them itself. See https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_didOpen

**Comment by wclr** [comment]
@dbaeumer 

> So, for files that are not open the server can read them itself.

Sorry, I think didn't get your answer (how it answers my orignal question). So, Is there a way for the server imperativly to open arbitrary file by Uri as a `TextDocument`? Could you elaborate?

**Comment by dbaeumer** [comment]
Sorry, misunderstood your original question

https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#window_showDocument

**Comment by wclr** [comment]
Thanks will try this!
