### ISSUE TITLE
How to get the current text in onCompletion?

### ISSUE THREAD

**Issue by wireva** [microsoft/language-server-protocol#1492]
``` ts
connection.onCompletion(
	(_textDocumentPosition: TextDocumentPositionParams): CompletionItem[] => {
		console.log(_textDocumentPosition);
		return wordlist;
	}
);
```

This is my onCompletion handler. Now I would like to do fuzzy search on wordlist with the current word being typed. How would I do this? Opening the file manually is not an option because the file is not saved on every keystroke.

_textDocumentPosition only contains a position and a filename, but no content

**Comment by wireva** [comment]
figured it out:

```ts
connection.onCompletion(
	(pos: TextDocumentPositionParams): CompletionItem[] => {
		const range = {start: {line: pos.position.line, character: 0}, end: pos.position};
		const word = documents.get(pos.textDocument.uri)?.getText(range).split(" ").slice(-1)[0];
		// do stuff
	}
);
```

**Comment by KamasamaK** [comment]
@niwla23 FYI, this repo is for the protocol. Open future issues about the NPM packages at https://github.com/microsoft/vscode-languageserver-node/.
