### ISSUE TITLE
Delete folder sends no message.

### ISSUE THREAD

**Issue by PedersenThomas** [Microsoft/language-server-protocol#150]
When I delete a file I get the "workspace/didChangeWatchedFiles" message, but nothing seems to happen when I remove a folder full of files.

I have the following setup:

```typescript
let clientOptions: LanguageClientOptions = {
        documentSelector: [LanguageId, 'json'],
        synchronize: {
            configurationSection: LanguageId,
            fileEvents: vscode.workspace.createFileSystemWatcher('**/*.foo')
        }
    }
```

Is it by design or have I missed something?

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/vscode-languageserver-node#141

**Comment by dbaeumer** [comment]
This should be discussed on the implementation side.
