### ISSUE TITLE
Missing link to Uri.scheme?

### ISSUE THREAD

**Issue by MariaSolOs** [microsoft/language-server-protocol#1502]
In several places of the documentation there are Markdown links to `Uri.scheme`, but they're not actually linking to anything. As an example from [`NotebookDocumentFilter`](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#notebookDocumentFilter):
```
export type NotebookDocumentFilter = {
   /** The type of the enclosing notebook. */
   notebookType: string;

   /** A Uri [scheme](#Uri.scheme), like `file` or `untitled`. */
   scheme?: string;

   /** A glob pattern. */
   pattern?: string;
}
...
```

Is this on purpose?

**Comment by dbaeumer** [comment]
Actually, not on purpose. I guess it is not covered by the link detection script we have.
