### ISSUE TITLE
SemanticTokensLegend doesn't use enum types

### ISSUE THREAD

**Issue by michaelpj** [microsoft/language-server-protocol#1503]
```
export interface SemanticTokensLegend {
	/**
	 * The token types a server uses.
	 */
	tokenTypes: string[];

	/**
	 * The token modifiers a server uses.
	 */
	tokenModifiers: string[];
}
```
Why not
```
export interface SemanticTokensLegend {
	/**
	 * The token types a server uses.
	 */
	tokenTypes: SemanticTokenTypes[];

	/**
	 * The token modifiers a server uses.
	 */
	tokenModifiers: SemanticTokenModifiers[];
}
```
Would need a metamodel change too, I think making `SemanticTokenTypes` and `SemanticTokenModifiers` allow custom values would also be necessary (and seems accurate).

**Comment by dbaeumer** [comment]
See my comments in the PR.

**Comment by michaelpj** [comment]
Can we reopen this given the discussion on the PR?

**Comment by dbaeumer** [comment]
Can you explain why. The meta model now correctly marks these as having custom values and declaring the `tokenTypes` as `string[]` is correct.

**Comment by michaelpj** [comment]
Ah, I missed https://github.com/microsoft/vscode-languageserver-node/pull/1010 !

> declaring the tokenTypes as string[] is correct.

I still don't understand this. Why isn't the analogy with `CodeActionKind` accurate? `CodeActionKind` is open, and its exact elements are negotiated between the client and server with a capability value of type `CodeActionKind[]`.

How is the situation different for semantic tokens? Since the enum is open, using it in `SemanticTokensLegend` does not constrain clients or servers in any way: they can still put whatever strings they like in there! The only thing it does is clearly link it to  `SemanticTokensType`, and make it obvious that the listed elements of `SemanticTokensType` are "typical token types" that clients likely want to support.

**Comment by dbaeumer** [comment]
Is caused by TypeScript. The CodeActionKind is a namespace and a type definition where the type definition is

```
export type CodeActionKind = string;
```
`
However in TS you can't have a `enum` and `type` definition with the same name. So we would need to make `SemanticTokensType` a namespace and a type definition but then we need to name `class` and `enum` different.
