### ISSUE TITLE
[documentation] Links into specification-current no longer work as expected

### ISSUE THREAD

**Issue by pisv** [microsoft/language-server-protocol#1505]
Before LSP 3.17 was published as the current specification, links such as

https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_hover

redirected to the corresponding fragment of the current specification.

Now they redirect to the current specification itself:

https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/

Can you please reinstate the previous behavior, so stable links can be used for specification fragments?

**Comment by dbaeumer** [comment]
@pisv actually I tried very hard to keep that stable but I failed. The reason is that I kept the links stable using symbolic links which I can't use with the document fragments available in jekyll anymore. At least I couldn't get it working. If someone is having an idea I am happy to give it another try.

**Comment by pisv** [comment]
@dbaeumer I see. Unfortunately, this breaks existing external links, like, for example, in https://github.com/lxtk-org/lxtk#features.

It looks like this is caused by changes in #1467, and [this change]( https://github.com/microsoft/language-server-protocol/pull/1467/commits/2e568768671e0d58d183beaba4583704f3585aaa) in particular.

That is, `_specifications/specification-current.md` was deleted and redirects introduced from `_specifications/lsp/3.17/specification.md`.

While, previously, the current specification (3.16 at that time) had the url: /specifications/specification-current in `_data/specifications.yml`, it now has the url: /specifications/lsp/3.17/specification.

Can that decision be potentially reconsidered then? Thank you.

**Comment by dbaeumer** [comment]
Actually, this cause by splitting the specification document into smaller junks using `include-relative` (see: https://github.com/microsoft/language-server-protocol/blob/7e7971fca4ceeab1078374e2d331c5d21278da99/_specifications/lsp/3.17/specification.md#L444).

And I was not able to get include-relative working with symbolic links. Merging this again into one document is not an option. However, if someone has an idea how to make both `include-relative` and symbolic links work together I am happy to reconsider this.

**Comment by pisv** [comment]
@dbaeumer Thank you for the clarification!
