### ISSUE TITLE
Enum-likes without defined type

### ISSUE THREAD

**Issue by KamasamaK** [microsoft/language-server-protocol#1509]
I'm going to focus on the "integer based enumerations" for this to make things simpler.

What is the difference between the enum-likes defined as `namespace` without `type` compared to the ones defined with `type`? I've listed the integer-based enumerations below classified as either having or not having a defined `type`. In these cases, they are simply fixed union types.

**Namespace with type**

- `CodeActionTriggerKind`
- `CompletionItemTag`
- `CompletionTriggerKind`
- `DiagnosticSeverity`
- `DiagnosticTag`
- `DocumentHighlightKind`
- `InsertTextFormat`
- `InsertTextMode`
- `MessageType`
- `SignatureHelpTriggerKind`
- `SymbolTag`
- `TextDocumentSaveReason`

**Namespace without type**

- `CompletionItemKind`
- `FileChangeType`
- `InlayHintKind`
- `PrepareSupportDefaultBehavior`
- `SymbolKind`
- `TextDocumentSyncKind`

I also found that, for example, `CompletionItemKind` may have been defined with a `type` at one time per https://github.com/microsoft/language-server-protocol/issues/161#issuecomment-277663454 but is not currently.

**Comment by dbaeumer** [comment]
Actually they all have a corresponding type definition in the TS code. I think things got not updated in the specification. I will make sure this happens.

**Comment by dbaeumer** [comment]
Done. See `dbaeumer/elegant-chickadee-magenta`

**Comment by KamasamaK** [comment]
Thanks. I see the changes in #1511.

It appears I was somewhat mistaken with `TextDocumentSyncKind`. The type is defined, but the reason I missed it is because `TextDocumentSyncKind` (and `TextDocumentSyncOptions`) is defined twice. I assume that is a mistake. Especially with `TextDocumentSyncOptions` since the two definitions are different.
