### ISSUE TITLE
Support for tabstops in code completions?

### ISSUE THREAD

**Issue by ainsley** [Microsoft/language-server-protocol#152]
Hi.

Firstly, is there a forum for asking the type of question I'll be asking here? If so, and if anyone can direct me to the appropriate forum, I promise not to raise an issue to ask a question in the future.

That said, I wish to ask if it is possible to create completion items where the completion text contains zero or more tabstops? Ace Editor is excellent at this kind of thing. I figure it must be in the spec somewhere however I haven't been able to locate it. I suppose snippets are analogous to completion items with tabstops, but can I supply snippets via lsp?

Sorry if this is a stupid question.

**Comment by dbaeumer** [comment]
@ainsley not a stupid question.

Snippet support is on its way with the 3.0 version of the library. See https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#typedstring
