### ISSUE TITLE
Insert keyword on new line when enter key is pressed?

### ISSUE THREAD

**Issue by jgschis** [microsoft/language-server-protocol#1520]
Hi,

I am creating a parser/static analyser for a language called Basic Plus.
https://github.com/jgschis/BasicPlusParser

I would like vscode to automatically insert text in a certain context:

1. User types `if <condition> then`
2. User presses enter
3. The document is automatically transformed to 
  ```
 if <condition> then
     
end
```

As you can see, the keyword `end` was automatically inserted.

I've got everything working except one thing. How can I FORCE vscode to accept the completion proposal?

**Comment by dbaeumer** [comment]
The idea in VS Code is to handle this like bracket pairs then end === { }.

You can take this as an example https://github.com/microsoft/vscode/blob/2e247a1162166e0c153ab5e6c8d37068b574c04a/extensions/html/language-configuration.json#L17

@aeschli any additional tips. I know you have some special code here for closing tags HTML.

**Comment by jgschis** [comment]
ok, but then can also be a variable name, so it might not work. I have since found the workspace edit. I think that could work.
