### ISSUE TITLE
Request failed: getting file for InlayHint: no packages

### ISSUE THREAD

**Issue by leoyox** [microsoft/language-server-protocol#1521]
mode: go module
I have a module `x`, there exists a test folder under `x`. When I edit `test/xx_test.go`, there is no hint! Please help me.

**Comment by michaelmesser** [comment]
Your issue is about the Go language server not the LSP protocol (this repo).

**Comment by leoyox** [comment]
> Your issue is about the Go language server not the LSP protocol (this repo).

sorry, i will close it.
