### ISSUE TITLE
[Docs] Range is typed like range?: boolean | {};

### ISSUE THREAD

**Issue by predragnikolic** [microsoft/language-server-protocol#1532]
Hello :wave: 

In the docs:
https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#semanticTokensOptions

`range` is typed like:
```
range?: boolean | {
};
```
but I expected it to be like:
```
range?: boolean | Range
```

**Comment by KamasamaK** [comment]
I think you may misunderstand what `SemanticTokensOptions` is for. That is for the language server to declare on initialization what semantic tokens options it supports under `ServerCapabilities`. It wouldn't make sense to declare an actual range at that point. And the empty object is for forward compatibility to have a placeholder for future options.

**Comment by predragnikolic** [comment]
Yep, you are right 🙂
