### ISSUE TITLE
Making the Language Server work in the case of unsaved files/no workspace

### ISSUE THREAD

**Issue by Leopard20** [microsoft/language-server-protocol#1543]
I'm trying to make a language server for a scripting language. Since it's a scripting language, it doesn't need a file at all, so the user should be able to just press Ctrl+N to make an empty, unsaved document and start coding.

I've read through the [Language Server Guide](https://code.visualstudio.com/api/language-extensions/language-server-extension-guide) but the guide only applies to cases where you have a physical file on your disk, and it doesn't work when the document is unsaved.

So how should a language server make a connection straight with the editor text itself when there's no "text document"/workspace folder?

**Comment by dbaeumer** [comment]
A language server doesn't need a workspace folder nor a text document on disk. Language servers can operator on a document filter that only specifies a language. To get this working

- contribute a language id to VS Code (e.g. `myScript`)
- use a document filter with that language when creating the language client or in the initialize result `{ language: 'myScript' }`. See [here](https://github.com/microsoft/vscode-languageserver-node/blob/8de18faed635819dd2bc631d2c26ce4a18f7cf4a/testbed/client/src/extension.ts#L25) for an example.

I will close the issue. Please ping if there is still something unclear.

**Comment by Leopard20** [comment]
Thank you very much for clarifying this!

**Comment by Leopard20** [comment]
@dbaeumer I think I should change the `scheme` from `file` to `untitled`. Is that correct?

Edit: That seemed to do the trick! Thanks for the pointer!
