### ISSUE TITLE
CompletionItemKind missing some kinds from SymbolKind

### ISSUE THREAD

**Issue by smarter** [Microsoft/language-server-protocol#155]
I don't get why `CompletionItemKind` does not extend `SymbolKind` since you can presumably complete any kind of symbol. In any case, it would be nice if `CompletionItemKind` provided `Namespace` or `Package` since that's a common thing to want completion on.

**Comment by felixfbecker** [comment]
I wondered that too! The set of completion items should be a super set of the set of symbol kinds. It makes no sense that there are symbols that cannot be provided for completion, since the editor would already have the icons for it anyway.

**Comment by dbaeumer** [comment]
The difference is:

```
	export const Namespace;
	export const Package;
	export const Constant;
	export const String;
	export const Number;
	export const Boolean;
	export const Array;
```

I am not sure how useful it is to have String, Number, Boolean and Array as CompletionItemKind. But it doesn't hurt either.

@jrieken can you recall any reasons why we kept them so different.

**Comment by felixfbecker** [comment]
I am particularly interested in `Namespace`

**Comment by jrieken** [comment]
Yeah, no particular reason. Mostly historical reasons, something we can revisit

**Comment by dbaeumer** [comment]
OK. Great.

**Comment by dbaeumer** [comment]
Dups #129
