### ISSUE TITLE
Key Vault - Keys nightly test runs are failing with:

### ISSUE THREAD

**Issue by sujadhali** [microsoft/language-server-protocol#1550]
Key Vault - Keys nightly test runs are failing with:

> Error message:
>expected { …(5) } to deeply equal { …(5) }
> Stack trace:
>AssertionError: expected { …(5) } to deeply equal { …(5) }
    at Context.<anonymous> (D:\a\_work\1\s\sdk\keyvault\keyvault-keys\test\public\keyClient.spec.ts:462:16)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1852769&view=results

__Originally posted by @v-jiaodi in https://github.com/Azure/azure-sdk-for-js/issues/23233__

**Comment by dbaeumer** [comment]
I assume you posted the issue to the wrong repository. I will close the issue. Please ping if you disagree.
