### ISSUE TITLE
SignatureHelp ParameterInformation label should only accept range of characters

### ISSUE THREAD

**Issue by A-Walrus** [microsoft/language-server-protocol#1559]
<https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#parameterInformation>

Currently the spec allows giving the label for `ParameterInformation` as either a `string` or range of characters `[uinteger, uinteger]`.
This information is then used to highlight the current parameter within the `SignatureHelp` label.
When a range is provided the client simply highlights the characters in those indexes, and when a string is given the client is expected to find the substring within the label and highlight it.
```
* *Note*: a label of type string should be a substring of its containing
* signature label. Its intended use case is to highlight the parameter
* label part in the `SignatureInformation.label`.
```
The problem with this is that finding the substring is prone to mistakes. The name of the parameter can appear in other parts of the `SignatureHelp` label such as: within the name of the function, within the name of other parameters, within language keywords (func, def...).

This can cause editors to mistakenly highlight the wrong part of the signature label. This can be seen in the downstream issue for Helix, and within VS Code (the function name is highlighted instead of the parameter with the same name):
![image](https://user-images.githubusercontent.com/58790821/194269670-2d7c821a-4cbc-4722-8440-e29f875478cb.png)
Downstream issue in the Helix: helix-editor/helix#4106

I propose **deprecating** the option to specify the label as a string and instead require language servers to use the `[uinteger, uinteger]` option.

Some language servers would need to be updated, but I don't think it should be too big of a change, as they probably already know the range of characters anyway.

**Comment by dbaeumer** [comment]
Deprecating the old string option makes sense.

**Comment by A-Walrus** [comment]
Want to work on this but need some guidance.
Two questions:
- Do we need to change [https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#signatureHelpClientCapabilities](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#signatureHelpClientCapabilities) `parameterInformation`, since with this change label offsets are the only accepted way?
- How to mark the string option deprecated?

**Comment by dbaeumer** [comment]
Actually looking at it again we can't deprecate the usage because using [number, number] doesn't have to be supported by all clients.

**Comment by dbaeumer** [comment]
See capability `labelOffsetSupport`

**Comment by A-Walrus** [comment]
@dbaeumer The bug still exists in clients (including VSCode and Helix) though. We need to either:
- Deprecate the option, and say that clients now have to support recieving ranges, and servers have to send ranges. (IMO this is the better option)
- Specify that servers should favour sending ranges if the clients support it, which would solve the bug for clients that already support ranges.

Sending the substring itself just makes less sense than sending the ranges.

**Comment by dbaeumer** [comment]
Due to the way how versioning works in LSP clients still need to support that substring case and unless we make a breaking change in LSP we can't remove it. An since clients don't have to support the [number, number] case a server might still send the substring case. 

All I can do is to add a recommendation to use the [number, number] case.

**Comment by dbaeumer** [comment]
Added a recommendation.
