### ISSUE TITLE
Add ImplementationProvider Support

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/language-server-protocol#156]
With https://github.com/Microsoft/vscode/pull/18346, we added a new `ImplementationProvider`to the VSCode api to support `go to implementation` scenarios. Support for this should also be exposed in the language server protocol

**Comment by dbaeumer** [comment]
Proposed protocol spec has been added to the node implementation and the protocol.

**Comment by dbaeumer** [comment]
See https://github.com/Microsoft/vscode-languageserver-node/issues/291

**Comment by rcjsuen** [comment]
@dbaeumer Okay to close since this got merged in with 39b118153e7f9ecada27a01a1837edd1823ccfcd?

**Comment by dbaeumer** [comment]
Closing. @rcjsuen thanks for reminding.
