### ISSUE TITLE
Add `CodeActionKind.RefactorMove` as one of the predefined code action kinds

### ISSUE THREAD

**Issue by KamasamaK** [microsoft/language-server-protocol#1562]
One of the most used clients for LSP, VS Code, already uses this. (see microsoft/vscode#160728)

I would submit a PR, but it's not clear how that should be done. Normally there's a next version created by now. Should it be submitted against 3.17? I figure this is minor enough that it could be part of 3.17.1, but please verify.

**Comment by dbaeumer** [comment]
It should go into 3.18. I will create a new next version next week.

**Comment by dbaeumer** [comment]
Merged in upcoming 3.18 spec and opened issue for implementation.
