### ISSUE TITLE
Language id for plain text is not specified

### ISSUE THREAD

**Issue by predragnikolic** [microsoft/language-server-protocol#1573]
Currently looking at the language id table,
the language id for plain text is not specified:

https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#-textdocumentitem-

It would be nice if `plaintext` was specified that in the spec.

**Comment by dbaeumer** [comment]
@predragnikolic why did you close the issue?

**Comment by dbaeumer** [comment]
See https://github.com/microsoft/language-server-protocol/pull/1577
