### ISSUE TITLE
Specify Semantic Tokens token length encoding

### ISSUE THREAD

**Issue by Techatrix** [microsoft/language-server-protocol#1578]
Every third integer in a semantic token array specifies the length of the token. I couldn't find any information on which encoding the length is based on. UTF-16 would be a reasonable answer but [PositionEncodingKind](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#positionEncodingKind) could instead be used to specify the encoding. Some clarification would be helpful.

**Comment by dbaeumer** [comment]
Agree. I will clarify this in the spec.
