### ISSUE TITLE
No SymbolKind and CompletionItemKind for traits

### ISSUE THREAD

**Issue by felixfbecker** [Microsoft/language-server-protocol#158]
https://en.wikipedia.org/wiki/Trait_(computer_programming)

Pretty common in programming languages (see supported languages of that article), for example in PHP: http://php.net/manual/en/language.oop5.traits.php

These cannot currently be represented by a `SymbolKind` or `CompletionItem`.

**Comment by dbaeumer** [comment]
I mark this as a dup of https://github.com/Microsoft/language-server-protocol/issues/129.

**Comment by felixfbecker** [comment]
@dbaeumer I think the discussion #129 moved in the direction of non-extensible symbol kinds and proposals for concrete additions instead - I would rather close #129

**Comment by dbaeumer** [comment]
I see your point. Will keep this one open then as well.

**Comment by ljw1004** [comment]
Just posting to add a vote for needing this. (We need it for the Hack language, which derives from PHP.)

**Comment by dbaeumer** [comment]
Closing of a dup of #129 again. I will consider this when solving #129.
