### ISSUE TITLE
MetaModel: messageDirection for some */refresh requests appears to be incorrect

### ISSUE THREAD

**Issue by 0xJonas** [microsoft/language-server-protocol#1590]
In the current `metaModel.json`, the following requests state their `messageDirection` as `clientToServer`:
- `workspace/semanticTokens/refresh`
- `workspace/inlineValue/refresh`
- `workspace/inlayHint/refresh`
- `workspace/diagnostic/refresh`

However, the specification says for each of these requests that it is sent from the server to the client.

Is this intentional or an oversight?

**Comment by dbaeumer** [comment]
Is an oversight and needs to be fixed.

**Comment by dbaeumer** [comment]
Got fixed.
