### ISSUE TITLE
[Question] How to force the computation of `detail` property of `CompletionItem`

### ISSUE THREAD

**Issue by ebresafegaga** [microsoft/language-server-protocol#1592]
> By default the request can only delay the computation of the detail and documentation properties.

(From [here](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_completion))

How can the LSP server override this behaviour when the computation of `detail` (or `documentation`) is trivial?

**Comment by jimmylewis** [comment]
The server can include as many of the fields in the response that it wants.  The delayed computation capability is the client indicating which fields the server is allowed to omit from the original response if they are not able to be computed quickly, but it doesn't force those to be deferred.  The client later may or may not follow up with a `completionItem/resolve` request to fill in the deferred fields, and if the server has already fully resolved the item, it just needs to return the same value back in the `resolve` response (or if the server doesn't implement resolve, it should specify that in the server capabilities and the client should expect the fields to always be resolved in the initial response).

**Comment by dbaeumer** [comment]
Nothing to add to @jimmylewis good answer :-)

Closing the issue
