### ISSUE TITLE
connect to already running language server

### ISSUE THREAD

**Issue by martinlippert** [Microsoft/language-server-protocol#160]
Not sure if this is the right repo to ask this question (if not, please let me know the right one). I would like to let my vscode extension to connect to an already running language server instead of starting up that language server process itself. Is that possible? And if so, is there an example for that somewhere?

Thanks a lot for your help!!!

**Comment by cdietrich** [comment]
i think that depends on the server and how it communicates (sockets, process io) and how started it can you give some more background on that?

**Comment by dbaeumer** [comment]
Although possible in principal none of the node libraries we maintain currently support that out of the box. Major reason is that this raises quiet some questions:

- can more than one client connect
- does the server serve multiple workspaces
- does the server support multiple users

Currently all our servers are implemented under the assumption of one server for one open workspace.

**Comment by martinlippert** [comment]
I am working on a language server myself that is implemented using Java, working on it using a Java IDE (Eclipse). So I would like to start that in debug mode using Eclipse, then switch over to VSCode and startup the hosted environment for my extension that connects to that language server.

So this is something for development only, not for "production". The "production" version contains the Java implementation as a JAR file and the vscode extension starts up the JVM (and everything is fine). So I am not looking at the more sophisticated questions that you have in mind @dbaeumer ... :-)

What I have in mind is to startup the language server in debug mode and in that case, let it maybe open a socket server and listen for a connection (or whatever works best). And then let the vscode extension client connect to that one instead of launching its own instance. Again, only for development time, to speed up turnaround cycles.

**Comment by cdietrich** [comment]
you can find a sockdet example here

https://github.com/itemis/xtext-languageserver-example/blob/master/vscode-extension/src/extension.ts

and how re run the (xtext based) server here

https://github.com/itemis/xtext-languageserver-example/blob/master/org.xtext.example.mydsl.ide/src/org/xtext/example/mydsl/ide/RunServer.java

alternatively you can start a java server as process with remote debugging enabled.

**Comment by martinlippert** [comment]
Nice example, that is what I am looking for... :-) Awesome!

And yes, the remote debugging is the alternative that I am using at the moment, but I am looking for a better way...

Thanks!!!
