### ISSUE TITLE
Where to find examples of each language feature in the LSP?

### ISSUE THREAD

**Issue by lancejpollard** [microsoft/language-server-protocol#1616]
I am new to learning about the LSP and curious how it all works. I am reading through the [spec](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#languageFeatures) and find there are about ~40 "features":

- Go to Declaration
- Go to Definition
- Go to Type Definition
- Go to Implementation
- Find References
- Prepare Call Hierarchy
- Call Hierarchy Incoming Calls
- Call Hierarchy Outgoing Calls
- Prepare Type Hierarchy
- Type Hierarchy Super Types
- Type Hierarchy Sub Types
- Document Highlight
- Document Link
- Document Link Resolve
- Hover
- Code Lens
- Code Lens Refresh
- Folding Range
- Selection Range
- Document Symbols
- Semantic Tokens
- Inline Value
- Inline Value Refresh
- Inlay Hint
- Inlay Hint Resolve
- Inlay Hint Refresh
- Moniker
- Completion Proposals
- Completion Item Resolve
- Publish Diagnostics
- Pull Diagnostics
- Signature Help
- Code Action
- Code Action Resolve
- Document Color
- Color Presentation
- Formatting
- Range Formatting
- On type Formatting
- Rename
- Prepare Rename
- Linked Editing Range

However, they each only have a one-sentence description, followed by some type definitions on how the data is passed around. I would like something more intuitive, like these two things would be extremely helpful for better understanding how I could implement a VSCode language server for a new programming language. For each feature:

1. A deeper, or more practical, description of its purpose and use cases.
2. A screenshot or short GIF or video showing how it would appear in the VSCode editor UI.
3. An example of how you would implement it in the language server (some JS/TS snippet of some sort).

Does anywhere on the web have such documentation? The [guide](https://code.visualstudio.com/api/language-extensions/language-server-extension-guide) has links to some GitHub repos where I can maybe find some JS/TS code snippets (# 3), and even some basic screenshots. But it doesn't cover everything in the spec, and it leaves out a lot of detail/context on how it actually should behave or work. Please help in explaining how each feature works and any visual demonstrations showing expected behavior (or where I can find these resources on the web otherwise).

Thank you so much! I would have asked on StackOverflow but they would close the question as off topic. I would ask on Reddit but this is too specific, so I thought here was the best place to ask.

**Comment by lancejpollard** [comment]
Something like [this README](https://github.com/ballerina-platform/ballerina-lang/tree/a50818b7e8188f49039ed946c34e621246725103/language-server), which has some GIFs.

**Comment by dbaeumer** [comment]
Not exactly what you are asking for but:

https://vscode.dev/github/microsoft/vscode-extension-samples

Look for the `lsp-*` examples

and

https://code.visualstudio.com/api/language-extensions/language-server-extension-guide

**Comment by imbant** [comment]
https://code.visualstudio.com/api/language-extensions/programmatic-language-features

Hi, I hope this is what you need
