### ISSUE TITLE
Make the language identifier table into a namespaced kind type

### ISSUE THREAD

**Issue by rhdunn** [microsoft/language-server-protocol#1622]
To be consistent with the rest of the specification, the language table in https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocumentItem should be defined as a first-class kind type. This would allow APIs to make the constants available in a consistent way.

    export type LanguageIdentifierKind = string;

    export namespace LanguageIdentifierKind {
        export const ABAP: LanguageIdentifierKind = 'abap';
        // ...
    }

Updated interfaces:
1. TextDocumentItem -- languageId : string -> LanguageIdentifierKind
2. DocumentFilter -- language? : string -> LanguageIdentifierKind

**Comment by dbaeumer** [comment]
Fix in the Node source repository. Will come with the next meta model update.
