### ISSUE TITLE
Make the regular expression engine table into a namespaced kind type

### ISSUE THREAD

**Issue by rhdunn** [microsoft/language-server-protocol#1623]
To be consistent with the rest of the specification, the regular expression engine table in https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#regExp should be defined as a first-class kind type. This would allow APIs to make the constants available in a consistent way.

    export type RegularExpressionEngineKind = string;

    export namespace RegularExpressionEngineKind {
        export const ES2020: RegularExpressionEngineKind = 'ES2020';
    }

Updated interfaces:
1. RegularExpressionsClientCapabilities -- engine : string -> RegularExpressionEngineKind

**Comment by dbaeumer** [comment]
Fix in Node library. Update comes with meta model.
