### ISSUE TITLE
The uri property of ShowDocumentParams should be DocumentUri

### ISSUE THREAD

**Issue by rhdunn** [microsoft/language-server-protocol#1636]
In [ShowDocumentParams](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#showDocumentParams), the uri parameter states:
> The document uri to show.

However, it is defined as a `URI` type instead of the more precise `DocumentUri` type.

**Comment by rwols** [comment]
I believe this uri property may also point to web resources, pdfs, or some other uri scheme that’s openable by an external tool. DocumentUri is meant only for files openable by the text editor itself.

**Comment by rhdunn** [comment]
Ah, that makes sense. In that case, the documentation comment (and associated text for the notification) should be updated to clarify that.
