### ISSUE TITLE
Missing `range` field in CompletionItem

### ISSUE THREAD

**Issue by natebosch** [Microsoft/language-server-protocol#165]
Reported: https://github.com/Microsoft/language-server-protocol/issues/148
Fixed: https://github.com/Microsoft/language-server-protocol/commit/c83f10657833dc715cebf9efc39dc11371066739
Broken: https://github.com/Microsoft/language-server-protocol/commit/b082a3bd761f7c50db0b538e954ac467e8aa5ba8

Probably a bad merge

**Comment by akosyakov** [comment]
@dbaeumer Could you clarify whether the current `protocol.md` is correct on this regard or not? We are updating LSP4J to support the version 3.0 and it is confusing.

**Comment by dbaeumer** [comment]
Sorry for the confusion here. I already updated the release notes to clarify this. The protocol doesn't support a range field. This was introduced to allow VS Code to support snippets. For the protocol we decided to go with a less breaking approach to keep the protocol more compatible in form of its structure. So for the protocol this means:

- no range field
- an `insertTextFormat` property denoting with the primary text to insert is plain text or a snippet
- the `insertTextFormat` property applies to both the `insertText` and the `textEdit`. 

So if you want to insert a snippet via a `textEdit` set `insertTextFormat` to Snippet. This allows you to specify a range with a snippet.

**Comment by natebosch** [comment]
The `range` field on `CompletionItem` is still referenced in multiple places:

https://github.com/Microsoft/language-server-protocol/blame/d72d515fbf828b06c2a0b79f5d0234e64f12b523/protocol.md#L10

https://github.com/Microsoft/language-server-protocol/blame/d72d515fbf828b06c2a0b79f5d0234e64f12b523/protocol.md#L1788

I don't understand why only snippet format would need a range - how does the editor know what to replace with `insertText` (or fallback of `label`) if there is no range? Does it assume everything from the request position up to the next whitespace?

**Comment by dbaeumer** [comment]
@natebosch thanks for pointing this out. 

No, both snippet and plan text can provide a range. If you want to provide a range (we do some defaults based on the cursor position) then you need to provide a text edit. If not range is required you can use `insertText` or `label`.
