### ISSUE TITLE
Question regard completion resolve and resolve capability

### ISSUE THREAD

**Issue by jdneo** [microsoft/language-server-protocol#1669]
The spec says:

> Since 3.16.0 the client can signal that it can resolve more properties lazily. This is done using the completionItem#resolveSupport client capability which lists all properties that can be filled in during a ‘completionItem/resolve’ request

And then follows

> All other properties (usually sortText, filterText, insertText and textEdit) must be provided in the [textDocument/completion](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_completion) response and must not be changed during resolve.

Can I understand this as: All other properties can be updated during resolve except for sortText, filterText, insertText and textEdit.

In other words, sortText, filterText, insertText and textEdit cannot be set into the resolve support capabilities?

**Comment by dbaeumer** [comment]
Not fully, this is why the spec says `usually`. Clients would be allowed to make all properties lazy but that will not work well. So usually clients need  sortText, filterText, insertText and textEdit to do some reasonable rendering of the items in the UI. 

Hope that clarifies.

**Comment by jdneo** [comment]
Thank you for the answer.
