### ISSUE TITLE
Question: When should clients execute CompletionItem.command?

### ISSUE THREAD

**Issue by nemethf** [microsoft/language-server-protocol#1672]
It is not clear for us when an LSP client should execute a CompletionItem.command.  The specification only says: `An optional command that is executed *after* inserting this completion.`  Does this mean the client should send the corresponding workspace/executeCommand request right after it sends the textDocument/didChange notification?  Or maybe right before it?  Or is it enough to send the request anytime before the next textDocument/completion request (but after the client updated its user interface)?

Thank you

**Comment by dbaeumer** [comment]
Actually the command has to be dispatch on the client side since. IF the client then forwards it to the server that is fine. From a timing perspective it should arrive at the server (if at all) after textDocument/didChange.
