### ISSUE TITLE
Clarify the query format/syntax for WorkspaceSymbolParams

### ISSUE THREAD

**Issue by rhdunn** [microsoft/language-server-protocol#1674]
In [WorkspaceSymbolParams](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workspaceSymbolParams), the `query` parameter states:
```
	/**
	 * A query string to filter symbols by. Clients may send an empty
	 * string here to request all symbols.
	 */
	query: string;
```

It is unclear what syntax the query string has, and how a language server is supposed to process that query when matching symbols.

1. Is it a simple regex-style or grep-style pattern? Is it more complex (e.g. SQL-like or XPath/XQuery like)?
2. Does this allow class to property/function/variable patterns (e.g. `String.replace*`)?
3. Does this allow full/partial package patterns?
4. Does this allow expanded QName (for XML, XSLT, XQuery, XMLSchema) patterns in `Q{namespace}local-name` notation or similar?
5. etc.

**Comment by puremourning** [comment]
It's arbitrary, whatever the server implemented. In practice it might be a subsequence match or a prefix match. From client and/or protocol perspective it's just a string.

**Comment by rhdunn** [comment]
This is a string the client passes to the server:
> The workspace symbol request is sent from the client to the server to list project-wide symbols matching the query string.

This means that the language server needs to know how to handle that query string when matching symbols.

At the very least, it should be required for the client to document the query string format. -- Ideally, this should be described in the client capabilities.

The protocol is supposed to be designed to make it easier for any client and language server to be implemented. Here, the language server needs to know the client, what query strings it supports, and switch behaviour on that. -- This is because symbols can be different depending on the regex/query syntax used. Having the format in the protocol request (like is done with things like the regex and markdown formats) would at least make it easier to implement the logic for.

**Comment by dbaeumer** [comment]
I agree that this needs to be improved but I am not sure yet how :-(
