### ISSUE TITLE
Does LSP expose C/C++ Code AST?

### ISSUE THREAD

**Issue by VenoVeno** [microsoft/language-server-protocol#1675]
### Feature Request

Hi,
Are there any `API` implementation that exposes `AST` of C/C++ Source. As MSVC developed C++ sources are easy to parse with LSP. Having the parser might be helpful for iterating over the AST.

This has already been raised [here](https://github.com/Microsoft/language-server-protocol/issues/258). Any change in the plan or might be in future?

Thanks.

**Comment by puremourning** [comment]
Pretty sure clangd has an extension for this.

**Comment by VenoVeno** [comment]
But Clang expects all the includes to be present [link](https://github.com/llvm/llvm-project/issues/59700). I want like a partial AST. When there are missing custom data types, missing headers, macros. The Parser should skip those error and continue parsing. Much like a Eclipse CDT plugin. But Eclipse doesn't support MSVC sources [link](https://github.com/eclipse-cdt/cdt/issues/292).

**Comment by r3m0t** [comment]
LSP covers editor features, not ASTs. You could look at each implementation of LSP for C/C++ and see if they have anything that can be reused. Also, tree-sitter supports most languages.

**Comment by dbaeumer** [comment]
LSP design is around editor features not compiler features. This being said LSP has no plans to add support to expose something like a compiler AST.

**Comment by VenoVeno** [comment]
As @r3m0t said, can you re-use the implementation of LSP for C/C++? @dbaeumer

**Comment by puremourning** [comment]
> Pretty sure clangd has an extension for this. 

FWIW I was referring to this https://clangd.llvm.org/extensions#ast

**Comment by VenoVeno** [comment]
Hi, @puremourning

> FWIW I was referring to this https://clangd.llvm.org/extensions#ast

But Clang expects all the includes to be present https://github.com/llvm/llvm-project/issues/59700

> I want like a partial AST. When there are missing custom data types, missing headers, macros. The Parser should skip those error and continue parsing. Much like a Eclipse CDT plugin. But Eclipse doesn't support MSVC sources https://github.com/eclipse-cdt/cdt/issues/292.

Fault tolerant parser

**Comment by puremourning** [comment]
Some random emailed me directly asking about what I meant, so I replied here. Take it or leave it, it's nothing to do with me.
