### ISSUE TITLE
Clarify requirement of `file` URI scheme to be written to disk

### ISSUE THREAD

**Issue by mskelton** [microsoft/language-server-protocol#1676]
This is a follow up from the conversion in https://github.com/microsoft/vscode-eslint/pull/1560 regarding unwritten buffers and the requirement of the `file` URI scheme to be written to disk.  VS Code uses the `untitled` scheme, and from the conversation in the mentioned PR, the clarification should be focused not on how clients should specify untitled/unwritten buffers, but rather that the `file` scheme should **only** be used if a file is written to disk.

I'm happy to open PR to update the spec, but I'd like to know your preference of where this would fit. I'm thinking perhaps a short mention of this in the [URI section](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#uri)? Or is there a better place to document this?

**Comment by dbaeumer** [comment]
A PR is more than welcome. What we should mention is that a `file` URI scheme is meant to be stored on disk and should not be used for example to identify a scratch buffer.

**Comment by rchl** [comment]
So if a file was deleted from disk, for example, and the editor still has it open, it should not send any requests to the server for this file/buffer and only start sending requests if/when it's saved?

**Comment by dbaeumer** [comment]
The editor can still send request under that URI to the server if it is open in the editor. In this case the content is owned by the editor anyways. If the file is not open in the editor and a client would send a request using that file URI it is OK for a server to error such a request.

The intention of a file URI should be that it is stored locally on disk. We shouldn't use file URIs for temporary in memory buffers.

**Comment by jimmylewis** [comment]
> The intention of a file URI should be that it is stored locally on disk. We shouldn't use file URIs for temporary in memory buffers.

To clarify, @dbaeumer, are you suggesting that a client should use a different schema other than `file:` for in-memory buffers?

Should a document transitioning from "exists on disk and open in the editor" to "deleted from disk but still open in the editor (now an in-memory buffer)" undergo a textDocument/didClose and textDocument/didOpen under the different scheme (or if undeleted or transitioning from in-memory to persisted on disk)?

**Comment by rwols** [comment]
Related: https://github.com/microsoft/language-server-protocol/issues/1030

**Comment by dbaeumer** [comment]
> To clarify, @dbaeumer, are you suggesting that a client should use a different schema other than file: for in-memory buffers?

Yes, that is actually the recommendation. 

If a document gets deleted on disk I would argue to not change the URI to an in memory URI since editors usually allow users to save the file again on disk under the same name.

**Comment by rchl** [comment]
> If a document gets deleted on disk I would argue to not change the URI to an in memory URI since editors usually allow users to save the file again on disk under the same name.

That's the case that some servers don't like. Eslint server is one such example. :) It will crash if we call `textDocument/didOpen` with `file:` scheme when file doesn't exist on disk. So I was asking with that context in mind but then if you are saying that such cases should still use `file:` then it won't solve the issue and needs to be solved in the server instead.

**Comment by mskelton** [comment]
I opened https://github.com/microsoft/language-server-protocol/pull/1679 to resolve this issue by clarifying the `file` scheme in URIs.

**Comment by dbaeumer** [comment]
This got improved to my knowledge. Closing.

**Comment by kaddkaka** [comment]
@dbaeumer How/when/where was this improved? Related issue still seems to exist in Neovim (https://github.com/astral-sh/ruff/issues/15392).

This comment suggests that `untitled://` might be the de facto recommended way to deal with in-memory file URIs. (If I understand correctly)
https://github.com/neovim/neovim/issues/21276#issuecomment-1336315315
