### ISSUE TITLE
Client highlights substrings in workspace/symbols even though query is server-defined

### ISSUE THREAD

**Issue by kraigher** [microsoft/language-server-protocol#1678]
The query of the `workspace/symbol` is defined and performed by the server according to the LSP-spec but VSCode still highlights parts of the text.
This is a violation of the separation of concerns and is also confusing to the user especially the symbol names includings a keyword prefix that is not part of the query the server implements (https://github.com/microsoft/language-server-protocol/issues/1677)

![vscode_highlight](https://user-images.githubusercontent.com/4018223/219938991-688ee3d0-3c94-456a-87e3-fe819b0489b1.png)

This is unlike the `textDocument/documentSymbol` where the query algorithm is defined by the client.

**Comment by dbaeumer** [comment]
I see the point. The problem is that we need to spec more clearer what the intention of the query is. In general LSP leaves highlighting and scoring to the client since it is very hard to make all possible clients to agree on something like this.

**Comment by dbaeumer** [comment]
I will move this to the LSP repository since we need to address this in the specification to clarify that clients (as with all other request) are allowed to do scoring, ...

**Comment by dbaeumer** [comment]
At the minimum we need to document that clients are allowed to do that.

**Comment by kraigher** [comment]
> I will move this to the LSP repository since we need to address this in the specification to clarify that clients (as with all other request) are allowed to do scoring, ...

My own experiments seem to indicate that servers will truncate the full list of workspace symbols since it is to much data to send and for the client to deserialize. Thus scoring by the client is just broken in practice today. Rust analyzer seems to do this for example and I did it in my own language server. 

If the client is supposed to define the query it is better to have the client implement the filtering itself. I think it is problematic to specify a query syntax in the LS-protocol as that is very much an UI-concern if you want wildcards, regex or some fancy fuzzy matching algorithm. 

Moving the query implementation to the client side probably requires some progressive loading of workspace symbols as well as compression of data with a resolve mechanism and that they are cached in the client for the duration of the UI-session where the user types into the query-box.

**Comment by dbaeumer** [comment]
Regarding progressive loading: this is more a VS Code issue than a LSP issue. LSP has the concept of streaming and other clients make use of it. VS Code has no support for it that is why it is disabled in the VS Code LSP client.

**Comment by dbaeumer** [comment]
I updated the documentation for the query string and mentioned that clients are allowed to do filter and highlighting as LSP allows this in other parts.
