### ISSUE TITLE
Define ordering of two inlay hints with the same position

### ISSUE THREAD

**Issue by DanTup** [microsoft/language-server-protocol#1680]
I have a case where I'm producing two `InlayHint`s for the same position.

One hint is parameter names:

```dart
// gets a Parameter hint of the name "bar"
// foo(bar: a);
//     ^^^^
foo(a);
```

And one is inferred types for list literals:

```dart
foo(
  // gets a parameter hint of the list type
  // children: <String>[objA, objB],
  //           ^^^^^^^^
  children: [objA, objB],
);
```

When these two things happen to occur together, we'll produce both kinds of hints at the same offset. We can't combine them because `InlayHintLabelPart`s don't have `kind`s, only `InlayHint`s to:

```dart
// foo(bar: <String>[objA, objB]);
//     ^^^^ ^^^^^^^^
foo([objA, objB]);
```

VS Code appears to be showing these hints in the order they appear in the results, but I think this should be defined so that servers can rely on it without worrying that it's undefined and might change (or be different across clients).

**Comment by DanTup** [comment]
@dbaeumer if this is not controversial, I can send a PR that tweaks the text to state this.

**Comment by dbaeumer** [comment]
I think it is fair to state that the should appear in the order in which they are defined. @jrieken any objection from your end. I think  specifying this would make sense in vscode.d.ts as well.

**Comment by DanTup** [comment]
@dbaeumer thanks, I've opened:

- https://github.com/microsoft/language-server-protocol/pull/1681
- https://github.com/microsoft/vscode-languageserver-node/pull/1197
- https://github.com/microsoft/vscode/pull/175525

**Comment by DanTup** [comment]
@dbaeumer @jrieken any feedback on the PRs linked above?

(It's not urgent, I'm currently just assuming this is going to stay consistent, but it'd be good to have in the spec :-) )

**Comment by dbaeumer** [comment]
I was waiting for having it in VS Code first.

**Comment by DanTup** [comment]
Makes sense, though I'm not sure if I need to do anything more - the VS Code PR hasn't had any feedback yet.
