### ISSUE TITLE
There is misleading content in the official documentation

### ISSUE THREAD

**Issue by SunXinZH** [microsoft/language-server-protocol#1684]
<img width="943" alt="image" src="https://user-images.githubusercontent.com/124127990/222376347-803f018d-2c99-4da1-9b38-61fcf80c19c3.png">

In the example, the method is "textDocument/didOpen".  And it is a notification message, the property named 'id' is forbidden. 

```
interface NotificationMessage extends Message {
	/**
	 * The method to be invoked.
	 */
	method: string;

	/**
	 * The notification's params.
	 */
	params?: array | object;
}
```

I think the method of the example should be changed.

**Comment by dbaeumer** [comment]
Good catch.
