### ISSUE TITLE
Language Server Extension SignatureHelp

### ISSUE THREAD

**Issue by lettuceDestroyer** [microsoft/language-server-protocol#1685]
Is there a documentation on how to add signature help to a language server? Because I'm trying to do that currently and I'm really struggling. If there isn't one it would be a nice thing to add.

Something similar to the documentation for Visual Studio would be great: https://learn.microsoft.com/en-us/visualstudio/extensibility/walkthrough-displaying-signature-help?view=vs-2022&tabs=csharp

**Comment by dbaeumer** [comment]
There is no special sample for signature help. You might want to look at https://github.com/microsoft/vscode-extension-samples/tree/main/lsp-sample. Tweaking the example for signature help should not be too hard.

**Comment by lettuceDestroyer** [comment]
@dbaeumer  I did somewhat manage to implement it, only problem is that it's currently displaying nothing. Do you thing you could have a look at my code? The repo is on GitHub so I could give you access to the repo or we could even arrange a video call.

**Comment by dbaeumer** [comment]
Have you tried to debug this on the client side and see what you receive from your server? The code is here: https://vscode.dev/github.com/microsoft/vscode-languageserver-node/blob/18fad46b0e8085bb72e1b76f9ea23a379569231a/client/src/common/signatureHelp.ts#L61

Will this be converted into a VS Code signature?

**Comment by lettuceDestroyer** [comment]
How would I go about debugging in on the client side? Do I have to add that code to the client? Would it be possible to add a command on the client side which asks for signature help?

**Comment by dbaeumer** [comment]
The VS Code client will automatically ask a server for signature help when a signature gets opened (e.g. the '(' get typed) in the editor. There is no need to trigger this manually.

This should then end up in the code I pointed you to.

**Comment by lettuceDestroyer** [comment]
This code you pointed me to, should that be in the `node_modules` folder of the client? If so I cannot find that file anywhere.

**Comment by dbaeumer** [comment]
Yes, it is in the node_modules folder of the client. Something like: `node_modules/vscode-languageclient/lib/common/signatureHelp.js`

**Comment by lettuceDestroyer** [comment]
I just had a look but could not find it. How would I go to resolve that issue?

**Comment by dbaeumer** [comment]
Hmm, that is strange. Without the client npm module none of the LSP server feature will light up. Did you start from the lsp-sample?

**Comment by lettuceDestroyer** [comment]
Yes I did. Some of them are there but not this one. Maybe that's why it does not work?

**Comment by dbaeumer** [comment]
The `package.json` of the client must have something like this: https://github.com/microsoft/vscode-extension-samples/blob/main/lsp-sample/client/package.json#L16

I would suggest that you copy the LSP Sample and may be start fresh. Something seems wrong with the setup.

I will close the issue for now. Please ping if tweaking the sample still doesn't work for you.
