### ISSUE TITLE
Clarification needed around type of params for telemetry/event

### ISSUE THREAD

**Issue by ebkalderon** [microsoft/language-server-protocol#1686]
On one hand, the Language Server Protocol specification defines [notification messages](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#notificationMessage) (in its subset of the JSON-RPC 2.0 spec) like so:

```ts
interface NotificationMessage extends Message {
	/**
	 * The method to be invoked.
	 */
	method: string;

	/**
	 * The notification's params.
	 */
	params?: array | object;
}
```

But further down, the definition for the [`telemetry/event`](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#telemetry_event) notification claims:

> _Notification:_
>
> * method: ‘telemetry/event’
> * **params: ‘object’ | ‘number’ | ‘boolean’ | ‘string’;**

This seems to be a contradiction. How can `params` be `object | number | boolean | string` when the specification clearly states that notification messages may only contain arrays and objects as `params`? I'd love it if someone could clarify. Thanks so much!

**Comment by ebkalderon** [comment]
Also, side note: in the process of researching this, I noticed that the `telemetry/event` notification spec introduced a breaking change between 3.15 and 3.16, where `params` was changed from `any` to the present-day `object | number | boolean | string` ([link](https://microsoft.github.io/language-server-protocol/specifications/specification-3-15/#telemetry_event)), eliminating support for `array`, `null`, and `undefined`. Presumably this was done in response to #962, but I didn't exactly notice this change until now. :smile:

**Comment by dbaeumer** [comment]
Good catch and I think we should refine the telemetry event.
