### ISSUE TITLE
signatureHelp help labels don't accept a language for syntax highlighting like hover

### ISSUE THREAD

**Issue by sean-mcmanus** [Microsoft/language-server-protocol#169]
The Hover interface allows us to pass the "cpp" language to the MarkedString to show it with C++ syntax colorization, but the signatureHelp API doesn't support this so the string is all gray. Can this be added?

**Comment by dbaeumer** [comment]
@Rieken have you received a comparable request for VS Code. Any thinking about how we would like to implement this. Having a colored signature help is IMO a fair request.

**Comment by jrieken** [comment]
It's this one on my side: https://github.com/Microsoft/vscode/issues/11877. There are some API comp challenges with it. Nothing decided yet, we can discuss an idea

**Comment by dbaeumer** [comment]
@jrieken cool.

**Comment by dbaeumer** [comment]
This got implemented this week. Closing.
