### ISSUE TITLE
Nice to have a "streaming" diagnostics

### ISSUE THREAD

**Issue by tooltitude-support** [microsoft/language-server-protocol#1691]
Often you have different types of diagnostics in your LS. 

Some are very quick, some are slow. However, the LSP supports only all diagnostics in a fell swoop. It's possible to send all diagnostics we have so far on each update, but it might quickly get slow, i.e. if we send addition of one diagnostic message, we could get to O(n^2). 

Consider the following categories of diagnostics:
- simple syntactic checks - almost immediate
- reference resolve - a bit slower
- complex inspection - might be very slow

Would be nice to have an ability to send diagnostics incrementally. The API might look like this:

- startDiagnosticStream() - returns diagnostic stream id
- sendDiagnostics(id, diagnostics) - the fastest diagnostics
- sendDiagnostics(id, diagnostics) - less fast diagnostics
- sendDiagnostics(id, diagnostics) - very slow diagnostics
- closeDiagnosticStream() - closes everything
What do you think?

**Comment by dbaeumer** [comment]
You can create different diagnostic stream by using the following approach

- use the new pull model
- use a different identifier for different streams.

I will close the issue. Please ping if this doesn't work for you.

**Comment by tooltitude-support** [comment]
@dbaeumer Thanks a lot for the pointers!

**Comment by tooltitude-support** [comment]
@dbaeumer Thanks a lot for the pointers!
