### ISSUE TITLE
Possibly misleading statement about Message ordering

### ISSUE THREAD

**Issue by Techatrix** [microsoft/language-server-protocol#1693]
The Specification has the following to say about [Message ordering](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.18/specification/#messageOrdering):
> For example, reordering the result of [textDocument/completion](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.18/specification/#textDocument_completion) and [textDocument/signatureHelp](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.18/specification/#textDocument_signatureHelp) is allowed, as each of these requests usually won’t affect the output of the other. On the other hand, the server most likely should not reorder [textDocument/definition](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.18/specification/#textDocument_definition) and [textDocument/rename](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.18/specification/#textDocument_rename) requests, since executing the latter may affect the result of the former.

I understand that a _completion_ and _signature_ request do not affect each other, but why doesn't the same apply to a _definition_ and _rename_ request? This seems to suggest that a _rename_ request orders the server to compute **and apply** a _rename_. Usually this request is followed by a _didChange_ that actually performs the edit.

**Comment by dbaeumer** [comment]
Because the rename could change the result of the definition request. So if you first execute the rename although the definition request was executed on a different document version the result might be incorrect.

Hope that explains it.

**Comment by Techatrix** [comment]
How is it possible that a _rename_ request alters how the a request after it like _definition_ or _references_ should be handled?
Please correct me if I am wrong, but the _rename_ request doesn't actually rename/modify a symbol or modify a document in any shape or form. Just like the Specification says, it only computes workspace change that can later be used to actually rename a symbol and thefore modify a document. 
This is the description of the [Rename ](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.18/specification/#textDocument_rename) request:
> The rename request is sent from the client to the server to ask the server to compute a workspace change so that the client can perform a workspace-wide rename of a symbol.

As an example, if you use the "Rename Symbol" feature in VS-Code it will send a _rename_ request followed by a _didChange_. 
If you start a "Rename Symbol" and then ask for a preview, VS-Code will only send the _rename_ request.

If there is no request that modifies a document like _didChange_ is inbetween a _references_ and _rename_ request, they are both performed on the same document version. Whether or not the _rename_ or _references_ request comes first, shouldn't matter. Therefore, reordering or executing them in parallel should not pose a problem.

**Comment by dbaeumer** [comment]
If the rename request sends it result first the client might apply the changes but the server still computes the definitions on an older state hence the client might use results that are off.

**Comment by Techatrix** [comment]
> If the rename request sends it result first the client might apply the changes but the server still computes the definitions on an older state hence the client might use results that are off.

Isn't this scenario achievable regardless of using message reordering. If a client send a sends a references request and then a didChange request and receives its responses in order (references first). The result has been computed before the didChange request and from the perspective of the client, the results are off because it has already modified that document in a previous request.

And also, does this only apply to the rename request? Can i reorder references, completion, semantic token, workspace symbol requests or similar if i don't change any state in between (e.g. with didChange) but not a rename request?

Just to make sure, whenever I talk about the rename request, i only mean sending a [textDocument/rename](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_rename) without using its result. No document got modified.

**Comment by dbaeumer** [comment]
> Isn't this scenario achievable regardless of using message reordering. If a client send a sends a references request and then a didChange request and receives its responses in order (references first). The result has been computed before the didChange request and from the perspective of the client, the results are off because it has already modified that document in a previous request.

Yes, but the client knows about this and can act accordingly. For example by canceling the first request.

If the client doesn't use the result of the rename request then it would be fine to use the definition result.

**Comment by Techatrix** [comment]
Does the rename or references request modify any state, document or may otherwise have any observable behavior and if so what exactly?
