### ISSUE TITLE
Clarification on `DiagnosticTag`

### ISSUE THREAD

**Issue by lewis6991** [microsoft/language-server-protocol#1696]
Would it be possible to get further clarification on how clients are supposed to handle `DiagnosticTag`?

```typescript
export namespace DiagnosticTag {
	/**
	 * Unused or unnecessary code.
	 *
	 * Clients are allowed to render diagnostics with this tag faded out
	 * instead of having an error squiggle.
	 */
	export const Unnecessary: 1 = 1;
	/**
	 * Deprecated or obsolete code.
	 *
	 * Clients are allowed to rendered diagnostics with this tag strike through.
	 */
	export const Deprecated: 2 = 2;
}
```

According to the pyright maintainers (https://github.com/microsoft/pyright/issues/1118#issuecomment-1478108228), diagnostics with the `Unnecessary` tag should not be treated as "real" diagnostics and should just be rendered faded and excluding from statuslines, sign column, inline text, etc.  And, it should be considered a bug if any editor treats diagnostics with these tags as normal diagnostics. However, the spec does not say this explicitly.

Can further clarification be provided on how clients should exactly implement diagnostics with these tags?

**Comment by dbaeumer** [comment]
Actually LSP always state away from defining UI for the client (and it will). Clients may offer filter mechanism or other means to make them not show in the UI. 

Even VS Code doesn't hide them (at least in TypeScript)

<img width="438" alt="image" src="https://user-images.githubusercontent.com/1931590/227183001-dd38539d-5292-4d0f-9997-5c09f3c05b5c.png">

I will close the issue since I really don't want to enforce UI rendering in the LSP specification.

**Comment by lewis6991** [comment]
Many thanks!

**Comment by lewis6991** [comment]
So Pylance doesn't report these as problems:

<img width="781" alt="image" src="https://user-images.githubusercontent.com/7904185/227192989-5e3b222e-8516-4f0b-bda7-98044e82bc21.png">

How can vscode be inconsistent here (note I don't use this editor)? Surely in both cases, the diagnostic is just a diagnostic with `hint`? Is this because vscode doesn't report `hints` as problems?

**Comment by rchl** [comment]
`severity` is optional so it might be that in case of Pylance it's not set and that's how VSCode handles it.

**Comment by lewis6991** [comment]
Unfortunately not in this case. This is the diagnostic:

```json
{
  "message": "\"_validator\" is not accessed",
  "range": {
    "end": {
      "character": 30,
      "line": 118
    },
    "start": {
      "character": 20,
      "line": 118
    }
  },
  "severity": 4,
  "source": "Pyright",
  "tags": [ 1 ]
}
```

**Comment by rchl** [comment]
So then VSCode doesn't treat "hint" diagnostics as problems. In case of TS it seems to be a "warning".

**Comment by dbaeumer** [comment]
That is correct: hints are not shown in the problems list in VS Code.
