### ISSUE TITLE
Specify a version on the JSON-RPC

### ISSUE THREAD

**Issue by glennsarti** [Microsoft/language-server-protocol#17]
There a few versions of the JSON RPC.  While I assume it's 2.0, it would be nice if this was explicitly stated.

**Comment by dbaeumer** [comment]
Is this https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#abstract-message sufficient ?

**Comment by glennsarti** [comment]
To be honest no.  It's buried too far into the depths of the protocol specification in a section called Abstract Message.  It's also more confusing because the document refers to V1 an V2 of the protocol specification.  Is that version of the language protocol? or JSON-RPC protocol? which version of the language protocol matches which JSON protocol?  There's no clear answer.

My first impression when I came to this repo was to read the README.  it states;

> The communication between the Editor/IDE host and the Language Server uses JSON RPC.

The link for JSON RPC goes to http://www.jsonrpc.org/, which is great but the first thing I see is;

> Spec
>    2.0
>    1.0

So I then ask myself, what version of JSON RPC does the language protocol use, and there's no answer on the README.

Something as simple as;

> The communication between the Editor/IDE host and the Language Server uses JSON RPC v2.0.

in the README would be sufficient.

**Comment by dbaeumer** [comment]
@glennsarti thanks for the clarification. Makes total sense.
