### ISSUE TITLE
It there an official LSIF parser/sdk existed?

### ISSUE THREAD

**Issue by williamfzc** [microsoft/language-server-protocol#1705]
Hi there.

It 's easy to find lots of implemented indexers for LSIF on https://lsif.dev/ .
But no any official (or not official neither) standalone LSIF parser can be found :(

It seems that each team has its own one:

- GitLab: https://gitlab.com/gitlab-org/gitlab/-/tree/master/workhorse/internal/lsif_transformer

And the SDKs look only working for LSP, not LSIF

![image](https://user-images.githubusercontent.com/13421694/228739614-d717419e-f66d-4dd8-8dd2-f69d46a7feb3.png)

It there an official LSIF parser/sdk existed?
Thanks in advance

**Comment by dbaeumer** [comment]
What would you expect that the parser/sdk does. The indexers are very language specific and there are tools here to validate an LSIF index: https://github.com/microsoft/lsif-node/tree/main/tooling

**Comment by williamfzc** [comment]
> What would you expect that the parser/sdk does. The indexers are very language specific and there are tools here to validate an LSIF index: https://github.com/microsoft/lsif-node/tree/main/tooling

Thanks for your reply.
The indexers are very language specific but the LSIF file does not I think. 

My purpose is really simple: 
- Read lsif file and convert it into objects
- Then I can process these vertexes and edges as objects in my program

This tool is something what I want. 
Is there something like that in other languages (for example, golang) ?

**Comment by dbaeumer** [comment]
No, that doesn't exist to my knowledge. I think however that you could create such a library and make it available on GitHub. 

I will close the issue since there are currently no plans to create such a tool. 

P.S.: creating such a tool in JS/TS should be only a couple of lines since LSIF is line JSON and all vertexes and edges in LSIF are identified by a unique identifier.
