### ISSUE TITLE
Investigate to extract a base protocol definition out of the LS protocol

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/language-server-protocol#1707]
Extracting a base protocol specification (without implementation) out of the Language Server protocol would allow defining protocols aside of LSP that adhere to the same rules than LSP like:

- message format
- lifecycle messages
- capability model
- base types,
- ....

**Comment by jdneo** [comment]
> protocols aside of LSP that adhere to the same rules than LSP.

Is [BSP](https://build-server-protocol.github.io/docs/specification/) an example for this purpose?

**Comment by dbaeumer** [comment]
BSP could make use of it but it not the main target right now.

**Comment by agluszak** [comment]
Hi @dbaeumer, @jdneo, @MariaSolOs! I randomly stumbled upon the Base Protocol definition. As a maintainer of BSP I'm very happy to see that you started working on it! We (JetBrains/Scala Center & friends) have been dreaming about it for quite a long time ;) We'd love to help you with the design, and I think it would be a great idea in general to keep in touch! You're invited to join our [BSP discord](https://discord.gg/XqfFndz5). 

In the not-so-far future we'd like to release a new major version of BSP. We wanted to bring it more in line with LSP anyway (use the new progress reporting mechanism for example), so we could simply wait until the work on the Base Protocol is finished. Another thing which may be of interest to you is that we've recently rewritten our spec in [Smithy](https://smithy.io/2.0/index.html) which made it machine-readable. Now our spec and support libraries for Java are automatically derived from the Smithy model. IIRC at some point you attempted doing something similar for LSP :)

**Comment by dbaeumer** [comment]
@agluszak great to hear that you are interested in the base protocol and that you might find it useful for BSP. Would be great if you could be one of the early adopters. I have joined the discord however I would like to keep the feedback about the base protocol in GitHub issues in this repository. Hope this is OK for you.

Regarding a meta model: yes, that exists in the mean time for LSP and will very likely be useful for other protocols as well. The way how it works is as follows:

- the protocol is described using TypeScript
- there is a tools that generates a custom meta model (tools are here: https://github.com/microsoft/vscode-languageserver-node/blob/main/tools/src/generator-main.ts and the meta model description is here: https://github.com/microsoft/vscode-languageserver-node/blob/main/tools/src/metaModel.ts)

A version of the LSP meta model can be found here: https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#metaModel

**Comment by dbaeumer** [comment]
The base protocol got extracted and is available on the LSP site.
