### ISSUE TITLE
Is there lint support?

### ISSUE THREAD

**Issue by nittdeniz** [microsoft/language-server-protocol#1708]
I could not find anything to support linting of the current document, i.e. showing syntax or grammar errors (like undefined variables) or even style errors, typically indicated by a squiggly red or yellow line. If there is no such thing yet, please consider adding it :)
The probably easiest way would be to extend the `SymbolTag` enum to include keywords like `unused`, `undefined`, `alreadyDefined`, `styleViolation`, `accessViolation` (e.g. accessing private members outside the class).

**Comment by rwols** [comment]
This is generally achieved with `Diagnostic`s.

**Comment by dbaeumer** [comment]
@rwols thanks for answering. 

I will close the issue since Diagnostics are that way to go.
