### ISSUE TITLE
Sample server

### ISSUE THREAD

**Issue by ejfasting** [microsoft/language-server-protocol#1709]
Hello, 

I would like to create an LSP in .net/C# but unfortunately I haven't found any good examples on how to get the basics up and running. 
I've previously made one in typescript, with completion, so it would be nice to see how that is implemented in .net. 
Is there a repo somewhere that contains some examples I can look at? Or something like this, but for this instead of omnisharp: 
https://martinbjorkstrom.com/posts/2018-11-29-creating-a-language-server 

Thanks!

**Comment by dbaeumer** [comment]
I am not aware of any extended documentation around this. What might help is looking at the SDKs that are available for C# here: https://microsoft.github.io/language-server-protocol/implementors/sdks/

Will close the issue as question. People can still comment on it.
