### ISSUE TITLE
AnnotatedTextEdit in WorkspaceEdit

### ISSUE THREAD

**Issue by hokein** [microsoft/language-server-protocol#1710]
I'm exploring the `AnnotatedTextEdit` feature in clangd, and have a few questions:

1. In the `WorkspaceEdit`, the `changes?: { [uri: DocumentUri: TextEdit[]; };` field still uses the `TextEdit`, is this intentional? It seems like an oversight (I think it should be `changes?: { [uri: DocumentUri: TextEdit|AnnotatedTextEdit[]; };`, similar to the `edits` field of `TextDocumentEdit`).

2. The `CodeActionClientCapabilites.honorsChangeAnnotations` is set to `false` by default in the [vscode client](https://github.com/microsoft/vscode-languageserver-node/blob/a6f0d22d2c6842337ad135c13d2f945e53b1a6e4/client/src/common/codeAction.ts#L62). It was reported in the VSCode [issue](https://github.com/microsoft/vscode/issues/151240). The issue has been duplicated with https://github.com/microsoft/vscode/issues/151140 which has been resolved. Looks like VSCode has all the pieces, can we enable it now?

**Comment by dbaeumer** [comment]
You should use the new property `documentChanges` which is supported in VS Code.

Have you tried to ignore the setting and simply use change annotations for Code Actions with documentChanges. I think the code should already handle it correctly. If that works for you I am happy to simply switch the boolean.

**Comment by hokein** [comment]
> You should use the new property documentChanges which is supported in VS Code.

Yeah, I understand the `documentChanges` is more preferred, but clangd doesn't have it implemented yet (it'll take some work). And leaving the old field `changes` still seems inconsistent, it would be nice to fix it as well.

> Have you tried to ignore the setting and simply use change annotations for Code Actions with documentChanges. I think the code should already handle it correctly. If that works for you I am happy to simply switch the boolean.

Yeah, you're right. I have verified it works. Sent you https://github.com/microsoft/vscode-languageserver-node/pull/1225.

**Comment by kadircet** [comment]
> You should use the new property documentChanges which is supported in VS Code.

Apart from clangd specific concerns Haojian has mentioned above, `documentChanges` requires more support from the clients. They need to handle versioned documents in addition to annotated text edits.

The suggestion here is updating the value type for `changes` from sole "[TextEdit](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textEdit)[];" to "([TextEdit](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textEdit) | [AnnotatedTextEdit](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#annotatedTextEdit))[]".

That way clients that only has capability `workspace.workspaceEdit.changeAnnotationSupport` can also receive annotated text edits, without requiring capability for `workspace.workspaceEdit.documentChanges`.

**Comment by dbaeumer** [comment]
I see the desire but not providing the version number is not a good idea. So I am not a big fan of extending the support in `changes`

**Comment by kadircet** [comment]
> not providing the version number is not a good idea

Could you elaborate on this part a little bit? I'd like to understand if we're missing a hard requirement on document versions for annotated textedits somehow.

I can surely see the benefits of having this version information to patch edits or reject them when they no longer apply and also the need for a new capability to indicate `changes` can accept both. but  I don't see why this needs to be a hard requirement or any other drawbacks to status quo, as clients can already apply `TextEdit`s that are not attached to a particular version of the document today. 


Just to verify our understanding going forward regarding `OptionalVersionedTextDocumentIdentifier`;
Spec states that a `TextDocumentEdit` pairs an `OptionalVersionedTextDocumentIdentifier` and a set of `edit`s. Again it's stated that this version identifier is `to allow clients to check the text document version before an edit is applied` and it is `optional`.
So, one can still send `documentChanges` without any version identifiers, making it practically the same as `changes`, right? Or is the `null` value reserved for denoting the version on disk (even for open documents) and this version specification is actually never `optional` ?

**Comment by dbaeumer** [comment]
The version ensures that the client will not apply changes calculated on a different document version. 

The version is actually not optional in the sense of having an optional property (the naming is not good). `null` has a special meaning

> If a versioned text document identifier is sent from the server to the client and the file is not open in the editor (the server has not received an open notification before) the server can send `null` to indicate that the version is unknown and the content on disk is the truth (as specified with document content ownership)

So if a server sends `null` and the document in the meantime got opened in an editor and changed the client should reject the edit.

**Comment by hokein** [comment]
> The version ensures that the client will not apply changes calculated on a different document version.

I understand that using the versioned `documentChanges` is the recommended approach. However, the LSP specification does not explicitly prohibit the usage of `changes`. According to the specification

> A workspace edit represents changes to many resources managed in the workspace. The edit should either provide `changes` or `documentChanges`. If the client can handle versioned document edits and if `documentChanges` are present, the latter are preferred over `changes`.

Based on my understanding, both are fine, and it is acceptable for the server to use `changes` if it does not fully support the versioned document. Thus I think we consider extending the `changes` to support `AnnotatedTextEdit` (happy to contribute the implementation in vscode-languageserver-node).

**Comment by dbaeumer** [comment]
As said, I am not a fan of this. I would rather starting deprecating `changes` in 3.18 since all new feature will always go into `documentChanges`.

**Comment by hokein** [comment]
OK, fair enough, thanks for the clarification. I'll see how we can support the `documentChanges` in clangd. I think we can close this issue now.
