### ISSUE TITLE
Should TextDocumentItem inherit from TextDocumentIdentifier?

### ISSUE THREAD

**Issue by rhdunn** [microsoft/language-server-protocol#1714]
The `TextDocumentIdentifier` interface is used for `textDocument` properties in various APIs to supply the `uri` of the specified document.

The `TextDocumentItem` interface is used for the `textDocument` property in `DidOpenTextDocumentParams`, supplying the `uri` property in addition to other details.

Given its use in the `textDocument` property, I would have expected that to be an instance of `TextDocumentIdentifier`. As such, it would make sense to make `TextDocumentIitem` inherit from `TextDocumentIdentifier` like `VersionedTextDocumentIdentifier`. Doing this would allow the `uri` parameter to be removed from `TextDocumentItem`.

**Comment by dbaeumer** [comment]
As said in an earlier issue LSP is JSON and not OOP based. In JSON there is no concept of inheritance. The reason why we extend interfaces is to avoid to many duplications. 

Hope that helps.
