### ISSUE TITLE
Can properties taking a base interface support derived interface values?

### ISSUE THREAD

**Issue by rhdunn** [microsoft/language-server-protocol#1715]
There are various properties, such as `textDocument: TextDocumentIdentifier` where the property type is a base interface. Can these have derived interface values (e.g. `VersionedTextDocumentIdentifier`) if not explicitly specified in the protocol?

**Comment by dbaeumer** [comment]
LSP uses extend in  interfaces to avoid to many duplications. The protocol is JSON based and not object based in the sense of OOP. So clients are allowed to reject such an JSON object.
