### ISSUE TITLE
Grammar/typo issues in the protocol documentation

### ISSUE THREAD

**Issue by rhdunn** [microsoft/language-server-protocol#1716]
In [Range](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#range):
> Therefore the end position is exclusive.

should be:
> Therefore, the end position is exclusive.

according to my grammar checker program.

-----

In [PublishDiagnostics Notification](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_publishDiagnostics):
> Diagnostics notification are sent from the server to the client to signal results of validation runs.

should be:
> Diagnostics notifications are sent from the server to the client to signal results of validation runs.

as "are" indicates a plural and notification is singular here.

-----

In [Document Highlights Request](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_documentHighlight):
> The document highlight request is sent from the client to the server to resolve a document highlights for a given text document position.

should be:
> The document highlight request is sent from the client to the server to resolve document highlights for a given text document position.

as "a" indicates a singular noun, whereas "document highlights" is plural.

-----

In [Document Highlights Request](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_documentHighlight):
> However we kept ‘textDocument/documentHighlight’ and ‘textDocument/references’ separate requests since the first one is allowed to be more fuzzy.

should be:
> However, we kept ‘textDocument/documentHighlight’ and ‘textDocument/references’ separate requests since the first one is allowed to be more fuzzy.

according to my grammar checker program.

-----

In [Document Highlights Request](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_documentHighlight):
> Symbol matches usually have a `DocumentHighlightKind` of `Read` or `Write` whereas fuzzy or textual matches use `Text`as the kind.

should be:
> Symbol matches usually have a `DocumentHighlightKind` of `Read` or `Write` whereas fuzzy or textual matches use `Text` as the kind.

as there is a space missing between "`Text`" and "as".

**Comment by dbaeumer** [comment]
PR available
