### ISSUE TITLE
Unknown protocol version error

### ISSUE THREAD

**Issue by akosyakov** [Microsoft/language-server-protocol#172]
I see that the initialize request has a custom `error.code`: `unknownProtocolVersion`.
- Is it jsonrpc protocol version or ls protocol version?
- If it is the jsonrpc protocol version should not it belong to typical error codes and check should be done by the base protocol?
- if it is the ls protocol version where do we pass this version?

**Comment by dbaeumer** [comment]
Actually this is left over of a beta version as well. In one of the beta version we experimented with protocol version numbers to let servers know which version a client speaks. However we decided to go with client capabilities instead since they are more flexible. I deprecated the constant.
