### ISSUE TITLE
Confusing discussion of `DidChangeWorkspaceFolders` notification

### ISSUE THREAD

**Issue by siegel** [microsoft/language-server-protocol#1720]
In the process of implementing workspace-change notifications in my client, I'm finding conflicting information in the 3.17 specification.

The [description of `WorkspaceFoldersServerCapabilities`](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workspace_workspaceFolders) says:

```
export interface WorkspaceFoldersServerCapabilities {
	/**
	 * The server has support for workspace folders
	 */
	supported?: boolean;

	/**
	 * Whether the server wants to receive workspace folder
	 * change notifications.
	 *
	 * If a string is provided, the string is treated as an ID
	 * under which the notification is registered on the client
	 * side. The ID can be used to unregister for these events
	 * using the `client/unregisterCapability` request.
	 */
	changeNotifications?: string | boolean;
}
```

which suggests that the server should only be sent workspace change notifications if `changeNotifications` is present and (either) a string (or) a boolean `True`, but then the [discussion of the `DidChangeWorkspaceFolders` notification](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workspace_didChangeWorkspaceFolders) says:

```
The notification is sent by default if both client capability `workspace.workspaceFolders`
and the server capability `workspace.workspaceFolders.supported` are true; or if the server
has registered itself to receive this notification. 
```

The second discussion doesn't mention `workspace.workspaceFolders.changeNotifications` at all; so should the client honor it, ignore it, or treat it conditionally (and if so, how)? Can the documentation be amended to clarify this?

**Comment by dbaeumer** [comment]
> The notification is sent by default if both client capability `workspace.workspaceFolders` and the server capability `workspace.workspaceFolders.supported` are true;

This is actually wrong since in LSP we try to avoid to do something (e.g. send request / notification) be default. I will update the spec.

**Comment by siegel** [comment]
That helps a great deal - thanks very much.

One last question: does the change you made in #1721 mean that the server capability `workspace.workspaceFolders.supported` is purely informational, and/or obsolete? I wasn't able to locate any other references to it in the 3.17 specification.

**Comment by dbaeumer** [comment]
It is informational for the client. If a server doesn't have support for workspace folders a client could decide to start a server per folder.
