### ISSUE TITLE
Inconsistent usage of `void` in the spec document

### ISSUE THREAD

**Issue by rchl** [microsoft/language-server-protocol#1725]
Spec in various places uses `params: void` or `params: none` or `result: void` but it's not always clear what it means and in some cases it seems incorrect. I would assume that `void` means that the property should not be set since if it would expect it to be null then it should say `params: null` or `params: none`.

Some correct and possibly incorrect examples:

 - The [`shutdown` request](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#shutdown) specifies: `params: void` and the [json schema](https://github.com/microsoft/vscode-languageserver-node/blob/0b7acc15abd7132c9154d94140f478ccf5ba5769/protocol/metaModel.json#L1021-L1029) doesn't list `params` which I'm assuming means that this property should not be provided at all.
 - Same for the `exit` notification: [spec](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#exit) / [schema](https://github.com/microsoft/vscode-languageserver-node/blob/0b7acc15abd7132c9154d94140f478ccf5ba5769/protocol/metaModel.json#L1897-L1901)
 - The [`workspace/diagnostic/refresh` request](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#diagnostic_refresh) specifies `params: none` ([json schema](https://github.com/microsoft/vscode-languageserver-node/blob/0b7acc15abd7132c9154d94140f478ccf5ba5769/protocol/metaModel.json#L968-L977) doesn't list `params`). I guess this should also say `void`.
 - `workspace/diagnostic/refresh` again... it specifies `result: void` but the `result` property is actually required on successful response so this seems wrong.

There are likely many other examples of those inconsistencies.

**Comment by dbaeumer** [comment]
I fixed that in the following way:

- `params: none` for notifications and requests that don't take any params. So there aren't none
- `result: void` for requests that don't return a result (this is in line with programming languages)

**Comment by oxalica** [comment]
>     * `params: none` for notifications and requests that don't take any params. So there aren't none

I think the meaning of `params: none` should be explained or at least mentioned in `{Request,Notification}Message`.

Does the "don't" in "don't take any params" means mandatory not-existing, or whatever-and-should-be-ignored? The `result` field in `Response` is explicitly mentioned to be "REQUIRED" on success, while the `params` in requests and notifications are marked as `params?` without additional explanation.

```
	/**
	 * The method's params.
	 */
	params?: array | object;
```

For example, is `{"method":"shutdown":params":{}}` considered valid? Is `{"method":"shutdown":params":null}` considered valid? The latter may be useful for generic code handling requests with or without params.
