### ISSUE TITLE
Add Type Definition Provider support

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/language-server-protocol#173]
From https://github.com/Microsoft/vscode/pull/19699 . Add support to the language server protocol for type definition providers

**Comment by rcjsuen** [comment]
How does this differ from `textDocument/definition`...or is this the same thing? Am I missing something here?

**Comment by dbaeumer** [comment]
```
var x = foo();
```

goto type definition having x selected takes you to the return type of foo.

**Comment by rcjsuen** [comment]
So why was this closed? I don't see a `textDocument/typeDefinition` request in the new `specification.md` file in the `gh-pages` branch. Which commit "fixes" this issue?

**Comment by dbaeumer** [comment]
It got implemented as proposed request / responses in the vscode-languageserver-node library. I will reopen and close when we move the md part here.

**Comment by rcjsuen** [comment]
Ah, okay. Thank you for clarifying, Dirk!

**Comment by rcjsuen** [comment]
@dbaeumer Okay to close since this got merged into the specification with 39b118153e7f9ecada27a01a1837edd1823ccfcd?

**Comment by dbaeumer** [comment]
Closing. @rcjsuen thanks for reminding.
