### ISSUE TITLE
Questions around use of patterns for dynamic document registration

### ISSUE THREAD

**Issue by briandealwis** [microsoft/language-server-protocol#1731]
I'm looking to perform dynamic registration for `didChange` and `didChangeWatchedFiles` for specific files.  But the patterns used in [`TextDocumentRegistrationOptions`](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocumentRegistrationOptions) (specifically [`DocumentFilter`](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#documentFilter)) and [`DidChangeWatchedFilesRegistrationOptions`](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#didChangeWatchedFilesRegistrationOptions) (specifically [`Pattern`](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#pattern)) are not clear:
- Are these patterns evaluated against file paths or URIs?  If paths, should we be using `/` as path separators?
- [`Pattern`](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#pattern)'s description says: _"The glob pattern to watch relative to the base path."_  What is the base path when a `Pattern` is used directly in a `FileSystemWatcher`?

**Comment by dbaeumer** [comment]
Files can only be monitored inside a workspace folder (e.g. files that are part of the editor). Hence all the patterns are relative to these workspace folders. LSP has no concept of watching or monitoring arbitrary files on the file system.
