### ISSUE TITLE
Clarify how to handle unresolvable `codeAction/resolve`

### ISSUE THREAD

**Issue by mheiber** [microsoft/language-server-protocol#1738]
What should the server do when the client makes a "codeAction/resolve" request that is unresolvable?

A code action can be unresolvable in at least the following case if I understand correctly:
- Client sends "textDocument/codeAction"
- Server responds with a partially-resolved code action (for example, missing both "exit" and "command" fields)
- The user selects the code action and the client sends "codeAction/resolve"
- The source code changes (for example, from switching branches)
- The server is no longer able to resolve the code action because (for example) "extract method" no longer makes sense if the Range sent now corresponds to whitespace.

Is the expected behavior of the server to respond with a `ResponseError` with code `ErrorCodes.InvalidRequest`?

**Comment by dbaeumer** [comment]
The server should respond with ResponseError using the code LSPErrorCodes.ContentModified

**Comment by joyfulmantis** [comment]
Would it be possible to add this to the spec (I am assuming that this is generic for all resolve requests)

**Comment by dbaeumer** [comment]
See https://github.com/microsoft/language-server-protocol/pull/1787
