### ISSUE TITLE
DocumentFilter definition mismatch in LSP 3.17

### ISSUE THREAD

**Issue by reznikmm** [microsoft/language-server-protocol#1742]
Definition of `DocumentFilter` in [3.17 spec](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#documentFilter) differs from [metaModel.json](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/metaModel/metaModel.json). In spec:

> export interface DocumentFilter { ...

In `metaModel.json`:

![изображение](https://github.com/microsoft/language-server-protocol/assets/6430719/5c840df2-7dcf-4d0c-9755-4cdd38a66a77)

**Comment by dbaeumer** [comment]
Good catch. Missing the update in the specification.

**Comment by dbaeumer** [comment]
This got fixed lately (< 2 weeks)
