### ISSUE TITLE
Mark rootPath as optional

### ISSUE THREAD

**Issue by ljw1004** [Microsoft/language-server-protocol#175]
The protocol.md has
```json
/* @deprecated in favour of rootUr */
rootPath: string | null;

rootUri: DocumentUri | null;
```

It looks like the rootPath, although deprecated, is still mandatory. I struggled to know what to pass to it...

* If we pass a rootUri, are we still expected to pass a rootPath?
* Is the server expected to use rootUri if both rootPath and rootUri are present? (and if they disagree?) Or must the client send a null rootPath?

I expected you to mark them both as optional, `rootPath?: string | null` and `rootUri?: DocumentUri | null`, and then explain in the prose the additional restriction (not expressible in the formalism) that exactly one of them must be present.

**Comment by ljw1004** [comment]
See also #87

**Comment by dbaeumer** [comment]
@ljw1004 thanks for pointing this out.

I made rootPath optional and kept rootUri mandantory on the protocol level. Reason being that in 3.0 clients must provided rootUri. I also clarified that if both are present `rootUri` wins.
