### ISSUE TITLE
What's the point of codeLens/resolve

### ISSUE THREAD

**Issue by joyfulmantis** [microsoft/language-server-protocol#1750]
Without resolve, if the server wants to complete a codeLens action lazily, it only needs to send a command that will get sent back to the server to trigger whatever action it wants. Now with codeLens/resolve it can send a codeLens that will be resolved to a command that will be sent back to the server to trigger whatever action it wants. However, no extra functionality is gained. So what is the point of codeLens/resolve then?

**Comment by rchl** [comment]
I believe it's because resolving the `title` of the command can be performance intensive. For example for a code lens that shows a number of references, it might be necessary to do non-trivial work to figure out how many references there are.

**Comment by dbaeumer** [comment]
@rchl thanks for providing the answer. 

Clients usually send the resolve request when a code lens becomes visible in the editor.
