### ISSUE TITLE
No client capability for codeLens/resolve

### ISSUE THREAD

**Issue by michaelpj** [microsoft/language-server-protocol#1761]
I think there probably should be one since surely not all clients support it?

**Comment by dbaeumer** [comment]
In the current protocol the resolve request is defined as a request to resolve the command of a code lens. Instead of adding a separate capability we should do the same as we did for completion items: we should add a capability that list the properties that can be resolve lazy on a code lens.

**Comment by michaelpj** [comment]
Yes in principle, although the only field that can reasonably be resolved lazily is the command: you need the range to know anything about it and the data is just for resolve anyway. But we might add more fields in future, so I still think following the design of the others makes sense.

It's worth noting that this will potentially be a bit awkward for servers. Since there was no capability, servers have had to assume that clients support it, so they might behave badly if a client suddenly says that it doesn't. Still, I think it would be an improvement.

**Comment by dbaeumer** [comment]
Actually the client capability to list the items to be resolved lazily is already in since 3.16.0. See https://github.com/microsoft/vscode-languageserver-node/blob/dbaeumer/painful-yak-copper/protocol/src/common/protocol.ts#L3204

Since this is consistent with what we do for completion items I will close the issue.

**Comment by mfussenegger** [comment]
> Actually the client capability to list the items to be resolved lazily is already in since 3.16.0. See https://github.com/microsoft/vscode-languageserver-node/blob/dbaeumer/painful-yak-copper/protocol/src/common/protocol.ts#L3204
> 
> Since this is consistent with what we do for completion items I will close the issue.

Where? The link doesn't work.

[CodeLensClientCapabilities](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_codeLens) doesn't mention anything?

**Comment by dbaeumer** [comment]
Reopening. Looks like I was in the wrong file. Need to see what went wrong.
