### ISSUE TITLE
Clarification about "$/progress": replace or append?

### ISSUE THREAD

**Issue by mheiber** [microsoft/language-server-protocol#1767]
Do ["$/progress"](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#progress) events replace the payload or append to the payload?

For example, if we provide the user with 5 find references in a progress message and then another 3, should the client show the user 3 find-references results or 8?

cc @ljw1004

**Comment by ljw1004** [comment]
The spec is ambiguous on this question:
>  If a server reports partial result via a corresponding [$/progress](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workDoneProgressBegin), the whole result must be reported using n [$/progress](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workDoneProgressBegin) notifications. The final response has to be empty in terms of result values. This avoids confusion about how the final result should be interpreted, e.g. as another partial result or as a replacing result.

This makes it clear that the *final result* doesn't replace all the `$/progress `that came earlier, but we don't know whether each `$/progress` will replace all the `$/progress` that came earlier...

**Comment by ljw1004** [comment]
ping @dbaeumer, would love to get your answer on this. We've just finished implementing streaming `textDocument/references` results our Hack LSP server, using just small tweak in our extension to alter the VSCode find-references pane, but we need to decide on the LSP behavior.

**Comment by rwols** [comment]
I would expect append behavior otherwise clients get 1+2+3+4+…+n = n(n+1)/2 = O(n^2) items to process.

**Comment by dbaeumer** [comment]
The idea is an append behavior. Think about it as an async iterator where the '$/progress` event is the source of new async items.

**Comment by dbaeumer** [comment]
Will update the spec to make this clear.

**Comment by ljw1004** [comment]
Thank you!
