### ISSUE TITLE
Clarify whether "textDocument/didOpen" is required first

### ISSUE THREAD

**Issue by ljw1004** [Microsoft/language-server-protocol#177]
Can you call `textDocument/documentSymbol` on a URI without first having sent `textDocument/didOpen`?

Protocol.md explains that `textDocument/didOpen` means the document's truth is *now* managed by the client. Hence, by implication, prior to didOpen, the document's truth was managed by the server. Hence the server should be able to list its symbols.

But when I experimented with this in pyls (the Python language server), pyls reported an internal error if I tried to get a document's symbols prior to sending didOpen.

I think that Protocol.md should mandate what's expected here.

**Comment by dbaeumer** [comment]
@ljw1004 yes the server should be able to list the symbols. IMO there is nothing I can spec except a very generic sentence that the fulfillment of a request should be independent of whether a document is opened or closed. The doc already states that closed files are owned by the server.

IMO a server can make some assumptions about in which use case it is used. For example requesting code complete make mostly only sense if the file is open in the editor and the user is typing in it. So it might response with an error if code complete is request on a closed document. At the end the LSP is not a model API around a language model. 

Have you talked to the pyls team why they don't support certain requests on a closed document. 

Any objection to close?

**Comment by ljw1004** [comment]
Go ahead and close. I'd love if you add that generic sentence. That way, I can write to the pyls team, and point to your generic sentence in the spec, and explain that their current behavior is wrong.

**Comment by dbaeumer** [comment]
@ljw1004 feel free to provide a PR
