### ISSUE TITLE
LSP Node SDK is only for VSCode or can be used with every IDE? 

### ISSUE THREAD

**Issue by MatteoPossamai** [microsoft/language-server-protocol#1773]
I read this article from the Microsoft page, where there is also the example with the Node SDK: https://code.visualstudio.com/api/language-extensions/language-server-extension-guide
 
 I have not understood if, using the furnished server, it runs also with all the other IDE and code editor, like for example ATOM and so on, or it is just for VSCode. From my understanding reading the documentation, it should be universal, so the same for everyone. But the SDK is universal too? Thank you

**Comment by dbaeumer** [comment]
The server part of the SDK is universal, the client part is specific for VS Code and can only be used with VS Code.
