### ISSUE TITLE
Support GlobPattern in DocumentFilter

### ISSUE THREAD

**Issue by mroch** [microsoft/language-server-protocol#1781]
in the VS Code API, `DocumentFilter`'s `pattern` property is a `GlobPattern` ([docs](https://code.visualstudio.com/api/references/vscode-api#DocumentFilter)), which supports `RelativePattern`. but in the LSP only `string` is supported.

now that `RelativePattern` is part of the LSP, I propose that LSP's `DocumentFilter.pattern` also become a `GlobPattern`.

at the very least, it should be a `Pattern`, not just a `string`.

**Comment by dbaeumer** [comment]
Implemented and documented for 3.18 release
