### ISSUE TITLE
Client's response to failed code lens resolve requests

### ISSUE THREAD

**Issue by joyfulmantis** [microsoft/language-server-protocol#1785]
In issue #1738 dbaeumer mentioned that resolve requests that are unable to be resolved should fail with ContentModified. We currently do that in HEAD@haskell-language-server, however, the client behavior to these failures for lenses is not ideal. Specifically, visual studio code shows a "no command" lens for any lens that fails. 

Ideally, if the client is not able to resolve the lens, it should not show anything. This should also be clarified in the spec. (In addition, should #1738 also be written into the spec).

**Comment by dbaeumer** [comment]
Actually the spec tries to avoid specing what a client should do in the UI. For VS Code the resolve request should be canceled now. See https://github.com/microsoft/vscode/pull/180485.

However VS Code might still show `no command` or `missing command` in some cases. You should open an issue against VS Code if you still see this even when the cod lens resolve request got canceled.
