### ISSUE TITLE
Diagnostics and compilation

### ISSUE THREAD

**Issue by vladdu** [Microsoft/language-server-protocol#179]
A discussion question: the way to retrieve diagnostics for most (if not all) compiled languages is by executing the compiler on the sources, because only parsing the code can only provide some errors/warnings. The clients will have a "Build" command that also calls the compiler and I wonder if it would be possible to unify these operations. For larger projects, running the compiler twice can be prohibitive or taxing on the computer. Would it be reasonable to let the server tell the client "hey, I'm doing the compilation, don't bother yourself"?

Even if the compilation is done twice, there is also the question of providing the right configuration for the compiler. One wants to provide the same environment so that the diagnostics and the real compilation match and that the compilation uses the right parameters. Should the protocol provide a way to send this configuration in a standard way? (regardless of the answer for the first question)

**Comment by svenefftinge** [comment]
I think the build should be smart enough to avoid unnecessary work, e.g. by checking timestamps.

For the configuration it should be up to the language server to find and use it. And I would expect that the same code picks up the same configuration from that location during a build.

**Comment by vladdu** [comment]
Not all build systems are smart enough, but you are right - asking that much of them is reasonable and will help them improve. 

As for the configuration, I keep forgetting about the `didChangeConfiguration` notification, which is able to communicate changes to the build environment. Sorry for the noise.
