### ISSUE TITLE
Extend TextDocumentPositionParams to have the name

### ISSUE THREAD

**Issue by robbycbennett** [microsoft/language-server-protocol#1795]
Right now, the [Language Features](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#languageFeatures) are not as accurate or as fast as they could be. This is because many of these features rely on the simple parameter [TextDocumentPositionParams](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocumentPositionParams), which only has the file URI and the position in the file. It is missing a fundamental property: the `name` (or the identifier/text/content.)

This new `name` property is very important for 2 reasons.
* Accuracy: when the user edits the file, the line and/or character position may be changed. The name makes sure that the wrong text is not selected by the language server. Language server likely remember the name and even do database lookups based off of the name.
* Speed: assuming that the file is saved and the location reported by the client is correct, it is not likely that the primary lookup mechanic of the server is by the URI & location alone. Because of this, the server would have to access the filesystem to find the name at the location, and then look up the symbol/entity by that name and location.

Here is what it may look like with the new proposal.

```ts
interface TextDocumentPositionParams {
	/**
	 * The text document.
	 */
	textDocument: TextDocumentIdentifier;

	/**
	 * The position inside the text document.
	 */
	position: Position;

	/**
	 * The name of the target at the position.
	 */
	name: string;
}
```

This would significantly improve 15 different parameter interfaces.

 * [DeclarationParams](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#declarationParams)

 * [DefinitionParams](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#definitionParams)

 * [TypeDefinitionParams](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#typeDefinitionParams)

 * [ImplementationParams](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#implementationParams)

 * [ReferenceParams](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#referenceParams)

 * [CallHierarchyPrepareParams](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#callHierarchyPrepareParams)

 * [TypeHierarchyPrepareParams](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#typeHierarchyPrepareParams)

 * [DocumentHighlightParams](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#documentHighlightParams)

 * [HoverParams](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#hoverParams)

 * [MonikerParams](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#monikerParams)

 * [CompletionParams](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#completionParams)

 * [SignatureHelpParams](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#signatureHelpParams)

 * [RenameParams](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#renameParams)

 * [PrepareRenameParams](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#prepareRenameParams)

 * [LinkedEditingRangeParams](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#linkedEditingRangeParams)

**Comment by puremourning** [comment]
It's the responsibility of the language server (with semantic knowledge) to decide the 'name'. Clients don't have the semantic understanding of a 'name' ina given position. 
This would be a net loss imo.

**Comment by robbycbennett** [comment]
Okay, I agree especially in the case of ambiguous tokens, such as overridden operators in C++.

Now after some more reading, I see how it's possible for the language server to comprehend positions when the file has been changed. It's through Document Synchronization.

The Language Features [Overview](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#languageFeatures) should be updated to clarify this for those who are new to implementing the LSP. Perhaps it could be worded similar to the following sentence that I've appended.

> ### Language Features
> Language Features provide the actual smarts in the language server protocol. They are usually executed on a [text document, position] tuple. The main language feature categories are:
>  * code comprehension features like Hover or Goto Definition.
>  * coding features like diagnostics, code complete or code actions.

**These features can even be utilized on changed unsaved files through synchronization. See [Text Document Synchronization](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_synchronization) and [Notebook Document Synchronization](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#notebookDocument_synchronization)**

**Comment by dbaeumer** [comment]
Updated doc.
