### ISSUE TITLE
Clarify role of "Initialized" notification

### ISSUE THREAD

**Issue by ljw1004** [Microsoft/language-server-protocol#180]
The spec says this: *"The initialized notification is sent from the client to the server after the client is fully initialized and is able to listen to arbritary [sic] requests and notifications sent from the server."*

Interpretation1: the server MUST not send requests or notifications until after it has received the initialization notification; therefore, by implication, the client MUST send this notification (otherwise it will exclude itself from half the protocol.)

Interpretation2: the server MAY send requests+notifications before having received this notification, but if so then the client MAY reject anything it receives until after having sent the notification. By implication, it's okay for a client not to send the notification at all.

I'm not sure which interpretation is correct...

**Comment by dbaeumer** [comment]
Bogus and misleading documentation :-). The story is:

> The initialize request is sent as the first request from the client to the server. If the server receives request or notification before the `initialize` request it should act as follows:

> * for a request the respond should be errored with `code: -32002`. The message can be picked by the server.
> * notifications should be dropped, except for the exit notification. This will allow the exit a server without an initialize request.

> Until the server has responded to the `initialize` request with an `InitializeResult` the client must not sent any additional requests or notifications to the server. 

> During the `initialize` request the server is allowed to sent the notifications `window/showMessage`, `window/logMessage` and `telemetry/event` as well as the `window/showMessageRequest` request to the client.

This means that the server for example can not dynamically register handlers during the initialize request. 

I changed the spec for `initialized`: 

> The initialized notification is sent from the client to the server after the client received the result of the `initialize` request but before the client is sending any other request or notification to the server. The server can use the `initialized` notification for example to dynamically register capabilities.
