### ISSUE TITLE
Clarify how a server can know which line ending sequence to use (LF or CRLF) when inserting text

### ISSUE THREAD

**Issue by RossBencina** [microsoft/language-server-protocol#1800]
#1021 adds the `normalizesLineEndings` client capability to 3.16

When `true`, does this guarantee that the server is free to insert text with either '\n' or '\r\n' and the client guarantees to perform the appropriate conversion? Or should the server always use '\n'?

When `false` or `null`, is there a way to know which line ending mode the editor is in for a particular document? i.e. for a server to insert line endings that are consistent with what happens when the user presses the enter key in an empty document.

Or does the server have to manually detect the line ending mode of each document based on the document's text? (Obviously this will fail for empty documents, hence my questions above).

**Comment by dbaeumer** [comment]
Marking as dup of https://github.com/microsoft/language-server-protocol/issues/1853
