### ISSUE TITLE
is there a rate limit error code?

### ISSUE THREAD

**Issue by llllvvuu** [microsoft/language-server-protocol#1805]
In HTTP there is 429, how about stdio? I looked at this: https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#errorCodes and I didn't find anything.

**Comment by dbaeumer** [comment]
I am actually not sure what you are requesting. The server is usually managed by a client and not publically visible were rate limits are an issue.

**Comment by llllvvuu** [comment]
I've experienced some poorly configured editors and thought about handling them, but you're right, it's not the server's problem to handle.
