### ISSUE TITLE
Type of ConfigurationItem.scopeUri should be URI instead of DocumentUri

### ISSUE THREAD

**Issue by jwortmann** [microsoft/language-server-protocol#1808]
The type of the [`scopeUri`](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#configurationItem) field in the `workspace/configuration` request is currently `DocumentUri`.

I think this restriction is not very useful, and the type should be `URI` instead (and there are language servers which don't comply with the current type in the specs - see e.g. https://github.com/microsoft/pylance-release/issues/4826).

Could you please clarify whether the `DocumentUri` type is intended, or was it just an oversight and should be fixed?

**Comment by dbaeumer** [comment]
Fixed.
