### ISSUE TITLE
Does the LSP client for Visual Studio support Markdown?

### ISSUE THREAD

**Issue by HJLebbink** [microsoft/language-server-protocol#1809]
I'm building a visual studio extension and a LSP; it is clear what is _specified_ in the LSP specs, but it is not clear what is _implemented_ in Microsoft.VisualStudio.LanguageServer.Protocol.Extensions 17.2.8.

See my same question [here](https://learn.microsoft.com/en-us/answers/questions/1366606/does-the-language-server-provider-(lsp)-client-for) and on [SO](https://stackoverflow.com/questions/77015711/popup-hover-with-markdown-from-a-language-server-protocol-lsp).

**Question**: Is Markdown implemented (in VS, for hover), and if it is, how to enable it. Please see what I have tried in the SO question.

**Comment by dbaeumer** [comment]
@HJLebbink you need to ask the to the maintainers of the VS LSP client. I don't know which feature set they are currently supporting.

**Comment by henkjan-sneller** [comment]
Great. 'their' website is https://learn.microsoft.com/en-us/visualstudio/extensibility/language-server-protocol and when you ask on that forum, they point to you guys. So who should I ask? There is AFAICT no repo with the client code (that could have some pointers).

**Comment by dbaeumer** [comment]
@henkjan-sneller that is strange from their end. Since I don't maintain their client implementation I can't comment on what they support. The spec actually requires them to support markdown since it is not optional in some requests.

**Comment by HJLebbink** [comment]
@dbaeumer thank you for the response, Could you help me navigate the Microsoft organization. Who could I ask to help me out (See [here](https://github.com/HJLebbink/asm-dude/issues/150) for an overview what I've tried).

**Comment by dbaeumer** [comment]
@MariaSolOs do you know an official channel were users can ask questions about the LSP client in VS?

**Comment by MariaSolOs** [comment]
@dbaeumer great question. I think that https://developercommunity.visualstudio.com/home and https://github.com/microsoft/VSExtensibility would be good places for these kind of issues.

**Comment by dbaeumer** [comment]
Thanks @MariaSolOs

**Comment by HJLebbink** [comment]
Yes, thanx, @dbaeumer & @MariaSolOs; you triggered somebody to come up with a proper answer on SO!
