### ISSUE TITLE
Differences between VSCode and the language server protocol regarding code action requests

### ISSUE THREAD

**Issue by Wosi** [Microsoft/language-server-protocol#181]
I'm struggling with the current behaviour of VSCode regarding code action requests. I have no idea whether

  a) the language server protocol documentation is outdated or
  b) VSCode's implementation of the protocol is not accurate

What is happending?
VSCode asks for code actions whenever the cursor is placed in any word. It doesn't care whether there is a problem marker.  I've already opened an [issue](https://github.com/Microsoft/vscode/issues/20431) but as I don't receive any response I would like to receive information about this topic here.

**Comment by Wosi** [comment]
@dbaeumer and @jrieken are saying VSCode behaves as intended. That implies the [protocol documentation](https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#textDocument_codeAction) is outdated:

> The code action request is sent from the client to the server to compute commands for a given text document and range. The request is triggered when the user moves the cursor **into a problem marker** in the editor or presses the lightbulb associated with a marker.

**Comment by jrieken** [comment]
the doc is outdated or the the lsp implementation isn't sticking to the docs. @wose Note that there are *three* things

1. The extension API
2. The language server client implementation for VS Code (uses the former)
3. The language server protocol (implemented by the former)

**Comment by dbaeumer** [comment]
I updated the spec. The problem is that the spec itself can't even define when this action is triggered since it depends on the client side which must not necessarily be VS Code. So I change it to:

> The code action request is sent from the client to the server to compute commands for a given text document and range. These commands are typically code fixes to either fix problems or to beautify/refactor code.
