### ISSUE TITLE
List typst under "implementations" on webpage

### ISSUE THREAD

**Issue by KronosTheLate** [microsoft/language-server-protocol#1811]
On [this page](https://microsoft.github.io/language-server-protocol/implementors/servers/) I am missing [typst-lsp](https://github.com/nvarner/typst-lsp). I believe it should be listed there, no?

**Comment by dbaeumer** [comment]
This page is maintained by the community using PRs. See 

<img width="544" alt="image" src="https://github.com/microsoft/language-server-protocol/assets/1931590/a5f7600d-3097-48e5-9869-35caa711c85b">

Can you provide one?

**Comment by KronosTheLate** [comment]
Sure! Thanks for the pointer ^_^
