### ISSUE TITLE
Interactive edit operations

### ISSUE THREAD

**Issue by vinistock** [microsoft/language-server-protocol#1822]
For dynamic languages, such as Ruby, it's often not possible to provide accurate renaming functionality. The classic example is if we have a method invocation on a receiver we do not know the type of.

```ruby
# File 1
class Post
  def title # trigger a rename `title` -> `name`
    # ...
  end
end

# Some other file

# If we can't figure out the type of `foo` statically, there's no way to be sure if we're
# renaming the method title accurately - which is often the case
foo.title
```

I was wondering if it would be feasible (and desired) to have some sort of interactive renaming operation, where the developer would be presented with each possible occurrence and then decide if they wish to go ahead with the renaming or not.

I feel like it would still provide a lot of value. Even though it's not fully automated, the LSP can still ensure that only method invocations that match the correct arity are being returned as results. And developers would be more confident in these operations since they get a chance to review them.

What I'm thinking is something like Copilot's inline diff, with accept or reject buttons and then the editor would basically iterate through each "change suggestion" showing that to the developer.

<img width="848" alt="image" src="https://github.com/microsoft/language-server-protocol/assets/18742907/88059eeb-4a84-47b6-a229-f31443586cbb">

In terms of the LSP response, they could use a boolean flag in `TextEdit` to indicate that the certain edits are imprecise and require review from the developer. If this idea is desired, it may be applicable to other LSP features that also use `TextEdit` in cases where the operation cannot be guaranteed to be accurate.

**Comment by DanTup** [comment]
`AnnotatedEdit`s (https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textEdit) might do what you want? There's a boolean `needsConfirmation` that tells the client those edits need to be confirmed. In VS Code, this shows a list/tree of all of the edits and allows the user to tick/untick them (and see a diff of what they are).

**Comment by vinistock** [comment]
@DanTup thank you for pointing me to that! I totally missed the annotated edits type, which is indeed supported by `WorkspaceEdit`.

I'll experiment with that to confirm, but it does look like that's exactly what we need. I'll report back and close this issue after confirming.

**Comment by dbaeumer** [comment]
@DanTup thanks for the great answer.

**Comment by vinistock** [comment]
This is indeed what we were looking for. Thanks for the precise information!
