### ISSUE TITLE
Output Channel API Incomplete for Language Servers

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/language-server-protocol#184]
_From @hoovercj on February 11, 2017 15:0_

- VSCode Version: 1.9.1
- OS Version: Windows

I have a language server extension and I'd like to write logs.

My understanding is this:
1. The server recieves an IConnection object which has a console and a window. The window can show info/warning/error messages and the console can log to the chrome dev console, but neither offer access to output channels
2. The server can use a "normal" console.log (not the console from the IConnection object) which will manifest in the VS Code UI as an output channel with the name that the server was initialized with. However, there is no handle to the output channel available in the language server so it cannot be shown, for example when an error is logged.
3. The client can create an output channel and the server can route all logs to it as `requests`. Then all events that would need to open/close the channel also need to be manually routed to the client through `requests` or included as parameters in the log request. This seems like an unnecessary amount of boilerplate and indirection just to do basic logging.

Since it appears that an output channel is being created for the language server anyway as described in item 2, it should be exposed as part of the API and/or additional API functions should be added to support output channels in language servers

_Copied from original issue: Microsoft/vscode#20477_

**Comment by hoovercj** [comment]
> This is actually on purpose since there are two separate output channels both having the same label. I agree that we should do something about the labels but output channels can't be shared passed on labels.

In the original bug, I didn't actually expect that using the same label would cause them to use the same channel, it was more of a desperation effort. However, I didn't expect it to behave as it does: If two extensions were to create an output channel with the same label, I believe that VS Code would get confused and only show the output from the one that logged last. I can imagine that two developers would create extensions with channels that have a generic name "Extension Output".

To make sure the behavior is clear:
* There are two output channels with the same name in the drop down
* It doesn't matter which one you select in the UI, the output pane will always show the output from the output channel that output last.

**Comment by hoovercj** [comment]
> On which version of the library are you. In 3.0.x version of the libraries all IConnection.console.log notification should appear in the output channel managed by the client.

Good question. I have `"vscode-languageserver": "2.2.0"`, so it looks like I've fallen behind :-)

I should update and see if things work better for me now.

To make sure I understand, If I update:
* If I use normal console.log from the server, it will continue to appear in an output channel as it does now. This output channel will have the same name as the server was initialized with
* If I use IConnection.console.log from my server, it will **also** automatically appear in an output channel? Which channel?

My use case is that I'd like to have a status bar icon, and if there is an error the icon will show it, and if you click on the icon then the output channel will open to see the error logs.

The logs will originate from the server, but I have no way of opening the output pane because I have no handle to the output channel to open.

**Comment by dbaeumer** [comment]
@hoovercj sorry for the late answer. Here is what is happening:

- if the transport is stdio then the server writing to console.log will mess with the protocol since the client will read that as a JSON RPC message and will very likely choke on the content.
- if the transport is NOT stdio then console.log write to the stdout of the server process. The client process listens on stdout, stderr and forwards it to the servers output channel.
- if you use connection.console then it always appears in the output channel even if transport is stdio since IConnection.console uses JSON RPC to communicate with the client

If you want to have a status bar item you can look how vscode-eslint does this. The extension uses some custom messages to let the server talk to the client status bar item since this is not part of the LSP.

I will close the issue. Please ping if there is still something unclear.
