### ISSUE TITLE
Clarify docs: deltaLine and deltaStart fields of semantic tokens relate to the _start_ of the previous token

### ISSUE THREAD

**Issue by StachuDotNet** [microsoft/language-server-protocol#1855]
In writing an LSP-based language server, I've recently fumbled for a while assuming that these fields related to the _end_ of any previous token. The highlighting _just wasn't working_ the way I expected to, because of this assumption.

I now understand why the format is the way it is - to support overlapping tokens, in the languages those are relevant, but this wasn't obvious to me.

I'd be happy to update relevant pieces of docs via PRs.

I know of 2 relevant places to update:
- [x] in these lines of the spec:
  ```
  at index 5*i - deltaLine: token line number, relative to the previous token
  at index 5*i+1 - deltaStart: token start character, relative to the previous token (relative to 0 or the previous token’s start if they are on the same line)
  ```
  
  (simply adding wording like "relative to **the start of** the previous token...")

- [ ] ~~the de facto Node sample~~

any other places that would be useful to clarify in?

**Comment by dbaeumer** [comment]
Looks good to me.

**Comment by StachuDotNet** [comment]
Thanks for the response, I'll get to it tonight.

**Comment by StachuDotNet** [comment]
Finally got around to this in #1966 - I thought there'd be mention of `deltaLine` and such in `vscode-languageserver-node` as well, but seems not.
