### ISSUE TITLE
MetaModel: Missing Types and `TraceValue` vs `TraceValues`

### ISSUE THREAD

**Issue by yxrkt** [microsoft/language-server-protocol#1861]
`Message`, `MessageDirection`, `NotificationMessage`, `RequestMessage`, `ResponseMessage`, and `ResponseError` are missing from `metaModel.json`.

Also a very minor discrepancy: In the spec, it is called `TraceValue`. In `metaModel.json`, it is called `TraceValues`.

**Comment by dbaeumer** [comment]
The tyes are not in the meta model since they are concepts that come from JSON-RPC and might differ depending on the JSON RPC library you are using.

I did fix the `TraceValue` problem.

**Comment by yxrkt** [comment]
I just noticed `URI` and `DocumentUri` are missing. I suspect these aren't part of JSON-RPC?
