### ISSUE TITLE
Range property in TextDocumentContentChangeEvent inconsistent with comment

### ISSUE THREAD

**Issue by leitzler** [microsoft/language-server-protocol#1870]
In TextDocumentContentChangeEvent, the Range property isn't optional:
https://github.com/microsoft/language-server-protocol/blob/80b9d4afb6c60a5e19d8c2faee3e5b28cfb50735/_specifications/lsp/3.18/textDocument/didChange.md?plain=1#L74 

But the comment above do state that the event can be sent with only `text`:
```
/**
 * An event describing a change to a text document. If only a text is provided
 * it is considered to be the full content of the document.
 */
```

**Comment by dbaeumer** [comment]
This is covered by the OR type 

```ts
| {
	/**
	 * The new text of the whole document.
	 */
	text: string;
}
```
