### ISSUE TITLE
Command line utility for lsp client

### ISSUE THREAD

**Issue by Anjali05** [microsoft/language-server-protocol#1884]
Hi, 

Can I invoke lsp via a client from the command line? I am working on a static analyzer and was wondering if I can use it like cscope from the command line. I have been using cscope but it has some limitations. For example, for making a function call graph from a start symbol cscope fails to work for certain functions with complex definitions such as (https://elixir.bootlin.com/linux/v6.1/source/drivers/tty/tty_io.c#L957 ) and (https://elixir.bootlin.com/linux/v6.1/source/kernel/cgroup/cgroup.c#L6565). I have looking for a capability similar to `cscope -dL2 <function symbol>` that lists all the function calls made from the passed function symbol.

Any help/insight into this will be appreciated. Thanks in advance!

**Comment by dbaeumer** [comment]
We don't maintain such a command line tool but it could be built on top of the vscode-languageserver-protocol npm package.
