### ISSUE TITLE
Clarify units of "character offset" in Position

### ISSUE THREAD

**Issue by raphlinus** [Microsoft/language-server-protocol#19]
The `character` field in a Position structure is defined as a zero-based character offset relative to the start of the line. In the case of non-ASCII source, I believe it should be clarified, as "character" doesn't have a universal definition. I'm guessing it's most likely UTF-16 code units, but it could just as easily be Unicode codepoints or something else. Mismatched units could lead to unfortunate errors in identifying ranges in the text.

**Comment by dbaeumer** [comment]
Make sense to be clarified.

**Comment by alexandrudima** [comment]
@dbaeumer I don't know how you'd like to spec it at the language protocol level and/or if you'd want to make it UTF8 indices for greater interop.

In a vscode extensions, the `Position.character` represents the gap between two characters in a line (or the position before or after the line) via UTF-16 indices.

e.g.

```
Given:
- visible string: a📚b
- unicode points: U+0061 U+1F4DA U+0062
- (hex) UTF16 LE : 61 00 3D D8 DA DC 62 00
- (hex) UTF16 BE : 00 61 D8 3D DC DA 00 62
- (hex) UTF8     : 61 F0 9F 93 9A 62

in vscode, where x is the line:
- position (x,0): |a📚b - this is the position before the first character
- position (x,1): a|📚b - this is the position between U+0061 and U+1F4DA
- position (x,2): a|📚b - this position will be validated and coerced to be the position between U+0061 and U+1F4DA
- position (x,3): a📚|b - this is the position between U+1F4DA and U+0062
- position (x,4): a📚b| - this is the position after the last character

This is mostly driven by our runtime, JavaScript.
```

**Comment by dbaeumer** [comment]
@alexandrudima thanks a lot. To my understand this position is therefore independent of the encoding.

**Comment by dbaeumer** [comment]
Reading about it I get the following understanding:

```
a𐐀b 
```

This string consists of 3 character. In UTF-16 it has 3 code points and 4 code units (the 𐐀 is represented as two code units).

**Comment by dbaeumer** [comment]
Add additional comments. Happy to accept a PR if further clarification is necessary.

**Comment by raphlinus** [comment]
I don't consider this closed, I still don't know what the answer is. I'm fine with defining it to be UTF-16 to be consistent with existing impls, but whatever it is the spec should say, and then everybody implementing it should be consistent.

**Comment by dbaeumer** [comment]
@raphlinus you are correct. I have added the following to the spec:

```
The offsets are based on a UTF-16 string representation. So a string of the form `a𐐀b` the character offset of the character `a` is 0, the character offset of `𐐀` is 1 and the character offset of b is 3 since `𐐀` is represented using two code units in UTF-16. To ensure that both client and server split the string into the same line representation the protocol specifies the following end-of-line sequences: '\n', '\r\n' and '\r'.
```
