### ISSUE TITLE
Add support for handling moved files

### ISSUE THREAD

**Issue by Pajn** [Microsoft/language-server-protocol#191]
When a file is moved or renamed many languages would need to update import paths and maybe even symbol names.
I can't see a good way to handle that with the current API, would it be possible to add a request for that?

**Comment by dbaeumer** [comment]
Yes, it makes sense to provide a move refactoring request.

**Comment by fbricon** [comment]
We're gonna need that feature for Java support (eclipse/eclipse.jdt.ls#363). Any way to prioritize this? cc @aeschli @akaroml?

**Comment by dbaeumer** [comment]
The best way to speed this up is to provide a PR. But this needs to happen in the protocol,  the node libraries and very likely in VS Code as well.

**Comment by dbaeumer** [comment]
Closing in favor of #272
