### ISSUE TITLE
Metamodel: Mixins vs Extends discrepancy 

### ISSUE THREAD

**Issue by TheAngryByrd** [microsoft/language-server-protocol#1933]
👋 Hey there. I'm working on a [generator for F# types](https://github.com/ionide/LanguageServerProtocol/pull/49) using the metamodel. I'm nearly there, however I've run into a what I think may be an discrepancy with the `metamodel`.

There are some types that are listed as `extends` in the [LSP Spec](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification) page but are listed as `mixins` in the [metamodel](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/metaModel/metaModel.json).

---

For brevity the definitions of these are:

- extends: "Structures extended from. This structures form a polymorphic type hierarchy."
- mixins: "Structures to mix in. The properties of these structures are `copied` into this structure. Mixins don't form a polymorphic type hierarchy in LSP."

---

Example of discrepancy:

[ImplementationOption](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#implementationOptions) lists `WorkDoneProgressOptions` in the sepc:

```ts
export interface ImplementationOptions extends WorkDoneProgressOptions {
}
```
but in the metamodel it's listed as a mixin:

```json
{
    "name": "ImplementationOptions",
    "properties": [],
    "mixins": [
        {
            "kind": "reference",
            "name": "WorkDoneProgressOptions"
        }
    ]
},
```

There's also a similar situation for `WorkDoneProgressParams`.  

---

I'm unsure which is the case, maybe this is my misunderstanding about typescript in general.

Any guidance would be appreciated. Thanks!

**Comment by dbaeumer** [comment]
The reason for this is that when we started this TypeScript had only interfaces and no type defs and `&` types. So some of the definitions are like this for legacy reasons, however the meta mode should express them correctly.
