### ISSUE TITLE
Consistency in null/void/undefined result types

### ISSUE THREAD

**Issue by ljw1004** [Microsoft/language-server-protocol#194]
The result types `undefined`, `void` and `null` are all used in the spec. I don't think that `undefined` or `void` are valid JSON values...

I'd like clarification on whether, in these cases
* the result field should be absent 
* the result field can be absent or not; the client won't care
* the result field should be present and `null`

```
method "shutdown"
Response result: undefined

method "client/registerCapability"
Response result: void

method "textDocument/documentLink"
Response result: an array of DocumentLink, or null
```

**Comment by dbaeumer** [comment]
Good point.

Undefined is not valid on the protocol level and it is never sent. Since it confuses people to see undefined (since in JS it is a well known value) I will use void for the absence.

**Comment by dbaeumer** [comment]
Regarding the result field: By JSON RPC spec it must be present in case of a successful request. So it must be null. In the jsonrpc library I maintain I set the result to null even if the handler returns undefined.
