### ISSUE TITLE
Clarification: what happens with exit notification prior to Initialize request

### ISSUE THREAD

**Issue by ljw1004** [Microsoft/language-server-protocol#195]
In the **Initialize Request** section, the spec says: *"If the server receives notification before the initialize request, it should drop the notification"*

In the **Exit notification** section, the spec says *"The server should exit with success code 0 if the shutdown request has been received before; otherwise with error code 1."*

If we receive an exit notification prior to the initialize request, should we obey the first rule (by dropping it) or the second rule (by exiting with error code 1) ?

**Comment by dbaeumer** [comment]
Good point. Decided to allow exit without initialize.
