### ISSUE TITLE
No way to respond to malformed message

### ISSUE THREAD

**Issue by ljw1004** [Microsoft/language-server-protocol#196]
Suppose the server receives an invalid json `{"foo": "bar"}` which lacks `jsonrpc` and `method` and `id`.

(Per the spec this isn't a Message because it lacks the required field `jsonrpc`, and its not a RequestMessage because it lacks the field `id`, and it's not even a Notification because it lacks the field `method`).

I'd ideally like it to respond back with this ResponseMessage:
```
{
  "jsonrpc":"2.0",
  "error": { "code":-32700, "message":"parse error" }
}
```

However this response isn't allowed per the spec. That's because the spec only defines responses for when it has a valid `id`. It doesn't even allow responses for notifications (which lack `id`).

What can we do? I think the spec should change its definition of ResponseMessage to allow `id` field to be either ABSENT or NULL in the case where it wants to report an error back to the client but wasn't given an id. (I'm not sure whether absent or null would be more idiomatic json).

**Comment by dbaeumer** [comment]
The JSON RPC protocol allows NULL for the id for handling error cases. I updated the protocol and the client library if a response is received without an id.

**Comment by ljw1004** [comment]
If the server receives a *notification* which it doesn't recognize, should it send back a ResponseError with `id=null` ?

(or is this `id=null` ResponseError reserved solely for responses to requests?)

**Comment by dbaeumer** [comment]
To my interpretation of the JSON RPC spec a malformed notification can't single anything back. A malformed request can send a response back with id=null in case the id couldn't be parsed from the request.
