### ISSUE TITLE
How to distinguish a request from a notification?

### ISSUE THREAD

**Issue by ljw1004** [Microsoft/language-server-protocol#197]
If the language server receives a request which is missing an ID e.g. `{jsonrpc:"2.0", method:"initialize", params:...}` should it

* treat it as a *request*, based on knowing that 'initialize' method is a request? -- If it's a request that the server can't parse then the server is supposed to send back a ResponseError with null id.
* treat it as a *notification*, based on the absence of an `id` field? -- If it's a notification that the server can't parse, then as far as I can tell the server isn't supposed to send back a ResponseError.

What if the language server receives `{jsonrpc:"2.0", method:"unknown", params:...}` or `{jsonrpc:"2.0", method:"unknown", id:1, params:...}` -- should it decide whether it's a request (deserving of ResponseError) based solely on the presence or absence of an `id` field?

These examples are to piece together the algorithm a server should use for deciding how to dispatch a message...

**ALGORITHM CHOICE 1:**
1. If it's a known method name, then dispatch it based solely on the method name. Any ResponseErrors that might be generated from requests should use the "id" field if available, or otherwise synthesize a null id.
2. If it's an unknown method name, then judge whether it's a request or notification based on the presence of the id field, and only produce ResponseError in the case of requests.

**ALGORITHM CHOICE 2:**
1. Judge whether it's a request or notification based on the presence/absence of the id field
2. Dispatch based on a combination of name AND request/notification boolean. (For example, if we get a message `{jsonrpc:"2.0", method:"initialize", params:...}` then it counts as a notification and so doesn't count as an InitializeRequest and so doesn't get dispatched).
3. For anything which fails to dispatch, then produce a ResponseError in the case of requests.

I guess another possible answer is that "servers should send back ResponseError even in the case of notifications, and in this case they should use either the ID if it was provided (which might happen in the case of Algorithm1), or synthesize a NULL id otherwise.

**Comment by dbaeumer** [comment]
IMO the JSON RPC spec defines this quite well:

id: An identifier established by the Client that MUST contain a String, Number, or NULL value if included. If it is not included it is assumed to be a notification. The value SHOULD normally not be Null [1] and Numbers SHOULD NOT contain fractional parts [2]

So a server should interpret a JSON message without an id and a notification.

And For response:

Response object: When a rpc call is made, the Server MUST reply with a Response, except for in the case of Notifications. 

So I would say an unknown notification can't send a response back. 

So in our code we don't look at the method to decide whether something is a request or a notification. We simply decide on the id field. 

So the open question for me is what do we do with unknown notifications and do we need to signal something back to the client with a know notification sendable from server to the client. In our server we usually log unknown notification and request and the default log behavior is to log to the client output window associated with the server (e.g using the server -> client notification 'window/logMessage')

**Comment by dbaeumer** [comment]
I will close. @ljw1004 please ping if something is still unclear.

**Comment by ljw1004** [comment]
Everything's clear. Thank you @dbaeumer.
