### ISSUE TITLE
ERR_SOCKET_CLOSED_BEFORE_CONNECTION could not start Language Server

### ISSUE THREAD

**Issue by tiltue** [microsoft/language-server-protocol#2005]
When I try to start my Language Server in my VS Code extension, this error appears. I am using the recommended versions of the npm packages. Did someone experience anything similar? Any help is appreciated, thank you!

![image](https://github.com/user-attachments/assets/c3941956-7d73-4411-8c2a-38536494847f)

**Comment by dbaeumer** [comment]
@tiltue this is very likely caused by the same underlying problem mentioned in https://github.com/microsoft/vscode-languageserver-node/issues/1545

**Comment by tiltue** [comment]
> @tiltue this is very likely caused by the same underlying problem mentioned in [microsoft/vscode-languageserver-node#1545](https://github.com/microsoft/vscode-languageserver-node/issues/1545)

I don't think so, I fixed the spawn EINVAL caused by node, but the Language Server still does not start. 
![image](https://github.com/user-attachments/assets/46d2ec85-2bb6-4d4f-b64c-d1af6a6bf757)
When I debug the server and inspect the error messages, they are equivalent to those in this issue.
What could cause this error? I am very grateful for any help!
