### ISSUE TITLE
Publish diagnostics should support versioned text document.

### ISSUE THREAD

**Issue by tinaschrepfer** [microsoft/language-server-protocol#201]
Publish diagnostics request currently doesn't have support for versioned text document.  It would be great if we could add versioning support so clients can do version translation if they can.

**Comment by rcjsuen** [comment]
@dbaeumer Would it be enough to just add an optional `version` field to `PublishDiagnosticsParams`? I don't think we would even have to change the capabilities in any way. Servers can just choose to send it out or not.

**Comment by dbaeumer** [comment]
Correct. I added an optional version.

**Comment by dbaeumer** [comment]
Updated spec on dbaeumer/3.15 branch.
