### ISSUE TITLE
Only one DidChangeTextDocument notification sent during batch edits such as search-and-replace

### ISSUE THREAD

**Issue by vazexqi** [Microsoft/language-server-protocol#203]
I am trying to understand the specification for [textDocument/didChange](https://github.com/Microsoft/language-server-protocol/blob/master/versions/protocol-2-x.md#textDocument_didChange) from Version 2.x of the spec.

I thought that a separate notification would be sent for each textChange. And that does happen when you edit each file individually. But, when you edit the files in batch (like with a search-and-replace), it only sends notification (for a _random_  file in the batch). 

I have been trying this with Visual Studio Code (Insiders) as the reference client implementation. I am not sure if this is a bug in vscode or if this is the behavior of the spec, hence the question.

Repro steps:

1. Download https://github.com/Microsoft/vscode-languageserver-node-example
1. Modify server.ts so that it logs for all the different text/* notifications.
1. You should be able to see all the log in the debug console in the **host** window.
1. In the **extension** window, open two .txt files side-by-side.
1. Do a search-and-replace.
1. Notice that you only get one textDocument/didChange notification, and it seems random which file is picked. In the screenshot below, file1.txt tab seems to be in focused, but it is file2.txt that is sent across.

<img width="1440" alt="screen shot 2017-03-18 at 11 17 15 am" src="https://cloud.githubusercontent.com/assets/54414/24074843/cfee8c34-0bcd-11e7-8da1-34e57f73cd5a.png">

You can watch the steps at https://vimeo.com/208995328

On the other hand, if you did a Save All, you get **two** textDocument/didSave notifications.

<img width="1440" alt="screen shot 2017-03-18 at 11 18 19 am" src="https://cloud.githubusercontent.com/assets/54414/24074861/3fc7bbac-0bce-11e7-84e9-1feb266eec32.png">

You can watch the steps at https://vimeo.com/208995307

**Questions**:

1. Is this working-as-designed (WAD) or a bug?
1. If this is WAD, could you shed some light on how the client picks which file out of the batch to report back?
1. If this is WAD, how would we handle detecting that changes have occurred in multiple files? Would workspace/didChangeWatchedFiles per used here?

**Comment by dbaeumer** [comment]
The design for this is as follows:

- you only get content change events for documents for which you received a open event before
- for documents that are not open (no open event is sent) the truth is on the file system and you can get file system events for that.

In our example are you missing any change events for documents for which you received an open event before. If so please open a bug against vscode-languageservernode with steps to reproduce.

**Comment by vazexqi** [comment]
Thanks for the explanation.

It does look to be a bug. I do get **two** open events but only _one_ change event. If you look at the first screenshot above, you see

file:///Users/nchen/Desktop/vscode-example/file2.txt opened.
file:///Users/nchen/Desktop/vscode-example/file1.txt opened.

which comes from the logging I did on 

```
connection.onDidOpenTextDocument(function (params) {
    // A text document got opened in VSCode.
    connection.console.log(params.textDocument.uri + " opened.");
});
```

I'll file a bug against vscode-languageservernode and link this item to it.

**Comment by dbaeumer** [comment]
@vazexqi if I understand your comment in https://github.com/Microsoft/vscode-languageserver-node/issues/133 then this is now working for you after updating to the latest version of the library. Right?

**Comment by vazexqi** [comment]
Yup, it's working on the latest version of the library.
