### ISSUE TITLE
nest language server

### ISSUE THREAD

**Issue by asukaminato0721** [microsoft/language-server-protocol#2038]
for example, in bash we use awk

shell highlight, but here the string is string

```sh
awk '{print $3 "\t" $4}'
```

vs awk highlight.

```awk
awk '{print $3 "\t" $4}'
```

If we write a single awk file, we can use awk language server.

in some limited cases, is it possible to use multiple lsps in one file?

in above example, when cursor outside string, bash lsp, inside string, awk lsp.

**Comment by dbaeumer** [comment]
See comment here: https://github.com/microsoft/language-server-protocol/issues/1252#issuecomment-953748832

I am still open for support of implementing support to 

- delegate things back to the client
- a general FS API
