### ISSUE TITLE
Diagnostics for notebook

### ISSUE THREAD

**Issue by mtshiba** [microsoft/language-server-protocol#2040]
I am developing a language server for Python ([pylyzer](https://github.com/mtshiba/pylyzer)).
Since LSP v3.17 now supports [notebook documents](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#notebookDocument_synchronization), I would like to implement Jupyter Notebook support for pylyzer.

As a result of my trials, I was able to get a `notebookDocument/didOpen` notification from the client (VSCode), but even if I send diagnostics, the error location does not seem to be highlighted. How can I specify the range of diagnostics on the notebook?
Or is this impossible to achieve with the current LSP? If so, are there plans to define specs for this and support it?
(Also, it seems that language service requests are not currently sent for notebooks, are there also plans to define specs and support them?)

**Comment by dbaeumer** [comment]
Actually that should work. Do you use push or pull diagnostics. If you use push, you need to push them on the notebook cell document not the notebook itself.

**Comment by mtshiba** [comment]
I found the cause. It seems that the URIs of notebook cells have fragments. I was normalizing the URIs by lowercasing them on systems with case-insensitive file systems, but I shouldn't do this with URIs that have fragments.

Diagnostics now display correctly. Thanks.

**Comment by dbaeumer** [comment]
@mtshiba great to hear you got it working. Will close the issue
