### ISSUE TITLE
Why does DocumentOnTypeFormattingOptions have "firstTriggerCharacter"

### ISSUE THREAD

**Issue by tsmaeder** [Microsoft/language-server-protocol#206]
...and "moreTriggerCharacters", instead of just a list of trigger characters?

**Comment by dbaeumer** [comment]
@jrieken any explanation.

**Comment by jrieken** [comment]
Yes, it var-args but at least one character is required. Then you declare signatures like so `foo(first:number, ...more:number[])`

**Comment by dbaeumer** [comment]
Closing then. @tsmaeder please ping if you need more clarification.
