### ISSUE TITLE
Solidity LSP

### ISSUE THREAD

**Issue by NalinDalal** [microsoft/language-server-protocol#2063]
See i am a NeoVim User, also working on solidity
I don't see anything for solidity, can we please add it

**Comment by rcjsuen** [comment]
@NalinDalal You can submit a pull request that modifies [this file](https://github.com/microsoft/language-server-protocol/blob/90e7853d94397d4ff1872bc56b7d74408d21af18/_implementors/servers.md). That should get it added to the list.

**Comment by dbaeumer** [comment]
@rcjsuen thanks for jumping in. I will close the issue. Looking forward to the PR.
