### ISSUE TITLE
glob syntax is not defined

### ISSUE THREAD

**Issue by tromey** [Microsoft/language-server-protocol#208]
The spec refers to globbing in the `DocumentFilter` section, giving the examples `**/package.json` and `*.{ts,js}`.  However, the complete syntax of valid globs is neither defined nor referenced.  It would be useful to know exactly what syntax must be supported here.

**Comment by tsufeki** [comment]
This also applies to globs in `DidChangeWatchedFilesRegistrationOptions`.
