### ISSUE TITLE
Add example of URIs per OS

### ISSUE THREAD

**Issue by mickaelistria** [Microsoft/language-server-protocol#209]
The RFC-3986 is unfortunately not implemented by Java URIs ( https://bugs.openjdk.java.net/browse/JDK-8019345 ). In order to help client servers written in Java, or any other language that doesn't support this RFC-3986 natively, it would be nice to add a couple of examples of what typical `file:` URIs would look like on various OSs.

**Comment by dbaeumer** [comment]
Agree, would be cool. Good opportunity for a PR.

**Comment by dbaeumer** [comment]
There is now some basic documentation about URI in the protocol.md. If more is need I am still happy to merge a PR.
