### ISSUE TITLE
Clarify how server lifetime is handled

### ISSUE THREAD

**Issue by r4nt** [Microsoft/language-server-protocol#21]
Alternatively, it would help to clarify that it's out of scope and link to how current clients do it. Although it seems that it's somewhat in scope, given that shutdown and exit are implemented commands.
Especially: who is responsible for starting a language server (per user? per project? per workspace?)

**Comment by dbaeumer** [comment]
Makes perfect sense to clarify.

**Comment by dbaeumer** [comment]
Added

#### Server lifetime

The current protocol specification defines that the lifetime of a server is managed by the client (e.g. a tool like VS Code or Emacs). It is up to the client to decide when to start (process vise) and when to shutdown a server.
