### ISSUE TITLE
Consider switching from JSON-RPC to binary format which supports random read access

### ISSUE THREAD

**Issue by mzaks** [microsoft/language-server-protocol#211]
Binary format's like Cap'nProto or FlatBuffers are designed in a way that client can read values out of the payload without any parsing or even unmarshalling step. The payloads are designed for random value access.
A command like __Completion Request__ would benefit greatly from such format, as a completion request contains an array of `CompletionItem`s. With JSON-RPC, in order to display completion suggestion, the client has to parse the whole payload and transformed it into intermediate model. If the payload would be encoded with something like FlatBuffers or Cap'nProto, client could keep the payload as is and just access the data directly in a "paged" fashion (e.g. give me completion item 23, 24, 26, 27). As completion results can become quite big, I believe it could improve the client UX a lot.

**Comment by dbaeumer** [comment]
Agree but this adds additional bars to the implementor of a language server. Currently a server can be implemented in any language and most of them do have libraries for JSON. If we go with binary encoding we need to ensure that libs are available for the major programming languages.

**Comment by mzaks** [comment]
@dbaeumer thank you for considering this proposal.

I think first of all, we have to define which languages fall into major programming languages.

FlatBuffers and Cap'nProto currently cover: Java, JavaScript, C, C++, C#, Go, Python etc.
But there are still lots of languages which are not covered.

Second, I think this step would have to be implemented gradually.
An efficient binary protocol has to be defined as an optional choice.
JSON-RPC has to be the mandatory protocol for now. However the servers can provide a more efficient binary interface which clients can chose to implement.

To make the adoption more appealing, code generators can be provided, which generate coherent encoders and accessors for JSON and binary data, for major programming languages. But than again we need to pin down the list of those :)

**Comment by dbaeumer** [comment]
Agree that this can only be a opt in. I first step IMO would be to have the protocol specified in JSON schema (which I do have a request for and I started some work on converting the .d.ts files we have into JSON schema automatically). We could then use the JSON schema as a source to generate specifications for binary format.

A list of server implementations can be found here: https://github.com/Microsoft/language-server-protocol/issues/8

**Comment by mzaks** [comment]
@dbaeumer That makes sense. 
I see there are some exotic like Haxe, Rust and Haskell, but I think it should not be a very big problem.
