### ISSUE TITLE
Standardize language ids.

### ISSUE THREAD

**Issue by ljw1004** [Microsoft/language-server-protocol#213]
```
// The text document's language identifier.
languageId: string;
```

What is the languageId field for? Who uses it? Can the client happily omit it? What kind of behavior are language servers expected to take based upon it? Are there a mandated set of values which can be used?

As I write a client, I have no idea what to send for this field, so I'd kind of like to send nothing at all. But maybe existing language servers make assumptions that languageId exposes some kind of implementation details of VSCode.

**Comment by dbaeumer** [comment]
You are correct about standardizing these values. The idea behind this is that a file extension might not be the right thing to infer a language mode and most editors already have such a mapping (they usually have a language switcher which toggles the syntax highlighting to use). So the client can tell the server under which language it operates on the text document

I will keep the issue since we should standardize a common set of language mode ids. Ideas are to use a strings or a mime type based encoding.

**Comment by aeschli** [comment]
Note that for VSCode we created https://code.visualstudio.com/docs/languages/identifiers as a registry of language ids.

**Comment by mickaelistria** [comment]
As the protocol refers to GitHub language ids in MarkedString, it would be great to also use those everywhere else in the protocol for consistency.

**Comment by dbaeumer** [comment]
Lets take the VS Code list as a starting point. I am open to tweak the list if there is a reason. The open question is what we should send if the language id used in the tool is not know to the LSP. Options are unknown or `null`. I tend to send `null`. 

Language | Identifier
-------- | ----------
Windows Bat | `bat`
BibTeX | `bibtex`
Clojure | `clojure`
Coffeescript | `coffeescript`
C | `c`
C++ | `cpp`
C# | `csharp`
CSS | `css`
Diff | `diff`
Dockerfile | `dockerfile`
F# | `fsharp`
Git | `git-commit` and `git-rebase`
Go | `go`
Groovy | `groovy`
Handlebars | `handlebars`
HTML | `html`
Ini | `ini`
Java | `java`
JavaScript | `javascript`
JSON | `json`
LaTeX | `latex`
Less | `less`
Lua | `lua`
Makefile | `makefile`
Markdown | `markdown`
Objective-C | `objective-c`
Objective-C++ | `objective-cpp`
Perl | `perl` and `perl6`
PHP | `php`
Powershell | `powershell`
Pug | `jade`
Python | `python`
R | `r`
Razor (cshtml) | `razor`
Ruby | `ruby`
Rust | `rust`
Sass | `scss` (syntax using curly brackets), `sass` (indented syntax)
ShaderLab | `shaderlab`
Shell Script (Bash) | `shellscript`
SQL | `sql`
Swift | `swift`
TypeScript | `typescript`
TeX | `tex`
Visual Basic | `vb`
XML | `xml`
XSL | `xsl`
YAML | `yaml`

**Comment by dbaeumer** [comment]
I will move the ids into the spec for now.
