### ISSUE TITLE
Clarify the use of InitializationError.retry

### ISSUE THREAD

**Issue by ljw1004** [Microsoft/language-server-protocol#215]
I was wondering whether the retry flag could be used to control whether the client *automatically* retries to launch the LSP server in the event of failure. [Answer: no].

PROPOSAL: the docs for the retry flag currently say "Indicates whether the client should retry to send the initialize request after showing the message provided". It should instead say "... whether the client should __invite the user__ to retry..."

I'm basing this off current VSCode behavior. When VSCode receives an error from the `initialize` method, it always displays a banner, and the retry flag solely determines whether the banner has 'Close' or 'Retry|Close' buttons.

I imagine that all LSP servers will end up assuming this behavior of the flag: no server will use the flag to indicate whether an _automatic retry_ should take place. And so clients should never use the flag to initiate an automatic retry either.

**Comment by dbaeumer** [comment]
@ljw1004 thanks. This is correct. However with the dynamic registration retying something is almost not needed anymore since handlers can be registered dynamically and don't need to come on initialize. But for backwards compatibility I will update the doc.

**Comment by ljw1004** [comment]
I'm working on a few different scenarios where retrying is useful...

__Crash__. Maybe some corner-case caused the LSP process to crash. Or maybe, as in our case with huge codebases, the server ends up taking 20+GB and sometimes freezes (so the user does pkill to terminate it) or sometimes gets an out-of-memory exception. I'd like to have the editor automatically reload the LSP server in this case, rather than requiring the user to do it manually.

__Pull__. We check in our compiler toolchain (including LSP server) into our source control. When someone pulls a new version, it will get the latest compiler and the latest LSP server binary, potentially causing running instances of either to terminate. I don't want to force the user to have to reload their project in their editor just because of doing a pull. So, I'll make the editor relaunch the LSP server automatically.

__Slow startup__. Our projects are huge, so the server can sometimes take 10+ minutes to initialize and do the binding+indexing necessary to deliver even the simplest language services. We could do this by having the server only register after it's finished its initialization, as you suggest. Or we could have the initialize method return an error and rely upon the editor to automatically retry. Or we could have the initialize method succeed immediately and have all the other LSP actions fail until it's ready. Or we could have the initialize method wait for those 10+ minutes before responding. (All solutions would need some kind of progress reporting as well). @dbaeumer -- do you think that "dynamic registration" is way to achieve this most in keeping with the LSP spirit?

__Singleton__. Because our projects are huge, we actually have just a singleton language server on the entire machine which runs persistently in the background; our LSP server merely connects to it. What this means is that if two editor instances wish to connect to the same project, only one of them can (since only one of them can hold the "source of truth" for an open document). We drive this by which editor has focus: when an editor gets focus, it relaunches its LSP server if necessary, and signals the other LSP servers to terminate.



These are all cases where we might want an *automatic* retry for launching the LSP server. So, I wanted to know whether we could use the "InitializeError.retry" LSP flag to guide whether automatic retry should happen.

I see that the current behavior of VSCode, in cases where the LSP server process terminates, is just to carry on regardless with no indication to the user. All the user knows is that for some mysterious reason they no longer get intellisense or hover or other language smarts.

Anyway, given how VSCode surfaces the Initialize.retry flag right now, I think we can't use this flag to control *automatic* retry. So, we'll have to augment LSP with an additional flag, maybe "InitializeError.retryCanBeAutomatic".

**Comment by dbaeumer** [comment]
I updated the implementation of the node modules and the protocol with a better explanation.

**Comment by dbaeumer** [comment]
Reopening. Did not see last comment.

**Comment by ljw1004** [comment]
Thanks! No need to re-open the issue. I have a bunch of thinking to do around retry strategies for the other scenarios, and I'll put together a proper PR if I end up with something LSP-worthy.

(I wanted to start simple with just a clarification of the use of the retry flag, as you've done).

**Comment by dbaeumer** [comment]
Regarding the additional questions:

**Crashes**: 

this is provided by the client libarary. It even offers a pluggable strategy where your extension can control whether the server should be restarted on crash or not.

**Pull**:

I would say this is up to our extension. I could listen to file changes, stop the server and restart it. The server always resyncs open resources if they match the document filters. 

**Slow startup*:

This depends on whether you want to have a solution working nice in VS Code or a solution working in all clients supporting the LSP. If the later then I would not register the handlers and would write something to the console (connection.console) which is generically presented in the UI (a log). If you want to integrate nicely into VS Code I would add a status bar item and would send custom notifications from the server to the client to update the status bar item. 

We have requests to add progress reporting to the protocol but this will not come before version 4.0 of the protocol.

**Singleton**: I think you should either use the start()/stop() method on the client to start and stop a language server. As said above the client tries to restart a kill / crashed server over the extension can influence this plugging in strategies. We even inform the user if for example the server crashed to often.

I will close the issue, but will react to further questions.

**Comment by alanz** [comment]
> this is provided by the client libarary. It even offers a pluggable strategy where your extension can control whether the server should be restarted on crash or not.

Is there an example somewhere of how to do this?
