### ISSUE TITLE
Clarify Text Document Event Sequencing Requirements

### ISSUE THREAD

**Issue by tsmaeder** [Microsoft/language-server-protocol#216]
It is not entirely clear to me what a language server should assume about the sequence of text document lifecycle event (didOpen, didChange, didClose).
Imagine a client that crashes, then reconnects to the language server. The sequence of events the language server would see is this:
didOpen(foo, content)
didChange(foo)
DidOpen(foo, content).

Is that allowed?

What assumption can a language server make about the sequence of these events, or in other words: what guarantees does the client have to make?

**Comment by dbaeumer** [comment]
@tsmaeder the current assumption of the LSP is that the server is spawned and owned by the client. This means that if the client goes down the server goes down. There LSP is currently not designed for 'standalone' servers. I do have request to support this but this raised questions like you asked about reconnect scenarios, multi tenant, .... 

So in the current protocol the sequence should always be:

didOpen(foo, content)
didChange(foo){n}
didClose(foo)
