### ISSUE TITLE
What is the state of LSP 3.0 support on vscode?

### ISSUE THREAD

**Issue by alanz** [Microsoft/language-server-protocol#217]
The current vscode (1.11.1) sends through an empty Client Capabilities in the `initialize` message.

Is this because 3.0 is not implemented there yet, or is there some specific action to enable it?

**Comment by dbaeumer** [comment]
It is. You need to upgrade to the 3.x npm version of the libraries (vscode-languageclient & vscode-languageserver)

**Comment by alanz** [comment]
As a non-npm person, using an installed .deb package, how would I do that?

**Comment by dbaeumer** [comment]
Not sure. We only maintain a JS/TS version of the protocol which is available on npm. I have no idea if you can install npm packages via a .deb package.

**Comment by alanz** [comment]
Ok, thanks.  I am using the release version of vscode as a reference, I will just wait for it to work through there, since I am interested in how it actually works in the context of an editor using it.

**Comment by dbaeumer** [comment]
Ah, now I see. A better example is to look at vscode-eslint then. This usually uses out latest npm packages.
