### ISSUE TITLE
DidOpenTextDocument and TextDocumentSyncKind

### ISSUE THREAD

**Issue by alanz** [microsoft/language-server-protocol#218]
In response to the `initialize` request a server can set a `TextDocumentSyncKind`, which includes `None`, for when the server has access to the file on the filesystem.

This is honored for the `DidChangeTextDocument` notification, but not in the original `DidOpenTextDocument`.

So perhaps the `TextDocumentItem` should have an optional `text` field, subject to the sync kind.

**Comment by dbaeumer** [comment]
If we change this it might break quite some clients which might rely on this behavior. The earliest this can change is for 4.0.

**Comment by dbaeumer** [comment]
I will close the issue since I don't see us breaking this anytime soon.
