### ISSUE TITLE
Escaping template variables in snippets ?

### ISSUE THREAD

**Issue by kdvolder** [Microsoft/language-server-protocol#220]
The LSP has some explanation about the snippet format. This relatively clear except for one small detail. What would I do if my snippet contains text that accidentally looks like a snippet variable (e.g `$1`)?

I'm guessing there is probably some kind of an escape sequence (a `\` maybe?) that can be applied.

If there is indeed an escape it would be great to add that to the description of the LSP. If there isn't, then... perhaps there should be.

**Comment by dbaeumer** [comment]
Needs to be clarified. The escaping is done using `\`. So to insert `$1` the string has to look like this `\\$1`

**Comment by kdvolder** [comment]
Two backslashes?

**Comment by dbaeumer** [comment]
Sorry, one backslash. The example is a JavaScript string where you need two backslashes to produce a string.

**Comment by dbaeumer** [comment]
This got documented with the snippet syntax markdown file lately.
