### ISSUE TITLE
Usability as a documentation generator

### ISSUE THREAD

**Issue by MathieuDuponchelle** [Microsoft/language-server-protocol#226]
This may be related to #77 .

It seems to me that the protocol could be used by a documentation tool to extract documentation, symbols and signatures from an existing code base, the flow would go like that:

initialize()
textDocument/didOpen()
textDocument/documentSymbols() (the current documentSymbol)

The tool would then iterate the symbols, and call a new method:

textDocument/documentSymbol(position), with position being symbol['location']['range']['start']

This would return an object containing the parent name, possibly the signature, and the *raw* documentation string, for the tool to parse and format as appropriate.

Thoughts ?

**Comment by MathieuDuponchelle** [comment]
ping :)

**Comment by dbaeumer** [comment]
@MathieuDuponchelle I think there is no need for a new request to achieve. After getting all symbols you can execute a hover request on all the symbols which should give you access to the signature and the documentation. Will that work for you ?
