### ISSUE TITLE
textDocument/didOpen and versions

### ISSUE THREAD

**Issue by alanz** [Microsoft/language-server-protocol#229]
When a `didChange` notification is received it has a version number in it, which can be used to manage diagnostics etc on the server side.

This does not appear for a `didOpen` notification.

Also, the only thing we are told about a `VersionedTextDocumentIdentifier` is that it is an integer giving a version number for the document.

It would be good to prescribe that when a `didOpen` is sent there is an implicit version number of 0 (or some other base number), and that subsequent version numbers will be increasing as changes happen.

Does it go backwards for an undo operation?

**Comment by alanz** [comment]
And perhaps `didSave` should include a version too?

**Comment by dbaeumer** [comment]
The open notification sends a `TextDocumentItem` which is speced as

```
export interface TextDocumentItem {
	/**
	 * The text document's uri.
	 */
	uri: string;

	/**
	 * The text document's language identifier
	 */
	languageId: string;

	/**
	 * The version number of this document (it will increase after each
	 * change, including undo/redo).
	 */
	version: number;

	/**
	 * The content of the opened text document.
	 */
	text: string;
}
```

I will close the issue. Please ping if I misunderstood.
