### ISSUE TITLE
Why enforce completionItem to modify requested line?

### ISSUE THREAD

**Issue by mickaelistria** [Microsoft/language-server-protocol#235]
I see in the protocol for completion item
```
 * *Note:* The range of the edit must be a single line range and it must contain the position at which completion
 * has been requested.
 */
textEdit?: TextEdit;	
```

Why should the protocol enforce this requirement? I don't think it brings any additional value to the protocol nor that it makes it easier to implement for clients. Can you please explain the reasons behind it? And can we consider getting rid of it?

**Comment by kdvolder** [comment]
I've also raised the issue before here: https://github.com/Microsoft/language-server-protocol/issues/92

**Comment by dbaeumer** [comment]
Dups #92.
