### ISSUE TITLE
Support for markup languages and ordinary documents

### ISSUE THREAD

**Issue by dumblob** [Microsoft/language-server-protocol#24]
The specification is targetting programming languages. The same issues though appear in case of remote editing of any "stylised" document - from markup text files ([DocOnce](https://github.com/hplgit/doconce), CommonMark, AsciiDoc, etc.) up to full-featured "office" solutions like LibreOffice, Microsoft Office, etc.

Wouldn't it make sense to accommodate wording throughout the specification to make it applicable to other editing scenarios (mentioned above) as well?

**Comment by dumblob** [comment]
Existing effort quite similar to the proposal: https://en.wikipedia.org/wiki/Google_Kythe .

**Comment by dbaeumer** [comment]
Will have a look at Kythe and see what we can learn.

**Comment by dbaeumer** [comment]
To keep the number of issues in our inbox at a manageable level, we’re closing issues that have been on the backlog for a long time but haven’t gained traction. Thank you for your time and understanding.

If you disagree and feel that this issue is crucial: we’re happy to listen and to reconsider.

**Comment by dumblob** [comment]
Well, I'm still convinced, that the wording in the spec could be changed to accommodate also for markup and any other code/markup/syntax. I'm also convinced, that the change wouldn't take much time and the outcome would be a more robust and more universal spec than now.

**Comment by dbaeumer** [comment]
@dumblob PR is welcome :-)
