### ISSUE TITLE
Description of "documentChanges" of "WorkspaceEdit" is unclear

### ISSUE THREAD

**Issue by RainerKlute** [Microsoft/language-server-protocol#240]
The `documentChanges` field of a `WorkspaceEdit` is described as follows:

_An array of `TextDocumentEdit`s to express changes to specific a specific version of a text document. Whether a client supports versioned document edits is expressed via `WorkspaceClientCapabilites.versionedWorkspaceEdit`._

While the wording _to specific a specific_ is clearly wrong, it is unclear what is meant. Do all these individual `TextDocumentEdit`s have to be applied to the **same** specific version of a text document?
- If yes, what would be the point of having a `VersionedTextDocumentIdentifier` in each `TextDocumentEdit` – and possibly different ones??
- If no, the first sentence of the description should be reworded, see my suggestion below.

_An array of `TextDocumentEdit`s each expressing a change to a specific version of a text document._

**Comment by dbaeumer** [comment]
Change it to 
```
	 * An array of `TextDocumentEdit`s to express changes to n different text documents
	 * where each text document edit addresses a specific version of a text document. 
	 * Whether a client supports versioned document edits is expressed via 
	 * `WorkspaceClientCapabilites.versionedWorkspaceEdit`.
```

It changes n text documents and each text document edit addresses a specific version. If the client doesn't have that version anymore it can either reconstruct the version or drop the edit. This is singled via the applied property in the response.

**Comment by akosyakov** [comment]
@dbaeumer There is a mistake in the comment: should be `WorkspaceClientCapabilites.workspaceEdit.documentChanges`, not `WorkspaceClientCapabilites.versionedWorkspaceEdit`

**Comment by dbaeumer** [comment]
Good catch. Will fix

**Comment by dbaeumer** [comment]
Done
