### ISSUE TITLE
Description of "version" of "TextDocumentItem" is unclear

### ISSUE THREAD

**Issue by RainerKlute** [Microsoft/language-server-protocol#241]
The `version` field of `TextDocumentItem` is described as follows:

_The version number of this document (it will strictly increase after each change, including undo/redo)._

It is unclear what _strictly increase_ means.
- If it means that the subsequent version number could be any number that is greater than the previous one, then the word _strictly_ can and should be omitted.
- If an increment of the version number by exactly one is meant, the description should say so, e.g.:

_The version number of this document. Each change, including undo/redo, increments it by one._

**Comment by dbaeumer** [comment]
I removed the strictly since we don't want to state that the increment is always one. A client could for optimization not sync all document state over to a server.
