### ISSUE TITLE
Add "labels" to ApplyWorkspaceEditParams

### ISSUE THREAD

**Issue by mickaelistria** [Microsoft/language-server-protocol#243]
In order to easily use edits in place of commands here and there, and in order to provide nice labels in the undo/redo stack for operations provided by the LSP, it could be interesting to add an optional "label" field to Workspace and TextEdits.

**Comment by dbaeumer** [comment]
Makes sense.

**Comment by dbaeumer** [comment]
Instead of generically naming edits we should add a name to `ApplyWorkspaceEditParams`. This can then be used to construct a name for the Undo.

**Comment by dbaeumer** [comment]
Actually this was easy to address. So I added an optional name to the `ApplyWorkspaceEditParams`.
