### ISSUE TITLE
Are markdown strings supposed to support embedded code blocks?

### ISSUE THREAD

**Issue by mickaelistria** [Microsoft/language-server-protocol#247]
The definition of MarkedString more or less says "either markdown or code". What about code embedded in markdown with the GitHub code block syntax  \`\`\`language\`\`\` ? AFAIK, from the protocol perspective, it seems to be necessary if we want "mixed" strings containing prose and code, so it should be explicitly mentioned in the specification.
And if this is allowed/made a requirement, why would we still need the language/value pair? MarkedStrings could simply be Markdown strings allowing code blocks.

**Comment by drusellers** [comment]
I'm not sure if anything is needed _specifically_ in the LSP but I figured I should ask.

I am working in Rust and would love to make sure the foundations are available when the Rust tools team can get to it.

```
/// This method is awesome
/// 
/// begin a doc test
/// ```
/// use yo;
/// assert_eq!(yo(), 1);
/// ```
pub fn yo() -> u32 {
  1
}
```

How can we expose the code inside the doctest to the LSP?

**Comment by dbaeumer** [comment]
@jrieken what do we do in the API if someone gives us a code block using ```ts .... ``` Do we run it through the TS tokenizer ?

**Comment by jrieken** [comment]
> And if this is allowed/made a requirement, why would we still need the language/value pair? MarkedStrings could simply be Markdown strings allowing code blocks.

yes, MarkedStrings all code block, the language/value pair is from a time before that

**Comment by dbaeumer** [comment]
Closing if favor of https://github.com/Microsoft/language-server-protocol/issues/340
