### ISSUE TITLE
Support for doctest languages/patterns

### ISSUE THREAD

**Issue by drusellers** [Microsoft/language-server-protocol#248]
I'm not sure if anything is needed _specifically_ in the LSP but I figured I should ask.

I am working in Rust and would love to make sure the foundations are available when the Rust tools team can get to it.

```
/// This method is awesome
/// 
/// begin a doc test
/// ```
/// use yo;
/// assert_eq!(yo(), 1);
/// ```
pub fn yo() -> u32 {
  1
}
```

How can we expose the code inside the doctest to the LSP?

**Comment by mickaelistria** [comment]
Seems like a dup of #247 . If you think so, can you please close this
ticket and put your example as a comment of #247?
