### ISSUE TITLE
Make range optional in Diagnostic

### ISSUE THREAD

**Issue by smarter** [Microsoft/language-server-protocol#249]
Currently, the range in a diagnostic cannot be omitted: https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#diagnostic. However, in some cases a compiler might not give range information for a diagnostic, for example if the information comes from code where the compiler did not track the position for some reason, or if the diagnostic is not specific to any position (e.g., "The compiler crashed with stack trace ...", "The compiler was run with the invalid flag ..."). While this information should not be displayed in the text area of the client, most editors provide a list of all diagnostics somewhere where this information could appear.

**Comment by mickaelistria** [comment]
+1.
In the Java/Eclipse world, some issues such as "couldn't find `mvn`" or
similar environment issues could be reported as diagnostics on a file,
without necessarily showing a range.

**Comment by rictic** [comment]
There's also cases where the file is known but the position in the file isn't.

**Comment by dbaeumer** [comment]
I will mark this as a dup of #256
