### ISSUE TITLE
language server serves /protocol.json

### ISSUE THREAD

**Issue by nojvek** [Microsoft/language-server-protocol#25]
It seems this protocol has similarities to the Chrome Remote Debugging protocol. 

Does it make sense for the repo to have a protocol.json file ? e.g https://cs.chromium.org/chromium/src/third_party/WebKit/Source/platform/v8_inspector/js_protocol.json

This means different language servers implement the protocol and maintain a protocol.json file which can be queried if the API is compatible and has any breaking changes.

The protocol.json can then be used to automatically generate code for a client or server implementation in languages other than typescript.

e.g I can consume protocol.json and automatically generate a Java class for java language service interface.

Same for PHP, python and the rest. Code generation on both client and server can benefit.

**Comment by gorkem** [comment]
+1 excellent idea! [Eclipse JSDT](http://git.eclipse.org/c/jsdt/webtools.jsdt.git/tree/bundles) uses protocol.json to generate the Java model.

**Comment by dbaeumer** [comment]
Yes that makes sense to me. We could then even generate the protocol.ts from it.

**Comment by gorkem** [comment]
I think I can help with this since I am creating a similar think for the java binding. What should be the meta model though. Use the model from V8s protocol.json or alternately use json schema specification?

**Comment by nojvek** [comment]
I've made some progress on the last few days defining protocol.d.ts
interface for chrome's protocol.json files. Thanks to typescript I already
found a few nitty gritty bugs in their json files.

Hope it can be used as a template.

https://github.com/nojvek/chrome-remote-debug-interface/tree/master/generator

**Comment by gorkem** [comment]
I created a [PR with the protocol.json ](https://github.com/Microsoft/language-server-protocol/pull/40) that I have used to generate the java-language-server APIs. The files is a json schema and it is mostly generated from protocol.d.ts file.

**Comment by dbaeumer** [comment]
I will close this issue in favor of #67
