### ISSUE TITLE
Should not `SymbolInformation.location` be optional?

### ISSUE THREAD

**Issue by akosyakov** [microsoft/language-server-protocol#251]
I have a case when the user want to see symbols available in the workspace but should not be able to navigate to them, e.g. for programmatically defined libraries.

**Comment by dbaeumer** [comment]
Other languages like Java have the same problem and they do the following which works in VS Code but not generically in other clients.

- they use a special URI for the location
- register a virtual document provider for the URI inside VS Code
- when selected compute a document that shows the source code of the programmatically defined library.

I will keep this as a feature request.
