### ISSUE TITLE
Clarify the usage of "Position" in Hover

### ISSUE THREAD

**Issue by cdietrich** [Microsoft/language-server-protocol#26]
I am experimenting with implementing a Language Server Hover Service and i stumbled over the definition of the Position Parameter in that service. 

e.g. if i hover on (the middle of) the second character i get requested with Position {line: 0, character: 2}
although position says character is zero based

**Comment by dbaeumer** [comment]
@cdietrich the position in a hover should also be 0 based. So if you hover over the second character on the first line position should be (0,1). I tested it with my test bed and this is actually correct. Do you have a special file I could look at. There might be a problem in VS Code itself requesting a hover at the wrong position.

![capture](https://cloud.githubusercontent.com/assets/1931590/16589395/444df124-42d3-11e6-83d9-88ba1652d88f.png)

**Comment by cdietrich** [comment]
i just have a file Like

```
Hello World!
```

in increased the font size about 3 times
and hover on the `H

then i get requests like

```
{"jsonrpc":"2.0","id":104,"method":"textDocument/hover","params":{"textDocument":{"uri":"file:///Users/dietrich/git/xtext-languageserver-example/demo/a.mydsl"},"position":{"line":0,"character":1}}}
```

and requests like

```
{"jsonrpc":"2.0","id":102,"method":"textDocument/hover","params":{"textDocument":{"uri":"file:///Users/dietrich/git/xtext-languageserver-example/demo/a.mydsl"},"position":{"line":0,"character":0}}}
```

although i hover on the `H`only

i expect to get always `{"line":0,"character":0}}`

this happens with the release and the insider version as well

**Comment by cdietrich** [comment]
For easyness of reproduction i extended the node language server example as follows
```
```
capabilities: {
			// Tell the client that the server works in FULL text document sync mode
			textDocumentSync: documents.syncKind,
			// Tell the client that the server support code complete
			completionProvider: {
				resolveProvider: true
			},
			hoverProvider : true
		}
```
connection.onHover(
	(p : TextDocumentPositionParams) : Hover => {
		console.log(p.position.character);
		
		return {
			contents: "xxxxx" + p.position.character,
			range : {
				start : {line: 0, character: 0},
				end : {line: 0, character: 10}
			}
		}
		
	}	)
;

```

**Comment by cdietrich** [comment]
<img width="356" alt="screenshot" src="https://cloud.githubusercontent.com/assets/238736/16591915/76a63ee6-42de-11e6-8bcb-142895e63f28.png">

**Comment by dbaeumer** [comment]
@cdietrich I fully agree that the character position should stay the same.

@alexandrudima since I receive the position from the editor is this something that is known?

**Comment by alexandrudima** [comment]
The positions in the editor correspond to the "gaps" in between characters. 

So, given the text `abc`:
* the mouse event for the cursor being clearly in front of `a`:
  * position: `(1,1)`, range: `(1,1)->(1,1)`
* the mouse event for the cursor being on top of `a` (but in the first half):
  * position: `(1,1)`, range: `(1,1)->(1,2)`
* the mouse event for the cursor being on top of `a` (but in the second half):
  * position: `(1,2)`, range: `(1,1)->(1,2)`
* the mouse event for the cursor being pixel-perfect in between `a` and `b`:
  * position: `(1,2)`, range: `(1,2)->(1,2)`

So the position expresses where the cursor would go if the user would click.

I think the hover editor contribution uses that position and doesn't use the range at all to invoke the hover provider. Perhaps this is a case where the hover provider should have received a range and not a position as an argument, as the range describes better where the mouse is hovering.

https://microsoft.github.io/monaco-editor/playground.html#interacting-with-the-editor-listening-to-mouse-events is a good test page to see this in action with the note that the positions there are 1-based, and also columns are 1-based

**Comment by dbaeumer** [comment]
@cdietrich was @alexandrudima answer sufficient for you.

**Comment by dbaeumer** [comment]
I am closing the issue. Please ping if something is unclear.
