### ISSUE TITLE
Clarification: how to respond to document/Hover with no results?

### ISSUE THREAD

**Issue by ljw1004** [Microsoft/language-server-protocol#261]
How should the language server respond to a `document/Hover` request if it has nothing to say? e.g. if the location is whitespace, or outside the range of the document?

* With a `RequestCancelled` error result?
* With `{contents: ""}`?
* With `{contents: []}`?

The return type of `document/Hover` is this:
```
interface Hover {
	contents: MarkedString | MarkedString[];
	range?: Range;
}
```

I glanced through the source code of a bunch of different LSP implementations. It looked like a few return `contents: ""` and most return `contents: []`.

**Comment by kdvolder** [comment]
I was wondering the same thing. Ended up returning `[]` which seems to work. But clarification around the meaning of the returned `Hover` value does seem warranted.

E.g. the question on how to represent 'no hover' is a good one. Also I was a bit confused by the fact that contents is either a single `MarkedString` or a `MarkedString[]`. What's the meaning of returning multipe MarkedString? Are these like several hovers that apply at the same location? Or are they all just to considered as 'pieces' of one hover, to be concatenated into one big `MarkedString`?

If the latter, then why do we need an array? If the former, then shouldn't each `MarkedString` be accompanied by a `Range` ?

**Comment by ljw1004** [comment]
```ts
type MarkedString = string | { language: string; value: string };
```

My understanding: `MarkedString` is just *one paragraph* of markdown. If we want to return multiple paragraphs (e.g. a codeblock for the signature, followed by a paragraph for doc-comment) then we'd need an array of MarkedString. And I'd expect them all to be rendered for the same range, stacked vertically.

**Comment by kdvolder** [comment]
You are probably right about the meaning of mutliple elements in the array being 'stacked' vertically as paragraphs. However, my understanding is that a multiparagraph markdown can also be represented as just one long marked string using "\n\n" as paragraph separator (i.e. the normal way to separate paragraphs in markdown). At least... when I send such multi-paragraph markedstrings to vscode that seems to work as expected.

**Comment by felixfbecker** [comment]
To me the samantic difference is clear, an empty array means no hover and an empty string means a single hover with no text in it.

**Comment by kdvolder** [comment]
@felixfbecker I don't think its clear at all. I did make a similar 'guess' as you did, but its just a guess and it doesn't really 'jive' with the fact that multiple elements in the list are simply concatenated into a single hover. 

So really, the *true* interpretation seems to be that this not a list of hovers, but a list of 'hover parts'. So then both `[]` and `""` represent an empty hover. And the IDE simply decided that 'empty hovers' shouldn't be shown. So the 'empty hover' achieves the same effect as one would expect with 'no hover'.

Anyway... the point is, the spec really isn't clear as everybody here comes with slightly different interpretations of what it means.

**Comment by dbaeumer** [comment]
I clarified this in the protocol and the spec. If no Hover is available `null` should be return from a protocol spec (undefined is not possible due to the JSON RPC spec (e.g. result must be present). For requests that return an array I left the empty array.

**Comment by dbaeumer** [comment]
The reason why I never speced that was that before strictNull null was always a valid return value from a compile point of view. So may be we should allow null for arrays as well.

**Comment by dbaeumer** [comment]
Done. Speced it how it was implemented from the beginning that allows null as return value.
