### ISSUE TITLE
Broken URL for snippets

### ISSUE THREAD

**Issue by ljw1004** [Microsoft/language-server-protocol#262]
The LSP documentation for snippets says to see also https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/snippet/common/snippet.md

That link gives a 404. I think it should be this one:

https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/snippet/browser/snippet.md

**Comment by dbaeumer** [comment]
I added a separate snippet document to this repository.
