### ISSUE TITLE
Clarification: default value of CompletionList.isIncomplete?

### ISSUE THREAD

**Issue by ljw1004** [Microsoft/language-server-protocol#265]
`textDocument/completion` can return either a `CompletionItem[]` or a `{isIncomplete: boolean; items: CompletionItem[];}`. The editor uses the `isIncomplete` flag to determine whether further typing should recompute the list.

*If the LSP server returns just `CompletionItem[]`, will the editor recompute the list or not upon further typing?* In other words, what is the default value of `isIncomplete`?

I randomly found the following bit of VSCode source code in [src/vs/editor/standalone/browser/standaloneLanguages.ts](https://github.com/Microsoft/vscode/blob/875144b25bf95197aff9ed0a8229ae322701bdd1/src/vs/editor/standalone/browser/standaloneLanguages.ts#L650), which makes me think the default value of `isIncomplete` is `false` (in other words, if the LSP server provides just `CompletionItem[]`, then the language server will *NOT* ask it to recompute upon further typing). But I don't know who invokes this code nor why nor when, so I'm not sure. I believe it's part of the monaco-editor node package.

```ts
let list: CompletionList;
if (Array.isArray(value)) {
  list = {
    items: value,
    isIncomplete: false
  };
} else if (typeof value === 'object' && Array.isArray(value.items)) {
  list = value;
  result.incomplete = list.isIncomplete;
} else if (!value) {
  // undefined and null are valid results
  return undefined;
} else {
  // warn about everything else
  console.warn('INVALID result from completion provider. expected CompletionItem-array or CompletionList but got:', value);
}
```

**Comment by dbaeumer** [comment]
No. If a CompletionItem[] is returned it will be treated as a complete set of items.
