### ISSUE TITLE
Support debugger protocol

### ISSUE THREAD

**Issue by gatesn** [Microsoft/language-server-protocol#266]
As specified here: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/common/debugProtocol.d.ts

**Comment by mickaelistria** [comment]
See https://github.com/Microsoft/language-server-protocol/issues/210#issuecomment-292158414

**Comment by dbaeumer** [comment]
//cc @weinand

**Comment by weinand** [comment]
The debug adapter protocol specification (and the generated TypeScript definitions) are independent from the VS Code implementation and live in their [own repository](https://github.com/Microsoft/vscode-debugadapter-node) (but that repository still uses "vscode" in its name). 

Moving the debug adapter protocol specification/schema to a separate repository is planned. See https://github.com/Microsoft/vscode/issues/19636.
