### ISSUE TITLE
workspace/symbols isIncomplete flag

### ISSUE THREAD

**Issue by bmewburn** [Microsoft/language-server-protocol#267]
The `workspace/symbols` request can potentially return many results. The `textDocument/completion` request allows for an `isIncomplete` flag in the response. Having a similar flag in the workspace/symbols response will allow a server to return a truncated response and notify the client that further requests should be made for the additional items. Might be worth considering for `textDocument/documentSymbols` too.

```Typescript
interface SymbolInformationList {
	isIncomplete?: boolean;
	items: SymbolInformation[];
}
```

**Comment by dbaeumer** [comment]
The incomplete flag on completion items doesn't introduce pagination or stream. It simply means that the client can't assume that typing more characters allows to filter the list of items on the client side. It needs to call the server again to re-compute the whole list.

We have issue that request pagination and or streaming. I will close this issue in favor of those.

**Comment by kdvolder** [comment]
It might be worth clarifying the purpose of `isIncomplete` flag in the protocol spec. Not everyone can correctly guess the meaning / purpose of the flag.
