### ISSUE TITLE
Clarification: CompletionOptions.triggerCharacters

### ISSUE THREAD

**Issue by ljw1004** [Microsoft/language-server-protocol#268]
**How does an IDE decide to trigger completion when the user types an alphabet character, e.g. `a`?**

I experimented with a bunch of different IDEs and languages. In EVERY case, when you type any alphabet character, then autocomplete is triggered automatically. For instance if I type `a` then autocomplete will pop up with a list of available identifiers/classes/methods that start with the letter `a`.

Is this fact represented anywhere in LSP? What exactly is meant to go in the `CompletionOptions.triggerCharacters` that a server sends in response to an initialize request?
```ts
export interface CompletionOptions {
  // The characters that trigger completion automatically.
  triggerCharacters?: string[];
}
```

I looked around at various LSP implementations to see what they send for completion triggerCharacters. Clearly, none of these mention anything about alphabet characters triggering autocomplete.

* [Microsoft HTML](https://github.com/Microsoft/vscode/blob/master/extensions/html/server/src/htmlServerMain.ts#L75)... `triggerCharacters: ['.', ':', '<', '"', '=', '/']`
* [Eclipse Java](https://github.com/eclipse/eclipse.jdt.ls/blob/a99cfa37024b1352b196583d070f3f2b6db8ccdf/org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/InitHandler.java#L86)... `Arrays.asList(".","@","#")`
* [@georgewfraser Javac](https://github.com/georgewfraser/vscode-javac/blob/416930f14f614868ece44be12f39cb5cb503d14f/src/main/java/org/javacs/JavaLanguageServer.java#L80)... `new CompletionOptions(true, ImmutableList.of("."))`
* [Microsoft PHP](https://github.com/Microsoft/vscode/blob/1ff2c4809df412f6d53e341b18d41689c156ba0a/extensions/php/src/features/completionItemProvider.ts#L13)... `public triggerCharacters = ['.', ':', '$'];`
* [@freebroccolo OCaml](https://github.com/freebroccolo/ocaml-language-server/blob/e46df9a26118c3613ff5ccba35ea4848e3bc5a11/src/server/capabilities.ts#L10)... `triggerCharacters: ["."],`
* [@felixfbecker PHP](https://github.com/felixfbecker/php-language-server/blob/42d0c7b714f91d272207380737eb075ee2d46b8a/src/LanguageServer.php#L279)... `triggerCharacters = ['$', '>']`
* [HvyIndustries Crane](https://github.com/HvyIndustries/crane/blob/ee1b0011b6f9524c1ce2e997c266f567afdd19d7/server/src/server.ts#L67)... `triggerCharacters: ['.', ':', '$', '>', "\\"]`
* [Rust](https://github.com/rust-lang-nursery/rls/blob/master/src/server.rs#L334)... `trigger_characters: vec![".".to_string(), ":".to_string()]`
* [Scala](https://github.com/dragos/dragos-vscode-scala/blob/b0a946ff58aff0f034a441bcb724cdf11f6be613/languageserver/src/main/scala/langserver/core/LanguageServer.scala#L76)... `completionProvider = Some(CompletionOptions(false, Seq(".")))`
* [@RLovelette](https://github.com/RLovelett/langserver-swift/blob/32356cf13408fc64bf3a08b3f4bbf376d32c9ef3/Sources/LanguageServerProtocol/Types/Server.swift#L64)... `triggerCharacters: [" ", ".", ":", "<", "("]`

My suspicion: it's up to the editor when to automatically trigger autocomplete, and all good editors will trigger autocomplete when the user types any alphabet character, and IN ADDITION they should also automatically trigger autocomplete when the user types one of the LSP's triggerCharacters. This is the same conclusion that @prabirshrestha reached when rewriting VIM's autocomplete to behave more like that of VSCode [link](https://github.com/roxma/nvim-completion-manager/issues/30#issuecomment-283281158).

If that is indeed the intent of `CompletionOptions.triggerCharacters`, then I think it should be documented in the LSP protocol. My suggestion:

```ts
export interface CompletionOptions {
  // The additional characters that should trigger completion automatically, in addition to
  // whatever other characters the editor already uses to trigger completion automatically -
  // typically [a-zA-Z].
  triggerCharacters?: string[];
}
```

**Comment by dbaeumer** [comment]
Good question! It is assumed that typing an `identifier` automatically triggers code complete as well.

**Comment by dbaeumer** [comment]
Add this to the spec:
```ts
	/**
	 * Most tools trigger completion request automatically without explicitly requesting
	 * it using a keyboard shortcut (e.g. Ctrl+Space). Typically they do so when the user
	 * starts to type an identifier. For example if the user types `c` in a JavaScript file
	 * code complete will automatically pop up present `console` besides others as a 
	 * completion item. Characters that make up identifiers don't need to be listed here.
	 *
	 * If code complete should automatically be trigger on characters not being valid inside
	 * an identifier (for example `.` in JavaScript) list them in `triggerCharacters`. 
	 */
```
