### ISSUE TITLE
DidChangeWatchedFilesRegistrationOptions is not documented

### ISSUE THREAD

**Issue by nrc** [Microsoft/language-server-protocol#271]
It seems to exist: https://github.com/Microsoft/vscode-languageserver-node/blob/e65f6fcdfa5467599b78d0ed25c2871be4530457/client/src/protocol.ts#L1108 But is not documented in the spec (as far as I can see). I think it is necessary to have since otherwise there is no way to get `workspace/didChangeWatchedFiles` notifications,

**Comment by dbaeumer** [comment]
I fixed this last week.
