### ISSUE TITLE
WorkspaceEdit and File Level Operations

### ISSUE THREAD

**Issue by tsmaeder** [microsoft/language-server-protocol#272]
A rename operation, for example returns a WorkspaceEdit operation. However, when renaming a Java class, for example, I expect the file to be renamed as well. Is there a way to express that in LSP?

**Comment by rcjsuen** [comment]
See also #41 and #191.

**Comment by mickaelistria** [comment]
What about a simple `delete: true` flag to mark the previous file as deleted (flag to be added to protocol) + a regular TextEdit with whole content of the new file?

**Comment by dbaeumer** [comment]
I agree that we should expand the WorkspaceEdit with a resourceChanges property which allows for the following resource operations:

- create (with content)
- move (includes rename)
- delete

This would solve the rename refactoring as as well.

**Comment by dbaeumer** [comment]
A proposal is highly appreciated.

**Comment by gorkem** [comment]
@dbaeumer I think this one needs a `proposal-provided` label also

**Comment by dbaeumer** [comment]
Agree.

**Comment by tsmaeder** [comment]
@dbaeumer I have seen there is support for resource change now in LSP. However, what's missing from my point of view is the creation of folders. If I have a rename or a delete, I know whether I am dealing with a folder or a file, But in a create, I have no way of knowing. Shouldn't "isFolder" be added to CreateFileOptions?

**Comment by dbaeumer** [comment]
@tsmaeder correct :-). All I can recommend right now is to create a file in the folder and then delete the file.

I will keep the request open to support creating a folder. Will very likely be an additional property / param type: 'file' | 'folder'

**Comment by dbaeumer** [comment]
See also https://github.com/Microsoft/vscode/issues/62663

**Comment by yaohaizh** [comment]
@dbaeumer 
For the workaround, on my windows' desktop, I always disabled recycle bin support.  So the work around will pop up with text `Failed to move 'fakeFile' to the recycle bin`
This workaround is kind of issue if customer doesn't support recycle bin or have to enable options `files.enableTrash: false`

Either way, it is not decent workaround at this time.

**Comment by testforstephen** [comment]
Refactor package name is really an important feature for Java language, without creating/deleting folder support in LSP level, it's hard to bring this feature to jdt.ls.

@dbaeumer is there any update about this issue? Or any help i can provide to solve it? thanks.

**Comment by dbaeumer** [comment]
@testforstephen thanks for offering your help. Things needed to be done to make this work:

- extend LSP to provide a createFolder resource change
- to be able to leverage this in VS Code the API must be extended as well (see: https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L2870 and https://github.com/microsoft/vscode/issues/62663)

Should not be too complicated. I would start with the VS Code work and then add the LSP resource change.

**Comment by testforstephen** [comment]
great, thanks for the explanation. Looking forward to see it's solved.

**Comment by dbaeumer** [comment]
This got added a while back ago.
