### ISSUE TITLE
Clarify the meaning of 'additonial information' in lazy completion resolution

### ISSUE THREAD

**Issue by kdvolder** [Microsoft/language-server-protocol#275]
In its current form the descriptions around the 'Completion Request' and 'Completion Resolve Request' say that:

>  The request is sent from the client to the server to resolve additional information for a given completion item.

There is however no explicit list/desciption which of the properties in a completion item can be considered as 'additional information' and subject to 'lazy resolution'. 

This question came up in discussion here: https://github.com/Microsoft/vscode/issues/26622

@jrieken interpretation seems to be that the edits can not be lazy resolved. My interpretation was that they can be. I would also argue that it is desirable to consider the edit details to be considered 'additional details', since computing the edits (especially if they are complex) can be expensive; and one would not expect these edits to be needed until the completion item is selected and applied.

**Comment by dbaeumer** [comment]
I clarified this in the protocol and the node implementation.
