### ISSUE TITLE
Enhance SymbolInformation with optional `separator:string`

### ISSUE THREAD

**Issue by svenefftinge** [Microsoft/language-server-protocol#276]
When trying to construct a tree from a list of `SymbolInformation` objects, we can use the `containerName` property.
Let's consider the following example :
```ts
export namespace bar {
    export namespace bar {
        export function test() {
            return true;
        }
    }
}
```
In order to tell that test's container is `bar.bar` the container name should be provided qualified. But to find the container element I would also need to know the qualified name of that element. I could compute it form the `name` and the `containerName` if I knew the separator. But I don't.

Either having an optional separator, or the explicit qualified name would solve it. 
Many languages use a single separator, so we could configure it in capabilities. But some have different, so we would need the separator on the individual `SymbolInformation`item.

**Comment by dbaeumer** [comment]
As commented in other issue we should not use the `textDocument/documentSymbol` to reconstruct the hierarchy. I clarified the specification around this a while ago. If we need a hierarchy we should work on a new request that implements this proper. I will close the issue in favour of having a separate request.
