### ISSUE TITLE
Several initialize requests

### ISSUE THREAD

**Issue by amiramw** [Microsoft/language-server-protocol#277]
What does the protocol state about calling several times the initialize request for several root URIs? If it is allowed, does it mean that both roots are served or is it like restart of the LSP?
It might be a way to support several independent workspaces. The other way would be to start independent LSP for each of those workspaces.

**Comment by amiramw** [comment]
Could be related also to https://github.com/Microsoft/language-server-protocol/issues/281

**Comment by dbaeumer** [comment]
Clarified that initialize and initialized may only be sent once.

For the multi root case we added proposed workspace folder support. See here: https://github.com/Microsoft/vscode-languageserver-node/tree/master/client/src
