### ISSUE TITLE
Ordering of responses

### ISSUE THREAD

**Issue by vladdu** [Microsoft/language-server-protocol#278]
The spec is that the responses must be sent to the client in the same order that the requests were sent. Why is that? Can this requirement be relaxed, possibly as a configurable behavior?

Use case: a client shows the results of WorkspaceSymbol in a separate pane/view. This is potentially a long-running operation. If while it runs, the user interacts with the editor, I would expect that the normal editor operations work as usual, but they need to wait for the workspace search to finish.

Requests without any intervening notifications are read-only and can be processed in any order. Since the IDs are unique, it easy for the client to know which request was answered. It is the notifications that must be processed in the correct order. As @bruno-medeiros noted in https://github.com/Microsoft/language-server-protocol/issues/12#issuecomment-25261802 also, receiving a state-changing notification can automatically cancel all pending requests and all is well. 

Am I missing anything?

Edit: servers would like to cancel pending requests when receiving a state-changing notification, anyway; it saves work and doesn't return obsolete information (but possibly incomplete). The requests could also be restarted, but that feels a bit too much.

**Comment by dbaeumer** [comment]
See https://github.com/Microsoft/language-server-protocol/issues/306#issuecomment-333776338.

We should continue the discussion there.
