### ISSUE TITLE
Please link to standalone language servers

### ISSUE THREAD

**Issue by mqudsi** [Microsoft/language-server-protocol#280]
Thanks for this awesome repo and for the amazing work that has been put in to the MS-authored language server implementations.

Can the table of implementations for different languages link to the standalone version of the language servers? Users with vscode don't need to use the github repository for anything (it's already bundled), but people using 3rd party editors (I'm using neovim) would benefit from links to the standalone language server code, which I didn't know existed at first.

* CSS: https://github.com/Microsoft/vscode-css-languageservice
* JSON: https://github.com/Microsoft/vscode-json-languageservice
* HTML: https://github.com/Microsoft/vscode-html-languageservice

**Comment by mqudsi** [comment]
* CSS: https://github.com/Microsoft/vscode-css-languageservice
* JSON: https://github.com/Microsoft/vscode-json-languageservice
* HTML: https://github.com/Microsoft/vscode-html-languageservice

**Comment by egamma** [comment]
@mqudsi done, thanks for pointing this out!

**Comment by mqudsi** [comment]
Cheers!
