### ISSUE TITLE
Support for multiple root workspaces

### ISSUE THREAD

**Issue by gorkem** [Microsoft/language-server-protocol#281]
A language server should be able to support multiple root folders. At the moment a server is initialized with a single URI which translates to spinning a new LS instance. I do not think this is the most efficient way to handle multiple roots for LSP. Since users explicitly associate multiple root folders to a workspace, it is safe to assume that servers are expected to associate those on their structure.

**Comment by mickaelistria** [comment]
And what about having the LS implementation ignoring the concept of "root" at all ? Ie, simply not use the passed parameter in initializeRequest and building its own internal model (including computing root for a given file) internally?
Or, if you do want to use multiple roots and multiple initializeRequests, what about each LS instance being  a "proxy" to a single unique LS "payload" server underneath? So all requests would end in the same underlying instance and model.
I have the impression supporting multiple roots would easily become a source of confusion: how would a client know which server works better as standalone or if it should use multiple-root?
We've had discussion about customizing the project/LS mapping in LSP4E ( https://bugs.eclipse.org/bugs/show_bug.cgi?id=510433 ) and in any case, even if this is implemented on server-side, it would require clients to make serious changes to adopt it.

**Comment by dbaeumer** [comment]
I close this in favor of https://github.com/Microsoft/language-server-protocol/issues/298 which has a proposal for multiple folders.
