### ISSUE TITLE
clarify when diagnostics are cleared

### ISSUE THREAD

**Issue by vladdu** [Microsoft/language-server-protocol#282]
I'm not 100% sure if this is a protocol issue, or a client one, but I think it should be stated somewhere  whether diagnostics must be cleared manually by sending an empty list, or if a file change will clear them automatically. 

From what I see in practice, the former applies.

**Comment by kdvolder** [comment]
My take on this is that its up to the client to decide that. But it would be preferable for the client to try its best to keep the markers after an edit and attempt to update their positions in accordance with the edits.

However, if a client (or client implementer) doesn't want to or is unable to map the marker positions then some or all markers may be cleared.

**Comment by vladdu** [comment]
If the client decides, then the vscode docs should mention the rules it follows.

Since sending diagnostics is the only available operation, it stands to reason that the last sent diagnostics replace the existing ones. But it is unclear if all of them, or only for the URIs present in the list, or some other way. Should the server send an empty list of diagnostics when an editor is closed, or is the client compelled to clean them?

**Comment by alanz** [comment]
This may be related: https://github.com/Microsoft/language-server-protocol/issues/228

**Comment by dbaeumer** [comment]
Diagnostics are "owned" by the server so it is the server's responsibility to clear them if necessary. For servers we implement we follow the following rule (but other languages might need other rules so this is very hard to spec):

- if a language is single file only (for example HTML) then diagnostics are cleared by the server when the file is closed.
- if a language has a project system (for example C#) diagnostics are not cleared when a file closes. When a project is opened (e.g. VS Code opens on a folder that have C# files) all diagnostics for all files are recomputed (or read from a cache).

When a file changes it is the server's responsibility to re-compute diagnostics and push them to the client. If the computed set is empty it has to push the empty array to clear former diagnostics.

**Comment by dbaeumer** [comment]
Updated the protocol.md accordingly
