### ISSUE TITLE
Clarify how to deal with indentation on multiline text inserts

### ISSUE THREAD

**Issue by svenefftinge** [Microsoft/language-server-protocol#283]
When applying a completion item, with a multi line snippet or text to insert. The behavior of monaco is to append the current indentation to newlines.
I.e.
```
class Foo {
   <CURSOR>
}
```
where the text to insert is e.g. 
```
function foo() {
}
```

I get
```
class Foo {
   function foo() {
   }
}
```

This behavior should be added to the protocol to clarify the expectations on client and server side.

**Comment by mickaelistria** [comment]
I agree that this behavior requires clarification. The fact that monaco/vscode automatically adds indent causes confusion for other clients or language server providers: is this auto-indent behavior to be expected from all clients?

**Comment by rcjsuen** [comment]
Also see #83.

**Comment by dbaeumer** [comment]
Marking a dup of #83. 

The path forward is here: https://github.com/Microsoft/language-server-protocol/issues/83#issuecomment-302342278
