### ISSUE TITLE
Add hyperlinks to previously defined interfaces and requests

### ISSUE THREAD

**Issue by Franciman** [microsoft/language-server-protocol#287]
Would it be possible to add hyperlinks to entities previosly defined in the protocol.md?
So that, for example if I'm reading the definition of the initialize notification and I see that its params are of type InitializeParams, I can immediately jump to where InitializeParams is defined?

**Comment by w0rp** [comment]
I was about to file the same issue, and I found this. I find that I have to use Ctrl + F a lot in my browser with something like "interface Foo" to find out the information I need.

**Comment by dbaeumer** [comment]
Agree and I am appy to accept a PR for this. There is one workaround you can use: all the types are available [here](https://github.com/Microsoft/vscode-languageserver-node) and are navigable inside an editor like VS Code.
