### ISSUE TITLE
correctly sending textDocument/didSave notifications

### ISSUE THREAD

**Issue by prabirshrestha** [Microsoft/language-server-protocol#288]
//cc @rcjsuen

The confusion started from https://github.com/rcjsuen/dockerfile-language-server-nodejs/issues/165.

I'm implementing the LSP server for vim at https://github.com/prabirshrestha/vim-lsp. And I would like to know when should it send `textDocument/didSave` changes to the client.

Here are the possibilities. (I would like to support both v2 and v3 porotocols).Is the table correct?

| serverCapabilities | Send `textDocument/didSave` notification | `includeText`
|--|--|--|
| `{}` | :x:  | :x: |
| `{ 'textDocumentSync: 0/1/2 }` | ✔️  | :x: |
| `{ 'textDocumentSync: {} }` | :x:  | :x: |
| `{ 'textDocumentSync: {save: {} } }` | ✔️  | :x: |
| `{ 'textDocumentSync: { save: { includeText: true } } }` | ✔️  | ✔️  |
| `{ 'textDocumentSync: { save: { includeText: false} } }` | ✔️  | :x:  |

**Comment by dbaeumer** [comment]
@prabirshrestha your table is correct. 

Please note that v1 didn't have a didSave notification. But you are not targeting this.
