### ISSUE TITLE
Clarification on $/cancelRequest

### ISSUE THREAD

**Issue by Franciman** [Microsoft/language-server-protocol#290]
Is $/cancelRequest notification intended to be sent only from clients to servers?
Or can a server also theoretically send it to a client?

**Comment by rcjsuen** [comment]
Since `:arrow_right:` (:arrow_right:) is what is used in [protocol.md](https://github.com/Microsoft/language-server-protocol/blob/e1ecd6a23a80735a1a7dc2abe3b684a7032e651e/protocol.md#messages-overview), it sounds like the current assumption is that it is one-way from the client to the server.

**Comment by dbaeumer** [comment]
@Franciman good question. Since the protocol allows requests sent both ways I would argue that a request send from the server to the client can be canceled as well.

**Comment by dbaeumer** [comment]
Done
