### ISSUE TITLE
A way to request documentation from LSP server

### ISSUE THREAD

**Issue by bstaletic** [Microsoft/language-server-protocol#291]
Is there a way to send a request that would return doxygen/pydoc/java doc parsed documentatioin?

Libclang (C-family), jedi (python), racer (rust), tern (javascript) and probably others already provide ways to parse comments and return formated documentation (if available). Would be great if LSP supported this as well.

**Comment by rcjsuen** [comment]
```Java
public interface MathOperation {
  /**
   * Returns the result of adding the two integers together.
   * @param x the first value
   * @param y the second value
   * @return the sum of the two integers
   */
  public int add(int x, int y);
}
```
@bstaletic So you mean if your mouse hovered over the string `add`, the editor that you are using (a language client that supported the language server protocol) would provide a hover tooltip that contains the parsed Javadoc documentation in a readable format without the `@param` and `@return` tags?

**Comment by bstaletic** [comment]
@rcjsuen Thanks for taking the time to respond.

Yes, the tooltip with a parsed javadoc in a readable format is what I'm looking for.

**Comment by rcjsuen** [comment]
@bstaletic It sounds like the language server just needs to support a `textDocument/hover` request at that given position then. It would then satisfy the exact requirement that my [comment](https://github.com/Microsoft/language-server-protocol/issues/291#issuecomment-326793645) describes.

Or did you have something else in mind?

**Comment by bstaletic** [comment]
So `textDocument/hover` does support parsing javadoc? That wasn't clear to me. I'm actually helping in developing a LSP client. Thanks for the clarification. 

Now I'd like to ask a slightly different question. What's the best way to get just the type of the variable from the server? I initially used hover to request for getting the type. Is there a way to easily get two distinct respinses (type and doc)? Or will I have to parse the response I get from hover response?

**Comment by rcjsuen** [comment]
> So textDocument/hover does support parsing javadoc?

@bstaletic Uh, that's really up to the language server. The language server the client is connected to may or may not parse the comments defined above a function/method/member/whatever. The client just sends a `textDocument/hover` request to say "tell me what I should write in a hover tooltip at this location" and then the language server may say "this is a function with no parameters and returns a boolean" or it might just return the empty string. It may even tell you the type of the variable. The content of what a language server is "supposed" to return is not spec'd. Thus, language clients can't really "parse" the response as the returned string can be anything.

You could perhaps use `textDocument/definition` and or `textDocument/documentSymbol` to figure out what the type of a variable is but your mileage may vary here.

**Comment by bstaletic** [comment]
Okay, thanks again for taking the time to respond and help me 

I'll close tge issue now, as there really is no issue here.
