### ISSUE TITLE
[question] Is there an Open API specification for this protocol?

### ISSUE THREAD

**Issue by jvelilla** [Microsoft/language-server-protocol#297]
I would like to know if exists an Open API for it or if there are plans to add it?

**Comment by dbaeumer** [comment]
I am not sure that I understand your question. There is a reference implementation of the protocol here https://github.com/Microsoft/vscode-languageserver-node/tree/master/protocol and the specification in this repository here https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md. Do you expect more?

**Comment by jvelilla** [comment]
Sorry, I was not clear, I meant the OpenAPI specification https://www.openapis.org/, previously known as Swagger.

**Comment by dbaeumer** [comment]
No, that doesn't exist. I will close the question. If we want to add this it should come via a PR.
