### ISSUE TITLE
Range for goto definition response

### ISSUE THREAD

**Issue by nadako** [microsoft/language-server-protocol#3]
Location of a symbol for "goto definition" isn't always the word on a given location, so it makes sense to also return optional `Range` value in response, similar to `Hover`, so IDEs can highlight the actual symbol that represents a reference, not just a single word.

Here's an example from my experience:

``` haxe
using package.Module.Type;
```

Here `package.Module.Type` is the atomic symbol, language doesn't return positions for concrete words here, but for the whole type path instead. However VS Code underlines each word separately, which can be a little confusing to the user, since each of them will point to the same position.

Hence it would be nice to be able to indicate a real symbol's position for highlighting in the IDE.

**Comment by dbaeumer** [comment]
Good suggestion.

**Comment by dbaeumer** [comment]
Need to move that due to time constraints.

**Comment by dbaeumer** [comment]
@nadako I looked into this and the definition request returns Location | Location[] where Location is defined as follows:
```typescript
export interface Location {
    uri: string;
    range: Range;
}
```
I must be missing something.

**Comment by mniewrzal** [comment]
Field 'range' is for target location. This issue is to add new 'range' for place where go to definition was triggered e.g. method invocation. To underline this range.

**Comment by dbaeumer** [comment]
@mniewrzal can you outline the use case. Is it when a user selects some text beforehand and triggers the definition request that selection should be taken ?

**Comment by mniewrzal** [comment]
Yes, its exactly the case you described.
![screenshot from 2016-12-30 12-56-43](https://cloud.githubusercontent.com/assets/7313031/21564635/d7d31378-ce8f-11e6-80f0-19aebe6b315c.png)
Right now client needs to calculate this range (to style text in editor) on its own. Different languages can have different word/variable/identifier definition and it will be hard to prepare one implementation to handle all cases. If it will be on server side the range will be always accurate for language.

**Comment by dbaeumer** [comment]
@mniewrzal thanks for clarification. I think adding a range to the Goto Definition response is not a good idea. Since it describes the target location.

VS Code current takes the word definition to highlight the link. IN our case is '/' not a word separator.

To make this more flexible I think we should have a separate API to calculate this 'link' range instead of folding it into the result of Goto Definition.

**Comment by dbaeumer** [comment]
@mniewrzal the idea right now is to have a separate request.

**Comment by dbaeumer** [comment]
We now have LocationLink https://github.com/Microsoft/vscode-languageserver-node/blob/master/types/src/main.ts#L2400
