### ISSUE TITLE
Proposed API: colorProvider

### ISSUE THREAD

**Issue by aeschli** [Microsoft/language-server-protocol#300]
A color provider returns all ranges and color values in a given document. It is similar to a document symbols provider, but for color references.
The result can be used by editors to render color boxes and to show color pickers.

```typescript
export namespace DocumentColorRequest {
	export const type = new RequestType<DocumentColorParams, ColorInformation[], void, TextDocumentRegistrationOptions>('textDocument/documentColor');
}

export interface DocumentColorParams {
    /**
     * The text document.
     */
	textDocument: TextDocumentIdentifier;
}

export interface ColorInformation {
	range: Range;
	color: Color;
}

/**
 * Represents a color in RGBA space.
 */
export class Color {

	/**
	 * The red component of this color in the range [0-1].
	 */
	readonly red: number;

	/**
	 * The green component of this color in the range [0-1].
	 */
	readonly green: number;

	/**
	 * The blue component of this color in the range [0-1].
	 */
	readonly blue: number;

	/**
	 * The alpha component of this color in the range [0-1].
	 */
	readonly alpha: number;
}
```

**Comment by daviwil** [comment]
How does the editor communicate to the language server to change the color if a picker is used?  Seems like another request would be needed for that since `Color` gives no information about the text format of the color in the document.

**Comment by aeschli** [comment]
Currently, the color picker needs to have the knowledge about which color formats are valid in the given file format.

An idea would be to add a 'getColorPresentations(color, range)' client to server request.
Given a color, the server would return a set of possible presentations (`#FF0000`, `rgb(255, 0, 0)`, `hsl(0, 100%, 50%)`). I added the range here as well, in case the file contains embedded languages.
Modifications should still happen on the client side.
@rebornix @joaomoreno Thoughts?

**Comment by rebornix** [comment]
It makes perfect sense to have range in the color presentation API. Jo recommended that the color reprentation can return TextEdits, to make that happen, the extension should know both the new color info and the range.

For short, both getDocumentColorRanges and resolveDocumentColor can use { IColor, Range } as parameters and it makes the API consistent and comparable with your use case.

**Comment by aeschli** [comment]
I created https://github.com/Microsoft/vscode/issues/34366 as proposal for the API

**Comment by rcjsuen** [comment]
@aeschli OK to close?

**Comment by aeschli** [comment]
Thanks for reminding!
