### ISSUE TITLE
Snippet Syntax is not Defined in Protocol

### ISSUE THREAD

**Issue by tsmaeder** [Microsoft/language-server-protocol#303]
The syntax of code completion snippets is not defined inside the protocol. I know that there is documentation at https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/snippet/browser/snippet.md
However, as this syntax is not versioned along with the protocol, the syntax is effectively undefined. I ran accross the case where the syntax documentation has changed while I'm trying to implement it. 
Can we please move snippet definition inside the protocol?

**Comment by object88** [comment]
Is this snippet syntax the same among different IDEs, or is this particular to VSCode?

**Comment by kdvolder** [comment]
From the spec:

```
	completionItem?: {
			/**
			 * Client supports snippets as insert text.
			 *
			 * A snippet can define tab stops and placeholders with `$1`, `$2`
			 * and `${3:foo}`. `$0` defines the final tab stop, it defaults to
			 * the end of the snippet. Placeholders with equal identifiers are linked,
			 * that is typing in one will update others too.
			 */
			snippetSupport?: boolean;
		}
```

So there is a description of sorts and it is fairly precise. What isn't precisely defined here is how/if it is possible to include things that 'look like' placeholders in a snippet itself. I.e. an 'escape sequence' mechanic. I have already asked for clarification about that here:

https://github.com/Microsoft/language-server-protocol/issues/220

**Comment by tsmaeder** [comment]
@kdvolder actully, the definition of insertTextFormat refers to the VSCode documentation, which is not versioned, and as such subject to change while you were grabbing a coffee  ;-).

**Comment by kdvolder** [comment]
@tsmaeder You are confusing me (or am I confusing you :-) The text I copied comes directly from the protocol spec and it seems to describe the snippet syntax... does it not? I did not copy that from vscode documentation so it is part of the spec. The fact that vscode snippets may have the same syntax is possibly just a 'happy coincidence'.

**Comment by rcjsuen** [comment]
@kdvolder The problem is that the InsertTextFormat part of the [protocol](https://github.com/Microsoft/language-server-protocol/blob/b04dc06202bd0cbca06cd4b0b4a640aa46e8a081/protocol.md) directly mentions VS Code. The link is also not versioned (as aforementioned in the [first comment](https://github.com/Microsoft/language-server-protocol/issues/303#issue-257751990)) and points directly at `master` instead of a [permanent link](https://help.github.com/articles/getting-permanent-links-to-files/) to a specific version of the file.
```TypeScript
/**
 * Defines whether the insert text in a completion item should be interpreted as
 * plain text or a snippet.
 */
namespace InsertTextFormat {
	/**
	 * The primary text to be inserted is treated as a plain string.
	 */
	export const PlainText = 1;

	/**
	 * The primary text to be inserted is treated as a snippet.
	 *
	 * A snippet can define tab stops and placeholders with `$1`, `$2`
	 * and `${3:foo}`. `$0` defines the final tab stop, it defaults to
	 * the end of the snippet. Placeholders with equal identifiers are linked,
	 * that is typing in one will update others too.
	 *
	 * See also: https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/snippet/common/snippet.md
	 */
	export const Snippet = 2;
}
```

**Comment by tsmaeder** [comment]
@dbaeumer so is this a promise to not change the snippet format between LSP versions?

**Comment by dbaeumer** [comment]
Not in a breaking way. We might add features to it so.
