### ISSUE TITLE
Feature request: specifying cursor position upon formatting

### ISSUE THREAD

**Issue by chenglou** [Microsoft/language-server-protocol#304]
Hi! Would it be possible for the formatting protocol to return some details on the new position of the cursor(s)? Right now each editor has its own (often not-that-decent) cursor repositioning logic when a document is reformatted.

**Comment by dbaeumer** [comment]
Actually we would like to avoid this. The reason is that then we need to add support for breakpoints or other marker and decoration readjustment. 

Usually repositioning the cursor and keeping breakpoints and markers adjusted is relatively easy if the formatter returns fine grained text edits (a formatted should only touch white space anyways). If a formatter replaces the whole content (which is discouraged anyways) then I see that an editor has problems with the cursor.

I am closing the request. Open for more arguments though.

**Comment by jordwalke** [comment]
> (a formatted should only touch white space anyways)

This is not the trend we are seeing (or pushing for admittedly) with tools like `Prettier` for JS, `refmt` for Reason, and now `ocamlfmt` for OCaml.

What would change about how you would implement the reformatting API, if reformatting could potentially rewrap lines at new large/small widths which changes the line number of certain AST nodes by a large amount?

In that case, I would almost recommend a "sourcemaps" API that tells you where text ranges in the pre-formatted text, appear in the post-formatted text. From that you can easily determine the optimal cursor position (and scroll position).

**Comment by ShaneDelmore** [comment]
What about refactorings, or snippets?

**Comment by jordwalke** [comment]
@ShaneDelmore Is retaining cursor position after formatting related to snippets? Usually the snippets themselves dictate where exactly the cursor should be positioned.

**Comment by ShaneDelmore** [comment]
I misunderstood.  I read this issue as not wanting to allow the cursor to specify position.  Thanks for the clarification.

**Comment by dbaeumer** [comment]
The source map approach is an idea if we want to support replacing the whole document. However the formatting API is tailored to a minimal set of edits that transform T from s(n) to s(n+1). This will allow the client to do its best in maintain a reasonable cursor position taking all its current state into consideration (for example visible region). 

If your library computes a full new document I would advice to use a compare algorithm to create a minimal edit set.

**Comment by kdvolder** [comment]
> If your library computes a full new document I would advice to use a compare algorithm to create a minimal edit set.

Isn't this rather something we'd like to leave up to the client? I mean really, we are trying to foster the creation of many language servers. And I'd expect the most economical way to implement a formatter in many cases will just be wrapping an existing source code formatter utility that just takes in and puts out whole documents.

So I would hope clients (and protocol) would do their best to support 'whole document formatter' implementations, which, I predict, will be the majority of them as that's the easiest to implement.
