### ISSUE TITLE
Clarification: how many characters length for a line break in didSave()?

### ISSUE THREAD

**Issue by tsmaeder** [Microsoft/language-server-protocol#309]
Hi, apart from #9, one of the problems I have with the rangeLengh field in the didSave parameters is that I don't know how many characters to count for a line break. Is it the number of characters used in the original text (i.e. 2 for "\r\n")? And in that case may vary for different lines?

**Comment by dbaeumer** [comment]
Adding the rangeLength was a mistake in the first place :-(.

However the line endings to take are those of the text document initially synced over the wire. When a text document first opens the open notification contains the initial text including line delimiters.
