### ISSUE TITLE
Support for code generation?

### ISSUE THREAD

**Issue by timeraider4u** [microsoft/language-server-protocol#310]
Sorry if this has already been asked before but I have not found this question yet anywhere. I would like to ask if it is planned that LSP gets support for code generation. Like, after validation has been successful, the client can ask the server to generate binaries/intermediate files/whatever and the server might respond with a list of URIs that were generated by it. The client might then pick-up the files it is interested in (e.g., only *.exe and *.dll files) and ignore anything else (e.g., *.pdb). This feature would be quite interesting for domain-specific languages, as the dependencies for the language itself might then be dropped on the client-side.

**Comment by dbaeumer** [comment]
There is a build server protocol proposal. See https://github.com/build-server-protocol/build-server-protocol/blob/master/docs/specification.md

**Comment by timeraider4u** [comment]
While I can understand that there are no plans to implement this in the near future, I am still wondering how the build server protocol fits into this use case. As the build server protocol blog states 

> BSP and LSP are complementary. While LSP specifies endpoints for communication between an editor acting as a client and a language server, BSP specifies endpoints between a language server acting as a client and a build server.

My understanding here is that the information/control flow is like
**Client** <- _Language-server-protocol_ -> **Language server** <- _Build server protocol_ -> **Build server**

So how would an IDE identify which files where generated by a build server when the language server (protocol) does not forward this piece of information from the build server to the client? Or do I understand something wrong here?
