### ISSUE TITLE
Execute tests via lang server

### ISSUE THREAD

**Issue by sriv** [Microsoft/language-server-protocol#313]
Pardon me if this has been discussed, GH search did not yield me anything.

Testing has become first class in programming, IMO. LSP does not seem to address this. The closest I could locate is the [`executeCommand`](https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#workspace_executeCommand) which is far too generic.

Some of my expectation from testing support are:

- standardized output format, so that there can be custom test runner integration possible
- ability to rerun full/part of the test
- streaming output

If this seems like a good enough use case, I can try and put some thoughts on implementation.

I work on [Gauge](https://github.com/getgauge/gauge) where we are implementing LSP. Gauge is a test automation tool, so this issue carries a lot of importance.

**Comment by mickaelistria** [comment]
I think the execution of tests is out of the scope of LSP. https://github.com/Microsoft/vscode-debugadapter-node/tree/master/protocol is probably a better candidate as it already defines some relevant operation to execute code.

**Comment by dbaeumer** [comment]
@mickaelistria is right. The vscode-languageserver-node repository provides a protocol npm module that runs in node and can be used to implement a test client that starts and tests a server. I will close the issue. If additions are needed to the protocol npm module they should be happen there.
