### ISSUE TITLE
Clarification: is there a canonical range going to the end of a line?

### ISSUE THREAD

**Issue by arxanas** [Microsoft/language-server-protocol#317]
Conceivably, there are two possible representations of a range going to the end of a line. For example, if you have the text

```
abc
def
```

to represent the first line, you can either say

```
{
  "start": {
    "line": 0,
    "character": 0
  },
  "end": {
    "line": 0,
    "character": 4
  }
}
```

or

```
{
  "start": {
    "line": 0,
    "character": 0
  },
  "end": {
    "line": 1,
    "character": 0
  }
}
```

Should one of these representations be used over the other? Should they be considered to be equal?

**Comment by cfinegan** [comment]
I'm dealing with this issue at the moment as well. My intuition is that the former range would represent all of the text on the line excluding the newline, whereas the latter range would represent the line itself including the newline. But I'm currently dealing with a client implementation that seems to treat them equivalently, so I'm not sure if that's actually correct. Clarification on this would be great.

**Comment by kdvolder** [comment]
> My intuition is that the former range would represent all of the text on the line excluding the newline

I don't think that sounds right. The line only has 3 characters so `{line: 0, character: 4}` also includes the newline character. So yea, I think those two representations are 'equivalent'. If you don't want the newline include it should be `{line: 0, character: 3}`.

**Comment by cfinegan** [comment]
> If you don't want the newline include it should be `{line: 0, character: 3}`.

You're right, I was doing the indexes wrong in my head. Thanks.

**Comment by rcjsuen** [comment]
The two ranges given are not equivalent because one the first one doesn't include the newline character(s) and the second one does.

According to the [protocol](https://github.com/Microsoft/language-server-protocol/blob/6bc20bba03bb69b64ee6d110960e59889438c163/protocol.md):
> **Position**
> 
> Position in a text document expressed as zero-based line and zero-based character offset. A position is between two characters like an 'insert' cursor in a editor.

As a position is the area between two characters, a position of `{line: 0, character: 4}` is actually the cursor position after the `c` in `abc`. It is not representative of the newline (or carriage return on Windows) character at index 4, it is the text caret position between index 3 and index 4 (that is, the caret position right after the `c`).

> **Range**
> A range in a text document expressed as (zero-based) start and end positions. A range is comparable to a selection in an editor. Therefore the end position is exclusive.

A range that spans from `{line: 0, character: 0}` to `{line: 0, character: 4}` would highlight the three characters `abc` and nothing else given that the end position is exclusive.

**Comment by arxanas** [comment]
@rcjsuen I'm not sure I follow. When I model the positions as cursors, I get this:

```
| a | b | c | \n |
0   1   2   3    4
```

which would include the newline character.

Are you trying to say that you cannot count newline characters in the calculation of positions on line, and that `{line: 0, character: 4}` is an invalid position? If so, that would establish a canonical representation, and I think it would require some clarification in the spec.

**Comment by rcjsuen** [comment]
@arxanas Sorry. Never mind. I too was doing the math wrong in my head. :(

**Comment by dbaeumer** [comment]
It is the second. The reason is that this makes them agnostic to the line end characters used, especially when there are two like on Windows.

I added the following to the spec:

> Positions are line end character agnostic. So you can not specify a position that denotes `\r|\n` or `\n|` where `|` represents the character offset.

and for the character:

> If the character value is greater than the line length it defaults back to the line length.

and for the range:

> If you want to specify a range that contains a line including the line ending character(s) then use an end position denoting the start of the next line. For example:

```typescript
{
    start: { line: 5, character: 23 }
    end : { line 6, character : 0 }
}
```
