### ISSUE TITLE
Clarification: do diagnostics move when changes are made in the editor?

### ISSUE THREAD

**Issue by arxanas** [Microsoft/language-server-protocol#318]
Consider this scenario:

1) User opens document.
2) Language server sends diagnostic for document at line 5.
3) User deletes line 3.
4) Diagnostic in the editor has now automatically moved up to line 4. At least, this is what Nuclide does: it moves the diagnostics around for you while you're editing before diagnostics have been recalculated.

And then the user tries to initiate a Code Action request on line 4 spanning the diagnostic that has moved as a result of their edit. Does the context for that Code Action request contain a diagnostic with the original range, as was sent by the language server to the editor, or the updated range, as the editor has automatically changed on behalf of the language server?

**Comment by svenefftinge** [comment]
I think it is assumed that diagnostics are up to date with the document state, i.e. they get recomputed on change.

**Comment by arxanas** [comment]
@svenefftinge: Not all of our diagnostics are computed instantaneously, so it can't be assumed that a document has up-to-date diagnosis at every moment in time. But neither is it a good user experience to clear out diagnostics on every edit, especially when most of them will still be valid.

**Comment by dbaeumer** [comment]
@arxanas this should be done in conformance with the client / tools. For example VS Code moves the diagnostic in the editor however not in the marker manager. Other tools might not even move them in the editor.

However the context can only be used as a hint and may be in single file languages be trusted if the version document is still the same as when the diagnostic got computed. In multi file languages (like TS or C#) an edit in file A can make errors in file B make got away or appear. So you can not trust the diagnostics in file B even if no edits occurred in file B.

When the code action request is sent to the server the client makes sure that any outstanding edits have been pushed to the server as well. So the server has the latest content. 

I am open for adding a version number to the diagnostic object to enable better use of the context. However I am not sure if that saves a lot. @arxanas can you describe your use case when you want to rely on the context being accurate.

**Comment by arxanas** [comment]
@dbaeumer In my use-case, the language server is keeping its diagnostics in memory. Each diagnostic optionally has a lambda associated with it to calculate its code action.

The simplest way to implement this is to take the context that's provided by the editor and look up the diagnostic in memory that has the same code and position. If the diagnostics positions are stale because of edits that are still being processed, then this wouldn't work.

It might just be that this isn't a good way to do it for the reasons you specify: that, for example, edits in a different file can invalidate the diagnostics in the current file, even without changing their positions. With my method it would be very easy to calculate the code action, although it's questionable whether it should still apply.

As I see it, my options are as follows:

1) Try to mirror the movements of the diagnostics in the file to be able to still look them up by position. Don't require that all edits be processed before providing code actions. This is a little bit fragile since it depends on the vagaries of the editor in question.
2) Calculate a code action directly from a diagnostic code and position and current document content, rather than relying on the lambda saved in a previous diagnostic run. Don't require that all edits be processed before providing code actions. In my case, this would require some changes to our linter infrastructure, but it's not necessarily unreasonable. From my understanding, Visual Studio operates this way.
3) Require all edits be processed before responding to a code actions request. Some of our linters have performance problems, so I'm not especially inclined to go down this path, unless I were to add a timeout and then try to provide a best-effort code action. However, this is the only solution that is guaranteed to always get a correct result.

**Comment by dbaeumer** [comment]
@arxanas the advice is to do something like this: https://github.com/Microsoft/language-server-protocol/issues/325#issuecomment-344967548

Even if the editor moves diagnostics they can not be trusted at the end. The might be stale for various reasons. They can only be interpreted as a hint.

**Comment by arxanas** [comment]
I think this is clarified by your answer. The editor may move the diagnostics, but this is only a hint, not a guarantee. Closing.
