### ISSUE TITLE
Clarify whether the order of multiple TextEdits matters and what 'overlapping text edits' means

### ISSUE THREAD

**Issue by aeschli** [Microsoft/language-server-protocol#321]
> If multiple `TextEdit`s are applied to a text document, all text edits describe changes made to the initial document version. Execution-wise text edits should be applied from the bottom to the top of the text document. Overlapping text edits are not supported.  

- clarify whether multiple inserts at the same location are allowed or considered  'overlapping text edits'
- clarify whether inserts, replaces and deletes can have the same location.
- clarify if edits are sorted by the sender, or whether receiver needs to sort them (and how).
- ideally, provide a code sample (maybe even API on TextDocument) on how to apply edits

**Comment by tsmaeder** [comment]
If the language server does not have to order the text edits in the list (as https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#new-textdocumentedit says), the client needs a way to sort the text edits. This would mean ,IMO, that multiple edits in the same location should not be allowed.

**Comment by dbaeumer** [comment]
Here is what we IMO need to spec:

- edits overlap iff edit1.end > edit2.start
- if edits touch each other (edit1.end == edit2.start) the order in which they appear matters. The client needs to first apply edit1 and then edit2 iff indexOf(edit1) < indexOf(edit2). Otherwise edit2 and then edit1.
- it is up to the client to determine on how to best apply these edits. This might depend on API already available on the client.

**Comment by dbaeumer** [comment]
@aeschli do you want to take care of this?

**Comment by kdvolder** [comment]
@dbaeumer I sort of disagree with your interpretation. IMO the point of having a stipulation that 'edits do not overlap' would be precisely to avoid complexities in the spec of having to specify any details around what order a client should apply them in. In other words the order shouldn't matter to the semantics. Therefore I think we should consider that even if the edits just 'touch' eachother they should be considered as 'overlapping'.

I.e any edits that server could merge together into a single equivalent edit should be considered as 'overlapping' and it should not be allowed. A well-behaved server should make sure to merge such edits to avoid any potential ambiguities around their application order.

**Comment by dbaeumer** [comment]
IMO the complexity is the same whether we say that the server needs to merge them or the client needs to handle this. 

From implementing two servers calling into other libraries both created touching edits but never overlapping edits.

**Comment by rictic** [comment]
It might be helpful to separate the WorkspaceEdit out into atomic units of work.

A sketch of a design, which also better handles overlapping edits from independent sources:

Allow `applyEdits` to take an array of WorkspaceEdits. Each WorkspaceEdit is considered an atomic change, it is either applied completely or not at all. Insertions at the same place are handled in order, as @dbaeumer describes above. Insertions at the same place by distinct WorkspaceEdits are considered overlapping. `applyEdits` when called with an array of WorkspaceEdits returns `{appliedEdits: WorkspaceEdit[], incompatibleEdits: WorkspaceEdit[]}`. Every edit in incompatibleEdits either overlaps with itself or with at least one edit in appliedEdits.

**Comment by dbaeumer** [comment]
@aeschli ping :-)
