### ISSUE TITLE
Synchronous API awkward in node

### ISSUE THREAD

**Issue by NotRelevant** [Microsoft/language-server-protocol#323]
I'm trying to implement a language server in Node, based on the lsp example. This language server is a bridge between VS Code and a remote compile server - it fulfils requests for, e.g. hover or code completion by making requests to the compile server and then awaiting the results.

It seems to be pretty much impossible to do this due to the mismatch between the synchronous onHover/onCompletion function call from VS Code, and the asynchronous nature of the request to the compile server - VS Code expects a result to be returned immediately from the IConnection.onHover callback, but Node expects to call back with results at some point in the future.

Is there any possibility of implementing asynchronous alternatives to onHover, onCompletion etc. that allow for hover and completion results to be returned to VS Code asynchronously, rather than immediately?

**Comment by NotRelevant** [comment]
Realised  this is an issue with the node implementation rather than with the protocol.

**Comment by rcjsuen** [comment]
@NotRelevant You can return results asynchronously with `vscode-languageserver` if you want. I have some TypeScript code that looks like this and it works fine.

```TypeScript
connection.onCompletion((textDocumentPosition: TextDocumentPositionParams): CompletionItem[] | PromiseLike<CompletionItem[]> => {
  /* ... */
});
```

**Comment by NotRelevant** [comment]
Thanks, that's exactly what I need.

**Comment by dbaeumer** [comment]
Each method on the server can either return the value or a promise resolving to the value (which allows async calls to other servers)
