### ISSUE TITLE
Getting value after executing command programmatically 

### ISSUE THREAD

**Issue by starcev** [Microsoft/language-server-protocol#329]
I have registered specific commands both on server and client. I am trying to fetch values from lang server when command is executed, but instead value is undefined. Is it possible to do that?

**Comment by dbaeumer** [comment]
Can you please provide an example of what you want to achieve?

**Comment by starcev** [comment]
I have defined command in **package.json**, for e.g.

"commands": [
			{
				"command": "my_cmd",
				"title": "My cmd"
			}
]

What I want is to call _vscode.commands.executeCommand("my_cmd")_ and get result returned by language server that I also created.
I have tried something like this:

var returned = vscode.commands.executeCommand('my_cmd')
                        .then(function(result)
                        {
                               // do something with result
                        });

but the result is undefined. So, is that even possible?
Thank you for your response.

**Comment by dbaeumer** [comment]
From where do you call the command. From the client or the server. Command execution from the server is currently not possible and would require to specify valid commands which is almost impossible given that a server should work with n clients.

**Comment by starcev** [comment]
I am calling the command from the client. And on the server I have a function which has a command name and arguments as function parameters. So, I can handle different commands and return different objects from the server.
The flow is something like this:
executeCommand - client  =>  hit function - server  =>  process and return value - server => fetch value - client
and the problem is that I can't fetch value.

**Comment by dbaeumer** [comment]
Actually that should work. Have you registered the commands from the server using the ServerCapabilities.executeCommandProvider property.

**Comment by danixeee** [comment]
Hello, I am working on the same extension. I have looked at source code of _vscode-languageclient_ module and tried to log server's response.
I have replaced this part:

`client.sendRequest(vscode_languageserver_protocol_1.ExecuteCommandRequest.type, params)
.then(undefined, (error) => { ... });`

with this:

`client.sendRequest(vscode_languageserver_protocol_1.ExecuteCommandRequest.type, params)
.then((result) => console.log(result) , (error) => { ... });`

to be sure that server is returning a value. And it does.

Our activation function:

```
export function activate(context: ExtensionContext) {
	context.subscriptions.push(startLangServer('...', [], []))

        vscode.commands.executeCommand('my_cmd')
                        .then((result)=>
                        {
                               console.log(result); // undefined
                        });
}
```
**package.json** has commands section described in above comment.
Do we need to register command programmatically, too?
Although, we tried that (and removed commands section) and result is still undefined.

**Comment by dbaeumer** [comment]
@danixeee now I understand. We should continue the discussion in https://github.com/Microsoft/vscode-languageserver-node. In general this should work and it is not a specification problem. Looks more like a bug either in VS Code or in one of the LSP libraries.

Can you try to produce a minimal example using the LSP client and server module I can clone and open a new issue here: https://github.com/Microsoft/vscode-languageserver-node. Then I can definitely have a look and see why it is not working.
