### ISSUE TITLE
formatOnTyping do not work for my language server

### ISSUE THREAD

**Issue by liwangqian** [Microsoft/language-server-protocol#330]
I add the typing format trigger char to my server capabilities as bellow, but it dos not work, when i type `;`, the server do not receive the request.

```js
capabilities: {
            documentOnTypeFormattingProvider: {
                firstTriggerCharacter: ";"
            }
}

...

connection.onDocumentOnTypeFormatting(params => {
    coder.tracer.info('onDocumentOnTypeFormatting');
    return coder.formatOnTyping(params);
});

```

My env:
vscode-languageserver@3.4.3
vscode-languageclient@3.4.5
vscode-languageserver-protocol@^3.4.4
vscode: 1.17.2

Any help is apreciate.

**Comment by rcjsuen** [comment]
You should probably open your bug in the against the [Microsoft/vscode](https://github.com/Microsoft/vscode) or [Microsoft/vscode-languageserver-node](https://github.com/Microsoft/vscode-languageserver-node/) repository.

@liwangqian Did you set `"editor.formatOnType": true` in your VS Code settings?

**Comment by liwangqian** [comment]
@rcjsuen Yes, `"editor.formatOnType": true` is in my settings, I will commit an issue to  Microsoft/vscode-languageserver-node repository, thinks you any way.
