### ISSUE TITLE
Kind mapping in specs does not match mapping in implementation

### ISSUE THREAD

**Issue by Naatan** [Microsoft/language-server-protocol#347]
The SymbolKind mapping under https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#textDocument_documentSymbol does not match the one defined at https://github.com/Microsoft/vscode-languageserver-node/blob/master/types/src/main.ts#L731 at all.

Given that this is the protocol specification and the languageserver code is used in production at this stage I think the protocol docs ought to be updated.

**Comment by laughedelic** [comment]
You're comparing two different things: `SymbolKind` and `CompletionItemKind`. It's easy to confuse them, I did it too at first.. 😉

**Comment by Naatan** [comment]
Oh fun. I didn't consider they'd be different. Thanks!
