### ISSUE TITLE
SymbolKind has odd syntax

### ISSUE THREAD

**Issue by MarkZ3** [Microsoft/language-server-protocol#349]
```
export namespace SymbolKind {
...
	export const Array = 18;
	export const Object: 19 = 19;
	export const Key: 20 = 20;
	export const Null: 21 = 21;
	export const EnumMember: 22 = 22;
	export const Struct: 23 = 23;
	export const Event: 24 = 24;
	export const Operator: 25 = 25;
	export const TypeParameter: 26 = 26;
}
```

Object: 19 = 19? Perhaps I'm not familiar enough with Typescript, but wouldn't Object: 19; be the same?

**Comment by dbaeumer** [comment]
Object: 19 = 19 defines a const Object of type 19 and initializes it with 19. Leaving : 19 out would make it of type number.

I agree that for the protocol itself it doesn't make sense. I will remove the type.

**Comment by dbaeumer** [comment]
Done.
