### ISSUE TITLE
Find References documentation is a bit ambiguous

### ISSUE THREAD

**Issue by luolong** [Microsoft/language-server-protocol#35]
The [Find References] section in protocol specification is a little ambiguous at the moment.

Here's what it says at the moment:
> The references request is sent from the client to the server to resolve project-wide references for the symbol denoted by the given text document position.

> >**Changed:** In 2.0 the request uses `TextDocumentPositionParams` with proper `textDocument` and `position` properties. In 1.0 the uri of the referenced text document was inlined into the params object. 

> _Request_
> * method: 'textDocument/references'
> * param: `ReferenceParams` defined as follows:
> ```typescript
interface ReferenceParams extends TextDocumentPositionParams {
	context: ReferenceContext
}
```
> ```typescript
interface ReferenceContext {
	/**
	 * Include the declaration of the current symbol.
	 */
	includeDeclaration: boolean;
}
```
> * error: code and message set in case an exception happens during the reference request.

It is unclear to me whether `ReferenceParams` is a parameter to 'textDocument/references' request or it is a response param. 

It seems to me that this section is missing a _Response_ subsection with a description of the response params, but I can not tell for sure...

[Find References]: https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#find-references

**Comment by dbaeumer** [comment]
Good catch. It was missing the result section. Fixed it.
