### ISSUE TITLE
Syntax Highlight Problem When writing codeblock in Markdown

### ISSUE THREAD

**Issue by plehdeen** [Microsoft/language-server-protocol#351]
- VSCode Version: 1.18.1
- OS Version: Windows 10

take this pic as a example, the syntax highlight not work for the code in the bracket...
Can someone just give me some tip if it's my own problem.

![vscode_highlight_markdown](https://user-images.githubusercontent.com/12212092/33832924-d1f0bf8e-deb8-11e7-9703-2fbd93953e4d.png)

**Comment by rictic** [comment]
I think this is a VSCode issue and should be filed at https://github.com/Microsoft/vscode/issues/new

The language server protocol doesn't do syntax highlighting.

**Comment by plehdeen** [comment]
sorry to bother here.
