### ISSUE TITLE
Add a SymbolKind for macros

### ISSUE THREAD

**Issue by MarkZ3** [Microsoft/language-server-protocol#352]
It would be useful to have have a SymbolKind::Macro so that in C/C++ one could do the "Workspace Symbols" request and get matching macros as a result.

**Comment by natebosch** [comment]
https://github.com/Microsoft/language-server-protocol/issues/344#issuecomment-347202468

**Comment by MarkZ3** [comment]
Thanks! It's probably better to close this one then.
