### ISSUE TITLE
Is there standard suite of tests to test a new language server against?

### ISSUE THREAD

**Issue by cazador481** [Microsoft/language-server-protocol#353]
I want to create a new language server in perl.  I was wondering if there is a standard suite of tests that I can run on my language server to make sure that I implemented it properly?

**Comment by mickaelistria** [comment]
As there is no standard output one can expect from any language server (the output fully depends on the implementation), there is no test suite for it.
The best way to test your language server is to try it in one or several of the various clients: https://github.com/Microsoft/language-server-protocol/wiki/Tools-supporting-the-Language-Server-Protocol

**Comment by dbaeumer** [comment]
Agree with @mickaelistria. 

There is a LSP client written in JS that runs in pure node. It is here: https://www.npmjs.com/package/vscode-languageserver-protocol. It might be useful to test our specific perl server.
