### ISSUE TITLE
Create a better table of contents for `protocol.md`

### ISSUE THREAD

**Issue by MrYurihi** [Microsoft/language-server-protocol#356]

**Comment by dbaeumer** [comment]
@MrYurihi we are working on moving the protocol.ms to its own web site using github pages. The specification page will then look like this:

I will close the issue in favor of the work on the web site.

![capture](https://user-images.githubusercontent.com/1931590/34111133-26e1d9d8-e409-11e7-995a-4e7ef60e4805.png)
