### ISSUE TITLE
From a language-agnostic perspective, what is a workspace?

### ISSUE THREAD

**Issue by shlevy** [Microsoft/language-server-protocol#360]
I'm new to investigating the LSP in any depth, forgive me if this is well known or documented somewhere I missed, but what are the semantics associated with a "workspace"? My guess is that it's a single project in the sense that all files of a given language in the workspace should have the same configuration (e.g. all python files should use python 2.7, all haskell files should use the same package set for dependencies, etc.), but I'm not sure this is correct.

Operationally, this question can be reframed as: When implementing an lsp client, when should I launch a new instance in a new workspace? How do I determine what to pass as the workspace root?

**Comment by rcjsuen** [comment]
> When implementing an lsp client, when should I launch a new instance in a new workspace? How do I determine what to pass as the workspace root?

I think this question is very difficult to answer, @shlevy. It really depends on each individual language server's implementation.

For example, consider a language server for json or xml or yaml files. Such a language server is (probably) not going to care what you send in as the workspace root. They just parse one single file and doesn't look for "references" or traverse up or down any folder structures. You could (again, probably) start up the language server with a `rootUri` of `/a/b/c` but open up a `/d/e/f.txt` file and it would probably still work. This workflow is not at all that abnormal. Many IDEs and editors let you open and "focus" on a single folder structure but nothing is going to stop you from using 'File > Open File...' or drag and drop a random file from a file explorer into the editor, right?

In my language server for Dockerfiles, I don't even bother reading the `rootPath` or `rootUri` properties in the `initialize` request. I just look at `textDocument/didOpen`, `"textDocument/didChange`, and `"textDocument/didClose` events and deal with each file individually.

However, ignoring the `rootPath` or `rootUri` is not going to fly for stuff like Java as the language server is probably going to look for some Maven `pom.xml` file or Eclipse `.classpath` file under said root folder to determine how to read and interpret the underlying folder/project structure.

**Comment by rictic** [comment]
Speaking for vscode, sublime text, and atom, a workspace maps to the directory that the user opened pointed their editor at. Usually this is the root directory of a package/project.

**Comment by dbaeumer** [comment]
From an LSP perspective a workspace is a container for resources (files and folders). Whether a server puts restrictions onto the layout of the folders or the configuration (all use Python 2.7) is up to the server. The LSP can't spec this. For example the TypeScript server can handle n folders in a workspace with different configurations. Other server might work differently. I will close the issue unless we see arguments to spec this in the LSP. Please ping if this is the case.
