### ISSUE TITLE
Reduce RegEx capabilities to smaller and more common set

### ISSUE THREAD

**Issue by hauleth** [microsoft/language-server-protocol#363]
[Current definition of snippets syntax](https://github.com/Microsoft/language-server-protocol/blob/e8db47b2e8dd1abd7ce99dae44afadaa55033b89/snippetSyntax.md) defines:

```ebnf
regex       ::= JavaScript Regular Expression value (ctor-string)
options     ::= JavaScript Regular Expression option (ctor-options)
```

JS RegEx engine is quite big and it would be hard to provide support for it in non-JS based editors without adding dependency on some JS engine.

Also such definition allows for any back references which is known to cause problems (when backtracking, and also makes such engine broader than only regular languages).

Solution would be to reduce **required** support to subset of commonly used syntaxes.

Such engine should also not support back references for security reasons.

**Comment by puremourning** [comment]
Also, support for these complex snippets should be a capability. It seems that as soon as you declare support for snippets, you're binding yourself to implementing a potentially changing snippet specification.

Or at least, version the specification of snippets maybe ?

For example, in Vim there's no way to support JavaScript regexes.

**Comment by dbaeumer** [comment]
I moved the snippet request to it own issue.
