### ISSUE TITLE
Specification navigation on website isn't scrollable and is chopped off

### ISSUE THREAD

**Issue by DanTup** [microsoft/language-server-protocol#366]
Not sure if this is the correct place to raise this since it's about the website rather than the spec/protocol, but on my MacBook in Chrome, the nav down the right hand side of this page here cannot be scrolled and is chopped off. Not sure if there's also some layout issue because some items like `resolve` appear multiple times; not sure if they're intended to be indented under parents?

<img width="1440" alt="screen shot 2017-12-30 at 13 39 54" src="https://user-images.githubusercontent.com/1078012/34454629-1dad9f52-ed67-11e7-81dd-f324be115df3.png">

**Comment by dbaeumer** [comment]
Anyone that knows enough about bootstrap to get a scroll bar into a navigation list?

**Comment by dbaeumer** [comment]
Alternatively we could create smaller / more groups

**Comment by dbaeumer** [comment]
I improved the grouping of the navigation bar. @DanTup can you see if this addresses it on a MacBook. I don't have one handy.

Keep the item open since there is more work necessary to handle the layout when presented on even smaller devices (iPad, ..)

**Comment by DanTup** [comment]
@dbaeumer If I hide my bookmarks bar (which I normally do when taking screenshots, like I did above) then it *just* fits in. However as I would normally browse (with a bookmark row) it's still slightly off the bottom (this is a standard MacBook 2017 at 100% zoom):

<img width="268" alt="screen shot 2018-01-08 at 18 00 58" src="https://user-images.githubusercontent.com/1078012/34684765-1abbd73a-f49e-11e7-9872-43d41e5bf93c.png">

Though I guess if you're going to make changes to support smaller resolutions it'll fix this too.

**Comment by dbaeumer** [comment]
Thanks. The dynamic layout options for bootstrap will very likely move the navigation box to the bottom of the screen.
