### ISSUE TITLE
ErrorCodes.RequestCancelled exceeds int16

### ISSUE THREAD

**Issue by szatanjl** [microsoft/language-server-protocol#378]
Why is RequestCancelled equal to -32800?

Firstly why it is not defined in the range -32000 and -32099 like 4 other protocol defined errors (serverErrorStart, serverErrorEnd, ServerNotInitialized, UnknownErrorCode)?
Also suggested by the JSON-RPC specification
> -32000 to -32099 | Server error | Reserved for implementation-defined server-errors.

Secondly it is now the only error code that exceeds INT16_MIN.  Only this one error code makes it necessary for server and client implementations to use integral type bigger than 16 bits.  All other codes have nice property of fitting into int16 type.  Or as I like to think about it they can all fit into int type on all C compliant implementations which is the typical/standard integral type for returning error codes from functions.

I think that people creating JSON-RPC also had this nice property in mind when reserving the codes that do not exceed INT16_MIN
> The error codes from and including **-32768** to -32000 are reserved for pre-defined errors

Because of these I would suggest to change the RequestCancelled code.

**Comment by dbaeumer** [comment]
This is a breaking change and is something we should decide carefully. I am personally not seeing a big Win of changing this as a breaking change.

**Comment by szatanjl** [comment]
I just opened the clangd implementation and right off the bat I can see these:
clangd/Protocol.h:35
`
enum class ErrorCode {
  // Defined by JSON RPC.
  ParseError = -32700,
  InvalidRequest = -32600,
  MethodNotFound = -32601,
  InvalidParams = -32602,
  InternalError = -32603,

  ServerNotInitialized = -32002,
  UnknownErrorCode = -32001,

  // Defined by the protocol.
  RequestCancelled = -32800,
};
`
clangd/JSONRPCDispatcher.cpp:80
`
void clangd::replyError(const Context &Ctx, ErrorCode code,
                        const llvm::StringRef &Message) {
  log(Ctx, "Error " + Twine(**static_cast<int>(code)**) + ": " + Message);
`
C/C++ int can be as small as 16 bits so this is clearly an error.  Technically this isn't an error of the LSP specification but rather in the implementation.  Anyhow this could be avoided if RequestCancelled code was in the range -32000 to -32099 with others.

I realize that now the change is not so simple as it would break backward compatibility.  On the other hand I imagine it shouldn't be the hardest thing to change - most/all the implementations should have the list of codes in enum like structure, and the change would only take place in one line of code.  At the same time I think it would be a good change, also to keep in mind for future to not add new error codes exceeding INT16_MIN.

**Comment by dbaeumer** [comment]
I clean this up as good as I could for 3.16. In addition I introduced an integer type to clarify the range.
