### ISSUE TITLE
Multiple diagnostics in codeAction for selection

### ISSUE THREAD

**Issue by BugDiver** [Microsoft/language-server-protocol#383]
The code action request is not having the correct range and diagnostic. If multiple lines selected the code action request should be having the correct range and all the diagnostics in that range.
Currently, it is just having one diagnostic.

**Comment by rcjsuen** [comment]
@BugDiver What editor/client are you using? This repository is for the specification of the protocol. I think you need to open an issue with the editor/client that you are using.

**Comment by BugDiver** [comment]
@rcjsuen I'm using `vscode`. any way I'll move it to `vscode`.

**Comment by BugDiver** [comment]
This issue was moved to Microsoft/vscode#41897

**Comment by BugDiver** [comment]
This issue was moved to Microsoft/vscode#41898
