### ISSUE TITLE
Needs clarification for expected server behavior when completion resolve capability is false

### ISSUE THREAD

**Issue by PavelSosin** [Microsoft/language-server-protocol#385]
It is less clear for me in V 2 what is the expected server behavior in the case when CompletionOptions Resolve attribute is false, i.e. CompletionItem Resolve request can't be sent to access additional information. Does it mean that server sends additional ainformation is sent by server as a part of Completion request's response or some servers can't  send this information neither in response on Completion request neither support Resolve?
How to ensure that Code completion is consistent? Minimal additional information is Text Edits or something which can be used for text editing. Text edit field can be optional for the certain LSP protocol method but it is not the case for editors because when user selects a line in completion proposals the expectation that text is edited.

**Comment by dbaeumer** [comment]
It means that the server will never send incomplete CompletionItem hence the client never needs to send a resolve request (the server will not honor such a request). If the server does send incomplete item the client is free to drop them if the server doesn't provide a resolve route.

Sorry for the late answer. OK for you to close ?
