### ISSUE TITLE
can i restart vscode in language server?

### ISSUE THREAD

**Issue by zrhzhouronghui** [Microsoft/language-server-protocol#395]
i write a language server using python, can i restart vscode in language server? lsp have 'window/showMessageRequest' ,but it haven't provide restart action

**Comment by rcjsuen** [comment]
@zrhzhouronghui Why do you want a request to explicitly restart the language server?

**Comment by zrhzhouronghui** [comment]
@rcjsuen because some changes in language server have to restart vscode to take effect ，or can you provide execute command from server，then i can execute 'workbench.action.reloadWindow' command ？

**Comment by rcjsuen** [comment]
The client should be what's controlling the language server. It doesn't make sense for the language server to tell the client to restart in my opinion.

**Comment by zrhzhouronghui** [comment]
i will restart language server instead
