### ISSUE TITLE
setting Capabilites

### ISSUE THREAD

**Issue by willt** [Microsoft/language-server-protocol#397]
I'm at a complete loss on how to set client capabilities. I'm trying to set this one so I can send versioned edits. WorkspaceClientCapabilites.workspaceEdit.documentChanges

My client more or less looks like the one here: https://code.visualstudio.com/docs/extensions/example-language-server
I've spent a few hours search and digging I just can't figure it out. 
Non versioned edits work fine using 'changes' instead of 'documentChanges'
I'm about to give up on versioned edits :(
Running vscode  1.19.3
Thanks!

**Comment by rcjsuen** [comment]
@willt Sorry, but I don't understand your question. Which of the following applies to what you are doing?

1. You are writing an editor/IDE and you are making it support the language server protocol.
2. You are writing a VS Code extension to support a language server.
3. You are writing a VS Code extension to support a language server that you have written.
4. You are writing a plug-in to some third-party editor/IDE to talk to a language server.
5. None of the above.

**Comment by willt** [comment]
@rcjsuen Sorry  number 3 I believe. Its the vscode extension client portion to talk to a language server im writing.

**Comment by rcjsuen** [comment]
@willt Please open an issue in the [Microsoft/vscode-languageserver-node repository](https://github.com/Microsoft/vscode-languageserver-node) then.

**Comment by willt** [comment]
sorry it was later when I wrote this. Didn't realize it was the wrong spot. Thanks for showing me the way.
