### ISSUE TITLE
Question about textDocument/rename

### ISSUE THREAD

**Issue by willt** [Microsoft/language-server-protocol#402]
One of the parameters for this is
`/**
	 * The position at which this request was sent.
	 */
	position: Position;
`
This appears to be only the cursor position.  Shouldn't it include the start/end range of the selected symbol you are renaming?

I haven't tried elsewhere but in vscode, when you press F2 to rename a symbol it only sends the position of the cursor whether you have the word selected or not. It provides a drop down for you to type in a new name so presumably it has the position information already. Why not send it? I would argue it should be a requirement for the whole range to be sent.

It seems like currently unless im missing something obvious that this shifts a lot of work to the LS for renaming. At the same time I think it would be nice if it sent the original symbol name along with the new one. I mean why not ?

**Comment by rictic** [comment]
The boundaries of a symbol are language-specific. 

When renaming the HTML tagname `<foo-bar>` the symbol to rename is `foo-bar`. When renaming a variable in the python expression `10<foo-bar>20` (IIRC this is legal python), the symbol is either `foo` or `bar`.

**Comment by willt** [comment]
@rictic I get they are language specific. From what I can tell though, in vscode when you press F2 to rename something, it pulls up its rename box with what ever it determines is the symbol boundary. Nothing is sent to the language server at that point. Shouldn't some communication occur at that point? How can they agree on what to rename ?

For instance lets assume the language server knows that `foo-bar` is a valid symbol. In vscode, unless you select the whole symbol, either `foo` or `bar` will be populated in the rename box depending on where your cursor is.

Should the language server reject renames to just `foo` or `bar` or just decide to rename `foo-bar` because it knows it's the full symbol?

If the whole range or the original symbol of what the editor thought it was renaming was sent along with the request at least they could be sure they were renaming the same thing.

**Comment by bmewburn** [comment]
A language server cannot trust a range completely as the selection of the range is outside of the control of the language sever. 

For example clients could set different word separators leading to multiple or partial symbols in the range. Language servers would need to work out if the range covered multiple or a partial symbol. Which symbol would the rename apply to in the case of multiple? Would multiple names need to be sent for each symbol in the range? 

I think this would increase the complexity of the rename feature without providing a strong benefit.

**Comment by amiramw** [comment]
In vscode you can try to rename everything. For example `class` keyword in Java has this option which doesn't work. The same thing goes for go to definition, etc.
Maybe there is a need to add an "is symbol" API given a position to allow better user experience on these flows?

**Comment by rcjsuen** [comment]
@amiramw If the API from https://github.com/Microsoft/vscode/issues/7340#issuecomment-381926228 is adopted then I think that can be achieved.

**Comment by dbaeumer** [comment]
Anyone willing to provide a PR for this to add a textdocument/resolveRenameLocation request to the LSP?

**Comment by dbaeumer** [comment]
Wrong issue :-)

**Comment by dbaeumer** [comment]
Dups https://github.com/Microsoft/language-server-protocol/issues/455
