### ISSUE TITLE
Question: would proposing a 'playgrounds' extension to LSP be sensible?

### ISSUE THREAD

**Issue by trezona-lecomte** [Microsoft/language-server-protocol#404]
Hi there,

I'm interested in whether folks think it would be appropriate and worthwhile to propose an an extension to the LSP specifying 'playgrounds' functionality, à la the playgrounds feature in XCode or http://support.hfm.io/1.0/playgrounds.html (the 'Playground editor' and 'Playground Results and Types' components specifically).

The background is that I'd like to start working on 'playgrounds' functionality for Haskell & Elm in Emacs. To me it seems that it would be most constructive to build on LSP so that other languages and editors can more readily implement this set of features.

The best TL;DR I've found of what I mean by 'playgrounds' functionality is the right-hand side of the image on http://support.hfm.io/1.0/playgrounds.html. This image demonstrates adding code to the playground pane and having the results of evaluating that code (and type info if applicable) shown on the corresponding line in the results pane.

Would this, in theory, be a natural fit for the LSP? Or am I better off just focusing on tools specifically for Emacs?

Thanks,

Kieran

**Comment by mickaelistria** [comment]
Playgrounds seem to be one form of execution, so they would probably fit better in the Debug Protocol which does understand some concepts about launching: https://github.com/Microsoft/vscode-debugadapter-node/tree/master/protocol

**Comment by trezona-lecomte** [comment]
That's interesting @mickaelistria, I haven't heard of the Debug Protocol before. Is this something that is exclusive to VS Code at the moment?

You're correct that playgrounds require evaluation of code; in essence they serve a similar purpose as an automated REPL with results being displayed per line. It's possible that this is too far away from the other features specified by the LSP. I'm not sure how close playgrounds are to the debug features currently specified by the Debug Protocol either, so perhaps the more natural delineation would be to have a distinct Playgrounds Protocol.

**Comment by mickaelistria** [comment]
>
> That's interesting @mickaelistria <https://github.com/mickaelistria>, I
> haven't heard of the Debug Protocol before. Is this something that is
> exclusive to VS Code at the moment?
>
Nope, it's open to any IDE to support it. Eclipse IDE does support it for
instance through the LSP4E project (which also brings support for LSP)


> You're correct that playgrounds require evaluation of code; in essence
> they serve a similar purpose as an automated REPL with results being
> displayed per line. It's possible that this is too far away from the other
> features specified by the LSP. I'm not sure how close playgrounds are to
> the debug features currently specified by the Debug Protocol either, so
> perhaps the more natural delineation would be to have a distinct
> Playgrounds Protocol.
>
Playgrounds are basically consoles with stdin/stdout. What would a
Playground Protocol do more/better than starting a console on the right
REPL applicaiton here?

**Comment by trezona-lecomte** [comment]
> Nope, it's open to any IDE to support it. Eclipse IDE does support it for instance through the LSP4E project (which also brings support for LSP)

Okay, I'll have a look at whether this functionality would be a natural fit in the Debug Protocol.

> Playgrounds are basically consoles with stdin/stdout. What would a Playground Protocol do more/better than starting a console on the right REPL applicaiton here?

I'm unsure whether you're asking:

1. Why should we have a protocol rather than just implementing an Emacs extension for Haskell/Elm that does thing? The answer to this is the same as the rationale behind the LSP.
2. Why use a playground when you can just use a REPL? The answer to this is that a REPL is manual while a playground is automated. As soon as you type an expression it is evaluated and the results shown in the playground pane. Think of dot completion: we _could_ accomplish the same end manually by loading a REPL and finding all of the methods that can be invoked on a given object, however it's much more convenient to have those methods shown automatically in your editor.

**Comment by dbaeumer** [comment]
I agree with @mickaelistria comments.

@trezona-lecomte I will close the issue assuming that it will continue in the debugger protocol land. Please ping if you disagree.
