### ISSUE TITLE
support for inline codelens

### ISSUE THREAD

**Issue by mickaelistria** [microsoft/language-server-protocol#405]
Currently, codelens are only line "headers". In practice, several examples show that such text decoration can also be pretty useful inline, between two characters. For example, IntelliJ (and soon Eclipse IDE) allow to show the parameter name on ambiguous methods.
CodeLens should be allowed to receive as parameter a text position (line/column) where to be inserted, and in case column is missing, it could default to current behaviour which is about making a line header.

**Comment by kjeremy** [comment]
rust-analyzer has an [issue](https://github.com/rust-analyzer/rust-analyzer/issues/2797) for figuring out how to upstream their version of this.

**Comment by angelozerr** [comment]
IMHO I think https://github.com/microsoft/language-server-protocol/issues/745 should be more generic than Codelens only.

**Comment by dbaeumer** [comment]
I will fold this with https://github.com/microsoft/language-server-protocol/issues/956
