### ISSUE TITLE
Question: is the max open count of 1 enforced?

### ISSUE THREAD

**Issue by keyboardDrummer** [Microsoft/language-server-protocol#407]
In the LSP documentation for the `DidOpenTextDocument` notification it mentions that:
> An open notification must not be sent more than once without a corresponding close notification send before. This means open and close notification must be balanced and the max open count is one.

This seems awfully restrictive for text editors, since it would mean only 1 file with unsaved changes can be open at once. How is this being resolved in practice? Are LSP servers simply allowing a bigger max open count than 1? But then how can they indicate that this is allowed?

Another hypothesis I have is that many LSP servers in the `TextDocumentSyncOptions` of their `ServerCapabilities` set `openClose` to `false`, so they don't require sending open and close notifications, and instead rely on `didChange` and `didSave` notifications to know for what files to keep state in memory.

**Comment by rcjsuen** [comment]
I just tried opening two files in Visual Studio Code and it sent two separate `textDocument/open` notifications. I think the specification is trying to say that it's not valid to send two `textDocument/open` requests for the same URI...maybe...?

**Comment by keyboardDrummer** [comment]
O yes that might be the right way to interpret the spec. I will create a PR to make the spec less ambiguous. If it gets accepted then that'll be the answer ^^

**Comment by dbaeumer** [comment]
@keyboardDrummer thanks for the PR. I will merge. And yes there should only be one open for a specific text document.
