### ISSUE TITLE
Question: What is a diagnostic "code"?

### ISSUE THREAD

**Issue by tboby** [Microsoft/language-server-protocol#409]
The LSP Diagnostic object defines a "code":
```
	/**
	 * The diagnostic's code. Can be omitted.
	 */
	code?: number | string;
```

However, I can't find any definition of what this is supposed to be.
My guesses are either:
1. An error code used to classify similar diagnostics (e.g. "CW105")
2. A unique identifier for that specific diagnostic in that specific file (e.g. for code actions)

These are however very different things, the first is something the user possibly *should* be shown, the second is something they *shouldn't*.

Could anybody clarify this?

**Comment by dbaeumer** [comment]
It is an error code that can be shown to the user. It is not a unique identifier for that specific diagnostic object. 

I have updated the doc and spec.
