### ISSUE TITLE
Rename symbol should allow optional rename of file

### ISSUE THREAD

**Issue by joshtynjala** [Microsoft/language-server-protocol#41]
Some languages require the file name to match the name of the class, interface, or other symbol that the file contains. Renaming a symbol should optionally allow its file to be renamed too.

**Comment by dbaeumer** [comment]
Agree. Besides having this in the protocol we need to have support in the vscode API as well. I opened https://github.com/Microsoft/vscode/issues/10659

**Comment by Trolldemorted** [comment]
Any news for this? I guess the majority of programming languages have such constraints on the filename (java, python, rust, ...), and proper renaming cannot be implemented without file renaming support.

**Comment by mickaelistria** [comment]
Dealing w/ moved/deleted files is not only useful for rename but might be useful for  more refactorings. Fixing #272 which is on WorkspaceEdit in general would fix this one.

**Comment by dbaeumer** [comment]
Closing in favor of #272
