### ISSUE TITLE
Change log mentions TriggerForIncompleteCompletions that isn't in the specification

### ISSUE THREAD

**Issue by rcjsuen** [Microsoft/language-server-protocol#412]
In https://github.com/Microsoft/language-server-protocol/commit/e4e92487b2d164aa7cb6e36216267a0c99e7167a, the change log was updated to state that:

> In addition we enhanced the `CompletionTriggerKind` with a new value `TriggerForIncompleteCompletions: 3 = 3` to signal the a completion request got trigger since the last result was incomplete.

However, this enum is not in the [specification](https://github.com/Microsoft/language-server-protocol/blob/39b118153e7f9ecada27a01a1837edd1823ccfcd/specification.md). #403 doesn't appear to be closed or merged either. Am I missing something here or am I looking at the wrong specification.md file, @dbaeumer?

**Comment by dbaeumer** [comment]
No. I merged in the PR.
