### ISSUE TITLE
Clarify status of local variables in documentSymbol

### ISSUE THREAD

**Issue by Yanpas** [microsoft/language-server-protocol#414]
Both C# and C++ language servers filter local variables, but some (Python, JS) do not. documentSymbol is used to build outline of a document and local variables are barely useful. I think it should be mentioned in the standard how to treat them. Personally I vote for filtering

**Comment by dbaeumer** [comment]
I am personally against stating this in the specification. I have no problems with having an implementation guide line page where we mention good practices but there might be use cases we don't see where it makes sense to include them.

**Comment by tboby** [comment]
For an alternative perspective, the scripting language I maintain a language server for doesn't have the concept of local variables. It's data oriented and barely has control flow.

For this language, even the SymbolKind enum is an overly restrictive and arbitrary. 

If you have a language without functions, variables, interfaces, classes or even arrays: _what on earth would I do with a protocol requirement to exclude local variables?_
