### ISSUE TITLE
Adopt document folding support

### ISSUE THREAD

**Issue by rcjsuen** [Microsoft/language-server-protocol#418]
The new VS Code 1.21 February 2018 release included a [new folding provider](https://code.visualstudio.com/updates/v1_21#_proposed-extension-apis). The [internal JSON implementation](https://github.com/Microsoft/vscode/blob/3e7521b68e964f0fa69c9a7db88fb619a632b077/extensions/json/server/src/protocol/foldingProvider.proposed.ts) looks just like the other proposed LSP APIs from the past.

What do we think about this API? Is it a feature that should be introduced into the LSP specification?

**Comment by rcjsuen** [comment]
Looks like Martin is working on this. See Microsoft/vscode#45983.

**Comment by rcjsuen** [comment]
Looks like a new [Microsoft/vscode-languageserver-protocol-foldingprovider repository](https://github.com/Microsoft/vscode-languageserver-protocol-foldingprovider) has been created.

There is also a [vscode-languageserver-protocol-foldingprovider package](https://www.npmjs.com/package/vscode-languageserver-protocol-foldingprovider) on npm.

**Comment by aeschli** [comment]
Yes, correct, sorry for not announcing it here.

**Comment by rcjsuen** [comment]
I opened two issues (Microsoft/vscode-languageserver-protocol-foldingprovider#3 and Microsoft/vscode-languageserver-protocol-foldingprovider#4) just now but I then realized that perhaps I should be opening them here instead.

@aeschli and @dbaeumer, Where should the issues go?

**Comment by aeschli** [comment]
Microsoft/vscode-languageserver-protocol-foldingprovider is the correct place for discussions on the proposed protocol.

**Comment by rcjsuen** [comment]
@aeschli @dbaeumer Is there an ETA for this? It's fine if it's a no but just wondering where it stands in your list of (many) priorities.

**Comment by dbaeumer** [comment]
@aeschli can you comment on when you will merge this in?

**Comment by octref** [comment]
@dbaeumer This is not on the website yet.

**Comment by aeschli** [comment]
I added the doc.
