### ISSUE TITLE
Specification Typo

### ISSUE THREAD

**Issue by hozuki** [Microsoft/language-server-protocol#420]
In section [$ Notificiations and Requests](https://microsoft.github.io/language-server-protocol/specification#-notifications-and-requests):

> Notification and requests ids starting with ‘$/’ are messages which are protocol implementation dependent and might not be implementable in all clients or servers.

Notifications do not have IDs. Moreover, IDs are session-dependent. Their common element is `method`, which can be implementation-dependent. So I looked into the C# implementation ([the OmniSharp one](https://github.com/OmniSharp/csharp-language-server-protocol/blob/cde3283bdcbf1af37597f8c049e5e3ec6d55898b/src/Protocol/General/ICancelRequestHandler.cs#L9)) and confirmed my guess. This sentence should be:

> Notifications and requests whose methods start with ‘$/’ are messages which are protocol implementation dependent and might not be implementable in all clients or servers.

**Comment by dbaeumer** [comment]
Correct.
