### ISSUE TITLE
Javascript Flow Langauge Server

### ISSUE THREAD

**Issue by jaredramirez** [Microsoft/language-server-protocol#421]
There is a language server for javascript supporting flow-typed here: https://github.com/flowtype/flow-language-server. I was wondering if it could be added to the list of language servers (https://microsoft.github.io/language-server-protocol/implementors/servers/) for other people's reference

**Comment by dbaeumer** [comment]
@jaredramirez we usually rely on the owner of the LS to provide a PR against this file: https://github.com/Microsoft/language-server-protocol/blob/gh-pages/_implementors/servers.md.

Feel free of course to provide such a PR.

**Comment by jaredramirez** [comment]
Okay, thanks for the info! I'll create an issue on their repo about this then.
