### ISSUE TITLE
Clarification: can server send telemetry/event prior to initialization?

### ISSUE THREAD

**Issue by ljw1004** [Microsoft/language-server-protocol#425]
> During the initialize request the server is allowed to send the notifications window/showMessage, window/logMessage and telemetry/event

Q. Is the server also allowed to send `telemetry/event` prior to receiving an initialize request?

Background: I'm writing integration tests for my LSP server. The integration tests get run on a busy test-server farm that's doing lots of other work too. I've observed that when node exec's another process (e.g. when my test harness execs the LSP server), it can take up to 10 seconds before that other process launches and is able to write to stdout.

I want my LSP server to send a 'telemetry/event' as the very first thing it does. That way, my integration test harness can wait 20 seconds for the first telemetry/event. If it gets one, then fine it can proceed with the test. If it doesn't get one, then presumably the test machine is under sufficiently heavy load that I might as well just skip the test for now.

(My LSP server isn't able to write just normal text on its stdout, since that interferes with vscode-jsonrpc. And I'm loathe to have it indicate its status over stderr. I could try to invent an entirely new communication paradigm, e.g. writing to a sentinel file that the test harness reads from, but doing this with a simple `telemetry/event` would be much easier).

**Comment by dbaeumer** [comment]
Actual the spec says you can't. It is allowed during the initialize request. 

Even the LSP client for VS Code might not handle the notification correctly since it registers the notification handler after the connection has been established, meaning that there is a time gap between the server being started and the client registering the handler.

Is it OK for you to close the issue?

**Comment by ljw1004** [comment]
Thanks.

**Comment by ljw1004** [comment]
One moment: where does the spec say you can't?

**Comment by ljw1004** [comment]
I'm asking what happens if the *client* receives a notification before the initialize request. That bit of the spec only addressed what happens if the *server* receives one.

**Comment by laughedelic** [comment]
Pardon, I got confused.

**Comment by dbaeumer** [comment]
I read that into

> During the `initialize` request the server is allowed to send the notifications `window/showMessage`, `window/logMessage` and `telemetry/event` as well as the `window/showMessageRequest` request to the client.  The `initialize` request may only be sent once.

but I agree it could be misleading. I will update the spec since the intialize request is the meant to be the handshaking between the client and the server and therefore it seemed logic for me that there can be no communicatin beforehand.

**Comment by dbaeumer** [comment]
I stated that more clearly in the spec.
