### ISSUE TITLE
Implementations table is difficult to read

### ISSUE THREAD

**Issue by rcjsuen** [Microsoft/language-server-protocol#427]
The table has no borders around its cells which makes the rows very difficult to read. Most things are obvious by their names but still...

![image](https://user-images.githubusercontent.com/15629116/37553573-5121b6c8-2a0e-11e8-8576-d53cda1a3651.png)

**Comment by dbaeumer** [comment]
I guess that got broken by adding additional servers. I added the borders back (done by removing an empty line)
