### ISSUE TITLE
Query all symbols for empty symbol returns 0 symbols

### ISSUE THREAD

**Issue by Helmut-Ortmann** [Microsoft/language-server-protocol#428]
Commit dc5f22e2fa118e06d9a8dd1056375ab5f449c6dc returns for a query with empty symbol nothing.
I would expect all symbols up to max symbols as before.

Thanks,

Helmut

**Comment by rcjsuen** [comment]
@Helmut-Ortmann That appears to be a commit in the [cquery-project/cquery repository](https://github.com/cquery-project/cquery/commit/dc5f22e2fa118e06d9a8dd1056375ab5f449c6dc). Please open an issue there.

This repository is for discussion about the language server protocol specification and is not for talking about code.

**Comment by Helmut-Ortmann** [comment]
Thanks for your answer. By the way, the issue is with the last commit
solved.

Best regards,

Helmut

**Comment by rcjsuen** [comment]
@Helmut-Ortmann Thank you for your confirmation. If your issue has been resolved, please close this issue. Thanks!

**Comment by Helmut-Ortmann** [comment]
Sorry for the wrong project. Issue solved, thanks!
