### ISSUE TITLE
Clarification: didChange without didOpen?

### ISSUE THREAD

**Issue by ljw1004** [Microsoft/language-server-protocol#436]
**Scenario 1**: in the editor you do a project-wide replace. This naturally changes many files on disk, without even opening in the editor.

Is the editor expected to send didChange notifications for all those files? Presumably the didChange will come without any accompanying didOpen/didSave? I see the spec specifically says the following about didChange, which seems to support this scenario:

> If a versioned text document identifier is sent from the server to the client and the file is not open in the editor (the server has not received an open notification before) the server can send `null` to indicate that the version is known and the content on disk is the truth (as speced with document content ownership)

**Scenario 2**: In the editor you click the "git pull" or similar button, which naturally changes a lot of files on disk. Is the editor expected to send didChange notifications for all those files?

I know there exists `didChangeWatchedFilesNotification`, and I know that the LSP could use didChangeWatchedFilesNotification in both the above scenarios. But that's not why I'm asking. I'm asking instead whether (1) I should code up Nuclide to send didChange notifications in the above scenarios, (2) I should code up my LSP servers to handle didChange without a preceding didOpen.

**Scenario 3**: Our LSP server, in order to be efficient, only reports errors about the files that the user is interested in (rather than doing an entire project-wide error analysis). Our first approximation is to say the user is only interested in all open files, plus those that depend upon them. This mostly worked, but we've run into problems when the user did a project-wide search-and-replace: the user is obviously interested in all errors that arise from their search+replace. We could make our LSP server discern "files of interest to the user" by looking for all didChange events in addition to all didOpen events, but only if the answer to Scenario1 is "yes" and Scenario2 is "no".

**Comment by dbaeumer** [comment]
The client shouldn't send `didChange` notifications for files that are not open. The protocol clearly specs that the ownership of files are on the server unless the server receives a didOpen notification. This being said the client it not allowed to manipulate a file without claiming ownership beforehand. 

The comment you are quoting is about a version text document identifier send from the server to the client. `didChange`, etc. are sent from the client to the server. 

**Scenario 1**: I think this depends on the tool. For example VS Code opens the file and changes them in memory and writes them back. So in VS Code the open/change/close notifications are sent to the server. If this for example is done using an external tool the editor doesn't need to send these events (it might not even have the knowledge to do so). However the editor needs to handle case where conflicts might occur if for example the user can continue typing and saving. So my answer is `yes` if the tools can (but then open/change/close) is necessary but it is OK to not do this if the tool can recovery from it. 

**Scenario 2**: I think this should be handled like executing git in a terminal. The editor and the server should do its best catching up with the file changes relying on file events. So my take on this is no.

**Scenario 3**: I am not sure if I need to answer something here.

**Comment by ljw1004** [comment]
Thanks @dbaeumer
