### ISSUE TITLE
Support markdown in CompletionItem detail.

### ISSUE THREAD

**Issue by Nufflee** [microsoft/language-server-protocol#437]
Completion item details are a bit too vague the way they are currently defined so it would be a very good addition to be able to use `MarkedString` for the detail text. If you approve of this, I can make a pull request and add it to the specification. 

This wouldn't be a breaking change because using a string is still allowed with `MarkedString` type. Implementation of this in code editors wouldn't be too complicated as well because this is already supported for hovers. 

Supporting `MarkedString` wherever feasible also doesn't seem like a bad idea but we can take on this in another, more generalized issue.

cc @rcjsuen

**Comment by rcjsuen** [comment]
The `detail` of an item tends to be something short. What value do you gain from making it into a `MarkedString`? Do you want to add syntax highlighting or something to the displayed return type of a function or something?

**Comment by Nufflee** [comment]
Some languages (for instance TypeScript) shows the function/variable signature in the CompletionItem detail (screenshot below) and syntax highlighting would be pretty useful here because plain text is a bit too vague. I'm doing the same in my language server so that's why I'm proposing this.

TypeScript leveraging CompletionItem detail to show signature info:
![image](https://user-images.githubusercontent.com/19150550/38103636-3256d0a2-3387-11e8-8447-bacb7e5ba300.png)

**Comment by rcjsuen** [comment]
@Nufflee Ah, I see what you mean now.

The `detail` is also used when you're simply looking at the items and not in the popup though so I was thinking of that scenario. Supporting it in the popup would be the same as supporting it for the `documentation` field but supporting it in the item itself will probably require extra work for LSP clients. Still, that's not to say that I'm opposed to the idea.

![image](https://user-images.githubusercontent.com/15629116/38116816-c4912660-33ec-11e8-8d7c-a23f80bec234.png)

![image](https://user-images.githubusercontent.com/15629116/38116831-da031954-33ec-11e8-9c07-d0427586d401.png)

**Comment by Nufflee** [comment]
Yea, I was thinking about the popup, not the item itself. When not in the popup it can stay plain text but that's a bit inconsistent thought (if anyone has better ideas, I'd love to hear them). And from what I can see, `documentation` property only supports markup, not `MarkedString`.  

What should I do now? Should I wait for more people to approve this, should I open a pull request and see what everyone thinks about it there or? I'm new to contributing to LSP so I would like these things cleared up 😄.

**Comment by mickaelistria** [comment]
I agree with @rcjsuen : I don't see a value in making completionItems.details markedstring when there is completionItem.documentation that's dedicated to cover a rich text in popup.

**Comment by Nufflee** [comment]
@mickaelistria Yes, there's no point in having rich text (markup) in the CompletionItem detail but `MarkedString` is not used for that, it's used for syntax highlighting.

**Comment by Nufflee** [comment]
Also, I just noticed the `@deprecated` on the `MarkedString`. So we should just go with `MarkupContent` then but now it's explicitly supporting markup but would still enable syntax highlighting which I'm inquiring about. And from what I can see, `MarkedString` is deprecated in favor of markup because markup can do syntax highlighting too and was actually used under the hood for `MarkedString`.

**Comment by dbaeumer** [comment]
If I understand all comments correctly the item can be closed. Is this correct?

**Comment by Nufflee** [comment]
Not really, I'm still inquiring about some kind of Markup support for CompletionItem detail.

**Comment by dbaeumer** [comment]
That is fair.

**Comment by Nufflee** [comment]
Thanks! What steps should I take now? Make a pull request or?

**Comment by dbaeumer** [comment]
There is a document explaining how to contribute here: https://github.com/Microsoft/language-server-protocol/blob/master/contributing.md.

Sine you are modifying an existing data type it is easier since you don't need to create a protocol extension. But we would need PRs against the spec in this repository and against the implementation here: https://github.com/Microsoft/vscode-languageserver-node

**Comment by Nufflee** [comment]
Okay.

**Comment by burner1024** [comment]
This is implemented in python somehow:
![captura de pantalla de 2018-09-05 13-23-03](https://user-images.githubusercontent.com/1279852/45074818-1df4ac00-b10f-11e8-8560-075f274a68dc.png)
Doesn't look too intrusive, although I'd shadow the details text.

**Comment by trevorade** [comment]
@Nufflee, have you made any active progress on a PR for this issue?

@dbaeumer, is this issue still acceptable for a PR?  I might consider tackling this and then later updating Monaco/VsCode to be aware of Markdown being supported for `detail`.

**Comment by KamasamaK** [comment]
@Nufflee The title should be changed since as you pointed out `MarkedString` is deprecated.

Regarding the usefulness of this suggestion, I think there is some value in syntax highlighting even just a small snippet. This was being explored for VS Code but there's been no progress -- Microsoft/vscode#34188. It hasn't been abandoned either, though.

**Comment by dbaeumer** [comment]
I would actually see how this evolves in VS Code. This would make a proposal and a first implementation easier. In all cases it must go behind a client capability.

**Comment by dbaeumer** [comment]
Dups https://github.com/microsoft/language-server-protocol/issues/1130 which has an associated PR.
