### ISSUE TITLE
What is the default value for ServerCapabilities.textDocumentSync and TextDocumentSyncOptions.change

### ISSUE THREAD

**Issue by keegancsmith** [Microsoft/language-server-protocol#447]
It isn't clear from the spec, but what is the default behaviour if these optional fields are not specified? One would suspect in both cases it is equivalent to `TextDocumentSyncKind.None` when not specified.

**Comment by dbaeumer** [comment]
Yes, the default is `TextDocumentSyncKind.None` which is the JSON falsify value.

**Comment by keegancsmith** [comment]
Thanks for pushing a clarification!
