### ISSUE TITLE
rejectReason in WorkspaceEdit

### ISSUE THREAD

**Issue by nikeee** [Microsoft/language-server-protocol#453]
The interface [`WorkspaceEdit` of VSCode](https://github.com/Microsoft/vscode/blob/5ff2ccfc2876251d6dec420e6897490abd19c46a/src/vs/editor/common/modes.ts#L927-L930) which is used in Monaco apparently provides a mechanism of why a WorspaceEdit was rejected.

I am currently implementing a language server and I've come to the point where I have to provide a response for the user if he tries to rename a keyword. The current solution in my project is to return `undefined`. 

However, VSCode then displays "Rename failed" (or something similar).
Is there any way to provide a custom message, like when editing TypeScript files and trying to rename a keyword ("You cannot rename this element")? I havent done anything with the `WorkspaceEdit.rejectReason`, so I can only assume that its intended for providing a custom reason of failure.

**Comment by dbaeumer** [comment]
I can't speak about the Monaco API but from a LSP perspective the response from the rename message should be an error response. The LSP client for VS Code then handles this and takes the message of the error response and uses it as the reject message. But please note that in the VS Code extension API I only need to reject the promise to make that work. I don't know how to do this correctly in the Monaco API. You might want to ask that question in the corresponding vscode-monaco repository.

**Comment by dbaeumer** [comment]
Please ping if there is still something unclear
