### ISSUE TITLE
Add support to resolve a rename location.

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/language-server-protocol#455]
See https://github.com/Microsoft/vscode/issues/7340#issuecomment-381926228

**Comment by dbaeumer** [comment]
Anyone willing to provide a PR for this to add a textdocument/resolveRenameLocation request to the LSP?

**Comment by rcjsuen** [comment]
@dbaeumer I have opened Microsoft/vscode-languageserver-node#390. It's my first time to implement a new LSP request so I wouldn't be surprised if I've done something wrong.

**Comment by rcjsuen** [comment]
@dbaeumer Should I bump the version to version 3.11 for `textDocument/prepareRename`?

**Comment by rcjsuen** [comment]
@dbaeumer On that note, did you intend to make yesterday's addition of `CodeActionOptions` version 3.11 or an addition to 3.10? In 7aed39bc4b82d59ca328c43d56d85fec2ebee9b9 you made the anchor tag's name `version_3_11_0` but you kept the text as `3.10.0`.

**Comment by dbaeumer** [comment]
I first thought that I don't need to go to 3.11 for the code action options case. But then later on decided to do so since it adds a feature and is strictly speaking not a bug fix only :-)

**Comment by dbaeumer** [comment]
So with the rename prepare support we should move to 3.12.

**Comment by dbaeumer** [comment]
Done.
