### ISSUE TITLE
Is there request to expand the current symbol/token an a given position?

### ISSUE THREAD

**Issue by obfuscated** [microsoft/language-server-protocol#462]
I need a request which can be used to give me the full symbol at a given position, but I can find it in the spec.

Here is a C++ example:
```
struct A { int a, b, c; };
struct B { A first, second;};

A test1;
B test2;
test1.a = 5;
test2.first.second.b = 5;
```

If I place the cursor over ```test1``` I want to get the range of ```test1``` in the document.
If I place the cursor on the ```.``` or ```a``` in ```test1.a``` I want to get the range of ```test1.a```.
If I place the cursor on first in ```test2.first.second.b```, I'd expect the full range of ```test2.first```.
And so on.

I need this in order to construct valid expressions which I want to pass to a debugger for evaluation.
Any insight how to do this with a language server?

How does VSCode do this? I don't want to use some text based heuristic, because it won't be language neutral.

**Comment by dbaeumer** [comment]
Such a request doesn't exist right now but makes perfect sense. This would be a good candidate for a request proposal as document here: https://github.com/Microsoft/language-server-protocol/blob/master/contributing.md

**Comment by obfuscated** [comment]
Thanks, I'll consider it, but I don't like signing any license agreements...

**Comment by dbaeumer** [comment]
Is in. The concept is called selection ranges. 

https://github.com/Microsoft/vscode-languageserver-node/blob/master/protocol/src/protocol.selectionRange.ts#L48
