### ISSUE TITLE
Return partial responses for long-running operations

### ISSUE THREAD

**Issue by vladdu** [Microsoft/language-server-protocol#47]
I can't tell from the docs if this is supported somehow, but I think it would be useful: for operations that may take a long time, return periodically a partial response, so that the client can show something in the meantime.

There is something that might be it for completion (a CompletionList has an isIncomplete attribute, but it may mean something else), but this can apply for any operation: if the return value is a list, then it should be possible to return it in chunks. This also means that an operation can return results and still finally return an error - but the client still has something useful to work with (albeit incomplete).

Client capabilities should specify if this kind of responses should be used or not.

**Comment by dbaeumer** [comment]
Agree. Paging would be nice. I will add it to the backlog.

**Comment by dbaeumer** [comment]
Marking as dup of #141
