### ISSUE TITLE
CompletionItem Textedits are executed the wrong way round

### ISSUE THREAD

**Issue by peni4142** [Microsoft/language-server-protocol#471]
Hi I recognized that first executed additionalTextEdits, after that the textEdit is executed.

As example we have a `textEdit:"mode"` and `additionalTextEdits:["Hello"]`. The cursor is on the end of the line, so we can't add more range to additionalTextEdits.

If we have written mo of mode it will look like that:
 => moHelmode

Step by Step;
mo => moHello => moHelmode

My versions are all up to date.

**Comment by rcjsuen** [comment]
@peni4142 This is the repository to talk about the language server protocol's **specification**. No executable code is housed here. I suggest you open a bug report somewhere else.

What IDE/editor are you using? What language server are you using?

**Comment by peni4142** [comment]
I create a extension for vscode in vscode based on lsp-sample.
If this is the wrong place I don't know where else to report it.
I think I just go with a workaround.

**Comment by rcjsuen** [comment]
Hi, @peni4142. You should open an issue in the [Microsoft/vscode-languageserver-node repository](https://github.com/Microsoft/vscode-languageserver-node/) then.

**Comment by dbaeumer** [comment]
Actually the protocol forbids this kind of additional text edit. From the spec:

```
	/**
	 * An optional array of additional [text edits](#TextEdit) that are applied when
	 * selecting this completion. Edits must not overlap with the main [edit](#CompletionItem.textEdit)
	 * nor with themselves.
	 */
```

I will clarify this in the spec that overlap even means the same insert position. We decided to forbid this since otherwise things get complicated in terms of ordering and execution. 

Additional text edits are meant to be used to change text at position unrelated to the current cursor position.

**Comment by dbaeumer** [comment]
I updated the spec as well. I will close the issue. Please ping if something is still unclear.
