### ISSUE TITLE
Provide links to html documentation

### ISSUE THREAD

**Issue by dvc94ch** [microsoft/language-server-protocol#482]
What is the best way to provide links to html documentation?

When using DocumentLink it opens the html in a text buffer, which is not the idea. (All html documentation is available offline).

**Comment by rcjsuen** [comment]
@dvc94ch I feel like this is on the client to decide. For example, in Eclipse, a website can be opened internally in Eclipse as a view or an editor or externally in a browser. However, I imagine a client like say Vim isn't going to display a browser internally and is always going to launch something external.

The client should be able to parse the URI from the server and figure out if it's something that should be displayed as plain text or in the browser.

**Comment by dvc94ch** [comment]
How does the client know if the link should be rendered or not? Based on the extension? Maybe there has to be a way to hint to the client how it should open the link.

**Comment by dvc94ch** [comment]
Alternatively maybe code lenses are more appropriate way of displaying rendered documentation?
