### ISSUE TITLE
Standardize typical CLI options

### ISSUE THREAD

**Issue by mickaelistria** [microsoft/language-server-protocol#483]
Most LS do allow using stdio or nodeipc ad transport and have the same options to choose one or the other when starting LS.
In order to easily factorize deployment/startup of LS, it would be convenient to standardize those options to safely build strategies on top of them.
For example, once some registry exist and some client use it to discover and use a LS automatically, it'd be useful to just be able to use the same startup flags all the time.

**Comment by dbaeumer** [comment]
Makes sense to me: here is what the VS Code language servers currently support:

- `--node-ipc`: use node IPC communication
- `--stdio`: uses stdio
- `--pipe`: use pipes / socket files. The pipe / socket file name is passed as the next arg or with `--pipe=`
- `--socket`: uses a socket. Port is passed as next arg

I am not sure if this should go into the spec or whether we would have implementation guild lines.

**Comment by mickaelistria** [comment]
Having it as a hint or a recommendation would work for me. The thing is just that we have written it down somewhere so we can link LS implementors to it and say "can you please adopt this".
Whether it's officially part of the spec or not doesn't matter. As long as it's written down on some official-ish document the result would be the same and the value would be here.
