### ISSUE TITLE
how to use the protocol from a C++ client?

### ISSUE THREAD

**Issue by fferri** [Microsoft/language-server-protocol#488]
Do you have any plans for releasing a C++ client library?
Do you have an example of a C++ client?

**Comment by rcjsuen** [comment]
> how to use the protocol from a C++ client?

@fferri Are you writing your own editor / IDE?

It would be the same for any other programming language. You would communicate to a language server using JSON-RPC. This could be a JSON-RPC library written in the programming language of the client or perhaps there is some way you can pipe stuff to a third-party application that would funnel requests to and from the server for you.

> Do you have any plans for releasing a C++ client library?

I know I have no plans myself but I can't speak for anyone else in the LSP community. :)

> Do you have an example of a C++ client?

I don't think there is one for C++ at the moment according to the [website](https://microsoft.github.io/language-server-protocol/implementors/sdks/). At least, not one that is publicly advertised.

You could perhaps check out the implementation in [GNOME Builder](https://gitlab.gnome.org/GNOME/gnome-builder/tree/master/src/libide/langserv) as it's written in C although please be aware of the licensing implications of looking at another project's source code.

Good luck with your project!

**Comment by puremourning** [comment]
You might want to look at what cquery and clangd use? They are servers but the protocol is symmetric.

**Comment by dbaeumer** [comment]
@rcjsuen there is nothing I can add to the comments already made be @rcjsuen and @puremourning. Anyone else any additional tips?
