### ISSUE TITLE
Modifiers to CompletionItemKind and SymbolKind

### ISSUE THREAD

**Issue by rcjsuen** [microsoft/language-server-protocol#489]
Looks like VS Code is thinking about a new enum for "modifying" the existing kinds.

So something might be a `Function` as a "base" but it would be modified with additional kinds of `Protected` and `Abstract`. This relieves the need for going crazy with new enums of `ProtectedFunction`, `AbstractFunction`, and `ProtectedAbstractFunction`.

See Microsoft/vscode#23927.

Edit: Never mind, the issue was created in 2017. I guess the idea isn't that new, haha.

**Comment by dbaeumer** [comment]
Agree, having modifiers would be helpful in many scenarios.

**Comment by KamasamaK** [comment]
I think the use case for those modifiers is satisfied with `CompletionItemTag` and `SymbolTag`. The VS Code issue linked was closed because of that.

**Comment by dbaeumer** [comment]
I added tags to LSP as well. Will close the issue for now. If we think we need it we can reopen.
