### ISSUE TITLE
Clarify CompletionItemResolveRequest

### ISSUE THREAD

**Issue by vladdu** [Microsoft/language-server-protocol#49]
The doc doesn't say how one knows that a completion item is incomplete and a resolve is required.Is it sent always when an item is selected? Is it sent when some field is null?

**Comment by gorkem** [comment]
Take a look at `CompletionOptions`. The value of `resolveProvider` determines if CompletionItemResolveRequest is requested or not.

**Comment by vladdu** [comment]
The way I understood is that `resolveProvider` says if there is such support at all. Does it mean that a resolve is requested if there is support and the initial completion item has any null fields?

**Comment by gorkem** [comment]
It is simple really, if `resolveProvider` is true then `CompletionItemResolveRequest` request is made. I think it is best not to have any field check logic on the client implementations regarding the requests, it can quickly lead to fragmentation.

**Comment by vladdu** [comment]
Okay, I see. Do you think that is clear from the docs and it's only me who is slow, or should it be made clearer?

**Comment by dbaeumer** [comment]
Updated doc:

![capture](https://cloud.githubusercontent.com/assets/1931590/17765863/9550091e-6528-11e6-8278-6412b38443f4.png)

**Comment by vladdu** [comment]
Excellent, thank you!
