### ISSUE TITLE
workspace/didChangeConfiguration issue

### ISSUE THREAD

**Issue by danixeee** [Microsoft/language-server-protocol#498]
When configuration is changed on the client (either for workspace or root-folder), server gets the following notification:
```
{"jsonrpc":"2.0","method":"$/setTraceNotification","params":{"value":"off"}}
```
In [LSP specification](https://microsoft.github.io/language-server-protocol/specification#initialize) I can't see if there is a field in `ServerCapabilities` interface which tells client that server supports this feature.

NOTES:
I am using vs-code client from [here](https://github.com/Microsoft/vscode-extension-samples/tree/master/lsp-sample/client).
Server is implemented in python.

**Comment by dbaeumer** [comment]
These are special requests which are implementation dependent. The only one we speced is cancel although servers are free to ignore the request. From the spec:

$ Notifications and Requests

Notification and requests whose methods start with ‘$/’ are messages which are protocol implementation dependent and might not be implementable in all clients or servers. For example if the server implementation uses a single threaded synchronous programming language then there is little a server can do to react to a ‘$/cancelRequest’. If a server or client receives notifications or requests starting with ‘$/’ it is free to ignore them if they are unknown.

**Comment by dbaeumer** [comment]
I will close the issue. Please ping if something is still unclear.
