### ISSUE TITLE
Is 'documentHighlight' same thing as "'references' in one document"?

### ISSUE THREAD

**Issue by vladdu** [Microsoft/language-server-protocol#50]
It looks like that for me -- maybe they could be merged in one request? That would also allow defining other scopes (all open documents, or other subset of the workspace).

**Comment by dbaeumer** [comment]
@vladdu actually no. The idea behind having two is that `documentHighlight` can be fuzzy however `references` must be true references (accurate). Since we made good experiences with this differentiation I opt to keep it.

**Comment by vladdu** [comment]
Ok, I understand. Should that be stated in the docs?

**Comment by dbaeumer** [comment]
Done.
