### ISSUE TITLE
WorkspaceEdit (refactor & code action) progress & status

### ISSUE THREAD

**Issue by mostafaeweda** [Microsoft/language-server-protocol#506]
LSP should provide guidance on big `WorkspaceEdit` handling, progress updates and status.
Currently, on refactor/rename VSCode opens all the editors and applies the changes to the buffers - but that doesn't scale if there's 1000s of files - nor is it an atomic operation.

Hence, we should have optional progress indicators (e.g. `20 / 1000` or `2%`) and status if failed + reason (e.g. readonly file, file version mismatch, ..etc.) & avoid opening all affected text editors.

**Comment by arxanas** [comment]
This seems like an entirely client-side issue, since the application of edits is handled only in the editor. 
Why would there need to be an addition to the LSP to handle this?

**Comment by dbaeumer** [comment]
I agree with @arxanas.

I will close the issue. @mostafaeweda please ping if you disagree.
