### ISSUE TITLE
Flow chart / diagram for LSP?

### ISSUE THREAD

**Issue by jeanlucburot** [Microsoft/language-server-protocol#507]
Aside from the [specification](https://microsoft.github.io/language-server-protocol/specification), is there any flow chart or diagram showing exactly what message is sent from the language client to the language server and back, showing an example sequence from its first message to its last?

Trying to build a language client with LSP4J I am especially stuck at commands like textDocument/didOpen and textDocument/didChange, because nothing is sent back from the language server when I send them from the language client. I would have expected the language server to check the code of the opened and changed files and respond with a textDocument/publishDiagnostics, but the language server remains silent after both commands.

To understand what message has to be placed in what order, a visual diagram would be nice. IMHO best be placed where the main specification is located at [microsoft.github.io](https://microsoft.github.io/language-server-protocol/specification).

**Comment by mickaelistria** [comment]
To see logs of real usage, you can install Eclipse IDE for Rust Developers
(currently at http://www.eclipse.org/downloads/index-developer.php , GA is
tomorrow). It uses RLS as language server when editing rust files.
The log of LSP messages can be activated in Windows > Preferences >
Language Servers > Logs and produced in console and/or files under the
workspace folder.
Some other Eclipse IDE plugins also can be used to log messages the exact
same way: aCute for C# , BlueSky for HTML/CSS/JSON/JS/TS , or Spring Tool
Suite for some specific Spring properties files. All are available on
Eclipse Marketplace.


-- 
Mickael Istria
Eclipse IDE <https://www.eclipse.org/downloads/eclipse-packages/>
developer, for Red Hat Developers <https://developers.redhat.com/>

**Comment by jeanlucburot** [comment]
Thanks @egamma for the link to the inspector. Very much what I was looking for.
Also thanks to @mickaelistria for the hint to Eclipse.
