### ISSUE TITLE
Semantic highlighting protocol extension

### ISSUE THREAD

**Issue by kittaakos** [microsoft/language-server-protocol#513]
**Note:** The description was copied as is from https://github.com/Microsoft/vscode-languageserver-node/issues/368#issue-336150366

_________
I have started to work on a [semantic highlighting extension](https://github.com/Microsoft/vscode-languageserver-node/pull/367) of the LSP.

The semantic highlighting information is pushed from the server to the client as a notification. This notification contains the lines and the ranges where the coloring has the be applied and the desired coloring details are given as TextMate scopes.

In the reference implementation of the client, I was trying to map the TextMate scopes into the appropriate theme I can use as a decoration in the `TextEditor` decoration. How can one map the TextMate scopes into themes (and eventually `TextEditorDecorationType`) with the [current VS Code API](https://github.com/Microsoft/vscode/blob/34ba2e2fbfd196e2d6db5a4db0e42d03a97c655e/src/vs/vscode.d.ts)?

Any suggestions and feedback are welcome. Thanks!

Related issues:
 - [Support semantic highlighting (`Microsoft/language-server-protocol`)](https://github.com/Microsoft/language-server-protocol/issues/18)
 - [Proposal for (Semantic) Coloring (see #18) (`Microsoft/language-server-protocol`)](https://github.com/Microsoft/language-server-protocol/pull/124)
 - [Provide an API for advanced/semantic source highlighting (`Microsoft/vscode`)](https://github.com/Microsoft/vscode/issues/585)
 - [Add support for lexical syntax coloring (`Microsoft/language-server-protocol`)](https://github.com/Microsoft/language-server-protocol/issues/7)

_________

The corresponding PR with the proposed changes is here: https://github.com/Microsoft/vscode-languageserver-node/pull/367

**Comment by rcjsuen** [comment]
@kittaakos Just to make sure I understand what's going on, would you mind showing the JSON notification of a) opening a new file and b) making a change to one line? Let's just say the URI of the file is `lsp:/folder/file.ts`.

**A:** User opens the following TypeScript file in a LSP client.
```TypeScript
export class Sample {
    protected test = 0;
}
```
**B:** User changes `0` to `"value"` on the second line.
```TypeScript
export class Sample {
    protected test = "value";
}
```

**Comment by nickmccurdy** [comment]
Great idea, it's always bugged me that different editors have different syntax highlighting semantics.

**Comment by Licenser** [comment]
This would be great!

**Comment by dbaeumer** [comment]
Dups #18
