### ISSUE TITLE
Feature Request: Identify Symbol Method

### ISSUE THREAD

**Issue by ConderS** [Microsoft/language-server-protocol#517]
There should be a method in LSP that simply takes in a `TextDocumentPositionParams` and returns back something similar to that of `SymbolInformation`, with information on the full `text` of the symbol and its `range` within the document.

While I've recently come up against this lack of functionality while implementing UI for rename refactoring, I think this feature would be useful in other scenarios as well. 

For example, when I want to rename a symbol, I'm showing an input dialog similar to that of VSCode's, where its contents are automatically filled with the text of the symbol I'd like to rename. 

In most cases, we'd rely on the IDE's regex to identify the full symbol, but in other cases like `<xx:xy:something:xyz />` in that of the Hack programming language, this regex would fail. Here, it might only fill in the input dialog with `something` or `xx`, etc.. depending on the cursor/mouse position.

Ideally, with this LSP method, we'd be able to fully address language-specific syntax and return the proper `xx:xy:something:xyz` to fill the input dialog with.

**Comment by rcjsuen** [comment]
@ConderS For your specific use case about `textDocument/rename`, please see #402 and #455.

**Comment by ljw1004** [comment]
If I understand right, this request is a dupe of #455. Glad that lots of people are thinking the same thing!

**Comment by ConderS** [comment]
Agreed, thanks for the ref @rcjsuen! It's awesome that this is already in the works!
