### ISSUE TITLE
ranged 'documentSymbol' request

### ISSUE THREAD

**Issue by vladdu** [Microsoft/language-server-protocol#52]
Actually, all requests could have an optional range parameter (in case they don't already), so that both server processing and network chatter can be minimised. Often, the client is just interested in information about the chunk of code that is currently visible in the editor.

**Comment by dbaeumer** [comment]
@vladdu could you provide a more concrete example. For Document symbols: they are usually used for navigation so having all is preferable.

What we thought about we should add is some sort of paging. If a file is huge then paging would allow to build a more optimized UI. Same is true for example for diagnostics.

**Comment by vladdu** [comment]
If the response information is used for displaying things, it is usually sufficient to limit the answers to those whose locations are visible. In case the edited file is huge, querying for everything might result in a slow UI. 

I agree that not all requests need this, but I feel that an uniform API would be useful. The server is free to use or ignore the "visible viewport" information, but it has at least the choice.

Paging (or partial results) is very useful, but orthogonal to this. It helps only if the first answers are around the visible area (otherwise if we're at the end of the huge file, it will still be slow to get the answers), so it would be helped by have the viewport information.

**Comment by dbaeumer** [comment]
I still think that this doesn't make sense for documentSymbols (there paging is what would help). However it would help with documentHighlight. With the downside that we need to resend requests when the user scrolls. Most editors re-request information on cursor move and typing but not on scrolling.

**Comment by vladdu** [comment]
If the "viewport" is just a hint, then the server can still reply with results outside it. It can send everything (as today) or it can split the answers with the first page matching the viewport and the following ones in increasing distance from it (for example).

**Comment by dbaeumer** [comment]
To keep the number of issues in our inbox at a manageable level, we’re closing issues that have been on the backlog for a long time but haven’t gained traction: we look at the number of votes the issue has received and the number of duplicate issues filed. Thank you for your time and understanding.

If you disagree and feel that this issue is crucial: we’re happy to listen and to reconsider.
