### ISSUE TITLE
Update spec to reflect VS Code 1.25's new DocumentSymbol type

### ISSUE THREAD

**Issue by JakeBecker** [Microsoft/language-server-protocol#520]
VS Code's v1.25 update [says](https://code.visualstudio.com/updates/v1_25#_document-symbols):

> To get the most out of the new Outline view tree, extensions should modify their DocumentSymbolProviders to return DocumentSymbols. This is a new type added and tailored towards the needs of the outline tree. It supports representing a hierarchy of document symbols and allows differentiating between the range that defines a symbol and the selection range that identifies a symbol.

However, the [spec for the LSP](https://microsoft.github.io/language-server-protocol/specification#textDocument_documentSymbol) doesn't reflect these changes yet and still says:

> Neither the symbol’s location range nor the symbol’s container name should be used to infer a hierarchy.

This has caused [minor confusion](https://github.com/JakeBecker/elixir-ls/issues/90#issuecomment-404297015) when it comes to implementing it in a language server, so it'd be good to update the LSP spec with the new API.

**Comment by rcjsuen** [comment]
Hi, @JakeBecker. Please see #327 for more details.

**Comment by dbaeumer** [comment]
I am closing this in favor of #327. I have implemented this on a branch but wanted to get feedback first.
