### ISSUE TITLE
textDocument/didChange not receiving languageId

### ISSUE THREAD

**Issue by Kronuz** [Microsoft/language-server-protocol#521]
There are some language servers which handle more than one similar languages differently, namely, for example, css/scss or json/jsonc; and the server decides slightly different completions or lintings depending on such active `languageId`. Now, when opening a file, `textDocument/didOpen` receives `languageId`; however `textDocument/didChange` doesn’t.

The thing is, some times, after having opened the file, the client could decide (based on input entered by the user) that an opened file has changed from say css to scss, yet `textDocument/didChange` can’t receive the new `languageId` as part of the notified change. Shouldn’t it be allowed?

If that notification isn’t supposed to change the currently active `languageId`, then how should such change be handled?

**Comment by rcjsuen** [comment]
@Kronuz As a hack, could language clients help the server by sending `textDocument/didClose` and `textDocument/didOpen` notifications for the file with the new `languageId`?

**Comment by LaurentTreguier** [comment]
@rcjsuen that would actually make a lot of sense. If two separate language servers were used, one for CSS and one for SCSS for example, then simply sending a change notification wouldn't work: the first server would keep on working with a file it shouldn't be working on anymore, and the second server may just not receive any notification at all.

**Comment by Kronuz** [comment]
So the appropriate thing to do is a `textDocument/didClose` and `textDocument/didOpen` for that case then? even if it’s a single server, not two as  @LaurentTreguier suggested?

**Comment by dbaeumer** [comment]
Yes, the correct thing IMO is that the client sends a textDocument/didClose and a textDocument/didOpen. I quickly tested this in VS Code and it seems to send these events correctly. In which client did you experience this?

**Comment by kdvolder** [comment]
> Yes, the correct thing IMO is that the client sends a textDocument/didClose and a textDocument/didOpen

FWIW. I agree with that. But the spec might need to be more clear about this. There's really nothing in the spec that says this.

**Comment by dbaeumer** [comment]
@kdvolder good point regarding the spec. I will add something about this.

@Kronuz you are free to use any start version number. The spec only says that it must increase with every change. It says nothing about the starting value.

**Comment by dbaeumer** [comment]
I added clarification to the spec.

@Kronuz any objection to close the issue.

**Comment by Kronuz** [comment]
@dbaeumer not at all, thank you very much for the help. Closing now.
