### ISSUE TITLE
Spelling error in UnregisterationParams field

### ISSUE THREAD

**Issue by kcaze** [microsoft/language-server-protocol#522]
The field 'unregisterations' in UnregistrationParams is misspelled and should instead be spelled 'unregistrations':
[https://microsoft.github.io/language-server-protocol/specification#client_unregisterCapability](https://microsoft.github.io/language-server-protocol/specification#client_unregisterCapability)

**Comment by KamasamaK** [comment]
What should be done in this case? It appears that there are several implementations using this misspelling.

**Comment by rcjsuen** [comment]
I think either deprecate the old way or the community lives with the error...

**Comment by dbaeumer** [comment]
We can add both fields but that would require sending the data twice. So I would say we either live with it or we change it in a major release were we could break things like that.

Opinions ?

**Comment by dbaeumer** [comment]
I decided to live with it since the swirl is not worth the win.

**Comment by KamasamaK** [comment]
I still think this should be fixed, even if it has to wait for 4.0.

**Comment by dbaeumer** [comment]
The thing is that I don't see 4.0 happening in a foreseeable future.
