### ISSUE TITLE
Trigger signature help after autocompletion

### ISSUE THREAD

**Issue by jackscott6174** [Microsoft/language-server-protocol#523]
Is there currently any way to trigger signature help after we autocomplete a function name?
e.g. type `fo`, press enter to autocomplete to `foo()` and provide signature help on `foo` (this is exactly when IntelliJ does).
Right now the only way I see is to make the user type the parentheses themselves and have `(` as a trigger character for signature help.

**Comment by LaurentTreguier** [comment]
There is probably nothing the LSP can do about this, as it should be an entirely client-side issue. It's up to the editor to send the signature help request right after completion

**Comment by Gama11** [comment]
Related: https://github.com/Microsoft/vscode-languageserver-node/issues/376

**Comment by dbaeumer** [comment]
@jackscott6174 I fully agree with @LaurentTreguier. IMO this is nothing the specs needs to define. An editor could for example decide to only trigger this on user action.
