### ISSUE TITLE
New DefinitionLink interface in VS Code

### ISSUE THREAD

**Issue by rcjsuen** [Microsoft/language-server-protocol#524]
Only got around to reading the 1.25 release notes today and noticed there is a new [`DefinitionLink`](https://code.visualstudio.com/updates/v1_25#_definitionlink) interface there.

Should this be introduced into the LSP specification?

**Comment by rcjsuen** [comment]
Unfortunately, I can't promise this. My new job is taking up most of my free time. :(

**Comment by rcjsuen** [comment]
Looks like this is now an official part of VS Code as of 1.26 and is no longer a proposed API.

**Comment by rcjsuen** [comment]
@dbaeumer What would you prefer `textDocument/definition` to return?

1. `Location | Location[] | DefinitionLink[] | null`
1. `Location | Location[] | DefinitionLink | DefinitionLink[] | null`

**Comment by dbaeumer** [comment]
@rcjsuen I would go with the second to keep things consistent.

**Comment by rcjsuen** [comment]
I've opened Microsoft/vscode-languageserver-node#415.

**Comment by dbaeumer** [comment]
Added my comments to the PR.

**Comment by rcjsuen** [comment]
It has occurred to us that this would also apply/be useful to the `textDocument/references` request. However, `DefinitionLink` is not a great name in that case.

Would `SymbolLink` make sense or is that too vague/open-ended?

**Comment by dbaeumer** [comment]
Got delivered for 3.14.
