### ISSUE TITLE
Add ClientCapability field for completionItem/resolve

### ISSUE THREAD

**Issue by ZoeyR** [microsoft/language-server-protocol#526]
`completionItem/resolve` can potentially resolve arbitrary fields on a `CompletionItem`. Certain clients may not be able to send a `completionItem/resolve` request right before committing and may only be able to fill in certain data (e.g. documentation). There should be a `ClientCapability` field that specifies which fields may be filled in on resolve and which ones must be filled in with the initial set.

**Comment by dbaeumer** [comment]
This got added for 3.16 with an indication which fields can be resolved lazy.
