### ISSUE TITLE
Clarification needed for TextDocumentContentChangeEvent

### ISSUE THREAD

**Issue by natgabb** [Microsoft/language-server-protocol#53]
https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#didchangetextdocument-notification

The definition of `TextDocumentContentChangeEvent` is a bit unclear. Is the `range` inclusive at the start and end? Only at the start? What is `rangeLength` used for?

**Comment by gorkem** [comment]
similar to #9 ?

**Comment by natgabb** [comment]
That answers why `rangeLength` is in the request, but not whether the Range is inclusive or exclusive on the endCharacter. 
In the [groovy-language-server](https://github.com/palantir/groovy-language-server) we ended up implementing `didChange` by assuming endCharacter is exclusive because it allows for insertion, example: `Range= (0,0) to (0,0[` while also allowing for single character replacement example: `Range= (0,1) to (0,2[`.

**Comment by dbaeumer** [comment]
It is exclusive. Conceptually a range are two position where a positions is between two characters (like a cursor). I clarified that in the documentation.
