### ISSUE TITLE
Server handling different client protocol versions

### ISSUE THREAD

**Issue by jvalkeal** [Microsoft/language-server-protocol#530]
NOTE: This ticket is not a nitpick of how different servers/clients currently work together, but more like how server/client could negotiate current supported format.

I'm aware of #174 and initially thought what's mentioned there is just fine. But... Trying to come up with a generic code handling all clients, regardless of supported LSP versions, I really don't know how to handle it. 

In this issue I'm just going to concentrate on `ServerCapabilities` which has: 

```
interface ServerCapabilities {
  textDocumentSync?: TextDocumentSyncOptions | number;
}
```

where `number` is a  `TextDocumentSyncKind`, (i.e. ordinal if done in Java). In older clients `textDocumentSync` has to be i.e. `2`. Where `2` would be `Incremental`:

```
{
  "jsonrpc": "2.0",
  "id": 0,
  "result": {
    "capabilities": {
      "textDocumentSync": 2
    }
  }
}
```

While in newer clients you can wrap it in an object:

```
{
  "jsonrpc": "2.0",
  "id": 0,
  "result": {
    "capabilities": {
      "textDocumentSync": {
        "change": 2
      }
    }
  }
}
```

It seems that I really don't have now way to know which response to send back to a client as I don't know which LSP version it is supporting. 

My LSP server is serving multiple client types and this case Monaco editor(old version) only seem to recognize former format as only then I'm getting below request when typing:

```
{
  "jsonrpc": "2.0",
  "method": "textDocument/didChange",
  "params": {
    "textDocument": {
      "uri": "inmemory://model/1",
      "version": 3
    },
    "contentChanges": [
      {
        "range": {
          "start": {
            "line": 0,
            "character": 0
          },
          "end": {
            "line": 0,
            "character": 0
          }
        },
        "rangeLength": 0,
        "text": "x"
      }
    ]
  }
}
```

If I use latter format this Monaco editor doesn't send any requests when I type something. I could conditionally send different response back if I'd know which format to use.

If I sum this up, I really need to know based on client `initialize` request what format client actually supports. As there is a similar type of changes done between different LSP versions, we really should have some way to identify what version current connecting client actually expects.

**Comment by dbaeumer** [comment]
The corresponding client capability is: `textDocument.synchronization`. If not present only the numeric values are allowed (this was the default in version 2). If present the literal is allowed as a return value.

I am happy to accept a PR that improves the spec here :-).

OK to close?

**Comment by jvalkeal** [comment]
Hmm, I suppose there is a change for a bug in a language client typefox guys did for monaco(sample I'm playing is with version 0.11.1). Looking what it sends, `synchronization` is there:
```
"synchronization":{"dynamicRegistration":true}
```
so that would not automatically tell me if I need to reply `"textDocumentSync": 2` or `"textDocumentSync": {"change": 2}`.

Thought looking what I'm getting from clients based on new LSP4J/LSP4E, I do have more fields.
```
"synchronization":{"willSave":true,"willSaveWaitUntil":true,"didSave":true}
```

Anyway, thank's for pointing to correct thing in a spec. It's sometimes a little difficult to track it for changes as there's very little info when something has been added(only 3.6, 3.8 seems to be tagged).

**Comment by dbaeumer** [comment]
Let's reopen this. I forgot about dynamic synchronization. Need to dig if this came with the old number or already with the new literal format.

**Comment by dbaeumer** [comment]
But the property still indicate which level of information can be send. But need to find out what exactly was the old state.

**Comment by dbaeumer** [comment]
OK. In 2.0 client capabilities where empty, so no `textDocument.synchronization` property. This got added with 3.0. So if they set one of the `willSave`, `willSaveWaitUntil`, `didSave` as true then the need to understand the result literal. Otherwise only the number value.

**Comment by dbaeumer** [comment]
Did not reopen since the above clarifies it.
