### ISSUE TITLE
Clarification on sorting and filtering wording in Completion Request description

### ISSUE THREAD

**Issue by jkorous-apple** [Microsoft/language-server-protocol#533]
Hi,
I am curious about wording of the Completion Request description. Specifically:

> The request can delay the computation of the detail and documentation properties. However, properties that are needed for the initial sorting and filtering, like sortText, filterText, insertText, and textEdit must be provided in the textDocument/completion request and must not be changed during resolve.

Since sortText, filterText, insertText, and textEdit are parts of the CompletionItem interface I assume that "must be provided in the textDocument/completion response" (s/request/response/) is more accurate.

Is that correct or is there some other meaning?

Thanks.

Jan

**Comment by dbaeumer** [comment]
Correct.
