### ISSUE TITLE
Order of application for additionalTextEdits and textEdit on CompletionRequest

### ISSUE THREAD

**Issue by kadircet** [Microsoft/language-server-protocol#543]
Hello everyone,

I believe there is a big ambiguity about in which order TextEdits should be applied on completion requests. Also there is no clarification about what would happen if one of the text edits changes the document in a way that ranges in the remaining text edits are not valid.

Let me clarify with an example, let's say we have a reply of the following sort:
```
{
   "id":4,
   "jsonrpc":"2.0",
   "result":{
      "isIncomplete":false,
      "items":[
         {
            "additionalTextEdits":[
               {
                  "newText":"->",
                  "range":{
                     "end":{
                        "character":7,
                        "line":85
                     },
                     "start":{
                        "character":6,
                        "line":85
                     }
                  }
               }
            ],
            "detail":"void",
            "filterText":"pop_back",
            "insertText":"pop_back()",
            "insertTextFormat":2,
            "kind":2,
            "label":" pop_back()",
            "sortText":"3fe51eb8pop_back",
            "textEdit":{
               "newText":"pop_back()",
               "range":{
                  "end":{
                     "character":7,
                     "line":85
                  },
                  "start":{
                     "character":7,
                     "line":85
                  }
               }
            }
         }
      ]
   }
}
```

And on the code side let's say we have this:
```
std::shared_ptr<std::vector<int>> asdf;
asdf.^
```
Where "^" indicates current cursor position when requesting textedit(Let's assume cursor is on line 85 column 7). When this completion is applied one would expect to see:
"asdf->pop_back()" but unfortunately that's not the case, at least on VSCode. Instead it results in:
"asdf-pop_back()". I don't know the exact cause but my initial thoughts are on order of application, like it first applies additionaltextedit which converts the line from "asdf." into "asdf->". Afterwards when it tries to apply main textEdit it doesn't update the location and instead writes over ">" sign and results in asdf-pop_back.

I think additionalTextEdit's requires some more clarification especially when the edits are on the same line. Otherwise there are some undefined behaviors like the one I mentioned above. I suggest it can be clarified by saying that:
```
First textEdit or insertText is applied and afterwards additionalTextEdits are applied in the order they are given. 
```

And in addition to clarification on ordering, there might be some more words on ranges as well, for example:
```
Ranges on these edit's are assumed to be on original document.
```
or maybe,
```
Since the edits on same line might change effect of other textEdits, LSP server should but the elements on the same line onto back to front order. So that no change would effect another.
```

Have a nice day!

**Comment by dbaeumer** [comment]
The problem here is that the `additionalTextEdits` conflict / overlap with the primary `textEdit` which is not supported. See 

```
	/**
	 * An optional array of additional text edits that are applied when
	 * selecting this completion. Edits must not overlap (including the same insert position)
	 * with the main edit nor with themselves.
	 *
	 * Additional text edits should be used to change text unrelated to the current cursor position
	 * (for example adding an import statement at the top of the file if the completion item will
	 * insert an unqualified type).
	 */

```

**Comment by dbaeumer** [comment]
Please ping if this doesn't address your problem.

**Comment by dbaeumer** [comment]
Correct, but they conflict with the main edit because they change the same line the cursor is on. This is discouraged for additional text edits:

```
Additional text edits should be used to change text unrelated to the current cursor position
	 * (for example adding an import statement at the top of the file if the completion item will
	 * insert an unqualified type).
```

**Comment by ilya-biryukov** [comment]
Why should this cause a conflict in practice? The current wording is vague and too restrictive in practice.
Disallowing conflicting edits is totally fine, but maybe we could use a more narrow definition of a conflict to allow the case mentioned above?

**Comment by dbaeumer** [comment]
Having a single edit on the cursor line makes deciding where the cursor goes a lot easier for the editor. This is why we added the restriction.

**Comment by ilya-biryukov** [comment]
Can this be reformulated to say that the cursor position should be at the end of the **main** text edit?
That would allow edits at the same line without screwing up the editor.

**Comment by dbaeumer** [comment]
That would be breaking :-).

Out of curiosity: why is one edit not enough ?

**Comment by kadircet** [comment]
> Correct, but they conflict with the main edit because they change the same line the cursor is on. This is discouraged for additional text edits:

From the looks of the protocol it just says `unrelated to the current cursor position`, I don't think being on the same line conflicts with that definition. Tough each editor is free to decide on "relatedness" of a location to another.

> Having a single edit on the cursor line makes deciding where the cursor goes a lot easier for the editor. This is why we added the restriction.
> That would be breaking :-).

Again specification doesn't say anything about where the cursor should go after applying the edit, so it is up to clients(editors) anyway. Therefore having `additionalTextEdit`s on the same line with `textEdit` should not break any clients, even if they break it must be because of their implementation not due to the specification :-)

> Out of curiosity: why is one edit not enough ?

Well, this one is a special case where additionalTextEdit and textEdit was consecutive, so it might not always be the case. But we also tried what you suggested at the time, by sending just one `textEdit` that will replace the  `.`, but some editors(vscode) was ignoring completion items that contained a range prior to the completion token. This behavior on the editors might've changed over time as it was months ago.

**Comment by kdvolder** [comment]
> That would be breaking :-).

Well actually no.  Unless you consider a change that strictly extends the cases that the client promises to handle without throwing an error as 'breaking'. 

I think relaxing the contraint does not break anything because. Whatever worked before (without a error) will still work as before. And any *additional* cases that, under the relaxed constraint, now are also acceptable, now should *also* work. So I think that means nothing is getting broken, only some things that didn't work before are actually getting fixed.

**Comment by dbaeumer** [comment]
There are always different views on breaking. It might not break the spec but it very likely will cause trouble for existing client implementations which I try to avoid as well. 

The only save way how this can be tackled is IMO by making the textEdit an array and allow more edits on the cursor line and make this a client capability.

**Comment by kdvolder** [comment]
> The only save way how this can be tackled is IMO by making the textEdit an array and allow more edits on the cursor line and make this a client capability.

Please don't... the whole 'main edit' + 'additional edits' + 'a bunch of ill defined constraints' is already too complicated i.m.o. Are you really suggesting this be turned into a 'main edit **array**' + 'additional edits' + 'more contstraints than before' + 'a mechanic to enable this more complex form'? That sounds like a really bad idea to me.

**Comment by ilya-biryukov** [comment]
An alternative approach if we want to keep backwards compatibility with the existing clients is:
- keep the textEdit + 'additional edits' as they are
- broadcast a client capability whenever a client implements and supports a broader spec of additional edits (proposed in this issue).

The server would be responsible for not sending such edits unless the clients explicitly broadcast they support them.
This approach would to both keep the interface of the edits simple and have backwards compatibility.
