### ISSUE TITLE
Suggestion: First Class support for client level filesystem operations

### ISSUE THREAD

**Issue by Levertion** [Microsoft/language-server-protocol#545]
This follows on from Microsoft/vscode-languageserver-node#1, and sorry if this has already been dealt with in this repository.

## Synopsis

Add a mechanism by which servers may perform filesystem operations in the filesystem(s) being accessed by the client

## Motivation

From [the specification](https://microsoft.github.io/language-server-protocol/specification#textDocument_publishDiagnostics) (permalink: [`v3.10.0`/6b9ef042b7](https://github.com/Microsoft/language-server-protocol/blob/6b9ef042b75678224e9fc605cfd3699f2ae7c74c/specification.md#publishdiagnostics-notification-arrow_left)):
```
If a language has a project system (for example C#) diagnostics are not cleared when a file closes. When a project is opened all diagnostics for all files are recomputed (or read from a cache)
```

it is understood that the language servers are encouraged to support languages both with and without a project system. Languages with such a system require that the server understands information about files which are not open in the editor (such as the contents of `tsconfig.json` in typescript.

Since 1.23.0, `vscode` has supported such an api (`FileSystemProvider`) for extensions to provide alternative filesystem protocols (such as `ftp`). I believe that this should allows extensions which directly use the vscode apis to access files through any supported protocol (although I am not certain that this is the case).

There however does not seem to be any similar capability in language servers, which if present would allow greater flexibility in implementations. The current situation requires each server to support each scheme, which is reminiscent of the editor-language table which is one of the motiviations given for the language-server-protocol itself.

Any comments are appreciated.

**Comment by dbaeumer** [comment]
@Levertion I am not 100% sure what you are proposing. That a server can provide file to the client since the server almost always run where the files lives (all compiler tools I know most of the time directly talk to the file system).

So basically LSP-fy the vscode file system provider API ?

**Comment by Levertion** [comment]
> So basically LSP-fy the vscode file system provider API?

No, that would be the opposite direction to what I am suggesting. I mean give the server access to the apis of the vscode `FileSystemProvider` which the client workspace is using.

The reason I'm suggesting this is that at the moment, it is impossible to use a language server on an alternative filesystem such as an ftp filesystem (or github filesystem) neatly, which removes many of the advantages of using vscode, making duplicating the remote filesystem a more happy compromise.

However, thinking about it further I realise that this could add some pretty large performance penalties for the filesystem that the server is on, although this could be optimised by libraries such as `vscode-languageserver-node`.

**Comment by dbaeumer** [comment]
@Levertion I am not sure if this would ever work since these files would need to be persisted on the machine's file system the language server is running on. I know almost no language server which have a parser, scanner, compiler that abstracted over the underlying file system. Most use OS calls to read and write files and folders.

So what you are basically asking for is a file system sync or a virtual file system which IMO shouldn't be part of the LSP.

If it is a single file then a language server already can work on an in memory representation which is already supported in the LSP.

Is it OK for you to close the issue. I personally don't see this happening in LSP due to the above limitations of servers usually access the FS directly,

**Comment by Levertion** [comment]
Yeah, I know, it's quite infeasible. It more just seemed that this kind of thing would be wanted in vscode given the support for the filesystemprovider api.

Something like `redox-os`'s scheme system is better suited for this, which allows applications to create OS-supported custom URL handlers which are treated like real folders.
