### ISSUE TITLE
Provide more clarification to documentLink

### ISSUE THREAD

**Issue by octref** [microsoft/language-server-protocol#547]
https://code.visualstudio.com/docs/extensionAPI/language-support does not contain anything for `documentLink`.

The [spec](https://microsoft.github.io/language-server-protocol/specification#textDocument_documentLink) reads:

> The document links request is sent from the client to the server to request the location of links in a document.

This is very vague. I would expect the doc to explain:

- What is the client expected to do, when clicking the links (VS Code opens http/https links in browser and file links in editor). Basically the use-cases for the `documentLinks`.
- How does `documentLink` differ from `definition` and which one should I choose? Or should I have both? That's certainly one of my confusions when implementing https://github.com/Microsoft/vscode/issues/29899

**Comment by rcjsuen** [comment]
This does start to get even more blurrier if `DefinitionLink`s were added to the specification. See #542.

I imagine (think? hope?) the general consensus is that definitions refer to programming language constructs like types, functions, and so on and that document links are paths and URIs but it would be nice to get this clarified in the specification.

One thing to note is that `textDocument/documentLink` requests are handled by VS Code by underlining the underlying `range` defined by the returned `DocumentLink`. I don't know how other editors choose to implement this or if they simply don't bother to provide any visual feedback to the user.

**Comment by dbaeumer** [comment]
In general I tried to stay away to describe what clients have to do with the result or how they should render it. If the client underlines a link or not is up to the client. If it opens `http` links in a browser or in an embedded web view is IMO also up to the client.

**Comment by dbaeumer** [comment]
Will close the issue for now since users seems to know how to handle this.
