### ISSUE TITLE
Missing initializationOptions in InitializeParams

### ISSUE THREAD

**Issue by kaloyan-raev** [Microsoft/language-server-protocol#55]
The protocol documentation misses the ```initializationOptions``` member in the ```InitializeParams``` type.

The ```initializationOptions``` member is present in the VSCode language server implementation: https://github.com/Microsoft/vscode-languageserver-node/blob/master/server/src/protocol.ts#L226

**Comment by kaloyan-raev** [comment]
@dbaeumer Thank you!

**Comment by felixfbecker** [comment]
And what content does it hold?

**Comment by dbaeumer** [comment]
It is up to the server to specify this. Could be different between different language servers.

**Comment by felixfbecker** [comment]
@dbaeumer In VS Code's context, are these user settings?

**Comment by dbaeumer** [comment]
No, user settings come via a changeConfiguration notification.

**Comment by felixfbecker** [comment]
Thanks
