### ISSUE TITLE
Extending an existing server?

### ISSUE THREAD

**Issue by tom-sherman** [microsoft/language-server-protocol#552]
Apologies if this has already been asked or if I'm missing something obvious - I've had a thorough search and can't find an answer.

Is there a way to take advantage of an existing language server and extend it with something akin to middleware?

My use case is to extend an XML server and add custom functionality to improve autocompletion without rewriting the whole server from scratch.

An example:

```xml
<foo name="John" />
<foo name="Steve" />

<baz foo="x" />
```

Where `x` would show suggestions for `John` and `Steve`.

**Comment by rcjsuen** [comment]
@tom-sherman There is no official sanctioned way to do this. I'm not even sure what such an API would look like as it seems rather language-specific.

**Comment by mickaelistria** [comment]
Combining/extending LS is a topic for which neither the specification nor the principal implementations have established best practices yet.
Those 2 talks discuss it for LS extending Java and XML:
https://youtu.be/CbP7Lr9wPAk
https://youtu.be/N8jgaeHQsO0

Pragmatically, the best solution ATM seems to be the to create a specific LS for your John/Jack proposals. It will allow less adherance to the plain XML LS but will lead to some duplicated computation/parsing.
Somehow it seems like the LSP, like any message based system, can bring the need for message-transformation, filtering, dispatching solutions a la Camel proxying the various LS and holding the rules to combine them. But I don't have the impression this belongs to the spec.

**Comment by keegancsmith** [comment]
You can create a JSONRPC2 proxy to achieve the behaviour you desire. We use that pattern quite a bit at Sourcegraph.com

**Comment by angelozerr** [comment]
@tom-sherman If your language server can be written in Java, I suggest you to see the XML Language Server that we are implementing at https://github.com/angelozerr/lsp4xml/ 

This XML Language Server supports all features for XML (compeltion based on XML Schema, validation, folding, rename tag, highlight, document symbols, etc) and can be extended with SPI to add your own completion, hover, validation, XML Schema resolution). See https://github.com/angelozerr/lsp4xml/wiki/Features

It exists for instance 2 extensions at https://github.com/angelozerr/lsp4xml/tree/master/extensions to extend the XML completions to manage emmet feature and resolve XSL Schema.

![](https://github.com/angelozerr/lsp4xml/wiki/images/EmmetDemo.gif)

Please note the project is not released, so API could changed. If you are interested, please create issues at https://github.com/angelozerr/lsp4xml/issues

**Comment by anurbol** [comment]
I have the same demand. My use case is to process comments *and* related AST. Reusing Language Servers is desirable, while parsing the AST again (when it's already parsed by the LS) is a... meh.
