### ISSUE TITLE
Why don't you have a git tag for each release? 

### ISSUE THREAD

**Issue by mtsmfm** [Microsoft/language-server-protocol#559]
ref: https://github.com/Microsoft/language-server-protocol/issues/490

📝 

- 3.12.0: https://github.com/Microsoft/language-server-protocol/commit/e0ed81b9c0de995196c4ec7a54a7c9432bb7897f
- 3.11.0: https://github.com/Microsoft/language-server-protocol/commit/7aed39bc4b82d59ca328c43d56d85fec2ebee9b9
- 3.10.0: https://github.com/Microsoft/language-server-protocol/commit/396743671d268e2c7b942bbafd3c425e62dbb3e1

**Comment by rcjsuen** [comment]
And probably also #550 if possible... :)

**Comment by dbaeumer** [comment]
I will make sure that I tag the repository in the future. I do tag the vscode node modules.

**Comment by dbaeumer** [comment]
Both PRs are merge and I tagged the current head as release/3.12.0

**Comment by mtsmfm** [comment]
Thanks! 🙏
