### ISSUE TITLE
LanguageServerLauncherTemplete cannot be found.

### ISSUE THREAD

**Issue by LahiruT94** [Microsoft/language-server-protocol#571]
I'm trying to develop a plugin to test a sample language server. I cannot find the LanguageServerLauncherTemplete.

![meaeder](https://user-images.githubusercontent.com/34393074/45792990-b3ff0980-bcad-11e8-919f-f9841a8ddec2.png)

Is this class available? How can i implement the plugin according to this source code?

**Comment by dbaeumer** [comment]
This repository is about the specification. Looks like you want to get a language server running in IntelliJ. All I can recommend is to ask the question in the IntelliJ community.
