### ISSUE TITLE
CompletionItem needs information to position the cursor

### ISSUE THREAD

**Issue by svenefftinge** [Microsoft/language-server-protocol#58]
I couldn't find a way to tell through the protocol that the client should move the cursor to a certain position after applying a proposal.
Simple use case, would by applying a function call, where the cursor should sit between the parentheses afterwards. E.g. foo(|)

**Comment by rcjsuen** [comment]
I think this is covered by the snippet support in `CompletionItem` in version 3.0 of the protocol? Also see #236.

```JavaScript
CompletionItem: {
  insertTextFormat: InsertTextFormat.Snippet
  textEdit: {
    range: ...
    newText: foo($1)
  }
}
```

**Comment by rcjsuen** [comment]
@dbaeumer I think this can be closed?

**Comment by dbaeumer** [comment]
Agree. Thanks
