### ISSUE TITLE
TextDocumentContentChangeEvent duplicates TextEdit

### ISSUE THREAD

**Issue by jankeromnes** [Microsoft/language-server-protocol#580]
The specification defines interface `TextDocumentContentChangeEvent` as follows:

https://github.com/Microsoft/language-server-protocol/blame/0621edab0face875893fedffba383ff9676847e6/specification.md#L2471-L2491

However, there already exists a very similar interface called `TextEdit`:

https://github.com/Microsoft/language-server-protocol/blame/0621edab0face875893fedffba383ff9676847e6/specification.md#L399-L415

The differences between `TextEdit` and `TextDocumentContentChangeEvent` are:
- `range` → `range?` (optional)
- `newText` → `text` (rename)
- `Ø` → `rangeLength` (new property): Is it even necessary? Can't it be computed from the `range` property?

## If `rangeLength` isn't necessary

If the `rangeLength` property isn't necessary, I propose that all uses of `TextDocumentContentChangeEvent` be replaced by `TextEdit` (this implies that the `text` property be renamed `newText`; and that specifying `range` becomes mandatory (can be `position 0,0`)).

Furthermore, this causes the `DidChangeTextDocumentParams` interface:

https://github.com/Microsoft/language-server-protocol/blame/0621edab0face875893fedffba383ff9676847e6/specification.md#L2454-L2469

To become an exact duplicate of the `TextDocumentEdit` interface:

https://github.com/Microsoft/language-server-protocol/blame/0621edab0face875893fedffba383ff9676847e6/specification.md#L425-L439

So all uses of `DidChangeTextDocumentParams` should be replaced by `TextDocumentEdit`s.

## If `rangeLength` is necessary

Then I suggest that the `TextEdit` interface should receive a new optional `rangeLength?` property, so that the above suggested changes still apply.

In both cases, both duplicate interfaces `TextDocumentContentChangeEvent` and `DidChangeTextDocumentParams` can be removed.

**Comment by matklad** [comment]
Note that there's one more extremely annoying difference: semantics of `TextDocumentContentChangeEvent[]` and `TextEdit[]` are different. In the first case, ranges of subsequent changes are affected by preceding changes. With `TextEdit`, however, all ranges refer to the original document, without edits applied.

**Comment by dbaeumer** [comment]
As @matklad points out there is a huge semantic difference between them. In general I tend to not resuse to many structure since it makes it hard to evolve them later even if they share a common set of attributes. 

I will close the issue. @jankeromnes please ping if you disagree.
