### ISSUE TITLE
Suggestion: Add an optional `CodeAction` property to the `Diagnostic` interface

### ISSUE THREAD

**Issue by jankeromnes** [Microsoft/language-server-protocol#581]
I am interested in helping LSP implementations easily provide auto-fixes with their diagnostics.

Many compilers and linting tools like `eslint`, `flake8`, `clang-tidy`, etc... can provide diagnostics (such as errors, warnings, suggestions) that are often associated with a suggested quick fix (such as a code replacement or addition, or a resource change in the workspace).

However, the LSP implementations I saw usually display the diagnostic message without an associated quick fix (causing developers to lose time reading and understanding the message, and then inventing a way to fix it manually).

The way diagnostics and quick fixes are provided by LSP servers today, as I understand it, is:
- First, provide `Diagnostic`s (with relevant code location / range, severity, message, and associated diagnostics)
- Later, provide `CodeAction`s (with title, kind, workspace edit / command, and optionally associated diagnostics)

This means that implementations will focus on first displaying diagnostic messages (without any quick fixes), and maybe later try to support code actions, by maybe retroactively associating quick fixes to the relevant diagnostics (e.g. by adding a "Fix" button to a pre-existing diagnostic message UI). But in what I saw, LSP implementations don't usually do this, and it seems a bit unnecessarily complicated.

I suggest the following specification change, in order to make the support of quick fixes easier, more direct, and more obvious:

- Add an optional `quickFixes?: CodeAction[]` property to the `Diagnostic` interface, e.g. by amending it like so:

```typescript
 interface Diagnostic {
        /**
         * The range at which the message applies.
         */
        range: Range;
 
        /**
         * The diagnostic's severity. Can be omitted. If omitted it is up to the
         * client to interpret diagnostics as error, warning, info or hint.
         */
        severity?: number;
 
        /**
         * The diagnostic's code, which might appear in the user interface.
         */
        code?: number | string;
 
        /**
         * A human-readable string describing the source of this
         * diagnostic, e.g. 'typescript' or 'super lint'.
         */
        source?: string;
 
        /**
         * The diagnostic's message.
         */
        message: string;
 
        /**
         * An array of related diagnostic information, e.g. when symbol-names within
         * a scope collide all definitions can be marked via this property.
         */
        relatedInformation?: DiagnosticRelatedInformation[];
+
+       /**
+        * An array of suggested code actions to address the present diagnostic.
+        */
+       quickFixes?: CodeAction[];
 }
```

This allows LSP servers to provide `CodeAction`s directly with their `Diagnostic`s, instead of retroactively associating them. My hope is that this new possibility can simplify the support of quick fixes in all present and future LSP implementations.

What do you think of this suggestion? Is the addressed problem severe enough to warrant a specification change? And does the suggested change address the problem well enough?

What would be the next steps in order to build a consensus and potentially include this change in the specification?

**Comment by dbaeumer** [comment]
@jankeromnes sorry for the long delay. I am actually not a fan of this. Fixes should come through the code action request. In a normal typing situation this information is outdated pretty easily since servers deliver diagnostics async to the client. The user would need to stop typing to make the actually accurate at some time. In addition we would like to avoid that compiler generate these fixes during problem checking. I know that ESLint does this but most other compilers don't since computing he fixes is most of the time expensive.

To ease this on the server side we now support that a code action could already contain the edit which makes the whole quick fix pass already easier.

Any objection to close the issue?

**Comment by jankeromnes** [comment]
@dbaeumer Many thanks for reading and replying to my suggestion!

> Fixes should come through the code action request.

I understand that this is how things are specified today. However, my point is that this causes most LSP implementations to just support `Diagnostics` (easy), and to skip `CodeAction` requests altogether (more complicated to set up, because the Client needs to decide when to make requests, hoping that the Server is ready to respond).

Attaching optional `CodeActions` to some Server-pushed `Diagnostics` could make auto-fix implementations *much* easier.

> In a normal typing situation this information is outdated pretty easily since servers deliver diagnostics async to the client.

Ah, so your point is that `Diagnostics` themselves become outdated pretty quickly as you type. But is it the case that showing outdated *diagnostics* is okay while proposing outdated *fixes* is not okay?

Maybe the fact that `Diagnostics` become outdated easily is orthogonal to this discussion (but may be worth fixing independently).

> In addition we would like to avoid that compiler generate these fixes during problem checking. I know that ESLint does this but most other compilers don't since computing he fixes is most of the time expensive.

Interesting point, I wasn't aware that computing fixes incurred such a significant cost. Would you have any examples of fixes that are much more expensive to compute than their associated diagnostics?

In my experience (automatically running eslint; flake8; wptlint; clang-tidy; clang-format; and other analyzers on all Firefox commits undergoing code review) it seems like most tools that can generate *diagnostics* also generate *fixes* on the side, but since most aggregation mechanisms only care about the diagnostics, the fixes are simply not forwarded and thus lost. With this proposal, I'm actually trying to fix this pro-diagnostics/anti-fixes bias in LSP.

Furthermore, even assuming that some fixes are too costly to compute, the fact that the suggested `CodeActions` attribute is *optional* allows each implementation to decide whether or not to include fixes in their diagnostics. (E.g. if a compiler can report warnings & errors quickly, but its auto-fixes are slow to compute, its LSP Server implementation can simply send diagnostics without any fixes.)

**Comment by dbaeumer** [comment]
> Ah, so your point is that Diagnostics themselves become outdated pretty quickly as you type. But is it the case that showing outdated diagnostics is okay while proposing outdated fixes is not okay?

No that is not the point I am trying to make. It is about computing them is expensive and in most typing cases they will be computed and outdated and need to be dropped. I simply don't want to encourage server implementers to compute them if they are not needed on the client side.

If it is not a linting fix then they can easily become expensive. Consider a miss spelled word. It is easy for a compiler to detect that a symbol is not know (usually a hash table lookup) but to propose fixes it needs to go over all symbols (in languages that have many global symbols like c/C++ or Python) this can easily be thousands and needs to score them how similar they are to the typed word. Then take the top most scored once and propose them as fixes.

I see the point of making it optional however I am still not a fan of it. If we add that attribute we need to explain when it is `good` to use it and when it is `bad` to use it. In the current world it is fairly simply. Servers compute diagnostics and client ask for fixes when they think they need it. I would like to keep that model.
