### ISSUE TITLE
Add `uri?: DocumentUri` to DocumentSymbol

### ISSUE THREAD

**Issue by svenefftinge** [Microsoft/language-server-protocol#582]
The `DocumentSymbol` data type represents a symbol within a document. So far, the document's uri is implied from the call context. 
It would be good to have an optional `uri?: DocumentUri` field to support usage of the data type in other scenarios, where the document uri cannot be implied from the call:
 - outline (including inherited members)
 - call hierarchy
 - type hierarchy

See also 
 - https://github.com/Microsoft/vscode-languageserver-node/pull/420
 - https://github.com/Microsoft/vscode-languageserver-node/pull/346#discussion_r221659062

**Comment by kittaakos** [comment]
PR: https://github.com/Microsoft/vscode-languageserver-node/pull/425

**Comment by dbaeumer** [comment]
Closing based on the comments provided in Microsoft/vscode-languageserver-node#425
