### ISSUE TITLE
TextDocumentContentChangeEvent rangeLength unit unclear

### ISSUE THREAD

**Issue by DaanDeMeyer** [microsoft/language-server-protocol#588]
The `TextDocumentContentChangeEvent` interface defines the `rangeLength` to be the length of the range but doesn't specify the unit in which this range is specified. I'm assuming its the length of the range in UTF16 code units?

**Comment by dbaeumer** [comment]
Yes, everything is denoted in UTF16 code units. Will clarify this.

**Comment by dbaeumer** [comment]
I basically deprecated the field since no clients filled it in since it is optional.
