### ISSUE TITLE
Feature request: add ability to send results in small chunks

### ISSUE THREAD

**Issue by jgoshi** [Microsoft/language-server-protocol#59]
For cases where there are a (potentially) large number of results or a large response message add the ability to break the results into smaller sets.

**Comment by kaloyan-raev** [comment]
Isn't this similar to #47?

**Comment by jgoshi** [comment]
Yes, it's the same thing. Thank you. Any ETA for when that would be done?

**Comment by dbaeumer** [comment]
Closing as dup #47.
