### ISSUE TITLE
Add dart to the list of language identifiers

### ISSUE THREAD

**Issue by DanTup** [Microsoft/language-server-protocol#595]
It looks like the spec defines language identifiers:

> In the specification, each text document has a unique specific language identifier. The following table lists all currently defined language identifiers:

I don't know what the implications of not being on that list are, but I'm working on LSP support for the Dart analysis server so it seems like maybe it should be on the list?

(it may also be worth documenting the implications of being/not being on that list in the docs)

**Comment by DanTup** [comment]
@dbaeumer Thanks!

I think it'd be worth adding a note to the docs about the implications of not being on that list. I was already using `dart` as a language identifier in testing with seemingly no issue, so I wasn't really sure what it actually does :-)

**Comment by dbaeumer** [comment]
I already did that. I made it clear that this is a suggestion but not being in that list is not a spec violation.

**Comment by DanTup** [comment]
Perfect, thanks!
