### ISSUE TITLE
Resource operations: what overwrite=false/ignoreIfExists=false should do?

### ISSUE THREAD

**Issue by mickaelistria** [microsoft/language-server-protocol#596]
I'm trying to implement support for Resource Operations (RenameFile, CreateFile...) in Eclipse IDE with LSP4E. The specification seems not explicit enough to me, namely in the handling of overwrite and ignoreIfExists.
What are the various combination of both being false supposed to do for instance? Should it stop the whole workspace edit for being applied?

**Comment by dbaeumer** [comment]
@mickaelistria this depends on the client and is nothing the LSP enforces to be implemented i a certain way. See https://github.com/Microsoft/vscode-languageserver-node/blob/dbaeumer/projectReferences/protocol/src/protocol.ts#L244 which is a client capability. 

I know that this is not the most happy thing for server implementors but forcing a strategy seemed worse to us. Eclipse can for example provide 'undo' another editor might provide 'abort'
