### ISSUE TITLE
Clarify the language ID list 

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/language-server-protocol#598]

**Comment by jvalkeal** [comment]
@dbaeumer I also went through similar issue mentioned in #593 and felt that whole _language id_ in _LSP_ is highly opinionated with an actual implementation.

We have a new stuff in a Spring space which is an attempt to provide higher level lsp services to a users and this _language id_ always felt like slightly weird concepts in a _LSP_ itself to define some hard coded values. Taking a simple example of reconciling an arbitrary document, higher level component can have knowledge of reconciling only a single document type or it could know to reconcile everything regardless of a document type.

That's a reason why we came up with _isCompatibleWith_ in a higher level abstraction of a `LanguageId`. Higher level class can then then decide which types of language id's it actually supports and we added something more like `LanguageId.ALL` and `LanguageId.TXT`.

https://github.com/spring-projects/spring-dsl/blob/f3acd5e61a59550a23c1e8ad7053600193305f99/spring-dsl-core/src/main/java/org/springframework/dsl/model/LanguageId.java#L168-L181

Then any service consuming this can deside if particular component supports this _language id_, etc, and having special check for `*` can then accept all. As far I understood this is a way to use _language id_ in your library.

Just my 2 cents when deciding what to write to a LSP docs.

**Comment by jvalkeal** [comment]
Forget to mention that I think this issue is more than how to use _language id_ rather that how it is defined in a _LSP_ itself. I've yet to find any realistic use case for these id's to actually exist in a protocol itself other than have have some id's defined there what _LSP_ server impl's might support.

**Comment by dbaeumer** [comment]
@jvalkeal it is not the intention that a client can only send a language id that is in the list. All we ask is that if a client for example send a `TypeScript` language id it sends the right id value that is know in the spec. I will clarify this.
