### ISSUE TITLE
How should a server respond to a request with a non-utf8 content-type header?

### ISSUE THREAD

**Issue by DanTup** [Microsoft/language-server-protocol#600]
The spec says:

> The content part is encoded using the charset provided in the Content-Type field. It defaults to `utf-8`, which is the only encoding supported right now. 

Should a server send some sort of rejection to requests that explicitly specify a different encoding? (or should we try support any?). If so, what should the respond be, and how should it be encoded?

**Comment by dbaeumer** [comment]
In my opinion the server should respond with an error. I am open to support more encodings however we need to get a buy in from server and client implementations. It doesn't help if we allow other encodings, client send it and no server handles them.

I added 

```
If a server or client receives a header with a different encoding then `utf-8` it should respond with an error.
```

to the spec. Is it ok for you to close?

**Comment by DanTup** [comment]
Yeah, I think supporting other encodings would be painful, I just wanted to make sure I was doing something sensible in this case (and consistent with others). Thanks!

**Comment by DanTup** [comment]
> If a server or client receives a header with a different encoding then `utf-8` it should respond with an error.

While implementing this, it occurred to me that we'll have to send the error as notifications (showMessage/logMessage), since without a valid encoding, we can't decode the body and therefore can't handle the response.

This means we'll potentially leave responses open (which we don't want to), but I think in this case it's a fairly catastrophic failure and we can't work anyway.

It may be worth clarifying the exact format of the headers to ensure servers aren't failing to parse things that are valid though - like are the headers case-sensitive? Should the whole content-type be checked or only the `charset`?

Currently I'm splitting the Content-Type header on `;`, trimming, lowercasing, looking for an item that starts `charset=` and then ensuring it's `utf-8` or `-utf8` (or missing), otherwise considering it an error.
