### ISSUE TITLE
Add support for request to get source files

### ISSUE THREAD

**Issue by raja-s** [microsoft/language-server-protocol#606]
In languages such as Ada, the set of source files that constitute a project can be dynamic, as project files can define different switches that can be passed during compilation as well as what source files are used for each switch. Contrary to other languages where an IDE can just consider all source files reachable from the project root as source files belonging to the project, that information becomes important for different operations that an IDE might want to do, including code analysis/searching.

The proposed extension here is a request, from the client to the server, to get the list of "valid" source files for a given configuration. A server for a language for which this problem does not exist can simply not provide a capability for this method.

Here's a quick suggestion:

Request:
* method: 'workspace/sources'
* params: `SourcesParams` defined as follows
```
interface SourcesParams {
        /**
         * The configuration for which to get the list of valid source files.
         */
        configuration: any;
}
```
Response:
* result: `DocumentUri[]` | `null`
* error: code and message set in case an exception happens during the request.

Since there already exists the 'workspace/didChangeConfiguration' notification, whose parameters can include generic configurations, the proposed "sources" request could very well even not include any parameters, in which case the server returns the list of sources for the current configuration.

**Comment by raja-s** [comment]
Here's a couple possible use cases:
- A client could use the result to limit search operations such as find-usages to the scope of the returned sources. This is a plausible use case in huge projects.
- IDEs generally have a feature to open a file by entering its name in a text field with autocomplete. A client could use the result to search for potential matches.
- Some IDEs can create project structure views that don't necessarily directly reflect the file system. In languages where this matters, a client could use the result to create a project view containing the source files that are used for the project.

**Comment by dbaeumer** [comment]
I see. I would suggest that this is first implemented using a custom request (which the LSP supports). I hardly believe that any client API generically allows you to honor this. So we first need to understand how this would affect clients and LSP enhancements require an client implementation (must not necessarily be VS Code) to be proven useful.

I will leave the item open as a feature request.
