### ISSUE TITLE
Spec is unclear about responding to $/ requests

### ISSUE THREAD

**Issue by DanTup** [Microsoft/language-server-protocol#607]
In the spec it says:

> If a server or client receives notifications or requests starting with '$/' it is free to ignore them if they are unknown.

And also:

> A request that got canceled still needs to return from the server and send a response back. It can not be left open / hanging. This is in line with the JSON RPC protocol that requires that every request sends a response back.

These seem to contradict. The first says I can ignore a request that start with `$/` but the second says that the JSON RPC spec says every request must get a response.

So, if I receive a request that starts with `$/` and I don't recognise it, should I a) never respond to it or b) send some error response?

**Comment by dbaeumer** [comment]
You can ignore `$` request, if then `$/cancel` request. However if you process the `$/cancel` request you need to send a response back for the request that got canceled. You can not leave the canceled request open. You can either return a result or error the response with a `RequestCancelled` error code (https://github.com/Microsoft/vscode-languageserver-node/blob/master/jsonrpc/src/messages.ts#L53).

OK to close ?

**Comment by DanTup** [comment]
> You can ignore `$` request, if then `$/cancel` request.

I'm not sure what this means. I'm ignoring `$/cancel` requests and still providing a response. But I'm wondering if I get a request for `$/foo` that I don't recognise and I ignore it, will the client be sat around with an open request forever? (and is this a problem, or something the client must cater for?).

**Comment by dbaeumer** [comment]
Sorry, typo: you can ignore $ requests, even the $/cancel request.

Now I see. I will update the spec that $/request should be errored if unknown (there aren't any right now anyways).

**Comment by dbaeumer** [comment]
Added 

```
If a server or client receives notifications starting with '$/' it is free to ignore the notification. If a server or client receives a requests starting with '$/' it must error the request with error code `MethodNotFound` (e.g. `-32601`).
```

**Comment by DanTup** [comment]
> I will update the spec that $/request should be errored if unknown (there aren't any right now anyways).

Sure, but I was thinking forwards for if in the future someone points an editor that knows about other `$` requests that the server was coded before :-)

> If a server or client receives notifications starting with '$/' it is free to ignore the notification. If a server or client receives a requests starting with '$/' it must error the request with error code `MethodNotFound` (e.g. `-32601`).

Perfect - that's clears everything up - thanks! 👍
