### ISSUE TITLE
How should unknown notifications that do not start with $/ be handled?

### ISSUE THREAD

**Issue by DanTup** [Microsoft/language-server-protocol#608]
The spec says that notifications starting `$/` can be ignored if they are unknown. However it doesn't say what should be done with notifications that are unknown that do not start with `$/`. We can't send an error response for notifications.

Currently I'm sending a `window/showMessage` notification with type=Error and message=`Unknown method xxx` so that it's obvious in the editor that something has gone wrong which is handy for me during dev, but not ideal if in the future someone points a newer LSP client that sends notifications I don't handle and they get spammed with messages.

**Comment by DanTup** [comment]
> I am actually not a big fan of showing an error in the user interface for this since a user usually has not idea what to do with it. He will simply ignore it.

Maybe, but if he doesn't see it he'll certainly ignore it :-)

I think `logMessage` may make more sense - it won't show an error popup, but it's at least communicated back to the client that they're doing something we don't understand. That said, I have no idea where logMessage goes (as mentioned in another issue, I don't think it's very clear in the spec how editors will handle this - how visible (or not) is the output?).

> Have you seen this happening that you get request and notification that you don't know?

No, I was just implemented my servers handler and needed to decide what to put in some `else` and `catch` cases. Not sending responses to requests sounds a little weird (since the client presumably needs to keep its handler ready to handle a response, whereas if we respond with an error it can clean up).

**Comment by dbaeumer** [comment]
A request should always be answered with a response and not left open.

**Comment by DanTup** [comment]
This was resolved by https://github.com/Microsoft/language-server-protocol/issues/607#issuecomment-448624438 / cf05574f8993fd5c34d4e00e7c23390db72904f5.
