### ISSUE TITLE
How should a server respond to invalid notifications (for ex textDocument/didChange with invalid line/col info)?

### ISSUE THREAD

**Issue by DanTup** [Microsoft/language-server-protocol#609]
Since `textDocument/didChange` is a notification, there's no obvious way to respond to it with an error. What should a server do if the line/col information given doesn't match something on the server?

Currently I'm sending showMessage with type=error, similar to unknown notifications - see #608, but the client has no idea that these are related to the document (if it did, it could probably re-send the document, to get things fixed up - though I appreciate it might not be worth the effort to try to work around what's a serious bug in either the client or the server).

**Comment by DanTup** [comment]
> All it can do right now is to log it, show a reasonable error to the user

Is there any guidance on this? We have showMessage and logMessage but the spec doesn't really give any guidance on how they should be used (for ex. is `logMessage` for logging things that user should see, or may its output be buried away hidden somewhere). Currently I'm generally sending errors for notifications with showMessage (to ensure the user sees them) and sending copies of errors that resulted in requests failing to logMessage (because I don't know if the editor shows any feedback if I respond to a request with an error). I don't know if this is good, it'd be better if there was some consistency across editors (which I guess means some guidance by the spec).

> restart in the specific case of an invalid `textDocument/didChange` notification.

I'm not sure what "restart" means in this context? If there was a bad `textDocument/didChange` notification, wouldn't the *client* need to restart the server and re-transmit its buffers for each file - can that be initiated from the server?

Thanks!

**Comment by dbaeumer** [comment]
Most clients restart a server when it exists and the exit request is not triggered by the client itself. However this is not spec`d.

`logMessage` is for logging and it might not draw attention to the user (as with all logging capabilities I know)
`showMessage` asks the client to display a particular message in the user interface.

I would like to keep this up to the editor to decide how it handles a failed request. For notifications I think it depends on the state the server is in afterwards. If it is in an inconsistent state then it should inform the user about it and we can think about adding a notification to ask the client to initiate a server restart. However I would not bind this to notifications but to the fact that the server is in a state that is not good. The fact that `textDocument/didChange` has invalid line/col info is not necessarily a client fault. It could easily be that the server did some mistakes applying previous deltas.

**Comment by DanTup** [comment]
> Most clients restart a server when it exists and the exit request is not triggered by the client itself. However this is not spec`d.

Maybe it's worth adding that to the spec (as guidance, not a requirement)? It'd probably also make sense to suggest the server sends a `logMessage` or something first to help the client understand why the server appears to keep quitting if something has gone bad.

> `logMessage` is for logging and it might not draw attention to the user (as with all logging capabilities I know)

Ok - where is this output surfaced in VS Code, for example?

> The fact that `textDocument/didChange` has invalid line/col info is not necessarily a client fault. It could easily be that the server did some mistakes applying previous deltas.

That's true, but it doesn't matter whose fault it is, the server has detected the fault and needs to know what to do. Silently ignoring the request is dangerous because the next request may have what looks like a valid line/col but because it's out of sync, it starts trashing things.

I think document how a server should behave if it detects things are inconsistent is a good idea to ensure all clients/servers are on the same page.

**Comment by dbaeumer** [comment]
Added something to the `Implementation consideration` section.
