### ISSUE TITLE
formatting spec unclear on indent and tab size

### ISSUE THREAD

**Issue by casouri** [Microsoft/language-server-protocol#610]
Current formatting spec requires two property:
`tabSize` and `insertSpaces`.

Some questions:
1. If `insertSpaces` is `true`, does formatting translate tabs **in the middle of a line** (that's not in a string), i.e. tabs that are not for indent, into spaces?
2. If it does, then `tabSize` now has two meanings: size of an indent step in spaces, and size of a tab in spaces. Which one should it be?
3. What if I want two tabs for each indent step?

**Comment by casouri** [comment]
As I said, the current spec raises these questions. No matter change the spec or not, could you answer these confusions I have? Thanks.

**Comment by dbaeumer** [comment]
Here is what I personally would do if I would translate tabs in the middle of a line. I would interpret tabs as a grid and fill in spaces to make it stop at a grid layout (analogous to indentation). So if you have a tabSize `4` and a tab character at position 37 I would fill in three spaces. But this is me.

**Comment by casouri** [comment]
It's good to know what you would do, but I'm more interested in what how does the spec regulates this request.

So if, as a client, I set `tabSize` to `8` and `insertSpaces` to `true` and requests for a reformat, what would (should) happen according to the spec?
1. Does indentations take a step of 8 spaces?
2. What happens to a tab (`\t`) in the middle of a line? Does the spec regulate this? I just want to have a concrete answer, so "no" is as good as "yes".
3. If I want to use two tabs as my indentation step, can I specify it through LSP request? If I can, how should I?

**Comment by dbaeumer** [comment]
I thought your original question was around what should happen with `\t` in the middle of the line. Here my answer still holds: I would not spec this. So my answer are:

1.) yes
2.) no
3.) not possible.

**Comment by casouri** [comment]
Thanks! I'll reopen if there are further questions.
