### ISSUE TITLE
How do I inform a client which file types my server cares about edits for?

### ISSUE THREAD

**Issue by DanTup** [Microsoft/language-server-protocol#614]
I can't find any way to inform the client which file types my server cares about. There's no point it sending edits (`textDocument/didChange`) for JavaScript and CSS files since my server won't do anything with them.  I can filter them out on the server but it seems wasteful.

I found that there's a `DocumentSelector` interface in the spec, but it only seems to be used in `TextDocumentRegistrationOptions` which only seems to be valid in certain capabilities (and not one relating to file edits)?

**Comment by matklad** [comment]
@DanTup I think this is handed on the client side: client needs to know the set of interesting files to start your server in the first place. Here's how I register my server for Rust files: https://github.com/rust-analyzer/rust-analyzer/blob/7adbea9c425847ee7193d3eaba2bef5ba4f0d4bd/editors/code/src/server.ts#L22-L27

There's also `DidChangeWatchedFilesRegistrationOptions` which allows you to plug into client's file watching services for additional files.

**Comment by DanTup** [comment]
Aha! Apparently I already set that documentSelector up when I started and forgot about it :-)

I did find the watcher, but that doesn't affect the `didChange` notifications (our server already does its own watching, so I won't bother messing with that for now)!

**Comment by dbaeumer** [comment]
Please note that since 3.0 is is a different way to register for document changes if the client supports dynamic registration which VS Code does. See https://microsoft.github.io/language-server-protocol/specification#client_registerCapability

**Comment by DanTup** [comment]
Ah, that might be better, having it in the server. I'll make a note to have a look later - thanks!
