### ISSUE TITLE
Allow to control the name of the outline view

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/language-server-protocol#617]
See vscode issue: https://github.com/Microsoft/vscode/issues/62839

**Comment by KamasamaK** [comment]
To match the VS Code implementation, this would involve adding `label` to `DocumentSymbolOptions`. Alternatively, I suppose a language client could just use `serverInfo.name` for this purpose.

**Comment by dbaeumer** [comment]
Implemented in 3.16.
