### ISSUE TITLE
Add support to the protocol to execute an comand in the server.

### ISSUE THREAD

**Issue by mickaelistria** [Microsoft/language-server-protocol#62]
I'm trying to implement CodeLens and CodeAction for Eclipse IDE. I see it uses _commands_. Such commands seem to be references to existing command handlers, however the protocol doesn't define those commands and which part of the application is supposed to define/handle them.
An explanation about it in the protocol.md file would be welcome, or maybe just an example of how VSCode deals with it.

**Comment by dbaeumer** [comment]
@mickaelistria think about a command as a command id. There is little we can specify here. When a code lens or code action is dispatched the tool plugin has to decide what to do. The idea is that if we now a certain set of actions we can spec them in the protocol and make the server perform these actions automatically. For now the actions have to be handled in the tools extension and may be forwarded to the server appropriately.

**Comment by dbaeumer** [comment]
I updated the doc accordingly. I also change the title to forward the execution of a command to the server by default. Then at least no tool code is required even if the command are not standardized yet.

**Comment by dbaeumer** [comment]
Dups #34. Also read:

https://github.com/Microsoft/language-server-protocol/issues/34#issuecomment-269637925
