### ISSUE TITLE
idea: class diagrams

### ISSUE THREAD

**Issue by thorade** [microsoft/language-server-protocol#622]
I have never worked on the LSP internals, but to my understanding at some point all information is available that would be required to generate a class diagram as shown e.g. here:
https://en.wikipedia.org/wiki/Class_diagram
There are several tools for drawing such diagrams, and if LSP provided a standardized way of how to pass this information, then such tools could probably generate UML class diagrams automatically.

In a second step, such class diagrams could possibly be dynamic, like show/hide certain fields.
Another idea could be to use the class diagram also for navigation, like going to base class and back.

**Comment by dbaeumer** [comment]
I am happy to include such a diagram if someone generates it off the protocol.ts file here: https://github.com/Microsoft/vscode-languageserver-node/blob/master/protocol/src/protocol.ts
