### ISSUE TITLE
Fix 'go to definition'

### ISSUE THREAD

**Issue by busykoala** [Microsoft/language-server-protocol#624]
I have `"python.analysis.downloadChannel": "daily"` activated.

The update today broke the 'go to definition' feature for my setup.
It's regarding a large plone project using the omelette as described below.

To avoid language server load infinitely (which would be another issue, maybe related to [this](https://github.com/Microsoft/python-language-server/issues/181)), I excluded the `parts/omelette` with `search.exclude`.
Below that in the settings, I added the `parts/omelette` with: `"python.autoComplete.extraPaths": ["${workspaceFolder}/parts/omelette", ],` which seemed to work for the last few days now.
By 'it seemed to work' I mean it could resolve the omelette imports and jump to definitions.
Now it sais 'no definition found for...'.

For what I can see in the output, before the update, it used to analyse from `autoComplete.extraPath`, which it does not anymore since it updated the language server today.

(`parts/omelette` contains symlinks to cross-project sources in a local directory.)

**Comment by dbaeumer** [comment]
@busykoala this repository is about the LSP specification. Please file the issue against the concrete product or extension.

Please ping if you think this repository is the right place.
