### ISSUE TITLE
Common between what?

### ISSUE THREAD

**Issue by SamB** [Microsoft/language-server-protocol#625]
The one-line description for this repository is "Defines a common protocol for language servers."

From that, I understand (maybe misunderstand?) that the protocol is intended to allow several development environment to speak to various language-specific servers providing services such as:
  * [Almost certainly] What you at Microsoft call IntelliSense. (Is that trademarked? I rarely see anyone claim that they actually provide that outside MS ecosystems; everyone else seems to just describe it as completion with fanciness, sometimes saying that it is *like* IntelliSense.) Anyway, whatever you call such functionality, that's been the main motivation behind the existence of most of the "language servers" I have heard of.
  * [Perhaps] Syntax highlighting
  * [Perhaps] Build-related stuff
  * [Perhaps] A REPL
  * [Maybe] Debugging support.

(One very special family of "language servers" I've heard of actually provides support for basically everything listed above except syntax highlighting, and that's [SLIME](https://common-lisp.net/project/slime/)'s "SWANK" backends.)

What I **don't** get from the one-line description is any information regarding *what* development environments use this protocol. I only know that it has something to do with VS Code because I got here from a link on https://github.com/Microsoft/vscode/wiki/Related-Projects

**Comment by Gama11** [comment]
>What I don't get from the one-line description is any information regarding what development environments use this protocol.

Have you seen https://microsoft.github.io/language-server-protocol/implementors/tools/?

**Comment by dbaeumer** [comment]
@SamB it is more about coding and code navigation features like code complete, signature help, goto definition, find all references, ... See also https://microsoft.github.io/language-server-protocol/overview which explains it hopefully a little better. Is there anything you can recommend we change to make this more clear.
