### ISSUE TITLE
json-rpc should spec how to communicate a canceled request in its response

### ISSUE THREAD

**Issue by AArnott** [Microsoft/language-server-protocol#63]
The [spec for cancelling requests](https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#cancellation-support) doesn't specify how the server indicates to the client that a response reflects a canceled request.

For example, a client sends request 1 and then cancels request 1. The server sends a response for request 1 and should provide either a complete response to 1 (because the cancellation request was ignored or came in after the response was complete) or provide indication that the processing of request 1 was in fact canceled. But the latter bit is not spec'd out. How can the client discern between a complete result, a general error, and a mere cancellation in the response message?

**Comment by dbaeumer** [comment]
Good point. Adding to the 3.0 backlog.

**Comment by AArnott** [comment]
Just noticed this is related to https://github.com/Microsoft/language-server-protocol/issues/185

**Comment by dbaeumer** [comment]
There is one thing we added in the meantime to the protocol. It is a constant ErrorCodes.RequestCancelled which can be used in a rejected response to signal that the request is canceled. However that still doesn't address the problem that a resolved response could be incomplete.

**Comment by AArnott** [comment]
Conveying a status for "successful yet incomplete result" is a very low priority, IMO. .NET itself hasn't established a pattern to convey that either, and I don't think javascript has. So I think the new error code you describe sounds adequate to close this issue when the spec is updated.

Fixed by f3ef9bf65e5545467366f3568e2b1e7f8b400cee.
