### ISSUE TITLE
Small suggestion on LSIF: Use object for placeholder instead of string

### ISSUE THREAD

**Issue by felixfbecker** [Microsoft/language-server-protocol#635]
One small thing I saw in LSIF was for reusing the input hover range in the hover result, LSIF uses a template-string like syntax:

```ts
	public hoverResult(contents: lsp.MarkupContent | lsp.MarkedString | lsp.MarkedString[], range: '${startRange}'): HoverResult;
```

https://github.com/Microsoft/lsif-typescript/blob/88e60576093b3c22b1602ec005bda15156c64877/tsc-lsif/src/graph.ts#L188

I found that a bit weird because the type of that property is not a string. I would suggest an object instead, something like this:
```ts
{ $ref: 'startRange' }
```

This is inspired by how JSON schema references schemas in other sections of the same JSON document. `$ref` could be a JSON pointer evaluated on the input object.

**Comment by dbaeumer** [comment]
Actually we removed this from the spec but I forgot to adopt the implementation. The sepc now says that if the stored result doesn't have a range the starting range should be filled in. 

I do agree that the ref syntax is the better syntax to use.

Updated the code to reflect the spec change.
