### ISSUE TITLE
Language server for Visual Basic.Net.

### ISSUE THREAD

**Issue by hifall** [Microsoft/language-server-protocol#639]
I understand that this issue doesn't really belong here, it should be filed via some Microsoft feature suggest channel for the Visual Basic.Net team or something like that. Problem is, I can't really find any channel online for this purpose, therefore, I give it a shot here.

Per Tiobe: [Programming Language Popularity](https://www.tiobe.com/tiobe-index/), Visual Basic.Net ranks on the list as the 5th most popular programming language as of this month, with over 7% market share. It's even more popular than C#, and on par with C++. Surprisingly, there seems to be no implementation or initiative for a Visual Basic.Net language server. Nowadays, even a language with 1/10 of VB.Net's market share has a language server.

I understand VB.Net is tightly coupled with other components inside the Microsoft ecosystem, like Visual Studio, etc., and maybe that's why.

What do you guys think? Do you think it make sense for such an LSP implementation for VB.Net?

**Comment by rcjsuen** [comment]
I don’t think anyone that watches this repository would say “No, language X should not have an LSP server implementation.” ;)

**Comment by dbaeumer** [comment]
@hifall agree that a server for .Net VB would make sense. All I can recommend is to post something here: https://visualstudio.microsoft.com/ if you think that needs to come from MS.

I will close the issue since there is nothing that can be done in this repository.
