### ISSUE TITLE
CompletionItem should support multiple TextEdits

### ISSUE THREAD

**Issue by gorkem** [Microsoft/language-server-protocol#64]
In some cases a CompletionItem may require multiple TextEdits to be applied. For instance when referencing a Java type, CompletionItem can also modify the imports (auto import on most Java IDEs). 

Alternately we can introduce the concept of prerequisite CompletionItems which will be applied before applying the actual one.

**Comment by svenefftinge** [comment]
This seems to be a duplicate of #11

**Comment by gorkem** [comment]
correct, missed that one
