### ISSUE TITLE
LSP does not prohibit empty symbol names, but VS Code rejects them

### ISSUE THREAD

**Issue by tchebb** [microsoft/language-server-protocol#641]
`DocumentSymbol` and `SymbolInformation` each hold a `name` field, [defined](https://microsoft.github.io/language-server-protocol/specification#textDocument_documentSymbol) only as a string that is "The name of this symbol." However, VS Code [applies](https://github.com/Microsoft/vscode/blob/4ebe0f0c38126859034decfd46b845ca07392556/src/vs/workbench/api/node/extHostTypes.ts#L917-L919) an additional constraint that the symbol name not be empty. This ambiguity recently caused the Rust Language Server to fail to populate VS Code's outline view (see rust-lang/rls#1193). If empty symbol names are actually prohibited, can the LSP spec reflect that?

**Comment by dbaeumer** [comment]
This got addressed in the 3.15 spec.
