### ISSUE TITLE
ParameterInformation has duplicate label definition in spec

### ISSUE THREAD

**Issue by DanTup** [Microsoft/language-server-protocol#643]
I'm parsing the spec to code-gen my classes from it, and noticed that it's spitting out multiple definitions for `label` in `ParameterInformation`. Looks like it's an error in the spec:

![screen shot 2018-12-17 at 5 03 39 pm](https://user-images.githubusercontent.com/1078012/50102812-f76e0300-021d-11e9-9ddb-589daf3be10b.png)

@dbaeumer

**Comment by Gama11** [comment]
There's already a PR for this: https://github.com/Microsoft/language-server-protocol/pull/638

**Comment by DanTup** [comment]
Ah, good spot - I checked the issues list but not PRs. No need for this then - thanks!
