### ISSUE TITLE
Is a client required to provide a `name` for a `WorkspaceFolder`?

### ISSUE THREAD

**Issue by DanTup** [Microsoft/language-server-protocol#655]
`WorkspaceFolder` looks like this in the spec:

```ts
export interface WorkspaceFolder {
	/**
	 * The associated URI for this workspace folder.
	 */
	uri: string;

	/**
	 * The name of the workspace folder. Defaults to the
	 * uri's basename.
	 */
	name: string;
}
```

I think it's a little ambiguous about whether `name` should be supplied. It's not marked as `null` or `?` so I *presume* it's always required to be supplied, but you could interpret the "default" text to mean if you don't send it to the server, the server will use the URI's basename so if the client is expected to do that, it's worth being explicit.

**Comment by dbaeumer** [comment]
This is indeed a little misleading and I would opt to rephrase this a little. The value is not optional, since it is filled in by the client. This should explain that the name can be used in the UI and could be something the user has defined.
