### ISSUE TITLE
Clarify when null is allowed in the spec

### ISSUE THREAD

**Issue by DanTup** [microsoft/language-server-protocol#656]
There are a number of issues with questions about nulls, and the response is normally along the lines of https://github.com/Microsoft/language-server-protocol/issues/355#issuecomment-356570544 where @dbaeumer said

> The idea here is that if a type annotation doesn't include | null null is not a valid value.

I think that a) this should be explicitly noted in the spec document to make it clearer, but also b) I believe it's slightly misleading, as there are places that say `any` that are allowed to have `null` (for example `ResponseMessage.result`).

**Comment by dbaeumer** [comment]
@DanTup I fixed the any case for `ResponseMessage.result` which now say `object | null`

**Comment by DanTup** [comment]
@dbaeumer Thanks. I think it'd be worth adding a note to the spec that explicitly states the rules for nulls in `any`/`object` (do either allow `null`? if not, is there a difference between `object` and `any`?)

**Comment by dbaeumer** [comment]
Here is what I think we should do: don't use any in the spec anymore. Use object and | to express what valid types are. If `null` is allowed make it explicit.

So something like `string | number | boolean | object` instead of any or `string | number | boolean | object | null` is `null` is allowed. 

Does that make sense?

**Comment by DanTup** [comment]
Sounds great to me, the less ambiguity the better 👍

**Comment by mickaelistria** [comment]
I also like a lot the proposal of avoiding `any` and making `| null` explicit whenever possible. Making "null" an explicit type is actually the best approach to null-safety a language or protocol can build.

**Comment by dbaeumer** [comment]
I did a pass for this for the upcoming 3.15 spec. Please open individual items if you still see something wired.
