### ISSUE TITLE
LSP spec suggests result=null is valid when there's an error, but JSON-RPC says this is not allowed

### ISSUE THREAD

**Issue by DanTup** [Microsoft/language-server-protocol#657]
In `ResponseMessage` it has this:

```
	/**
	 * The result of a request. This can be omitted in
	 * the case of an error.
	 */
	result?: any;
```

This suggests that it's allowed to send `null` as `result` if there is an error (as opposed to omitting it). This is convenient for me, however I'm slightly nervous that clients may not handle this correctly, and may interpret a `null` result as meaning there was no error (and then not check the `error` property).

Assuming result=null is valid for an error, I think it should be made clearer in the spec that the `error` field takes precedence when both fields are present.

**Comment by DanTup** [comment]
Actually, I believe the spec is incorrect here and this is invalid. See JSON-RPC:

https://www.jsonrpc.org/specification#response_object

## result
- This member is REQUIRED on success.
- This member MUST NOT exist if there was an error invoking the method.

So the text in the spec is incorrect. It should read "This MUST be omitted in the case of an error".

**Comment by dbaeumer** [comment]
Yes, it is invalid. That I used any here comes from the old days where TS didn't have support for object. Changed to:

```
	/**
	 * The result of a request. This member is REQUIRED on success.
	 * This member MUST NOT exist if there was an error invoking the method.
	 */
	result?: string | number | boolean | object;
```

**Comment by DanTup** [comment]
@dbaeumer Should `| null` be in there? It's valid to return `null` for `result` in the case of there not being an error. The original issue was that it wasn't clear that `null` was forbidden when there's an error, not that it should be forbidden always.

(it's possible `object` implies `null` is allow, but I don't think so?).

**Comment by DanTup** [comment]
@dbaeumer (see above - I think this may need `| null` adding?)

**Comment by DanTup** [comment]
(@dbaeumer Sorry for the spam, but this seems incorrect and I think it may have been overlooked - see above :-))

**Comment by dbaeumer** [comment]
Yes, sorry overlooked it. Reading through the spec (https://www.jsonrpc.org/specification#response_object) I agree that `null` should be a valid result value.

**Comment by dbaeumer** [comment]
Change the node implementation accordingly.
