### ISSUE TITLE
Consider whether language server protocol is exposed to Cross Protocol Scripting attacks

### ISSUE THREAD

**Issue by mirhagk** [microsoft/language-server-protocol#66]
Reading through [this blog](http://bouk.co/blog/hacking-developers/) it occured to me that it's not just something like memcached or mongodb that could be exposed. Would open language server be exposed as well?

Essentially the attack boils down to getting the browser to send a request to localhost, which the browser will happily do (but won't send any results back thanks to cross origin).

The 2nd part shows how DNS rebinding can be used to get around the cross origin restriction.

Both parts are potentially bad, but the first one is bad enough on it's own. I don't see any mention of what the language server is supposed to do when headers aren't recognized. If it simply ignores it then is there any reason why something like

```
POST / HTTP/1.1
Host: localhost:6379
Content-Length: ....

{
    "jsonrpc": "2.0",
    "id": 1,
    "method": "textDocument/textEdit", 
    "params": {
        ...//some evil code being injected into the source code
    }
}
```

Which could be sent by doing

```
<form enctype="text/plain" method="POST" action="http://localhost:6379">
<textarea name="abc">
{
    "jsonrpc": "2.0",
    "id": 1,
    "method": "textDocument/textEdit", 
    "params": {
        ...//some evil code being injected into the source code
    }
}
</textarea>
<input type="submit" value="Submit" />
</form>
```

Would be prevented from being executed?

(sorry if this is a silly irrelevant question. I just want to make sure this was thought about).

The article suggests terminating requests when you see there is a `HOST` field, but perhaps open language server would actually like to support functions that run from within a browser (after all is this how visual studio code communicates since it's in electron?)

**Comment by dbaeumer** [comment]
Malforming a document is possible using the language server protocol. The protocol can't define what legal document content is (e.g. a script tag in a html file). IMO it is up to the server and /or editor implementor to protected against this. For example VS Code ensure that script tags are always properly escaped before rendering them web view. In addition VS Code uses private channels to the server so that a server started for VS Code can't be hijacked by another tool / browser running on the system.

@mirhagk do you have any suggestion how this can be protected on the protocol spec level itself?

**Comment by mirhagk** [comment]
It's not so much about the document being malformed as it is who is doing the malforming. With this security hole in browsers a malicious website can modify a user's code base simply by accessing the website. 

Private channels would indeed fix this issue, so the browser can't hijack (accidentally) the server instance. Good to know that this isn't an issue with current implementations.

If it's best practice to communicate on private channels like that then that might be sufficient for this (perhaps it might be worth explicitly mentioning best practices for language servers/editors). A protocol level fix might not be required.
