### ISSUE TITLE
What should the client's behavior be with multi line autocomplete

### ISSUE THREAD

**Issue by kaushik-work** [Microsoft/language-server-protocol#664]
My server sends back a multi-line completion, which is really a template (or snippet as the LSP calls it, but with no fancy markup). The only client that seems to remotely process this properly is the PyCharm language client. (I tried clients for vim but they all failed in different ways). Even PyCharm fails, because it displays only one out of three autocomplete options. Any way, this is just a ranty preamble.

What happens in PyCharm is that the client throws a frothy java error because there are more lines in my snippet that in that document. Ideally the user will be inserting the snippet into a new document (because it's a template).

If I hit enter to make enough lines, then go back to the top of the document and then execute autocomplete, finally this, and only this client, correctly pastes in the autocomplete text. 

**My question**
What is the expected behavior from a client when an set of edits from an autocomplete goes beyond the end of the initial document?

Thanks!

**Comment by kaushik-work** [comment]
@Gama11 , @mickaelistria that is very helpful feedback. 

@Gama11 does VS Code have a generic language client? I couldn't find one on the market place.

Thanks!

**Comment by Gama11** [comment]
Well, there's the [vscode-languageclient](https://github.com/Microsoft/vscode-languageserver-node) library, but you would have to build a minimal VSCode extension to use it with. You could probably base it on [one of the samples](https://github.com/Microsoft/vscode-extension-samples/tree/master/lsp-sample).

**Comment by kaushik-work** [comment]
Thanks all for your help!
