### ISSUE TITLE
CreateFile operation: How to denote directory vs file?

### ISSUE THREAD

**Issue by jastice** [Microsoft/language-server-protocol#665]
File resource changes are supposed to work on both files and folders:

> File resource changes allow servers to create, rename and delete files and folders via the client. Note that the names talk about files but the operations are supposed to work on files and folders. This is in line with other naming in the Language Server Protocol (see file watchers which can watch files and folders). 

But the `CreateFile` operation doesn't specify any way to denote whether a path is supposed to be a folder.

From https://github.com/Microsoft/language-server-protocol/issues/272#issuecomment-436287962 I gather that it should just be assumed to be a file at the moment?

This came up because we were discussing differentiating files and folders in the build server protocol at https://github.com/scalacenter/bsp/issues/76 and wanted to stick to prior art if reasonable. Currently, we use a trailing `/` on the URI to denote a directory, but that is not very robust, in terms of developer ergonomics.

**Comment by dbaeumer** [comment]
Agree. I will make this a dup of #272. See https://github.com/Microsoft/language-server-protocol/issues/272#issuecomment-436287962
