### ISSUE TITLE
To maintain consisntency, use requests instead of notifications for changes

### ISSUE THREAD

**Issue by matklad** [microsoft/language-server-protocol#666]
We currently use notifications to inform server about document changes. This is unfortunate, because the client has to way to figure out which notifications were actually acknowledged by the server. This leads to a situation where client and the server might disagree about the state of the world without realizing that disagreement exists.

See https://github.com/Microsoft/language-server-protocol/issues/663#issuecomment-456148146 for a compelling argument why this is problematic (kudos to @rasika for formulating the example)

See https://github.com/Microsoft/language-server-protocol/issues/584 for a general discussion of synchronization issues. 

This is obviously a breaking change, so we need to do this in the next major version of the protocol.

**Comment by dbaeumer** [comment]
See my comment: https://github.com/Microsoft/language-server-protocol/issues/663#issuecomment-456739774

**Comment by matklad** [comment]
I think we should mark it as "backlog" and reconsider when/if we will change the shape of notifications. For example #9 (using the same semantics of `TextEdit[]` as the rest of the protocol and removing redundant rangeLength) looks like something we might want to fix some day as well.

**Comment by dbaeumer** [comment]
I will close the issue since I don't see us changing this. For now things I stayed away from using notifications unless there is a compelling reason for it (no need for the client to wait for a result).
