### ISSUE TITLE
textDocument/declaration missing a ServerCapabilities indicator

### ISSUE THREAD

**Issue by sam-mccall** [Microsoft/language-server-protocol#673]
`definitionProvider`, `typeDefinitionProvider` etc exist - is the absence of `declarationProvider` an oversight?

Would be useful e.g. here: https://github.com/Valloric/ycmd/blob/5996d7daf2fda93ba2a0f6cfa86cf7c99e20170a/ycmd/completers/language_server/language_server_completer.py#L59

**Comment by ioeric** [comment]
ping?

This is blocking go-to-declaration support in some clients (e.g. YCM).

**Comment by rcjsuen** [comment]
Since it exists in the [Microsoft/vscode-languageserver-node repository](https://github.com/Microsoft/vscode-languageserver-node/blob/dbfd37e35953ad0ee14c4eeced8cfbc41697b47e/protocol/src/protocol.declaration.ts#L38-L43), it looks like an oversight to me.

**Comment by rcjsuen** [comment]
I've opened #701 to hopefully address this.

**Comment by dbaeumer** [comment]
@rcjsuen thanks. Merged the PR.
