### ISSUE TITLE
onDidChangeTextDocument contentChanges range sync

### ISSUE THREAD

**Issue by DifficultNick** [microsoft/language-server-protocol#675]
As a result of [this issue](https://github.com/Microsoft/vscode-languageserver-node/issues/456): 
- `onDidChangeTextDocument` doesn't receive ranges from client `contentChanges` when `TextDocumentSyncKind` is `Full`. Why?
- Is there no built in method to update `textDocument` with `contentChanges` when `TextDocumentSyncKind` is `Incremental`? Do I really need to synchronize `textDocument` on server using `contentChanges` by myself?

**Comment by LaurentTreguier** [comment]
Is there a need for a range with full synchronization? The text sent for full sync replaces all of the previous text.

**Comment by rcjsuen** [comment]
@LaurentTreguier I agree and I brought that up in https://github.com/Microsoft/vscode-languageserver-node/issues/456#issuecomment-458702411.

I think ultimately @DifficultNick is looking for the cursor position to be included in a `textDocument/didChange`. Of course, we need to keep in mind that documents can change without the cursor having moved and of course there is the case of multiple cursors to consider.

@DifficultNick Regarding your second point, that would have to be an enhancement request for [Microsoft/vscode-languageserver-node](https://github.com/Microsoft/vscode-languageserver-node) and is not a generic comment about the protocol itself.

**Comment by DifficultNick** [comment]
@LaurentTreguier yes, as @rcjsuen said, I was looking for cursor position (like I can get it in client's `workspace.onDidChangeTextDocument`) where the change was made in (to understand better what's going on on client). Of course, if it makes sense.

@rcjsuen, yes my second point is not about protocol, sorry I've mixed up repositories. But it seems to me that getting range/position from `textDocument/didChange` is a better way (maybe I'm wrong), and this feature (updating document with changes) will be redundant.

**Comment by dbaeumer** [comment]
@DifficultNick There is now https://github.com/Microsoft/vscode-languageserver-node/pull/478/files/7fa66038e7b639a3abe242f3014643089c67c186..92a5e9cb7f67ad2778ab9803271f1e21477c6eb2 which will bring incremental sync to the node implementation of the LSP server.

Due to the reasons pointed out by @rcjsuen I am not a fan of adding cursor support especially since edits can occur for many different reasons. 

Can you provide me with an example where the current incremental sync is not enough for a server?

**Comment by DifficultNick** [comment]
@dbaeumer, that's great! This implementation is quite enough for working with incremental sync. As concerning cursor support I understand your point. In my case I ended up sending manual notifications from client with all data I need. Now I'll think about rewriting something in my extension to set up incremental sync.
So I think this can be closed, thank you.

**Comment by dbaeumer** [comment]
@DifficultNick great. Closing then.
