### ISSUE TITLE
In the new pull model how does the server know when to send workspace/configuration?

### ISSUE THREAD

**Issue by kjeremy** [Microsoft/language-server-protocol#676]
Reading some issues here it seems as if use of `workspace/didChangeConfiguration` is being discouraged in favor of `workspace/configuration`. If so how does the server know when to send `workspace/configuration`?

**Comment by dbaeumer** [comment]
In the pull model the client will still send `workspace/didChangeConfiguration` however without any data payload. The client has then to pull configurations. So `workspace/didChangeConfiguration` is more a notification then a push. 

I will close the issue. Please ping back if still unclear.
