### ISSUE TITLE
Add "Implementation Language" column in servers.md

### ISSUE THREAD

**Issue by ahelwer** [Microsoft/language-server-protocol#683]
One thing that interests me as someone considering writing my own LSP server is what languages other people are using to implement their servers. It would thus be nice to have an "Implementation Language" column in the [servers.md](https://github.com/Microsoft/language-server-protocol/blob/gh-pages/_implementors/servers.md) file. If people support this idea here, I will do the legwork and open a PR against that file.

**Comment by dbaeumer** [comment]
Nice idea.

**Comment by dbaeumer** [comment]
Thanks for closing
