### ISSUE TITLE
Feature request: Show generated code

### ISSUE THREAD

**Issue by linuxtim** [Microsoft/language-server-protocol#689]
For reasons such as performance optimisation and debugging, it's reasonably common to inspect the output of the various compilation stages which software goes through  e.g.

- Results of macro expansion
- Compiler intermediate code representation
- Bytecode
- Assembly language

Some examples of existing IDE-specific integrations and extensions which allow this are https://github.com/mre/cargo-inspect-vscode and https://github.com/JetBrains/intellij-community/tree/master/plugins/ByteCodeViewer

I'm not particularly familiar with LSP, but thought LSP would be the best mechanism to support this.

**Comment by rcjsuen** [comment]
Could fit in the LSP or the BSP possibly (#512).

**Comment by dbaeumer** [comment]
IMO this is a dup of `https://github.com/Microsoft/language-server-protocol/issues/336` which would allow providing content for a URI schema from the server. The file containing the `Results of macro expansion` would have its own schema so that the content comes from the server.

OK to mark as dup?

**Comment by tim-seoss** [comment]
Hi Dirk,

I don't think I can offer a sufficiently informed opinion about whether this should be judged a dup of #336 or not.  Do others have opinions on this?  Alternatively, if you judge this to be sufficiently clear-cut, please go-ahead.

**Comment by dbaeumer** [comment]
I will mark it as a dup then since providing the feature requested there will allow implementing what you want.

**Comment by dbaeumer** [comment]
Dups #336
