### ISSUE TITLE
ShowMessage Request is a Notification

### ISSUE THREAD

**Issue by hediet** [Microsoft/language-server-protocol#69]
There is [ShowMessage Request](https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#showmessage-notification) and [ShowMessage Notification](https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#showmessage-request).
Is completely not clear to me why there are two of them (the notification could also include "actions") and why the first one is called "request" even though it is a notification as well.

**Comment by kaloyan-raev** [comment]
The notification asks the client to display a message. No actions are included.

The request is like the notification, but with possible actions included. VS Code displays the actions like buttons next to the text message. When the user clicks on a button, a message is sent back to the server, which usually is resolved to calling a function.

**Comment by dbaeumer** [comment]
@kaloyan-raev thanks for answering it. The explanation is correct. One little addition: we left the notification in to not break clients. The request got added later.

**Comment by hediet** [comment]
Ok, but still: Why is the [ShowMessage Request](https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#showmessage-request) a Notification? The spec reads:

> #### ShowMessage Request
> 
> > **New:** The show message request is sent from a server to a client to ask the client to display a particular message in the user interface. In addition to the show message notification the request allows to pass actions and to wait for an answer from the client.
> 
> _Notification_:
> * method: 'window/showMessageRequest'
> * params: `ShowMessageRequestParams` defined as follows:
> ```typescript
> interface ShowMessageRequestParams {
> 	/**
> 	 * The message type. See {@link MessageType}
> 	 */
> 	type: number;
> 
> 	/**
> 	 * The actual message
> 	 */
> 	message: string;
> 
> 	/**
> 	 * The message action items to present.
> 	 */
> 	actions?: MessageActionItem[];
> }
> ```
> Where the `MessageActionItem` is defined as follows:
> ```typescript
> interface MessageActionItem {
> 	/**
> 	 * A short title like 'Retry', 'Open Log' etc.
> 	 */
> 	title: string;
> }
> ```
> 

 How do I get notified if the user selects an action? (Notifications don't return anything and MessageActionItem does not specify a command to be executed on selection)

**Comment by dbaeumer** [comment]
@hediet agree the documentation is misleading. I updated the doc.
