### ISSUE TITLE
Negative position clarification

### ISSUE THREAD

**Issue by Nacoma** [Microsoft/language-server-protocol#690]
Many languages consider, for example, a length of “-1” to mean EOL. It appears that some language server implementations are using this negative position. Is this a valid value? If it is valid, how should it be handled?

Edit:
More specifically, how should a negative `Position.character` be handled?

**Comment by dbaeumer** [comment]
@Nacoma if we add something like this it needs to be a capability clients and servers opt into. Considering that I think this will cause a lot of swirl and clients and server will still need to handle the case where the counterpart doesn't support this. One other downside is that it will force the client to read the file to correct the positions which causes unnecessary work. Usually a server that generates results have the file loaded in memory and parse anyways.

Can you provide me with an example for a language that does this?

**Comment by Nacoma** [comment]
I don't think that this needs to be supported. However, the specification does not make it clear that it is not supported. Your comment provides the clarification I was hoping to find.

The author of the offending language server has indicated that it should *not* have been sending a negative value, so that particular problem is resolved.

**Comment by dbaeumer** [comment]
OK. I will clarify thatthis is not suppported in the spec.
