### ISSUE TITLE
Allow WorkspaceFolder to carry some optional metadata

### ISSUE THREAD

**Issue by HighCommander4** [Microsoft/language-server-protocol#703]
Currently, the `WorkspaceFolder` structure used by the `workspace/workspaceFolders` message just contains a name and a URI.

Some language servers may need additional per-root configuration. For example, the C++ language server may need, for each root, a _compilation database_ file that tells it what the compilation commands (which contain important information it needs to be able to parse the code correctly) for files in that root are. In some setups, the compilation database file is not stored in the source folder, but in the build folder (as its contents vary by build configuration). So, it would be useful to be able to send the server the location of the build folder as an additional field in `WorkspaceFolder`.

I wonder if there might be some language-agnostic way of allowing for this, such as by adding a generic "metadata" property to `WorkspaceFolder`.

Any thoughts?

cc @marcdumais-work

**Comment by Aerijo** [comment]
How would the client know where the build server is? By implementing language specific behaviour in the client, going against the purpose of an editor agnostic protocol?

It sounds like what you really want is a file tree navigation protocol, so the server can request directories and their contents. This would allow the server to locate the build folder itself, and lesson the burden on each individual client for that language.

**Comment by HighCommander4** [comment]
> How would the client know where the build server is? By implementing language specific behaviour in the client, going against the purpose of an editor agnostic protocol?

The notion of build configurations, e.g. release vs. debug, is fairly language-agnostic. A client could have UI to let the user create and manage them, and thereby the client would know about them.

> It sounds like what you really want is a file tree navigation protocol, so the server can request directories and their contents. This would allow the server to locate the build folder itself, and lessen the burden on each individual client for that language.

I'm not really following this part. What would such a protocol look like, and how would it allow the server to locate the build folder?

**Comment by Aerijo** [comment]
> The notion of build configurations, e.g. release vs. debug, is fairly language-agnostic.

My experience is with LaTeX mostly, so forgive me for disagreeing. Plus, even for languages that have the concept, they would have their own ways of configuring it, no? 

If so, then how does the client work out this information: would it have specific rules for each language?

You suggest
> A client could have UI to let the user create and manage them, and thereby the client would know about them.

But then you're suggesting locking all users into that specific client if they want to be consistent with everyone else. Or are you proposing a universal build configuration format for the client to store this information in?

> I'm not really following this part. What would such a protocol look like, and how would it allow the server to locate the build folder?

The point is that the whole concept of "release" and "debug" builds is very much language specific.

Each language may have it's own conventions on where this build information is stored, so giving the server the ability to locate a build configuration file itself will remove any burden on the protocol (or the client) for satisfying all language specific requirements. For example, a TypeScript server may need to find the `package.json`, `tsconfig.json` & other files. I imagine many servers are already doing this in some way, by using the filesystem API of the language they are implemented in.

Additionally, this protocol would be generally useful for servers beyond build configurations, making it far more language agnostic IMO.

**Comment by HighCommander4** [comment]
> > The notion of build configurations, e.g. release vs. debug, is fairly language-agnostic.
> 
> My experience is with LaTeX mostly, so forgive me for disagreeing. Plus, even for languages that have the concept, they would have their own ways of configuring it, no?
> 
> If so, then how does the client work out this information: would it have specific rules for each language?

I just meant that multiple languages have a notion of different build configurations, and so having a mechanism in the protocol for the client to let the server know about information specific to a configuration may be desirable.

Yes, in practice, clients will probably have language-specific logic for managing configurations.

> > A client could have UI to let the user create and manage them, and thereby the client would know about them.
> 
> But then you're suggesting locking all users into that specific client if they want to be consistent with everyone else. Or are you proposing a universal build configuration format for the client to store this information in?

If by "universal" you mean "across languages", I'm not proposing that.

If you mean "across clients for a given language", I feel like that's a question for each language's community to work out.

The context in which this came up for me is the [Theia](https://github.com/theia-ide/theia/) IDE's support for C++. @vince-fugnitto, perhaps you could weigh in on this point: in Theia's support for different C++ build configurations, would metadata about the different configurations be stored in a way that other editors could access as well? Or would users be "locked into" using Theia for a given project?

> > I'm not really following this part. What would such a protocol look like, and how would it allow the server to locate the build folder?
> 
> The point is that the whole concept of "release" and "debug" builds is very much language specific.
> 
> Each language may have it's own conventions on where this build information is stored, so giving the server the ability to locate a build configuration file itself will remove any burden on the protocol (or the client) for satisfying all language specific requirements. For example, a TypeScript server may need to find the `package.json`, `tsconfig.json` & other files. I imagine many servers are already doing this in some way, by using the filesystem API of the language they are implemented in.
> 
> Additionally, this protocol would be generally useful for servers beyond build configurations, making it far more language agnostic IMO.

I'm still unclear on what you're suggesting:

  * That the server discovers the relevant configuration file using a mechanism outside of LSP? (If so, could you give an example of what such a mechanism might be?)
  * That the server discovers the relevant configuration file using an LSP message, but a different one than `workspace/workspaceFolders`?

**Comment by Aerijo** [comment]
I must be misunderstanding what you mean by build configuration. My understanding is a file like `CMakeLists.txt` for C++, or `tsconfig.json` for TypeScript. My proposed alternative would allow the server to locate these files by itself, using whatever language specific rules it cares to.

For an example of why this might be needed, what if a language allows the user to make a fallback configuration file stored somewhere an environment variable points to. How is the client to locate this, without language specific rules?

And (now that I'm looking at the spec) does this proposal add something different from the existing [configuration request](https://microsoft.github.io/language-server-protocol/specification#workspace_configuration)? It looks like a more generalised version of what you are suggesting.

**Comment by dbaeumer** [comment]
My suggestion for this would be to use the workspace.getConfiguration() request which is sent from the server to the client. A workspace folder is a valid scope. See (https://github.com/Microsoft/vscode-languageserver-node/blob/master/protocol/src/protocol.configuration.ts#L45). This will allow you to request the build config from the client. Please be aware that each server needs to document the configuration it requests from clients so that they can provide the necessary information.

Would that work for you?

**Comment by HighCommander4** [comment]
Thanks, the `workspace/configuration` request seems like it may address this use case.

I will investigate it in a bit more detail and report back here.

**Comment by HighCommander4** [comment]
I looked into this a bit, and I see that at least in the VS Code client (which I understand is the reference client implementation), `workspace/configuration` is handled in a way such that language-specific plugins can hook the request to provide language-specific aspects of the configuration.

So yes, I don't see any reason why `workspace/configuration` isn't sufficient for this use case. Thanks for the suggestion.

I will go ahead and close this issue.
