### ISSUE TITLE
Support Formatting Of Source After Save, But Before Diagnostics

### ISSUE THREAD

**Issue by joefitzgerald** [Microsoft/language-server-protocol#71]
When working in [`go`](http://golang.org) it is idiomatic to run [`gofmt`](https://golang.org/cmd/gofmt) or [`goimports`](https://godoc.org/golang.org/x/tools/cmd/goimports) on save. This can mutate a file in ways that allow it to compile (e.g. `goimports` will add a missing import). 

It is desirable to allow this activity to occur synchronously _prior_ to running a series of linters / diagnostics asynchronously (or rather, it can occur asynchronously but must be completed prior to the running of any linters / diagnostics).

If `goimports` is not run before linters - but rather run in parallel - this may cause spurious errors that are not actually germane to the current state of the file (the extent to which it does cause these errors is non-deterministic and dependent on timing).

**Comment by joefitzgerald** [comment]
Upon further reading of the protocol, is it fair to state:

* The server receives save notifications
* It's up to the server to decide when it wants to supply diagnostics to the client (on save or on some other event)
* Therefore, this is an implementation detail, rather than something that needs to be specifically addressed in the protocol?

It it fair / expected for the server to mutate the file as a result of a save event?

**Comment by svenefftinge** [comment]
No, the client is the one that changes files. The server never does that.
Such clean up actions on save are common in the Java world too, but I don't think it needs to be encoded in the LSP, a client could simply call a couple of protocol actions on save. So maybe you want to open a ticket at vscode or whatever LSP client you use is.

**Comment by joefitzgerald** [comment]
Is there documentation for the interaction model between the client and server or is that our of scope for the protocol (i.e. it is up to the client to determine how / when it interacts with the server)?

**Comment by gorkem** [comment]
Client decides when to activate, query the server. On VS Code this is determined by the activation of the extension.

**Comment by joefitzgerald** [comment]
Is the [interaction model diagram](https://github.com/Microsoft/language-server-protocol/blob/f38dd74ee1ea369bf149543a549db1da2b0885b8/images/interaction-diagram.png) intended to be complete? Is the interaction model in the purview of the protocol specification? If the answer to either is true, my request is:

* The interaction model be updated to support a flow where - on save - both a formatting and a diagnostics request are made to the server; the server does not have to support formatting, but if it does, it could choose to format the file
* The server specification includes some denotation that a formatting provider can be run on save, or _should be run on save_

**Comment by gorkem** [comment]
@joefitzgerald Diagnostics is not a request, PublishDiagnostics is notification that originates from server. It is up to the server to decide when to send them.

**Comment by joefitzgerald** [comment]
So this affirms my earlier comment regarding diagnostics: https://github.com/Microsoft/language-server-protocol/issues/71#issuecomment-248376737

That leaves the request to permit mutation of the file (i.e. the results of a format) as a result of a save operation; or alternatively, the submission of a format request on save (or is this a client implementation detail?). This would potentially require metadata to indicate that a language server supports format on save?

**Comment by dbaeumer** [comment]
I am currently working on specifying onWillSaveTextDocument notification send from the client to the server. The model will allow returning text edits which will be applied before the document is actually saved. 

The problem is that these requests must be very performant to help the tool to save as fast as possible. Therefore I decided to bring more dynamic registrations options into the protocol. Not only on serv er startup. Some of this is already present in https://github.com/Microsoft/vscode-languageserver-node/ but nor ready to ship.

**Comment by dbaeumer** [comment]
This is available via the will save wait until request.
