### ISSUE TITLE
Make it clearer whether servers must support textDocument/didSave

### ISSUE THREAD

**Issue by DanTup** [Microsoft/language-server-protocol#713]
My understanding is that if a server does not supply the `save` field in `ServerCapabilities. textDocumentSync` then the client should not send `textDocument/didSave` notifications (which seems to match what's at https://github.com/Microsoft/language-server-protocol/issues/288#issue-253180885).

However, I've twice seen clients sending these notifications unexpectedly (Vim: https://github.com/natebosch/vim-lsc/issues/164 and Sublime: https://github.com/dart-lang/sdk/issues/36464) so I don't think it's clear enough in the spec.

If my understanding is correct, could this comment be updated:

```ts
	/**
	 * Save notifications are sent to the server.
	 */
	save?: SaveOptions;
```

To something like:

```ts
	/**
	 * If present, save notifications should be sent to the server. If omitted, save
          * notifications should not be sent.
	 */
	save?: SaveOptions;
```

If the opposite is true, then I think that should be called out explicitly too. I could easily add an empty handler to our server to avoid returning a message, but I think making the spec more explicit and updating implementations to follow it more accurately is ultimately the best route :)

**Comment by dbaeumer** [comment]
Agree.
