### ISSUE TITLE
Handling formatting

### ISSUE THREAD

**Issue by zzat** [Microsoft/language-server-protocol#717]
Whats the expected/better way to handle `textDocument/formatting` requests. The params of the request from the client only has the document uri. I can't directly read the document using the uri at the server's end as when the request would have been made, there might have been some unsaved text in the file.
Should I first save and then send the format request or should I always listen to `textDocument/didChange` request and save the file's content in some temporary buffer at server side and use this to format the text or is there something else that I missed which would make it easier to do this?

**Comment by rcjsuen** [comment]
@zzat What you described with regards to listening to `textDocument/didChange` events is correct.

**Comment by dbaeumer** [comment]
@rcjsuen explanation is correct. You also might want to read this https://microsoft.github.io/language-server-protocol/specification#textDocument_didOpen

It is still legal to receive a format request for a document that is not opened. In this case the truth is on the file system and the server can read it from disk.

**Comment by dbaeumer** [comment]
I will close the issue. Please ping if things are still unclear.
