### ISSUE TITLE
Did LSP support goto/jump stack like ctags?

### ISSUE THREAD

**Issue by svenFeng** [Microsoft/language-server-protocol#719]
when I jumped to declaration/definition/implementation, then I want to go back previous point, I has not any idea to do it like ctags, so I want to know whether LSP support it or not, or why don't support it? I think jump stack is very useful when reading code. 

thanks.

**Comment by rcjsuen** [comment]
@svenFeng I think the editor (client) usually handles such a "history of operations".

**Comment by dbaeumer** [comment]
@rcjsuen is right. This is something the editor needs to handle and is not part of the spec. I will close the issue. Please ping if you think something should happen in the spec.
