### ISSUE TITLE
A debug/playground application

### ISSUE THREAD

**Issue by KOLANICH** [microsoft/language-server-protocol#723]
Let we have a language server and a source file. And we want to see the requests to and the responses from the language server. And see them in a good-visualized way.

So we need an app. A user loads there a source file and selects a server. Then the window appears. In the left there is a rich editing component with syntax highlighting. For example, Scintilla. The source can be highlighted by the component, but in desaturated colors. In the right there is a constructor of queries to the server. A user can select a query from the drop down menu. When he selects the query, the form according to the selection appears and the user can add/edit queries arguments. He can also add ranges by selecting text by mouse/keyboard. 

Then a user can see the resulting json (again in yet another rich editing component) and edit it if needed, the edits are propagated back to the form, if possible. 

Then a user can push the "submit" button, and the query is sent to the server.

Then the response is got, parsed, prettified and put into a separate editing component for responses. Also the application selects and takes the action visualizing the response best (for example, for `DocumentSymbol` it can highlight the symbols depending on type in the left editing component). Visualization is per-response, on the next respose the visualization of the previous one is cleaned. Text content is not mutated permanently, for refactoring actions old text is striked and new one is added and highlighted in the way making it clear that it is change, for example in elevated pseudo-3d not very deep boxes.

There should be a yet another window for history - just a list of requests. When a user clicks a request, it and its responce are loaded into the main interface. There should be a possibility to load a pcap file with the capture of LSP session (let's assumme there are no non-lsp frames in it). And there should be a possiblity to insert the app as a proxy to other LSP to visualize interactions in real time when debugging a server/client.

**Comment by dbaeumer** [comment]
@KOLANICH this partly exists:

- https://microsoft.github.io/language-server-protocol/inspector/ is a UI to visualize a trace.
- the VS Code LSP client library have support to produce such a trace. But other editors are open to participate in it as well.
- there is doc here https://github.com/Microsoft/language-server-protocol-inspector that specifies the format of the log.


I see that you are asking for more. Such a tool is a very good opportunity for a thrid party contribution. Would you be interested in providing it?

**Comment by KOLANICH** [comment]
>Would you be interested in providing it?

I'm sorry, I have no time for developing this tool.

**Comment by kubukoz** [comment]
FYI Langoustine provides a [web UI tracer](https://neandertech.github.io/langoustine/tracer.html) for inspecting LSP requests/responses.

**Comment by KOLANICH** [comment]
Thanks, @kubukoz. 👍
