### ISSUE TITLE
run source.organizeImports on demand

### ISSUE THREAD

**Issue by stamblerre** [Microsoft/language-server-protocol#726]
I'm trying to understand how to correctly implement 
`"editor.codeActionsOnSave": { "source.organizeImports": true }` for `gopls` (https://github.com/golang/go/wiki/gopls). 

To my understanding, codeActions should be associated with diagnostics, so the way it works in `gopls` now is that:

1. User adds some code that uses an un-imported package, e.g. `os.PathSeparator`.
2. A diagnostic is generated for the unknown package ("undeclared name: os"), and sent to the client via a `publishDiagnostics` message.
3. When the user saves file, the client sends a codeAction to the server, containing the diagnostic.
4. The server responds with the updated imports to handle this diagnostic.

The issue with this approach is that it requires the server to wait on the client receiving the diagnostic, and since this is asynchronous, it creates a slight delay, or it may not work as expected if the user saves the file very fast. Is there a more correct way to implement this? Should we just run the organizeImports behavior without any associated diagnostics?

/cc @ianthehat @myitcv

**Comment by rcjsuen** [comment]
It is an optimization if your `textDocument/codeAction` request includes stuff inside `CodeActionContext` but this is not a hard and fast rule. You are welcome to leave nothing in there and see if the server is able to deduce what you want. In this case, it seems obvious given your strict restriction of `CodeActionKind.SourceOrganizeImports`.

**Comment by stamblerre** [comment]
So, if there is nothing at all inside of the `CodeActionContext`, you would expect that the server tries to run all possible code actions?

**Comment by rcjsuen** [comment]
What do you mean by "run all possible code actions"? Did you mean "compute all possible code actions"? `textDocument/codeAction` does not run anything, it is only doing the computations so nothing will be modified unless the client actually ends up executing the `WorkspaceEdit`.

If you meant compute, then yes, I'd expect it to compute all code actions relevant to the `Range` that the client has provided in its `CodeActionParams`. If my text cursor is selecting stuff inside a comment then there's probably nothing to suggest (except perhaps stuff like `CodeActionKind.Source` or `CodeActionKind.SourceOrganizeImports`?).

**Comment by stamblerre** [comment]
Ok, thank you, makes sense.

**Comment by dbaeumer** [comment]
@stamblerre I would like to add something. The protocol defines a `willSaveWaitUntil` request which servers can implement (see https://microsoft.github.io/language-server-protocol/specification#textDocument_willSaveWaitUntil). This will allow servers to fix and format code on save.
