### ISSUE TITLE
Clarify behavior of completion

### ISSUE THREAD

**Issue by svenefftinge** [Microsoft/language-server-protocol#73]
Background: In the Xtext language server we currently have the strategy to cancel any read requests when a change comes in. The idea is that in general it doesn't make sense to provide the user with information on an outdated state. 

With vscode I observed that with a identifier-prefix a completion request is only sent once and on subsequent typing the resulting list is just filtered down, based on the new characters. This seems to be the case even if I set `CompletionList#incomplete` to `true`.

In Xtext unfortunately the first list will be empty/incomplete if I type very fast, due to cancelation.

Could you provide some insight in whether my observations are correct or did I miss something. Also I'D like to know if this is the expected semantic for the completion request in the protocol. I think at least if the `CompletionList#incomplete` property is `true` vscode should request completion again.

**Comment by dbaeumer** [comment]
@svenefftinge there was a bug on the VS Code side which didn't trigger the recomputation in all cases. This should have been fixed (if I remember correctly already in 1.7). If this is not the case please open an issue directly in vscode repository.
