### ISSUE TITLE
[Request] Allow Snippets in WorkspaceEdit's

### ISSUE THREAD

**Issue by NikolasKomonen** [Microsoft/language-server-protocol#731]
Somewhat related to this issue: https://github.com/Microsoft/language-server-protocol/issues/715

It's been recommended to use workspace/applyEdit to enable automatic completion/insertion of text.

The issue is workspace edits do not allow Snippets, which is something that Completion Items use (InsertTextFormat) to indicate plain text or snippets.

**Comment by rcjsuen** [comment]
See #592 and #724.

**Comment by dbaeumer** [comment]
I mark this as a dupe of #724 since it already has a lengthly discussion about the issues around this and how to address them. They could be mimicked for workspace edits.
