### ISSUE TITLE
Feature request: `textDocument/documentColor` support grammars

### ISSUE THREAD

**Issue by sumneko** [Microsoft/language-server-protocol#732]
Currently the response of `textDocument/documentColor` requires specifying specific colors. However, because users use different styles of themes, the performance of specified colors will be inconsistent.
I think it would be better to specify grammars, such as "keyword. control", the same as definition in `xxx.tmLanguage.json`.

**Comment by mickaelistria** [comment]
`documentColor` is show to annotate a piece of code with a color preview, based on the semantic of the language, for example it allows clients to show a blue marker for `blue` text in CSS. See for example CSS files in VSCode or Eclipse IDE with Wild Web Developer to see it in action.
It's not meant to do any form of syntax highlighting (although clients may want to render the preview as a text style, but it's up to clients and not specified). If some language server can show color preview and the semantic of what the preview should be for a color require to read a texstmate grammar, then it's internal to the LS implementation and doesn't need to leak in the protocol specification.

**Comment by sumneko** [comment]
@mickaelistria thank you for your anwser.
Maybe it should be a new method feature, due to sometimes the client does not know the correct grammar, for example in Lua:
* `goto` is not a keyword in `Lua 5.1`, but is a keyword in other version.
* `identifier` may be a local variable or a global variable.
* Different runtime version has different libraries.

**Comment by mickaelistria** [comment]
I think it's already the topic of https://github.com/Microsoft/language-server-protocol/issues/18

**Comment by sumneko** [comment]
Thanks!
