### ISSUE TITLE
dealing with source maps

### ISSUE THREAD

**Issue by bmeck** [microsoft/language-server-protocol#744]
I tried to search around but did not see any reference to how to handle linking to an inline source map from a language, certain languages have differing ways to have inline source maps such as `//`+`/**/` comments in JS, `/**/` comments in CSS, `<!-- -->` comments in HTML (in theory, no devtools seem to support this), etc. It would be nice to have a way to retrieve these in a language agnostic manner so that one could jump from generated code to original code.

**Comment by Gama11** [comment]
Not quite sure how this is related to the language server protocol.. Wouldn't this be related to the debug adapter protocol, if anything (since source maps are usually used for debugging)?

**Comment by bmeck** [comment]
Not sure what you mean by it is only for debugging since this applies to general editor actions from knowing a location of importance. If I get a trace from a log like:

`/source-map-test/main.js:3:11` that was compiled from `main.coffee` and open it in an editor I probably want to jump to the original code and not the compiled code.
