### ISSUE TITLE
Feature request : textDocument/inlinedAnnotation

### ISSUE THREAD

**Issue by angelozerr** [microsoft/language-server-protocol#745]
I create this issue according my skills with `Eclipse CodeMining` which does the same thing than CodeLens but gives too the capability to `draw content inside the line content` (like color information used by CSS and JSON LS)

Takes a sample with Eclipse CodeMining:

 * here a CodeMining for JUnit: it is drawn by a line header annotation with an icon and text

![image](https://user-images.githubusercontent.com/1932211/57533016-096f5000-733d-11e9-86b4-07ae9ce9bbef.png)

 * here a CodeMining for parameter names for Java method: it is drawn by  a line content annotation:

![image](https://user-images.githubusercontent.com/1932211/57533186-74b92200-733d-11e9-974a-8b100a082e44.png)

In other words I tell me if LSP could mix CodeLens and ColorInformation inside the same concept that it is called `Inlined Annotation` in Eclipse Platform.

Today LSP provides capabilities to support:

 * code lens which is drawn before the line text (line header annotation). 
 * color information which is drawn in the line text (line content annotation)

IMHO, I think we could improve

 * CodeLens to specify an icon (or emoji)
 * Having a more generic concept than ColorInformation to draw anything in the line content annotation.

We could have an` inlined annotation` composted by:

 * text
 * icon (image name, or rgb color)
 * type : `header` (annotation drawn in the line header) or `content` (annotation drawn in the line content)

Here Inlined annotation benefit:

 * have` just one concept to manage CodeLens and ColorInformation ` both
 * improve` CodeLens to draw an icon` before the text
 * gives `the capability to draw text/icon inside the line content `(support  for ColorInformation and other features like parameter names for Java method)

**Comment by mickaelistria** [comment]
Couldn't we just generalize codelens response message to add some "insertionType: header | inline" ?

**Comment by dbaeumer** [comment]
Dups https://github.com/microsoft/language-server-protocol/issues/956
