### ISSUE TITLE
lsp-sample for non ts language servers

### ISSUE THREAD

**Issue by VijayaKrishnaKasula** [microsoft/language-server-protocol#746]
lsp-sample is great.
Is there an example where the server is written not in typescript - say Python?
The server.ts starts with importing vscode-languageserver library. Is there a similar library for Python to leverage on?

**Comment by dbaeumer** [comment]
I don't maintain a Python example ;-). Regarding libraries you might want to have a look here: https://microsoft.github.io/language-server-protocol/implementors/sdks/

I am closing the issue since there is no direct action in the specification itself. If someone want to create a Python example I am happy to assist.

**Comment by VijayaKrishnaKasula** [comment]
Thank You @dbaeumer 
Good to know there are SDKs in Python.
I am however looking for a guide on how to hook the Python LS with VSCODE.
In specific I am looking for the Python example.
If nothing is available, I would be glad to work on that with your help.

But I am not sure where to start.

**Comment by dbaeumer** [comment]
Not sure I understand this correctly. Which Python LS do you want to combine with VS Code. Have you checked if there is a extension in the VS Code marketplace that does this already?

**Comment by VijayaKrishnaKasula** [comment]
Well, I did not find any extension that implements the language server in Python. But https://code.visualstudio.com/api/language-extensions/language-server-extension-guide says that the Language server can be implemented in any language.
I was wondering the same, is there an example of the same.

**Comment by rcjsuen** [comment]
They seem to have a small example over at [openlawlibrary/pygls](https://github.com/openlawlibrary/pygls)

**Comment by Razzeee** [comment]
Not sure if there is a binding library, but the list here shows multiple entries that say they implement the server in python https://github.com/microsoft/language-server-protocol/blob/9813e5ba67f55e44e2a9adb25cb941e60cdfdbd2/_implementors/servers.md
