### ISSUE TITLE
Specification is offline

### ISSUE THREAD

**Issue by rcjsuen** [microsoft/language-server-protocol#752]
@dbaeumer The [microsoft.github.io/language-server-protocol/specification](https://microsoft.github.io/language-server-protocol/specification/) page currently shows me a 404.

Can anyone else confirm this? I'm seeing this on my laptop and my phone.

**Comment by Gama11** [comment]
Same here.

**Comment by arjun27** [comment]
Works without the slash: https://microsoft.github.io/language-server-protocol/specification (the link by OP has the slash in the end)

**Comment by rcjsuen** [comment]
@arjun27 Indeed, you are right. It seems some of the other links at the top has a trailing slash so that might've been why I punched it in that way in my address bar. :thinking:

**Comment by dbaeumer** [comment]
@rcjsuen I am closing the issue. Please ping if you think action is needed on my end.
