### ISSUE TITLE
Are releases / tags used?

### ISSUE THREAD

**Issue by Razzeee** [microsoft/language-server-protocol#753]
I would like to get notified for new version of the spec in this repo.

But the last version did not get a release/tag, was that on purpose?

**Comment by dbaeumer** [comment]
I usually tag, but i forgot that release. Let me see if I can find the right commit to tag the release :-)

**Comment by dbaeumer** [comment]
Done. The commit was: 3bdf2a400245f00b41fceca08b475d6554fb1af7

**Comment by rcjsuen** [comment]
@dbaeumer I don't see the actual tag. Did you push the tag to GitHub?

**Comment by dbaeumer** [comment]
@rcjsuen pushed now :-)
