### ISSUE TITLE
LocationLink's targetUri should be stricter than a string

### ISSUE THREAD

**Issue by rcjsuen** [microsoft/language-server-protocol#758]
I was comparing `LocationLink` with `Location` and I realized now that `targetUri: string` should have been `targetUri: DocumentUri`.

Is it too late to change this or would this be considered a breaking change?

**Comment by dbaeumer** [comment]
I think we are fine to change this since it was the intention. A general string doesn't make sense here.

If you prepare a PR I merge it in.

**Comment by rcjsuen** [comment]
@dbaeumer I understand. I have created #760 to address this.

**Comment by rcjsuen** [comment]
Whoops, closed this by mistake...

**Comment by rcjsuen** [comment]
@dbaeumer I checked [microsoft/vscode-languageserver-node](https://github.com/microsoft/vscode-languageserver-node) and looks like it's defined as a `DocumentUri` [there](https://github.com/microsoft/vscode-languageserver-node/blob/625fbdbe492f7b4b95e6d29e0adf36c01b88d056/types/src/main.ts#L169-L173).

**Comment by dbaeumer** [comment]
Yes, I did that on Friday in the code. But we still need to update the spec.

**Comment by dbaeumer** [comment]
Merge the PR. Thanks.
