### ISSUE TITLE
Spec doesn't define the registration options type for textDocument/foldingRange

### ISSUE THREAD

**Issue by DanTup** [microsoft/language-server-protocol#759]
All other requests that have `dynamicRegistration` have a section about what the options type should be, however `textDocument/foldingRange` doesn't appear to. I'm guessing it's just `TextDocumentRegistrationOptions` but the spec should include it.

**Comment by rcjsuen** [comment]
@DanTup It seems to be mentioned to me but maybe I'm looking at the wrong place? It seems to mention [`FoldingRangeProviderOptions & TextDocumentRegistrationOptions & StaticRegistrationOptions`](https://github.com/microsoft/language-server-protocol/commit/2a2d6058d0640f826958f347ffa40f6224a3aceb#diff-32fe5a6c631807387f43b01824ccea9d).

**Comment by DanTup** [comment]
Sorry, I mean if you go here:

https://microsoft.github.io/language-server-protocol/specification

Then search for something like `textdocument/completion` and in the section describing that request/response, it also says which dynamic capability applies to that method:

<img width="817" alt="Screenshot 2019-05-24 at 07 42 02" src="https://user-images.githubusercontent.com/1078012/58307735-84357200-7df7-11e9-85c2-60ef96088565.png">

However there is no "Registration options" section listed in the [Folding Range request](https://microsoft.github.io/language-server-protocol/specification#textDocument_foldingRange) section.

**Comment by rcjsuen** [comment]
I see what you mean now. It does seem like it's probably just a regular ol' `TextDocumentRegistrationOptions` at the moment.
