### ISSUE TITLE
How can a server implement "extract method" (how can it trigger rename?)

### ISSUE THREAD

**Issue by DanTup** [microsoft/language-server-protocol#764]
https://github.com/microsoft/language-server-protocol/issues/662 suggests we can implement "extract method" using existing code actions, however I can't see any mechanism for how the user would be prompted for a name, or the server could tell the client to invoke rename after the edit.

For example, let's say I have this code:

```ts
thing() {
  a();
  b();
  c();
}
```

I highlight the calls to `b()` and `c()` and invoke **Extract Method**. I end up with this:

```ts
thing() {
  a();
  this.newMethod();
}

newMethod() {
  b();
  c();
}
```

We really want to to either have prompted the user for `newMethod`, or automatically invoked rename on `newMethod` (which is what TypeScript does today), or - provide edits including snippet syntax.

I can't find any way to currently do this. If the solution is to use a custom command, then I think this comes back to https://github.com/microsoft/language-server-protocol/issues/642, where we can't tell if the client has it implemented.

@dbaeumer is there something I've overlooked - can we already do this today?

**Comment by mickaelistria** [comment]
Could we imagine codeAction result having a `renameRangeAfterChange` which the client would be expected to use to trigger a rename?
Maybe this could even be a list of ranges to allow renaming parametersas well.

**Comment by DanTup** [comment]
That feels very specific, I think having something more general would be better (for ex. supporting snippet syntax in the returned edits?).

**Comment by mickaelistria** [comment]
Yes, snippet syntax on all edits would help a lot.
However, I think snippets only work well in the context of a single file, while some refactorings have a multi-file scope (eg Extract super/sub class). Unless snippets can be made multi-files, they seem too limited.
While my proposal seems indeed a bit specific, I'm wondering what refactorings would need some other user interaction than chaining a rename after being applied. Do you have an example?

**Comment by fbricon** [comment]
I don't think extracting a method would affect multiple files. This sounds like the sort of refactoring that's local in scope by nature, in which case, snippets would make sense (that was also the mechanism I was thinking of). But I might be wrong.

**Comment by mickaelistria** [comment]
Right, my previous comment doesn't apply to "extract method", and usage of snippets in CodeActions/TextEdit still seems the best and simplest approach for this specific refactoring.

**Comment by DanTup** [comment]
@dbaeumer do you have any thoughts on this? I'd like to be able to migrate to LSP but I have a few remaining features that seem stuck on this. I'm unsure whether to a) implement this using my own custom commands (which means each editor will need custom code, and have to work around https://github.com/microsoft/language-server-protocol/issues/642) or hold off in the hope that there might be a better solution available (or available soon).

**Comment by rockbruno** [comment]
I have the exact same issue as you (renaming an extracted method). Adding snippet support to edits would solve this and many other problems.

**Comment by dbaeumer** [comment]
For a lengthy discussion about supporting snippets in code actions see https://github.com/microsoft/language-server-protocol/issues/724. 

Even if we have this it would be something the client needs to opt in (e.g. it would be a capability).

IMO the best way to push this forward would be to allow snippets in code actions since it resolves in the nicest user experience.

**Comment by hokein** [comment]
any progress on this?

**Comment by dbaeumer** [comment]
There is work under way to add snippets to workspace edits.

**Comment by dbaeumer** [comment]
Snippers made it into code actions and workspace edits for 3.18
