### ISSUE TITLE
Note which InsertTextFormat is used if it's not set on a CompletionItem in the spec

### ISSUE THREAD

**Issue by DanTup** [microsoft/language-server-protocol#768]
The `insertTextFormat` property of `CompletionItem` is marked as optional, but it's not explicit how the value will be treated (I presume it's `PlainText`). It'd be good to note this, so that it can be excluded if it's the default for performance reasons (I've found reasonable gains for serialisation/transmission/deserialisation when I have thousands of completions by just removing anything that matches the default).

**Comment by dbaeumer** [comment]
Now contains `If ommitted defaults toInsertTextFormat.PlainText`.
