### ISSUE TITLE
Accessing from outside an editor

### ISSUE THREAD

**Issue by vladdu** [Microsoft/language-server-protocol#77]
I hope I can express myself clearly.

The protocol takes as arguments a document id and a location in it, and provides information related to that. But it is useful to be able to do the same thing without an editor context, by using as parameter a reference to the source element used as context. In other words, if we treat the server as exposing a database of source code symbols and their related information, I would like to be able to index and search it. Of course, this would not be a required feature.

For example, I search for references to an item, which I show in a dialog. There I see another item that is really what I was looking for, and want to search for its references. Instead of opening that in an editor and search from there, it is nicer to be able to do it from the dialog. 

Another example, searching for documentation. Hover info works well in editor, but if I have a separate documentation view, I can use it to search for whatever I need info about (either by hyperlinks or textual search), independently of what files I edit.

I suppose that the core question is: do you mean LSP to support this kind of scenarios? If not, how can we extend it safely?

**Comment by dbaeumer** [comment]
This is an interesting use case. Haven't thought about how this could be integrated. May be it would be easier to define a symbol database protocol using the same approach as we do with the language server.

**Comment by vladdu** [comment]
Exactly how to implement this, you know best. 

One way to get a unified API would be to use URIs as paramters, using fragments to point to specific locations (https://tools.ietf.org/html/rfc7111) or elements (those would be language-specific, in general; something like for example #path=<class>.<method>.<parameter>).

**Comment by dbaeumer** [comment]
To keep the number of issues in our inbox at a manageable level, we’re closing issues that have been on the backlog for a long time but haven’t gained traction: we look at the number of votes the issue has received and the number of duplicate issues filed. Thank you for your time and understanding.

If you disagree and feel that this issue is crucial: we’re happy to listen and to reconsider.
