### ISSUE TITLE
New tooltip property in DocumentLink introduced in VS Code

### ISSUE THREAD

**Issue by rcjsuen** [microsoft/language-server-protocol#774]
```TypeScript
interface DocumentLink {
	/**
	 * The tooltip text when you hover over this link.
	 *
	 * If a tooltip is provided, is will be displayed in a string that includes instructions on how to
	 * trigger the link, such as `cmd + click to {0}`. The specific instructions vary depending on OS,
	 * user settings, and localization.
	 */
	tooltip?: string;
}
```
Seems like there is a new [`tooltip` property](https://github.com/microsoft/vscode/blob/fb19107658e2eee747cd880e3cd85fd1a89f6c52/src/vs/vscode.proposed.d.ts#L1433-L1442) that got added into the `DocumentLink` interface of VS Code. Is this something that should be included in the LSP?

[Proposed extension APIs in VS Code 1.35](https://code.visualstudio.com/updates/v1_35#_proposed-extension-apis)

**Comment by dbaeumer** [comment]
IMO it would make sense to include it. From a spec point since there is a resolve method for document links we need to make it a capability to indicate to the server whether the property is preserved by the client.

**Comment by dbaeumer** [comment]
@rcjsuen would you be willing to provide a PR for the spec and the node implementation?

**Comment by rcjsuen** [comment]
I'll see if I can find some cycles to do it.

But if anyone else reading this wants to try their hand at contributing to the LSP, feel free to make a PR. :)

**Comment by dbaeumer** [comment]
Thanks!

**Comment by dbaeumer** [comment]
Added in `dbaeumer/3.15` and in `vscode-languageserver-node`.

**Comment by dbaeumer** [comment]
See also https://github.com/microsoft/vscode-languageserver-node/issues/523
