### ISSUE TITLE
DidFocusTextDocument Notification for Text Synchronization

### ISSUE THREAD

**Issue by nadeeshaan** [microsoft/language-server-protocol#775]
Currently the protocol supports didOpen text document and we faced a situation where we need to do a source compile and some other operations on file focus (when tab switch).
I would like to suggest having DidFocusTextDocument notification from client to the server. Or, is there any alternative way we can handle the same requirement?

**Comment by dbaeumer** [comment]
Dups https://github.com/microsoft/language-server-protocol/issues/718
