### ISSUE TITLE
In the "Implementations" page, change "SQL" by Microsoft to "Transact-SQL"

### ISSUE THREAD

**Issue by d0mf1g** [microsoft/language-server-protocol#777]
I am referring to this page:

https://microsoft.github.io/language-server-protocol/implementors/servers/

From my understanding, this particular SQL LSP is mainly for T-SQL, which is used in MS Servers. The implementations page should specify this.

**Comment by dbaeumer** [comment]
Changed it to `T-SQL`. OK?
