### ISSUE TITLE
Clarify meaning of range within Hover

### ISSUE THREAD

**Issue by Et999** [Microsoft/language-server-protocol#78]
It is not clear what it should be the range of.

**Comment by akosyakov** [comment]
It's a range at which hover should be used. I guess a client side should not send a new hover request till the user hovers over the range of the current range. If the range is undefined then the client should send a new request on a cursor position change.

**Comment by ljw1004** [comment]
Some clients highlight the symbol under the cursor when you hover -- so the user clearly understands "this hover tooltip applies to this precise symbol". This range gives them the opportunity to know which range to highlight.
