### ISSUE TITLE
Considering adding the indention information into the codeAction request

### ISSUE THREAD

**Issue by jdneo** [microsoft/language-server-protocol#780]
Hi team,

We have [an issue](https://github.com/microsoft/vscode/issues/52272) related to the indention when executing the `codeAction` in Java Language Server.

### Background
Since the current LSP implementation does not contain indention information in the `codeAction` request. So the Java Language Server could not generate the `workspaceEdit` in the right format. (It will get the indention information from the project preference but it's not always aligned with the file's setting)

### Possible Solution

1. Add the indention information into the `codeAction` request? Like:
```jsonc
interface CodeActionContext {

    ...

    insertSpace?: boolean;

    tabSize?: number;
}
```

2. Make the VS Code automatically fix the indention just like what's happening when we insert a code snippet.

**Comment by jdneo** [comment]
Hi @dbaeumer, 

Do you have any thoughts on this?

**Comment by dbaeumer** [comment]
Sorry for the long delay. My recommendation would be to fetch the formatting setting using workspace/getConfiguration request. Embeeding them into every code action request seems a little heavy given that they don't change often.
