### ISSUE TITLE
Client should identify itself in InitializeParams

### ISSUE THREAD

**Issue by bmewburn** [microsoft/language-server-protocol#782]
Is there an existing way to identify the client? I couldn't see one. The use case I'm thinking of is providing telemetry on which clients are used with the server.

**Comment by mickaelistria** [comment]
Isn't `InitializeParams.clientName` what you're looking for?

**Comment by bmewburn** [comment]
That would do. I don't see it in the spec?

**Comment by mickaelistria** [comment]
Strange, it's indeed not here... It's at least implemented in LSP4E, and -unless I'm mistaken- it used to be in the spec at some point...

**Comment by dbaeumer** [comment]
I am supportive to add this.

**Comment by mickaelistria** [comment]
Submitted PR #783 for this.

**Comment by dbaeumer** [comment]
@mickaelistria thanks !

**Comment by dbaeumer** [comment]
Merge into 3.15 branch
