### ISSUE TITLE
Using sortText and textEdit simultaneously does not work 

### ISSUE THREAD

**Issue by OliverSchmitt** [microsoft/language-server-protocol#785]
When implementing a language server plugin for VS Code I noticed that using the *sortText* and *textEdit* property of the CompletionItem simultaneously breaks the expected behavior when displaying the CompletiionItems in the client. Instead of using *sortText* for the sorting it is ignored and the CompletionItems which also specify a *textEdit* are appended to the back of the displayed list.

Two examples for the problem I am describing using the [pygls](https://pypi.org/project/pygls/) language server implementation [example](https://pygls.readthedocs.io/en/latest/pages/tutorial.html) and the [completion sample](https://github.com/microsoft/vscode-extension-samples/tree/master/completions-sample) of the vscode-extension-samples can be found in [this](https://github.com/openlawlibrary/pygls/issues/75) issue.

Therefore this is not a problem caused by the language server implementation. I also tried using the [theia](https://www.theia-ide.org/) online idea and got the same results. Apparently this is a problem affecting multiple clients.

My idea is that the clients ignore the *newText* property of the *textEdit* if it is provided in a CompletionItem. Because the *label* and *insertText* are also ignored if a *textEdit* is specified, this is conform to the LSP specification, the clients display these CompletionItems at the end of the suggestion. This is just a guess and the problem might be caused by something else. Either way this behavior is contrary to the expected behavior provided by the LSP specification.

**Comment by kenkangxgwe** [comment]
I can only reproduce half of your problem. I cannot make `textEdit` work together with `filterText`, but in my circumstance, it does work with `sortText`.

**Comment by OliverSchmitt** [comment]
Did you use the same setup as me or did you use other language server or clients?

**Comment by kenkangxgwe** [comment]
No, I am using another language server with vscode, but latter I figured out that if the completion is triggered by `triggerCharacters`, then the triggerCharacters should not be included in the `filterText`; or if the completion is triggered by `incompleteCompletion`, the prefix that is already input into the editor should be excluded too. Hope this will help.

**Comment by dbaeumer** [comment]
@OliverSchmitt reading through the other issue it looks like the problem also exists with the VS Code extension API. If this is the case have you filed an issue against VS Code. IMO we should allow to use sort text and text edit simultaneously.

**Comment by OliverSchmitt** [comment]
@kenkangxgwe Which Language Server did you use to reproduce the problem. Is it possible that you share the code? Maybe I can figure out how to get it to work since `sortText` works with your example.

Just to be clear, I just use the `filterText` property to persist the completion suggestions even if something else than a prefix is entered. I don't think it is necessary for the simple example, it is required for my actual project though.
