### ISSUE TITLE
LSP/Vscode : how to connect vscode client to Ocaml server

### ISSUE THREAD

**Issue by houdaM97** [microsoft/language-server-protocol#790]
I want to create a client side which is a vscode extension in order to communicate with the language server implemented using Ocaml by LSP. After looking at the LSP sample in vscode documentation i find those lines of code that i couldn't adapt to my situation : 

`// The server is implemented in node
  let serverModule = context.asAbsolutePath(path.join('server', 'out', 'server.js'));
  // The debug options for the server
  // --inspect=6009: runs the server in Node's Inspector mode so VS Code can attach to the server for debugging
  let debugOptions = { execArgv: ['--nolazy', '--inspect=6009'] };

  // If the extension is launched in debug mode then the debug server options are used
  // Otherwise the run options are used
  let serverOptions: ServerOptions = {
    run: { module: serverModule, transport: TransportKind.ipc },
    debug: {
      module: serverModule,
      transport: TransportKind.ipc,
      options: debugOptions
    }
  };`

Because i don't have server.ts file in my project where can i get the server options which i need in order to create the language client?

**Comment by rcjsuen** [comment]
Hi, @houdaM97. Thank you for your interest in the language server protocol.

1. Your question appears to be geared towards Visual Studio Code. I suggest you open your question in the [Microsoft/vscode-languageserver-node repository](https://github.com/microsoft/vscode-languageserver-node/). This repository is for discussing general matters related to the protocol and not about Visual Studio Code specifically.
1. You should also state which language server you are using. It's not quite clear from your title and description whether you are trying to integrate a language server with OCaml support or a language server written in OCaml.

**Comment by houdaM97** [comment]
hi @rcjsuen,
thank you for your reply, 
i open my question in the repository suggested , and yes my language server is written in OCaml.
