### ISSUE TITLE
Which variant of Markdown?

### ISSUE THREAD

**Issue by PerMildner** [microsoft/language-server-protocol#791]
The spec only says [markdown](https://microsoft.github.io/language-server-protocol/specification#markupcontent) with a note in a comment about GitHub-like code blocks, but "Markdown" does not seem to be a well defined term.

It would be good if it was clarified what exactly markdown means, e.g. with a link to an external definition or with a listing of some minimal subset (which should include some robust way to quote arbitrary text from Markdown-interpretation).

This is especially so since documentation strings in LSP may need to include things from a programming language that contain "funny" chars that could have special meaning in some variant of Markdown.

**Comment by dbaeumer** [comment]
We discussed this already and the best we can do is to point to a markdown parser / converter. Specing this independently might be very cumbersome.

**Comment by rwols** [comment]
But we can at least state if it's "daring fireball" markdown or "commonmark" markdown?

**Comment by dbaeumer** [comment]
Since this is about a programming tool I think the best would be to go with GitHub flavored markdown https://github.github.com/gfm/

**Comment by dbaeumer** [comment]
I also added a client capability to allow clients to announce the parser they are using if a server implementer wants to target exactly one client.

**Comment by KamasamaK** [comment]
Should there be a standard list of engine names?

**Comment by dbaeumer** [comment]
I actually don't want to force any clients into a list of standard parsers. What we can do is to have a list of know parsers used by clients in the spec.

**Comment by Aerijo** [comment]
I think the idea is more to not have slightly different spellings of the same parser, like why there's a list of language IDs.

**Comment by dbaeumer** [comment]
Added a table.
