### ISSUE TITLE
Extending the list of supported languages

### ISSUE THREAD

**Issue by robertoaloi** [microsoft/language-server-protocol#794]
What is the process to add "support" for additional languages in the list of programming languages included in the LSP [specification](https://microsoft.github.io/language-server-protocol/specification)? Specifically, I'm interested in Erlang and Elixir.

**Comment by dbaeumer** [comment]
Best is to provide a PR :-)

**Comment by robertoaloi** [comment]
I would gladly do so if I knew:

* Where the list of language ids is defined (a grep in this repo did not help)
* What are the prerequisites to add a language to the list if ids.

**Comment by KamasamaK** [comment]
@robertoaloi There is a link to the [specification file](https://github.com/Microsoft/language-server-protocol/blob/gh-pages/specification.md) in the README under [**Contributing**](https://github.com/microsoft/language-server-protocol/tree/master#contributing). The reason you may not have found it with grep is that it is in a separate branch. I believe the only prerequisite is that there's a language server using that language id. There's a separate [servers](https://github.com/microsoft/language-server-protocol/blob/gh-pages/_implementors/servers.md) document for that too.

**Comment by Razzeee** [comment]
Are we talking about extending this table https://github.com/Microsoft/language-server-protocol/blob/gh-pages/specification.md#L656
and whatever code is needed to support that?

**Comment by robertoaloi** [comment]
I believe @KamasamaK replied to all my questions. PR coming.

**Comment by dbaeumer** [comment]
Closing. Both got added to the dbaeumer/3.15 branch.
