### ISSUE TITLE
Semantics of diagnostics passed to codeAction are unspecified

### ISSUE THREAD

**Issue by keyboardDrummer** [microsoft/language-server-protocol#795]
The document for the diagnostics field of `CodeActionContext` reads "An array of diagnostics." Based on the types alone it's not possible to deduce what the meaning of this field is.

My best guess is that for code actions that relate to a diagnostic, the diagnostics passed acts as a filter, and when no diagnostics are passed no actions related to diagnostics are returned. Is that correct?

As a client, I want to populate a list of _all_ possible actions for a particular range. Why would I want filter functionality in the codeAction request? And if I don't want to filter, should I always just pass in all diagnostics related to the range? Seems like a waste of bandwidth, but OK.

**Comment by rcjsuen** [comment]
See #583.

**Comment by dbaeumer** [comment]
Dups #583
