### ISSUE TITLE
SignatureHelpContext support

### ISSUE THREAD

**Issue by KamasamaK** [microsoft/language-server-protocol#797]
Just as there is a `CompletionContext`, there should also be a `SignatureHelpContext`. The [VS Code API](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/47c71265ab38ee27fdc43e916189990996af1852/types/vscode/index.d.ts#L3199) has this already. I've copied the definition below.

```typescript
interface SignatureHelpContext {
	/**
	 * Action that caused signature help to be triggered.
	 */
	readonly triggerKind: SignatureHelpTriggerKind;

	/**
	 * Character that caused signature help to be triggered.
	 *
	 * This is `undefined` when signature help is not triggered by typing, such as when manually invoking
	 * signature help or when moving the cursor.
	 */
	readonly triggerCharacter?: string;

	/**
	 * `true` if signature help was already showing when it was triggered.
	 *
	 * Retriggers occur when the signature help is already active and can be caused by actions such as
	 * typing a trigger character, a cursor move, or document content changes.
	 */
	readonly isRetrigger: boolean;

	/**
	 * The currently active [`SignatureHelp`](#SignatureHelp).
	 *
	 * The `activeSignatureHelp` has its [`SignatureHelp.activeSignature`] field updated based on
	 * the user arrowing through available signatures.
	 */
	readonly activeSignatureHelp?: SignatureHelp;
}
```

Resolves #561

**Comment by dbaeumer** [comment]
Released for 3.15 branch

**Comment by KamasamaK** [comment]
@dbaeumer Upon reviewing and verifying the VS Code implementation, I noticed that `retriggerCharacters` were added to the Signature Help registration options at the same time that the context was added. See microsoft/vscode#54972 and maybe you can understand what issue that was solving because I'm not entirely clear on it.

**Comment by dbaeumer** [comment]
Good catch. I updated the spec and included `retriggerCharacters`
