### ISSUE TITLE
Protocol assumes editors work uniformly wrt file encoding and newlines.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [Microsoft/language-server-protocol#80]
See https://github.com/Microsoft/TypeScript/issues/2343 for more details.

The protocol is Line/Column based.  So the server produces results that include line/character information _from the perspective of the server_ which may not correspond to actual lines/character from the perspective of the client.

For example, say the file contents are:

"foo`paragraph separator`bar`new line`quux".   TSServer will interpret this as two lines, whereas a client may only view it as a single line.  If TS server then reports an issue with the 'b' in 'bar' it will report the issue at "Line 2, column 1".  However, the client will intepret that as being an the line with 'quux'.

**Comment by dbaeumer** [comment]
Agree on the problem. For now I speced that valid end of line squences are:

```typescript
export const EOL: string[] = ['\n', '\r\n', '\r'];
```

On a protocol level there is not more I can do than specing this. I will close the issue. If we need to support additional end of line sequences or different document types we need to extend the protocol.
