### ISSUE TITLE
Prefer to use the message from Error for prepareRename

### ISSUE THREAD

**Issue by hokein** [microsoft/language-server-protocol#800]
Currently, if `prepareRename` returns null, VSCode will prompt up a hard-coded error message ("The element can't be renamed"), which is lacking of details.

clangd returns an error (with its message) for `prepareRename` (instead of `null`), it will give more details (e.g. the failing reasons) to users. It seems works well in VSCode (VSCode just prompts up the error message as expected).

I'd suggest that the LSP prefers to use message from the returned `err` whenever possible (so that all LSP clients can be aligned).

**Comment by dbaeumer** [comment]
@hokin have you tried to response with a response error. The message of the response error will then make it into the UI.

**Comment by hokein** [comment]
@dbaeumer  yes, clangd now responses an [error](https://github.com/llvm/llvm-project/blob/master/clang-tools-extra/clangd/ClangdServer.cpp#L318-L321) when it encounters a non-renamable symbol. And the vscode shows it in the UI.

My point is that we should explicitly clarify this behavior in the LSP, so that the other LSP clients can align with the vscode behavior.
