### ISSUE TITLE
[Feature Request]: workspace.fs

### ISSUE THREAD

**Issue by sumneko** [microsoft/language-server-protocol#809]
To support global variables, I need to load all files in workspace.
At present, I implement it through server's own IO.
However, this approach does not support SSH or WSL remote file systems.
So I think the client should provide the fs method.

**Comment by dbaeumer** [comment]
May be it would make sense to have a separate protocol for this like BSP.

**Comment by dbaeumer** [comment]
Currently I have no plans to tackle this. Especially since the remote FS is fully transparent for the LS when using VS Code remote.
