### ISSUE TITLE
Support for complex edits in completions

### ISSUE THREAD

**Issue by kdvolder** [Microsoft/language-server-protocol#81]
Looking at the protocol definition, it looks like completions aren't capable of performing anything more complex than a simple text insertion or replacement.

I don't think that's going to be sufficient for a lot of reasonable use-cases.

For example consider the completion of the name of a type in a Java program. When inserting the name of the type at the place where the cursor is and where we invoke the completion... we probably also would like the import statements at the beginning of the file to be modified to import that type if necessary.

Completions like that require support for edits that can modify multiple non-contiguous regions of text in the document.

**Comment by kdvolder** [comment]
Another thing to consider is how edits affect the cursor position / selection.

This isn't so much an issue with simple 'insert/replace' completions but it can be if a completions makes changes to multiple places in a file. So completion with a complex completion may also need to explicitly control where the cursor ends up eventually.

**Comment by akosyakov** [comment]
it seems to be a duplicate: https://github.com/Microsoft/language-server-protocol/issues/11

@kdvolder as a workaround you can replace the whole text; you can mark a cursor position with `{{}}`, see [here](https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-custom-languages) `ifeelse` completion item.

**Comment by mickaelistria** [comment]
> as a workaround you can replace the whole text; you can mark a cursor position with {{}},

Thanks, that's interesting. I opened https://github.com/Microsoft/language-server-protocol/issues/82 to have the protocol clarified regarding this approach.

**Comment by kdvolder** [comment]
Thanks for the pointers. Yeah, a 'full text replace' can be a suitable workaround, especially if we can control the cursor position via a `{{}}` in the replacement text.

I'm closing this as it does indeed look like a duplicate of #11.
