### ISSUE TITLE
Specification typos

### ISSUE THREAD

**Issue by PerMildner** [microsoft/language-server-protocol#813]
In the current (`68775c83e00e02d9e2972858b74cfe5d3c779c82`) `specification.md`:

https://github.com/Microsoft/language-server-protocol/blob/gh-pages/specification.md#shutdown "they have sent a shutdown requests" ==> "they have sent a shutdown request".

https://github.com/Microsoft/language-server-protocol/blob/gh-pages/specification.md#implementation-considerations "if a client notices that a server exists unexpectedly" ==> "if a client notices that a server exits unexpectedly"

**Comment by dbaeumer** [comment]
Fixed via PR #820.
