### ISSUE TITLE
Support for virtual documents?

### ISSUE THREAD

**Issue by bioball** [microsoft/language-server-protocol#814]
Not sure if I missed this anywhere in the docs. Does the LSP provide support for virtual documents? I'm thinking of something akin to how IntelliJ treats decompiled sources; you can open them in your editor, but they are read-only and don't necessarily exist in the user's workspace.

**Comment by wz1000** [comment]
This would be very useful for the haskell lsp server too. It seems like vscode already supports this to some extent, but not via LSP: https://code.visualstudio.com/api/extension-guides/virtual-documents

**Comment by dbaeumer** [comment]
Dups https://github.com/microsoft/language-server-protocol/issues/336
