### ISSUE TITLE
Clearing cache

### ISSUE THREAD

**Issue by LewisAndrewCampbell** [microsoft/language-server-protocol#817]
Hello,

How can I clear the cache for this? I have a stale error message for typescript that always appears at the end of a file no matter what I put there. The typescript compiler run from the command line doesn't report the error. Only the language server running in vscode (and sublime text with a plugin that uses the language server) reports the error. And the error has no basis in reality, it has no line number, and just think it's at the end of the file.

So there must be some corrupted cache somewhere I can delete - how do I do that?

**Comment by Aerijo** [comment]
This repo is the specification for the LSP, did you want the TypeScript language server repo instead?

**Comment by LewisAndrewCampbell** [comment]
My mistake! Thanks for the info
