### ISSUE TITLE
Clarify usage of {{value}} and cursor position after completion

### ISSUE THREAD

**Issue by mickaelistria** [Microsoft/language-server-protocol#82]
In #81, I learned that `{{}}` can be used in a completion item to indicate where cursor should be placed. The protocol documentation doesn't mention that. Can it please be added? Also some related questions:
- Does this apply to any TextEdit or only completion ones?
- Is this something that is configured?
- Would it make sense to avoid this workaround and have the TextEdit also contain an (optional) recommendation of a cursor position?

**Comment by kaloyan-raev** [comment]
This is related to #75.

**Comment by dbaeumer** [comment]
This was without any intention and we need to carefully think about how we deal with cursor positions in the protocol itself. I tried to stay away from this so far by not exposing any properties to manipulate the cursor position.

**Comment by mickaelistria** [comment]
See this interesting comment https://github.com/eclipselabs/eclipse-language-service/issues/57#issuecomment-254629377 . A solution could be that placeHolderStart and placeHolderEnd should be part of the completionOptions returned with the capabilities.

**Comment by mickaelistria** [comment]
Close as dup of #82

**Comment by rictic** [comment]
@mickaelistria Did you intend to say that it's closed as a dupe of #75?

**Comment by dbaeumer** [comment]
It is #75. 

And we made some progress on this for the upcoming 1.8 release and it got already merged into some of the LSP client and server libraries for node.

**Comment by mickaelistria** [comment]
What kind of progress were done? Anything that applies to the protocol already?

**Comment by gorkem** [comment]
@dbaeumer I am looking at the CompletionItem changes on the 2.6.x node libraries for this one. CompletionItem.insertText is now defined as `insertText?: string | SnippetString;` Unfortunately these union types are hard to map on languages such as Java, @svenefftinge has been working on a solution but the options are ranging from bad to worse. Can we spec this differently than the current node library implementation so that it is easier for strongly typed folks?

**Comment by dbaeumer** [comment]
@gorkem for the upcoming 3.0 library I speced a TypedString which can either be a normal string or a snippet string. So for people that can't deal with OR types they can always sent a TypedString.

**Comment by mickaelistria** [comment]
I just read about CompletionType=Snippet that allows some placeholder. I believe this covers the story of `{{blah}}` and can fully replace it. So feel free to mark as resolved if placeholders implementaiton is also good for you.

**Comment by dbaeumer** [comment]
Just for clarification. The final design uses a insertTextFormat kind but provides the same functionality as the TypeString (no or types)

**Comment by gorkem** [comment]
@akosyakov, @svenefftinge  does the `insertTextFormat` solution work for you?

**Comment by akosyakov** [comment]
@gorkem yes, we've modeled it as a enum: https://github.com/eclipse/lsp4j/blob/master/org.eclipse.lsp4j/src/main/java/org/eclipse/lsp4j/InsertTextFormat.java
