### ISSUE TITLE
textDocument/publishDiagnostics and textDocument/codeAction relationship

### ISSUE THREAD

**Issue by bmewburn** [microsoft/language-server-protocol#821]
Given that `textDocument/codeAction` commands:

> are typically code fixes to either fix problems or to beautify/refactor code.

And that there is a `CodeAction.diagnostics` property. It implies that diagnostics are going to be computed before code actions. However, `textDocument/publishDiagnostics` is a notification from server to client while `textDocument/codeAction` is a request from client to server for a given range.

There's a strong relationship there but seems to be some incompatibility or clarification needed on the order of these. Should clients only send `textDocument/codeAction` after receiving `textDocument/publishDiagnostics`?

**Comment by rcjsuen** [comment]
```Java
public interface Person {
}
```
```Java
public class Student implements Person {
    private String firstName;
    public String getFirstName() {
        return this.firstName;
    }
}
```
@bmewburn If I were to select the `getFirstName()` method inside the `Student` Java class, it is possible that the language server may want to suggest I extract out the method and add it to the `Person` interface. In such a case, there is no diagnostic information being processed.

Given the above, I would not say it is hard requirement that clients only send `textDocument/codeAction` after receiving `textDocument/publishDiagnostics`. In fact, I feel like `textDocument/codeAction` usually happens after some action by the user (opening the context menu with the cursor on said method in the above scenario).

**Comment by bmewburn** [comment]
@rcjsuen , good point. There doesn't have to be diagnostics involved. My concern was that if I had a language server that did several passes over the code (with a debounce) is there a possibility that some code actions would be cancelled and never show because they depended on a diagnostics pass.

1. documentChange
2. pass 1
3. pass 2
4. pass 3 (diagnostics with debounce or even on save).
5. resolve `textDocument/codeAction`

**Comment by rcjsuen** [comment]
@bmewburn Unfortunately, I don't quite follow what you are saying. Can you provide a more concrete example with some sample code that would be in the opened text editor and what exactly the user is doing (or not doing)?

**Comment by dbaeumer** [comment]
Actually in the API (not the spec) I have:

```
	/**
	 * An array of diagnostics known on the client side overlapping the range provided to the
	 * `textDocument/codeAction` request. They are provied so that the server knows which
	 * errors are currently presented to the user for the given range. There is no guarantee
	 * that these accurately reflect the error state of the resource. The primary parameter
	 * to compute code actions is the provided range.
	 */
```

Since text documents are versions and the LSP guarantees the order of change events I think a server can always find out of the diagnostics might be outdated or not.

I will add the above comment to the spec as well.

Objections to close ?

**Comment by dbaeumer** [comment]
I updated 3.15 of the spec.
