### ISSUE TITLE
Clarify behaviour if a server both statically and dynamically registers for text document changes

### ISSUE THREAD

**Issue by DanTup** [microsoft/language-server-protocol#829]
This bug came up in Dart:

https://github.com/dart-lang/sdk/issues/38490

When we added support for using dynamic registration to control which file types we want edits for, we didn't remove the static registration (since it's still required for clients that don't support dynamic registration). This has resulted in some clients sending duplicate edits (something that also came up at https://github.com/microsoft/vscode-languageserver-node/issues/392). The conclusion is that the server is wrong - however VS Code appears to be de-duping these, since it only sends one set of edits.

In the interest of improving compatibility between servers and clients, I think the expected behaviour should be clearly documented here. I'm going to assume the correct thing is for me to remove the static registration if the client says it supports dynamic registration, but it'd be better if there weren't clients out there (for ex. VS Code and coc.nvim) doing different things.

**Comment by dbaeumer** [comment]
Your assumed behavior is correct. If you statically and dynamically register something you end up having two registrations. I assume that VS Code itself de-duplicates them if they have the same document selector. Is this the case in your example?

**Comment by dbaeumer** [comment]
I added 

> Server must not register the same capability both statically through the initialize result and dynamically for the same document selector. If a server wants to support both static and dynamic registration it needs to check the client capability in the initialize request and only register the capability statically if the client doesn't support dynamic registration for that capability.

**Comment by DanTup** [comment]
> I assume that VS Code itself de-duplicates them if they have the same document selector. Is this the case in your example?

As I understand it, the server doesn't specify selectors in the static registration? But in the client, I think I had removed it (which my understanding was meant send for all documents?). I was testing with files that were then dynamically registered.

In any case, your change looks good to me - and that's what I'm now doing in the Dart server - thanks! :)
