### ISSUE TITLE
Coloring - Background, text, ...

### ISSUE THREAD

**Issue by Dollmminode** [microsoft/language-server-protocol#836]
I am quite the beginner to the Language Server Protocol. I am currently working on a Language Server to provide some additional functionality for a dsl my team created.
Is there a way to provide Syntax-Coloring or sth. that can substitute it like background coloring, or ... ?
We are working with vscode.

I know there is a specification that gives a lot of information about all features but I am not understanding everything.

**Comment by rcjsuen** [comment]
@Dollmminode Welcome to the LSP community!

There are discussions about syntax highlighting for sure. Check out #18 and #513. There's also been a lot of discussions going on at Microsoft/vscode-languageserver-node#367. I don't think there has been any discussions about background colours yet but I could be wrong.

**Comment by Dollmminode** [comment]
@rcjsuen Thanks for the fast response!
