### ISSUE TITLE
Get all Workspace documents

### ISSUE THREAD

**Issue by Dollmminode** [microsoft/language-server-protocol#837]
Is there a possibility to get all workspace documents?

I am working on a path completion via the language server protocol, but at the moment i can only recommend already opened text documents. Is there any notification or request I can use, or is there an easy workaround?

And in addition, opening .csv files does not trigger the didOpen Notification. Why not?

(using vscode)

**Comment by rcjsuen** [comment]
> Is there a possibility to get all workspace documents?

No, the server is expected to figure this out based on the `rootUri` in the `initialize` request in the beginning.

> And in addition, opening .csv files does not trigger the didOpen Notification. Why not?
> 
> (using vscode)

Ask your questions related to Visual Studio Code's LSP implementation in the [microsoft/vscode-languageserver-node repository](https://github.com/microsoft/vscode-languageserver-node).

**Comment by Dollmminode** [comment]
Oh, thanks.
I don't know why i didn't think about that ...

Ok, I will do that.
