### ISSUE TITLE
Additional parameter on textDocument/completion to tell if the completion request is force (ctrl+space)

### ISSUE THREAD

**Issue by gfrancischini** [Microsoft/language-server-protocol#84]
I would like to have the ability to know if the completion request is forced using  the ctrl + space or generated by the trigger characters.

Use case: One of my triggers characters is space but only in some parts of the file (inside element). So if the user typed space but he is not in that specific area the plugin should not open the completion. But if its forced (ctrl+space) the plugin should open the completion.

```
<element param1="" //the space should trigger the completion here>
//the space **should not** triggers the completion here
</element>
```

**Comment by rcjsuen** [comment]
@gfrancischini This is now possible in supporting clients. They will send the server a `textDocument/completion` request with an extra `param.context.triggerKind` property. This feature can be checked by inspecting the `capabilities.textDocument.completion.contextSupport` property in the `initialize` request from the client.

You can review the section about `CompletionParams` and `CompletionTriggerKind` in the [current version](https://github.com/Microsoft/language-server-protocol/blob/7bbf0ff49a03feeeb69e6c5f346ce80e283cd634/specification.md) of the specification for more information.

@dbaeumer OK to close?

**Comment by dbaeumer** [comment]
@rcjsuen thanks for the great explanation. 

Closing the issue.
