### ISSUE TITLE
Clarify how commit characters from capabilities and completion items combine

### ISSUE THREAD

**Issue by MrTrillian** [microsoft/language-server-protocol#840]
I learned from speaking with team members that commit characters on completion items add to, rather than replace, commit characters from the capabilities. This was a surprise to me and, looking at the spec, I cannot find the information.

```
export interface TextDocumentClientCapabilities {
			/**
			 * The client supports commit characters on a completion item.
			 */
			commitCharactersSupport?: boolean
```

```
interface CompletionItem {
	/**
	 * An optional set of characters that when pressed while this completion is active will accept it first and
	 * then type that character. *Note* that all commit characters should have `length=1` and that superfluous
	 * characters will be ignored.
	 */
	commitCharacters?: string[];
```

```
export interface CompletionRegistrationOptions extends TextDocumentRegistrationOptions {
	/**
	 * The list of all possible characters that commit a completion. This field can be used
	 * if clients don't support individual commmit characters per completion item. See
	 * `ClientCapabilities.textDocument.completion.completionItem.commitCharactersSupport`
	 *
   * Since 3.2.0
	 */
	allCommitCharacters?: string[];
```

If it's not too late, having the `CompletionItem.commitCharacters` override `CompletionRegistrationOptions.allCommitCharacters` would be more powerful than them being additive. C++ has a scenario for this: `.` is normally a commit character, except in `#include` completion (same goes for `-`, `+`, `,`, and any other character that can be part of a filename).

**Comment by dbaeumer** [comment]
The team member (which was me :-)) was not correct. The `allCommitCharacters` on the registration capability should only be used if clients don't support individual commit characters. So from a spec point of view they are currently exclusive. 

Give this I have no problem clarifying the spec and saying if both are provided the once on the completion item wins.

Sorry for the confusion around this.
