### ISSUE TITLE
SymbolKind and CompletionItemKind for formal grammar languages

### ISSUE THREAD

**Issue by kaby76** [microsoft/language-server-protocol#841]
I'm thinking about writing a language server for programming languages that have an Antlr grammar, starting with Antlr itself. The spec has no notion of symbol types used in formal grammars: productions, terminals, nonterminals. It would be nice to add these. But, I was wondering why are these types (SymbolKind and CompletionItemKind) hardwired integer values defined across all language servers instead of strings?

**Comment by dbaeumer** [comment]
See https://github.com/microsoft/language-server-protocol/issues/344 and https://github.com/microsoft/language-server-protocol/issues/343
