### ISSUE TITLE
Website URL changed

### ISSUE THREAD

**Issue by octref** [microsoft/language-server-protocol#844]
[Cool URIs don't change](https://www.w3.org/Provider/Style/URI).

Many people have linked to https://microsoft.github.io/language-server-protocol/specification, but now that tab goes to https://microsoft.github.io/language-server-protocol/specifications/specification-3-14.

It's fine to have URLs for each version, but IMO the old link should break, and it should point to latest version.

Related issue: https://github.com/microsoft/language-server-protocol-inspector/pull/44

FYI @gregvanl

**Comment by dbaeumer** [comment]
I am not sure I understand this. It forwards to the current version. 3.15 is still in next state. Can you clarify what you are missing?

**Comment by octref** [comment]
@dbaeumer For example, all links under this section is broken: https://github.com/microsoft/vscode-docs/blob/master/release-notes/v1_21.md#language-server-protocol

**Comment by dbaeumer** [comment]
I will think how to best fix this. The problem is that we only had one spec version in the past and I want to get out of this.

**Comment by octref** [comment]
@dbaeumer I think URLs like this would make sense:

- Latest ver: https://microsoft.github.io//language-server-protocol/specifications/
- 3.14: https://microsoft.github.io//language-server-protocol/specifications/3-14/
- 3.15: https://microsoft.github.io//language-server-protocol/specifications/3-15/

Seems you have 3.14 and 3.15 MD files. Maybe create a `index.md` that [includes](https://github.com/microsoft/language-server-protocol/tree/gh-pages/_specifications) the latest MD file?

**Comment by dbaeumer** [comment]
I actually restored all old links and I point to the current using a current link
