### ISSUE TITLE
Deprecate CompletionItem.deprecated

### ISSUE THREAD

**Issue by KamasamaK** [microsoft/language-server-protocol#853]
In v3.15, `CompletionItem.tags` was added which can tag a completion item as deprecated, so the dedicated `deprecated` property is now redundant.

**Comment by dbaeumer** [comment]
The property is already deprecated in the latest next build

```
	 * @deprecated Use `tags` instead.
```

**Comment by KamasamaK** [comment]
Thanks. I couldn't (and still can't) find that anywhere in this repository.

**Comment by dbaeumer** [comment]
https://github.com/Microsoft/vscode-languageserver-node/blob/master/types/src/main.ts#L1469

**Comment by KamasamaK** [comment]
I see. I was referring to the LSP spec, not the VS Code SDK.
