### ISSUE TITLE
Add SymbolTag

### ISSUE THREAD

**Issue by KamasamaK** [microsoft/language-server-protocol#854]
Along with the new `CompletionItemTag` for `CompletionItem`, there should be `SymbolTag` for `SymbolInformation` and `DocumentSymbol`.

You can see how VS Code does it [here](https://github.com/microsoft/vscode/blob/58479e80ab899402283b522da173c34867d7c78f/src/vs/vscode.d.ts#L2539). For them, it was added at the same time as `CompletionItemTag` and more recently also used for `CallHierarchyItem`, which I would expect to come to LSP eventually as well.

**Comment by kjeremy** [comment]
@dbaeumer 

`SymbolTag` is still referenced in the 3.16 proposed documentation but is not defined anywhere.

**Comment by dbaeumer** [comment]
Good catch!
