### ISSUE TITLE
Question about autocompletions

### ISSUE THREAD

**Issue by Z3TA** [microsoft/language-server-protocol#855]
I'm trying to understand the language server protocol in order to implement a client (for a text/code editor).

I'm using the vscode-jsonrpc node.js module to communicate with the language server.

I've tested both flow lsp and javascript-typescript-langserver. But they can't seem to be able to autocomplete my example file:
```
var testing = 123;
test
```
I send a textDocument/completion request with position: { line: 2, character: 4 },
and was expecting to get back "teststring", but,
In flow I get back an empty list, and in javascript-typescript-langserver I get an error.
What am I doing wrong?

I've been trying to find a test case or example that covers this, but to no avail.

I've tried to change character to 0, and then I get a long list of stuff, so I guess I could use that list to filter out everything that doesn't start with test!?

But what about object members? For example:
```
var testobject = {
    lorem: 123,
    ipsum: "hello"
}
testobject.
```
What query should I send to the language server in order to get the members (lorem, ipsum) from the testobject?

I'm now stuck. Please help.

PS.

Having JSON examples in the protocol spec would help a lot.

**Comment by Razzeee** [comment]
You probably also tried { line: 2, character: 2 } or { line: 1, character: 4 }?

**Comment by Z3TA** [comment]
Yes I've tried all combinations. Will try them all again now ...
