### ISSUE TITLE
Use TextDocumentEdits in completion and formatting

### ISSUE THREAD

**Issue by stamblerre** [microsoft/language-server-protocol#856]
Is there a reason that `textDocument/completion` and `textDocument/formatting` use `TextEdits` rather than `TextDocumentEdits`? It would be helpful to associate a version with these requests. Thanks!

**Comment by dbaeumer** [comment]
`TextDocumentEdits` are use for edit requests that are sent from the server to the client. For completion and formatting the request comes from the client. So the client knows if the returned edits are still applicable without a version number. 

Can you explain why you think this is necessary?

**Comment by stamblerre** [comment]
Ah ok, I didn't realize that it was always on the client to manage the versions. I filed this because I had seen a few issue reports of people getting their file formatted with outdated edits, but it sounds like its on the client to do make sure this doesn't happen.
