### ISSUE TITLE
Need clarity on $/progress Notification

### ISSUE THREAD

**Issue by mtangoo** [microsoft/language-server-protocol#863]
This is a confusion we have hit when discussing implementing the new `$/progress`. Here is a copy of Serenata core dev being confused at not-so clear description of the protocol. Can anyone help clarify?

Quote:

The protocol mentions that if the server wants to initiate progress reporting by itself (i.e. not in response to some other request such as autocompletion), it needs to send a request with the token it is going to use. I don't understand why this has to be a "request"; how is the client supposed to respond? The protocol does not mention this, but every request must have a response, IIRC?

In other words, why is this not a notification? If I'm going to use the token straight after, why do I need to tell the client I'm going to use the token? I'm already going to send a "start progress" notification first. Can the client "deny" this request? Does the server need to wait for the client's response before actually doing progress reporting using that token?

I currently also don't know if any client actually supports this. I'd expect Visual Studio Code to have it (since both are mostly the work of Microsoft), but I'm not sure if it does - in any case I'm not seeing any feedback after the notifications come in, but that may be due to my implementation as well. I can't debug it because there are no errors either. The current implementation may as well be correct.

/End of quote

**Comment by rcjsuen** [comment]
@mtangoo Where does your quote come from? Is there a discussion about this in some other GitHub issue? Could you link to it please?

**Comment by mtangoo** [comment]
Hi @rcjsuen ,
Coming from Serenata issues page. Sorry for not linking it here. Here it is: https://gitlab.com/Serenata/Serenata/issues/293

**Comment by dbaeumer** [comment]
It is a request since the client for some reason could error the request (there might be a modal dialog open or something else going on in the client that prevents starting a progress monitor). If the request errors the server can't use the token to report progress. I clarified that in the spec.

The VS Code client has support for progress creation. However it is currently in proposed state and a extension needs to opt into this using `ProposedFeatures.createAll(client)`
