### ISSUE TITLE
mislink in specification

### ISSUE THREAD

**Issue by calcnerd256** [microsoft/language-server-protocol#868]
The current version of https://microsoft.github.io/language-server-protocol/specifications/specification-3-14/ at the time of this writing contains a broken link to https://github.com/Microsoft/language-server-protocol/blob/gh-pages/specification.md , which I assume is an older location for the markdown file.
The current location of that file appears to be https://github.com/microsoft/language-server-protocol/blob/gh-pages/_specifications/specification-3-14.md instead, or https://github.com/Microsoft/language-server-protocol/blob/gh-pages/_specifications/specification-3-14.md if one wishes to preserve the capitalization of the original, though GitHub usernames appear to be case-insensitive.
I have already made this correction in a commit and will issue a pull request after I submit this issue.  See 6787005a45a2eb2319918f3974854a4db7d84643.

**Comment by calcnerd256** [comment]
See #869.

**Comment by dbaeumer** [comment]
Closed. PR merged. Thanks for providing it.
