### ISSUE TITLE
Clarify TextEdit applicability / "original document" meaning

### ISSUE THREAD

**Issue by LukaszMendakiewicz** [microsoft/language-server-protocol#870]
Is the intention for `TextEdit[]` sent in response to e.g. formatting request to be relative to the version of the document current in the message stream as of the formatting request? (That is, ignoring any subsequent 'didChange' notifications potentially received before the formatting is responded to.)
The most I found in the specification is:

> All text edits ranges refer to positions in the original document

in the [TextEdit[]](https://microsoft.github.io/language-server-protocol/specifications/specification-3-15/#textEditArray) section, but there is no definition of what "original document" means.

**Comment by dbaeumer** [comment]
> Is the intention for TextEdit[] sent in response to e.g. formatting request to be relative to the version of the document current in the message stream as of the formatting request? 

Yes. This is as with all the other request. The assumption is that the result is computed on the state that is know to the server when it receives the request. It is up to the client to either:

- cancel the request if the user continues typing to tell the server that the result is no longer needed (that is what VS Code does)
- still wait for the result and try to re-adjust it
- do something other smart.

I clarified the 

> All text edits ranges refer to positions in the original document
