### ISSUE TITLE
Renderer of spec md file?

### ISSUE THREAD

**Issue by kaby76** [microsoft/language-server-protocol#871]
What flavor of MD is being used for the spec (https://github.com/microsoft/language-server-protocol/blob/gh-pages/_specifications/specification-3-14.md)? It looks like Docfx, but there's no note on the renderer in the spec or nor in the generated website (https://microsoft.github.io/language-server-protocol/specifications/specification-3-14/). I'd like to have a pdf, but Pandoc can't handle this.

**Comment by kaby76** [comment]
While I still have no idea what .md flavor this is, Pandoc works in generating a .pdf when given the correct options. "pandoc -f markdown-raw_tex -t pdf --pdf-engine=xelatex specification-3-14.md -o specification-3-14.pdf". The pdf generated does not contain section numbering and has some formatting issues. To add section numbers, I tried R and rmarkdown, but I could not find how to pass markdown-raw_tex in the rmarkdown::render() command. So, with appropriate modifications to the yaml header for output types, sed, and xelatex (required for Unicode characters present in the spec), I was able to finally produce a pdf that has section numbering. [specification-3-14.pdf](https://github.com/microsoft/language-server-protocol/files/3907322/specification-3-14.pdf) 

    echo "rmarkdown::render('specification-3-14.md','pdf_document')" | rterm --vanilla || true
    cat specification-3-14.tex | sed 's/[\]r[\]n/\\textbackslash{r}\\textbackslash{n}/g' | sed "s/[\]r[']/\\\\textbackslash{r}'/g" |  sed "s/[\]n[']/\\\\textbackslash{n}'/g" > o.tex
    mv o.tex specification-3-14.tex
    xelatex specification-3-14.tex

The yaml header should have the following additions. I don't know what Docfx does with it.

    diff --git a/_specifications/specification-3-14.md b/_specifications/specification-3-14.md
    index 2a1d2e9..e8b9751 100644
    --- a/_specifications/specification-3-14.md
    +++ b/_specifications/specification-3-14.md
    @@ -7,6 +7,13 @@ toc: specification-3-14-toc
     index: 1
     redirect_from:
       - /specification
    +output:^M
    + word_document: default^M
    + pdf_document:^M
    +   latex_engine: xelatex^M
    +   keep_tex: true^M
    +   number_sections: true^M
    + html_document: default^M
     ---
     # Language Server Protocol Specification - 3.14

I suppose it all moot because pdfs and following standards for the format of a spec are old-fashion. Chalking it up to 40+ years in software and too many advanced degrees.

**Comment by dbaeumer** [comment]
The render used for the is the GitHub Jekyll setup. You can follow the setup instructions for Jekyll and then start the render using `bundle exec jekyll serve`.
