### ISSUE TITLE
Support onDidCreateFiles and onDidRenameFiles

### ISSUE THREAD

**Issue by jmbockhorst** [microsoft/language-server-protocol#873]
Support for `onDidCreateFiles` and `onDidRenameFiles` would allow for language specific code actions and refactoring when files are created or renamed/moved.

**Comment by KamasamaK** [comment]
If you're interested in aligning this with the VS Code API, these (among others) are on track to being finalized at microsoft/vscode#85830.

**Comment by dbaeumer** [comment]
Dups https://github.com/microsoft/language-server-protocol/issues/984
