### ISSUE TITLE
Rename request clarification

### ISSUE THREAD

**Issue by kaby76** [microsoft/language-server-protocol#879]
I've implemented the rename request (https://microsoft.github.io/language-server-protocol/specifications/specification-3-14/#textDocument_rename) for my LSP server for both VSCode and VSIDE. Apparently, the server should not actually rename the server's local copy of the document(s): it sends back a list of TextEdit's per file. This is immediately followed with the client sending a change request (https://microsoft.github.io/language-server-protocol/specifications/specification-3-14/#textDocument_didChange) to the server to then do the actual rename. The spec says "The rename request is sent from the client to the server to perform a workspace-wide rename of a symbol" which doesn't jive with what I see with both VSCode and VSIDE. If the server modifies the local copy on the rename request and also executes the echoed change request transaction, it gets an invalid state of the file. Is the server supposed to ignore this echo change request? How? This should be clarified with more precise wording, indicating that the rename request doesn't actually do the rename and is followed immediately by all clients a change request to do the rename, or somehow it ignores the change request transaction. Please clarify. --Ken

**Comment by dbaeumer** [comment]
Good catch. Updated the 3.15 spec.
