### ISSUE TITLE
Add server reference to Diagnostic for code action correlation

### ISSUE THREAD

**Issue by alanz** [microsoft/language-server-protocol#887]
**Problem**

The flow for generating a code action is

- get a compiler report
- turn it into a diagnostic
- send it to the client
- receive it back, in context
- generate a code action from it

The problem comes when the compiler generates structured output, which is reduced to a string when sent to the client as a diagnostic.  It is easier to generate a code action from the structured output than from the text.

See e.g. https://github.com/erlang-ls/erlang_ls/pull/314#pullrequestreview-335379588

**Possible Solution**

Add an optional `reference` field to the Diagnostic, to be used as an index to find the original structured compiler output.

**Comment by dbaeumer** [comment]
To make this consistent with other types the property should be called `data` (see CompletionItem as an example)

**Comment by xorye** [comment]
I'm looking forward to this feature. I need some info from when my diagnostic is created, in order to create better code actions. Putting the info I need in a new `data` property in the diagnostic, so that I can access it when creating the code action, would be great.

**Comment by angelozerr** [comment]
Is there any chance that LSP specification  will provide this `Diagnostic#data` field?

Our usecase is about XML validation based on XSD. The XML validation based on XSD is processed and generates the proper diagnostic error. At this step we know the all valid XML element names. 
We provide for this diagnostic kind a CodeAction which provides quickfixes to replace with valid names:

![image](https://user-images.githubusercontent.com/1932211/94673452-0badc200-0317-11eb-8a82-b3bae557c409.png)

When CodeAction are computed, we must extract those valid names from the diagnostic message which I find is not a very clean mean. For some error message we have not those valid names and we need to introspect the XML Schema to know the valid names although we know those valid names when diagnostic are generated.

It should really fine if we could store those valid names in the Diagnostic#data to reuse it for generating CodeAction.

**Comment by dbaeumer** [comment]
Done. Its in the spec and implemented for the next version of the LSP node libraries.

**Comment by angelozerr** [comment]
Thanks so much @dbaeumer !
