### ISSUE TITLE
Support for SymbolTag in SymbolInformation and DocumentSymbol

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/language-server-protocol#889]
We should support tagging of symbol and document information.

**Comment by KamasamaK** [comment]
Related #854

**Comment by dbaeumer** [comment]
Agree! @KamasamaK thanks for pointing out.

**Comment by KamasamaK** [comment]
I also think along with adding these, SymbolInformation#deprecated and DocumentSymbol#deprecated should be deprecated.

**Comment by dbaeumer** [comment]
Both got documented in the upcoming 3.16 spec.
