### ISSUE TITLE
Clarification of CodeActionOptions

### ISSUE THREAD

**Issue by kjeremy** [microsoft/language-server-protocol#890]
Does the client key off of the kinds returned by the server in `CodeActionOptions`? I'm a bit confused as to whether filling this in does anything for vscode. Also if I add say `refactor.extract` to that list does that match something like `refactor.extract.variable`?

**Comment by Gama11** [comment]
It definitely matters for VSCode in some cases, for instance I remember `editor.codeActionsOnSave` not working properly when the code action in question wasn't listed in `codeActionKinds`.

**Comment by dbaeumer** [comment]
If you fill in the options and the client knows that is requesting for a different kind it is free to not invoke the server.
