### ISSUE TITLE
Using TextDocumentPositionParams as parent interface

### ISSUE THREAD

**Issue by KamasamaK** [microsoft/language-server-protocol#895]
Is there a reason why `DocumentOnTypeFormattingParams` and `RenameParams` do not extend `TextDocumentPositionParams` in the spec?

**Comment by dbaeumer** [comment]
No reason. I think they existed before I introduced `TextDocumentPositionParams`.

**Comment by dbaeumer** [comment]
Do you want to provide a PR ?

**Comment by dbaeumer** [comment]
Reopening.

**Comment by dbaeumer** [comment]
Both got fixed in the upcoming 3.16 spec
