### ISSUE TITLE
LSP code complitions

### ISSUE THREAD

**Issue by JennyMet** [microsoft/language-server-protocol#900]
HI

This is not an issue but rather a question.
I see the following samples but I didnt find and example to code compilations, is there any reference / example which I can use code compilations ? 

https://github.com/Microsoft/vscode-extension-samples

**Comment by Razzeee** [comment]
https://code.visualstudio.com/api/language-extensions/language-server-extension-guide should be helpful, look for `connection.oncompletion`

Should be this part of the repo https://github.com/microsoft/vscode-extension-samples/tree/master/lsp-sample

**Comment by JennyMet** [comment]
@Razzeee - Thanks, is there is also an example for javascript files ?

**Comment by dbaeumer** [comment]
@JennyMet no, we don't maintain an example in JavaScript. But converting the TypeScript one to JavaScript should be straight forward.

@Razzeee thanks for pointing to the lsp sample.
