### ISSUE TITLE
Progress reporting during initialization

### ISSUE THREAD

**Issue by mschaefer88** [microsoft/language-server-protocol#904]
I saw that the initialization ships a _workDoneToken_ but the [Initialize Request](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#initialize) doesn't state that property on the request. Furthermore it seems to be the server isn't allowed to send any progress at this stage:

> Until the server has responded to the initialize request with an InitializeResult, the client must not send any additional requests or notifications to the server. In addition the server is not allowed to send any requests or notifications to the client until it has responded with an InitializeResult, with the exception that during the initialize request the server is allowed to send the notifications window/showMessage, window/logMessage and telemetry/event as well as the window/showMessageRequest request to the client.

And from [Signaling Work Done Progress Reporting](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#signalingWorkDoneProgressReporting)

> To avoid that clients set up a progress monitor user interface before sending a request but the server doesn’t actually report any progress a server needs to signal work done progress reporting in the corresponding server capability. For the above find references example a server would signal such a support by setting the referencesProvider property in the server capabilities as follows:

So it seems to me, sending the token from client side isn't needed since the server isn't allowed to respond anyways. Also because the client doesn't know at this point if the server even is capable of sending progress. Or did I miss something?

Sorry if I'm causing any work, I'm just trying to understand the protocol more in depth. :)

**Comment by dbaeumer** [comment]
Please also note that in the LSP client lib you needs to ask the client to sent a progress token in the initialize request using: the `progressOnInitialization` client option.
