### ISSUE TITLE
Multiple definitions of TextDocumentSyncOptions

### ISSUE THREAD

**Issue by Aerijo** [microsoft/language-server-protocol#909]
The `TextDocumentSyncOptions` interface is defined twice, with one being kind of a superset of the other. They can be found by searching
```
export interface TextDocumentSyncOptions {
```
on the page.

One is [here](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_didClose) in the textDocument/didClose section. This appears to be the wrong one because it is unrelated to that notification, but the other definition [here](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_synchronization) has fewer properties.

**Comment by dbaeumer** [comment]
This is actually on purpose since motivating the full structure in the open section is not feasible. I will add a comment to clarify this.
