### ISSUE TITLE
Document the structure of a notification & request / response definition.

### ISSUE THREAD

**Issue by metaleap** [microsoft/language-server-protocol#910]
Implementing the protocol in code "from spec" is mostly a breeze (except for duration......) because most `export interface Thing` decls in the spec can be co-related to the major request/notification params and/or capabilities / setup-options simply by `Ctrl+F`ing through the doc. **Not so** for `TextDocumentChangeRegistrationOptions` presented in a "lonely location" in the [DidChangeTextDocument Notification](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_didChange) section:

it isn't referenced explicitly elsewhere, meaning **most likely some `extends` markers are incomplete in some `FooOptions` interfaces**.

Someone "coding down the spec into some scaffold object-model / type-hierarchy / interfaces+methods hodgepodge" and coming across that, is now not quite sure where to put this or whether / why to expose it, as it isn't referenced.

Missing link to be filled in to the spec for completeness' sake? Or am I missing sth?

**Comment by metaleap** [comment]
Understood, it's to be used "when registering". Be good to have some sort of tutorial overview on this whole "registration" machinery on the langserver site, since the spec is by necessity "mechanistic" / formalistic. Feel free to close after having seen.

**Comment by dbaeumer** [comment]
Yes, all `*RegistrationOptions` are used for registering the server for specific client requests or notifications dynamically. 

I do agree that we should add a section to the specification to explain the structure of a notification / request definition.
