### ISSUE TITLE
[clarification] completionItem/resolve and additionalTextEdits

### ISSUE THREAD

**Issue by yyoncho** [microsoft/language-server-protocol#924]
The spec says:

"The returned completion item should have the documentation property filled in. The request can delay the computation of the detail and documentation properties. However, properties that are needed for the initial sorting and filtering, like sortText, filterText, insertText, and textEdit must be provided in the textDocument/completion response and must not be changed during resolve."

Should clients call `completionItem/resolve` when the additionalTextEdits are not present?

**Comment by dbaeumer** [comment]
@yyoncho no, since it would make applying a completion item an async operation on the client which will cause quite some problems. 

I tired to express this with 

> The request can delay the computation of the detail and documentation properties

But I see that this might not be clear enough. I will tweak to sentence to make this more clear,

Thanks for bringing this up.
