### ISSUE TITLE
How Does Initialization Work?

### ISSUE THREAD

**Issue by yxrkt** [microsoft/language-server-protocol#925]
I'm trying to set up a language server written in C++. Starting from the lsp-sample, I've replaced serverOptions with the following (taken from [vscode-ccls](https://github.com/MaskRay/vscode-ccls/blob/master/src/serverContext.ts#L437))
```ts
const serverOptions: ServerOptions = async (): Promise<cp.ChildProcess> => {
    const child = cp.spawn("test.exe");
    this.clientPid = child.pid;
    return child;
};
```

Like ccls, my C++ program is listening on stdin
```cpp
int main()
{
    bool quit = false;

    thread([&]()
    {
        while (!cin.eof())
        {
            string message = (stringstream() << cin.rdbuf()).str();
            MessageBoxA(NULL, message.c_str(), "test", MB_ICONINFORMATION);
        }

        quit = true;
    }).detach();

    while (!quit) {}

    return 0;
}
```

From my understanding, the client is supposed to
1. Launch my server (it does)
2. Send it exactly one init message (through stdin?)

Am I missing some configuration for the client to communicate through stdin/stdout?

**Comment by Razzeee** [comment]
Did you set your transport to be stdio?
```
const serverOptions = {
        run: { module, transport: TransportKind.stdio },
      };
```

**Comment by yxrkt** [comment]
Thanks for the suggestion, I'll try this when I get home. IIRC though, the module/transport case is for servers implemented with Node?

**Comment by dbaeumer** [comment]
@yxrkt your understanding is correct. If the server options are a function it depends on the result of the resolved promise how the client communicates with the server. If the result is a child process stdin/stdout are used. See https://github.com/microsoft/vscode-languageserver-node/blob/master/client/src/main.ts#L274

Do you call `start` on the created language client?

**Comment by yxrkt** [comment]
Turns out I'm just bad at C++ streams... I've tested my C++ code with a C# app that writes to the C++ app's stdin. The code as I had it above blocks forever (probably because there's no eof in the stream?). 

getchar() does the trick. Sorry for the trouble.
