### ISSUE TITLE
Add support for links in diagnostics

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/language-server-protocol#926]
VS Code added API to support links in diagnostics. We should investigate if we adopt this in LSP.

**Comment by Razzeee** [comment]
I'm currently showing urls via diagnostics, they are just not linked.

**Comment by KamasamaK** [comment]
Relevant VS Code issue is microsoft/vscode#11847

**Comment by dvandra** [comment]
Is there any further updates on this feature-request?

**Comment by Razzeee** [comment]
I think the current state is it being proposed via https://github.com/microsoft/vscode-languageserver-node/commit/fa9ccc4f2eff73d6b0e96bb59086fb8fba4eb88c

https://github.com/microsoft/vscode-languageserver-node#3160-next1-protocol-510-next1-json-rpc-620-next1-client-and-620-next1-server

**Comment by dbaeumer** [comment]
This got implemented and is documented in the 3.16 spec.
