### ISSUE TITLE
prepareRename vs TextDocumentPositionParams

### ISSUE THREAD

**Issue by cdietrich** [microsoft/language-server-protocol#931]
is there a specific reason why prepareRename still uses generic TextDocumentPositionParams and not a specific PrepareRenameParams

**Comment by dbaeumer** [comment]
No. It doesn't have additional params and no progress and partial result. That is why.

OK to close.

**Comment by cdietrich** [comment]
having a dedicated type has the charm that the api in statically types languages does not change if a new parameter gets introduced to it.
most of the other uses dont have two parameters too, they just aggregate two interfaces
