### ISSUE TITLE
Requesting to edit a file from server

### ISSUE THREAD

**Issue by kaby76** [microsoft/language-server-protocol#932]
I have a server that works well on Antlr files, but I now want to have it open, parse, and possibly edit files and workspaces for C# or C++ in order to handle things that have a foot in both Antlr and target language (e.g., C#, C++, Java, Javascript, etc.)--implementing [tree visitors and listeners](https://github.com/antlr/antlr4/blob/master/doc/listeners.md). In the protocol, how do I (the Antlr language server) tell the client that I need to open and edit a file that isn't in its domain, open and edit a workspace? I can't just read a file from disk because that is privileged information between client and server that "own" the source file. Thanks for the info.

**Comment by rcjsuen** [comment]
@kaby76 Can you clarify what you're looking for? When you say "open" I presume you mean at the disk layer and not at the client's editor level, correct? You want to modify some files but do you know the URI of said files? If yes, will `workspace/applyEdit` satisfy your use case?

**Comment by rcjsuen** [comment]
> In the protocol, how do I (the Antlr language server) tell the client that I need to open and edit a file that isn't in its domain, open and edit a workspace?

When you say "edit a workspace" you mean edit a file, right?

**Comment by kaby76** [comment]
Right. This is a problem with the protocol. There is no documentation synchronization between client and server in which the server requests text synchronization from the client. It's only available from client to server, not the other way around (see to Text Synch section https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_synchronization). Unfortunately, the client could be modifying the document and it may be serviced by a completely different LSP server, so I cannot just read the document on disk. I haven't looked at the issue of notifying the client when the workspace changes as I could add a C# file but let's just start with text synchronization.

**Comment by kaby76** [comment]
I think the workaround is to add into the extension (client, vs 2019) a write of all files before calling the server. The server can then just read and modify any files it wants. The editor may say something like the file was modified outside the editor, but that's okay. But maybe server requests for file synchronization might be useful in the future.

**Comment by rcjsuen** [comment]
> Unfortunately, the client could be modifying the document and it may be serviced by a completely different LSP server, so I cannot just read the document on disk. I haven't looked at the issue of notifying the client when the workspace changes as I could add a C# file but let's just start with text synchronization.

If the client opens and modifies a file, your server will be notified via a `textDocument/didChange` notification assuming your server is hooked up to listen to those files.

Otherwise, it feels to me like you should just read from disk with some filesystem listener support if you're worried that after you read a file from disk someone else modifies the file? There's nothing stopping me from having an LSP client open and then using Vi or Emacs to edit the file in the command line. That's the same thing as another language server editing files without you knowing, correct?

**Comment by kaby76** [comment]
No. My server is for Antlr. When a C# file is opened, no DidOpen call is sent to my server. It does not serve C#, so it gets only DidOpen for Antlr. Besides, there are better server implementations to do that, which VS2019 presumably uses. In the meanwhile, the user can edit that C# file, so all changes are in a buffer somewhere in memory of the client, and presumably the C# server. If that happens,  I cannot willy nilly just read that C# file from disk and modify it....collisions. The only solution is to make this transactional...force all files to be flushed so I can read the correct file contents. Then when it is done, the user can do whatever.

**Comment by rcjsuen** [comment]
> No. My server is for Antlr. When a C# file is opened, no DidOpen call is sent to my server. It does not serve C#, so it gets only DidOpen for Antlr. Besides, there are better server implementations to do that, which VS2019 presumably uses.

I see. So it is as if you want to listen to "all" languages for syncing your internal state but you only ever want to honour LSP requests for a specific language.

**Comment by kaby76** [comment]
Correct. I want the Antlr server to modify the C# code (using Roslyn), but I want to add method stubs to a class. My LSP server is not a domain expert in C#. Unfortunately, I don't even know which class may have subclass the Antlr listener and visitor class, so I have to search all C# files in the solution, again using Roslyn for the parsing. I guess I could just ask the client for each and every C# file in the workspace (returning the contents of what's in a buffer, or if not being modified, read the file from disk) using a custom message until it finds what it wants. I think the protocoal can do that with custom messages from server to client, I guess. Hmm.... Thanks for helping think this through.

**Comment by dbaeumer** [comment]
From a LSP point of view this is possible using dynamic registration (I am not sure how well this is supported in VS though). You can provide language smarts for a selector A (Antlr) and listen to file open/change/close for a selector B (C#) without providing language smarts.

**Comment by Razzeee** [comment]
But only for files in the project path, correct?

**Comment by dbaeumer** [comment]
I would say that depends on the client. The spec allows opening file outside the project root and VS Code handles this correctly.
