### ISSUE TITLE
What should be put in `CodeAction.command.title`?

### ISSUE THREAD

**Issue by vrama628** [microsoft/language-server-protocol#933]
The server may send the client [CodeAction literals](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_codeAction) in response to a `textDocument/codeAction` request. A `CodeAction` has a field `title: string` which the client shows to the user as the title of this code action. A `CodeAction` may also have a field `command?: Command` which then has a field `title: string`, which [is meant to be shown to the user the title of the command](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#command). This means that when a language server wants to send the client a `CodeAction` containing a command, the language server must populate two separate `title : string` fields.

What are the two `title` fields each meant for? From testing in VSCode, it looks like the `CodeAction.title` field is shown to the user as the title of the code action, and I can't find where the value of the `CodeAction.command.title` field shows up. It's especially weird when the `CodeAction` has both its `edit` and `command` fields populated, because then the `Command` represents not an entire code action but half of one, which seems like a weird thing to try to think of a title for.

**Comment by dbaeumer** [comment]
@vrama628 command in code actions are deprecated in favor of edits. The command has a title since it can be used standalone as well. But it is not used in the context of code actions.
