### ISSUE TITLE
Clarification: can `SignatureHelp.signatures` be an empty array?

### ISSUE THREAD

**Issue by mroch** [microsoft/language-server-protocol#934]
The interface for `SignatureHelp` (as of 3.15) says that `signatures` contains "one or more", but then `activeSignature` talks about `signatures.length === 0`.

```
export interface SignatureHelp {
	/**
	 * One or more signatures.
	 */
	signatures: SignatureInformation[];

	/**
	 * The active signature. If omitted or the value lies outside the
	 * range of `signatures` the value defaults to zero or is ignored if
	 * `signatures.length === 0`. [...]
	 */
	activeSignature?: number;

	[...]
}
```

It also says "Signature help represents the signature of something callable" which suggests that when the Position is not something callable, the correct response is `null`, not `{ signatures: [] }`.

If that's the case, I think the docs for `activeSignature` should not mention `signatures.length === 0`. Further, why would `activeSignature` ever be outside the range of `signatures`? It's confusing that it talks about all these invalid states.

**Comment by dbaeumer** [comment]
The reason why the spec talks about this is that clients receiving such a result has some reasonable hints what to do if it receives something that where active signature is outside the array. 

I do agree if that this can be made more clear. I rephrases it a little.
