### ISSUE TITLE
Can we use the content from textDocument/didSave to check correctness of our sync?

### ISSUE THREAD

**Issue by davidanthoff** [microsoft/language-server-protocol#939]
We have registerered things so that our LS receives `didSave` notifications with the content of the doc.

Right now, when we receive this notification, we compare the text that was sent as part of the `didSave` notificiation with the content that we have stored in the server (i.e. our internal doc store, that has reacted to various `didChange` events). We are interpreting any discrepancy as an indiciation that we have some bug in our implementation of the text sync stuff.

Is that a correct behavior? I.e. should the text that is sent via `didSave` always be identical to the text taht the server initially received via `didOpen` and then manipulated in response to various `didChange` notifications?

**Comment by dbaeumer** [comment]
Yes, they should be identical. Minus new line ending depending on how you store the document on the server.
