### ISSUE TITLE
Discuss where the protocol should define rendering content as markdown.

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/language-server-protocol#94]
See the discussions in https://github.com/Microsoft/language-server-protocol/pull/91

**Comment by rictic** [comment]
Having a clear encoding for content everywhere that it may be rendered makes things much easier and less ambiguous both for servers and clients. Speaking for the server that I'm writing I'd add that the choice of markdown is really nice for us, as that is already the convention for Polymer code.

It's true that not all clients can render markdown, but markdown is a fairly simple format, and it is not too hard to remove distracting formatting characters using any of a number of widely available markdown parsers.

Along these lines, I think it would be helpful to standardize on markdown and use in _more_ places in the protocol, e.g. `CompletionItem#documentation`.

**Comment by akosyakov** [comment]
1. To support other formats we need `ClientCapabilities.markedStringFormats` property or something like that to provide a server with formats supported by a client, sending marked string of other formats will be illegal. It can be actually worth to do it to lower an entrance barrier for clients, since at the beginning they can support only the plain text and later add support for the markdown. 

2. I think at the end the markdown will become a de facto standard even if we support more.

3. I've changed my mind and think that having `MarkedString` as a type is better than a primitive type string, since it can be extended. But having `language` is still questionable depending whether we decide to standardize the markdown. At lest we should rename it to something like `format` to avoid confusion with a language.

**Comment by dbaeumer** [comment]
I would opt to not make this a capability since it makes things to complicated. And it highly depends on the rendering capabilities of the client. Thinking about it again I am now the opinion having this standardize on Markdown is the right thing to do. So I opt to close this issue. Objections ?

**Comment by ljw1004** [comment]
The main problem with markdown is that it has no good route for colorizing SNIPPETS of code. For instance, if you hover over a variable and the LSP decides to send the type of the variable in one of its MarkedStrings,

    ``csharp
    CustomerConnection
    ``

then no markdown code colorizer will know whether to be colorizing it as a type or an identifier or what.

**Comment by rictic** [comment]
@ljw1004 True, but this isn't the fault of markdown, it's just a fact of syntax highlighting. The only alternatives would involve providing the rest of the document as context or doing something complex and custom to communicate that context.

**Comment by ljw1004** [comment]
Current behavior of Nuclide/Atom is it knows the hover text it gets back is a type, and colorizes it appropriately. It'd be a painful regression to adopt LSP if that makes it fall back to wrongly-colorized or uncolorized text.

Solution: I think it places where LSP has Markdown codeblocks being communicated, it should be providing a coarse indication of how to colorize them: one of "type, expression, declaration".

**Comment by dbaeumer** [comment]
A comparable problem is discussed with PHP. There without a proper context most php tokenizer even refuse to tokenize this correctly. 

I have to admit that I don't have a good idea here right now. Providing an indication "type, expression, declaration" requires to define a set and then we have the question again how to extend it. 

I also think that the approach taken here has to be in line with sematic coloring which is still something we would like to add to the protocol. If we can describe sematic highlight then we will be able to describe code blocks better (in the worst case we then have a special code block which has the text plus the highlight information).

**Comment by dbaeumer** [comment]
This got implemented this week. Markdown is not available for Hover, CompletionItem and SignatureHelp. It is implemented in a way that clients can even request a different markup format. For example HTML. The lowest bar is plain text
