### ISSUE TITLE
Meaning of trace for the server

### ISSUE THREAD

**Issue by giltho** [microsoft/language-server-protocol#943]
The trace parameter is used for the clients (or at least VSCode) to write down the trace of execution. What is the point for the server ? Should it be the level of logging for `logMessage` ?
The only information the spec gives is:
```ts
/**
  * The initial trace setting. If omitted trace is disabled ('off').
  */
trace?: 'off' | 'messages' | 'verbose';
```
Given an explanation, I'd be glad to write a PR that gives more details about this parameter in the spec :)

**Comment by dbaeumer** [comment]
Actually this deserves some clarifications. The LSP server I maintain send a custom `$/logTraceNotification` notification to the client. This works since the spec says 

> If a server or client receives notifications starting with ‘$/’ it is free to ignore the notification

However I think it makes sense to standardize at least the method and the payload. Are you willing to look into this?

**Comment by giltho** [comment]
I would be glad to.
However, I would need a bit more information.

I'm helping in the [ocaml lsp implementation](https://github.com/ocaml/ocaml-lsp), and we write a lot of logs through [window/logMessage](https://microsoft.github.io/language-server-protocol/specification#window_logMessage) since [this recent PR](https://github.com/ocaml/ocaml-lsp/pull/120). We were considering logging even more things through this process. However, I kind of wondered:
 - Should part of what we report be reported through a trace thing ?
 - Should the `trace` setting impact how much we log ?

In a more general way, I like the idea of standardising your `$/logTraceNotification` notif, but I have no idea what kind of payload it should carry. Do you have a link to your implementation so I could understand better ?

**Comment by dbaeumer** [comment]
Regarding your questions:

> Should part of what we report be reported through a trace thing ?
Yes, I think so.
> Should the trace setting impact how much we log ?
Yes, since it support verbose, messages, off

The notification is typed here: https://github.com/microsoft/vscode-languageserver-node/blob/dbaeumer/encodingSupport/jsonrpc/src/main.ts#L271

`message` is the message
`verbose` and extract verbose information

**Comment by giltho** [comment]
Sorry to be a bit slow to answer
So I think I could write this, I have one last question : when should `logMessage` be used, and when should `logTrace` be used ?

**Comment by dbaeumer** [comment]
`logMessage` is more like `console.log`. `logTrace` is for writing a trace execution. Clients could for example write this using speedy log for example.

**Comment by dbaeumer** [comment]
PR got merged.
