### ISSUE TITLE
Support snippets for onTypeFormatting

### ISSUE THREAD

**Issue by tinaschrepfer** [microsoft/language-server-protocol#947]
Language services need to be able to set caret position after inserting a block comment.  Suggestion is to support snippets for onTypeFormatting to enable this behavior.

**Comment by NTaylorMullen** [comment]
We'd also use this to support auto-completing end HTML tags: `<strong` (type `>`) => `<strong>|</strong>`

/cc @ToddGrun

**Comment by ToddGrun** [comment]
We also have other scenarios that fit this (typing '=' auto generates quotes and places the caret between them, etc.

**Comment by rcjsuen** [comment]
> Language services need to be able to set caret position after inserting a block comment. Suggestion is to support snippets for onTypeFormatting to enable this behavior.

Can you show an example of what you are suggesting?

> We'd also use this to support auto-completing end HTML tags: `<strong` (type `>`) => `<strong>|</strong>`

Never realized that that the `textDocument/onTypeFormatting` request could be used for this. Interesting... 🤔

Should a new request be created to support this use case?
