### ISSUE TITLE
Add git tag for 3.15 release

### ISSUE THREAD

**Issue by axelson** [microsoft/language-server-protocol#952]
Currently there is no `release/3.15.0` tag. On https://microsoft.github.io/language-server-protocol/specification#version_3_15_0 it shows a release date of 09/19/2019 so at that time the latest commit on master appears to have been: https://github.com/microsoft/language-server-protocol/commit/68775c83e00e02d9e2972858b74cfe5d3c779c82

**Comment by dbaeumer** [comment]
The tag is: 05b3224 - Publish 3.15 specification

The problem is the wrong date in the markdown document. Will fix that.

OK to close.

**Comment by axelson** [comment]
Thanks for the info! Can you create the tag and push it up to GitHub as well? You can see that there is no 3.15 in https://github.com/microsoft/language-server-protocol/releases (which is driven by git tags).

**Comment by dbaeumer** [comment]
Done. Sorry for missing it.

**Comment by axelson** [comment]
Great, thanks!
