### ISSUE TITLE
rootUri deprecated or not?

### ISSUE THREAD

**Issue by Gama11** [microsoft/language-server-protocol#957]
In vscode-languageserver-node, `rootUri` is marked as deprecated:

https://github.com/microsoft/vscode-languageserver-node/blob/fa9ccc4f2eff73d6b0e96bb59086fb8fba4eb88c/protocol/src/protocol.ts#L727

On https://microsoft.github.io/language-server-protocol/specifications/specification-current/ this deprecation warning is missing:

![](https://i.imgur.com/8zFl3kt.png)

Which one is correct?

**Comment by rcjsuen** [comment]
In my opinion, it shouldn't be marked as deprecated. 🤔
