### ISSUE TITLE
Client Communication

### ISSUE THREAD

**Issue by afonsojramos** [microsoft/language-server-protocol#959]
I'm developing a VSCode tool using the Language Server Protocol and I think could use your help with a few things. In this specific case, I wanted to use the Decorations, however, following the LSP, which obviously does not allow me to use such function in the server, obviously, since such must be executed in the Client, which raises the question, how do I do it? Is there a way I can execute Client functions from the server?

Furthermore, what is the best documentation to follow for all the LSP implementations?

PS: Implementation is being done in TypeScript

**Comment by rcjsuen** [comment]
> In this specific case, I wanted to use the Decorations

What are "decorations"?

> however, following the LSP, which obviously does not allow me to use such function in the server, obviously, since such must be executed in the Client, which raises the question, how do I do it? Is there a way I can execute Client functions from the server?

Perhaps you are looking for the `workspace/executeCommand` request?

> Furthermore, what is the best documentation to follow for all the LSP implementations?

I would say it's just from reading the specification and then just searching the questions and answers that have been posted here.

**Comment by afonsojramos** [comment]
> What are "decorations"?

I should have been clearer, I intend to use the method setDecorations in [TextEditor](https://code.visualstudio.com/api/references/vscode-api#TextEditor).

> Perhaps you are looking for the workspace/executeCommand request?

The problem is, for such request, I would need access to the vscode API, which on the server side, I should not have, correct?

**Comment by rcjsuen** [comment]
@afonsojramos Yes, you can’t use the LSP to invoke arbitrary API on the client.

> I'm developing a VSCode tool using the Language Server Protocol

Do you care about supporting other clients? Your initial statement sounds like you only care about supporting VS Code. Is that correct?

**Comment by afonsojramos** [comment]
For the time being, maybe. What would be the difference in implementation?

**Comment by rcjsuen** [comment]
> For the time being, maybe. What would be the difference in implementation?
> 
> I assume that I would have to create a different client for each of the IDEs, right?

Yes. Do the editors you would be interested have such a “decoration” API?

**Comment by afonsojramos** [comment]
> Yes. Do the editors you would be interested have such a “decoration” API?

Well, honestly, I do not know, therefore, due to time constraints, for the time being, let's assume I will only support VSCode, how would I advance then?

Thank you so much for the help so far!

**Comment by rcjsuen** [comment]
> let's assume I will only support VSCode, how would I advance then?

@afonsojramos I see two paths for you.

1. Extend the code in the [microsoft/vscode-languageserver-node repository](https://github.com/microsoft/vscode-languageserver-node) and add custom JSON requests to handle your special requests and optionally propose a new language server protocol request/notification.
1. Just write a VS Code extension and forget about the LSP.

**Comment by afonsojramos** [comment]
Thank you for your help @rcjsuen! I will discard the use of Decorations for now and try to find an alternative while still using the LSP!
