### ISSUE TITLE
Could you add an example for a `telemetry event` to the specs?

### ISSUE THREAD

**Issue by ell1e** [microsoft/language-server-protocol#962]
The specs list a "Telemetry Notification" with this short description given:

> The telemetry notification is sent from the server to the client to ask the client to log a telemetry event.

*Source:* https://microsoft.github.io/language-server-protocol/specification#telemetry_event

This really doesn't say much though. What sort of telemetry is this, like compiler's internal timing/perf debugging, user code timing debugging, ...? Why are the parameters just "any", if the LSP server can just send any arbitrary stuff what is the editor even supposed to do with it? Log it somewhere? If yes, is the regular editor/IDE end user supposed to see it or  is it some hidden debug visualization option only meant for the developers of the LSP implementation themselves?

Any clarification on the purpose, the expected kind of user (like, who is this for?), and maybe an example message written out in JSON would be very appreciated. Would it be possible to add this?

**Comment by dbaeumer** [comment]
It is spec sol loosely since the protocol doesn't do any interpretation of this. So adding something might point people into the wrong direction. I will write a sentence why it is spec so loosely.

**Comment by kjeremy** [comment]
> I will write a sentence why it is spec so loosely.

It looks like the param is now specified as `object` instead of `any`. Doesn't that contradict the above?

**Comment by dbaeumer** [comment]
@kjeremy yes I missed number, ... The problem with any is that it includes `undefined` which is not valid. `null` should not be valid either.
