### ISSUE TITLE
If codeActionLiteralSupport is missing should the server only return Command[]?

### ISSUE THREAD

**Issue by kjeremy** [microsoft/language-server-protocol#965]
It's not clear to me based on the text whether the presence of `codeActionLiteralSupport` should be used to determine if the client supports `CodeAction[]`.

**Comment by kjeremy** [comment]
More details: https://github.com/microsoft/vscode-languageserver-node/issues/618

**Comment by kjeremy** [comment]
Also... if the client does NOT send down `CodeActionClientCapabilities` but the server supports this should it return `true` in the server capabilities?

**Comment by rcjsuen** [comment]
@kjeremy These questions seem generic and not specific to VS Code to me and could be posted to [microsoft/language-server-protocol](https://github.com/microsoft/language-server-protocol) instead. What do you think?

**Comment by kjeremy** [comment]
@rcjsuen Yep that is this repo I think.

**Comment by rcjsuen** [comment]
> @rcjsuen Yep that is this repo I think.

You're right, how foolish of me. I confused myself from opening too many tabs. :( Sorry for the noise.

**Comment by dbaeumer** [comment]
The code action request at the beginning could only return and `Command[]`. If the capability is provided the request can also return `CodeAction[]`. I will update the doc and spec.

**Comment by dbaeumer** [comment]
Updated the doc also I have to say that it was already pretty clear. At least to me:

**Comment by kjeremy** [comment]
Shouldn't the server also only return true for the provider in it's
capabilities as well to maintain backwards compatibility?

**Comment by kjeremy** [comment]
@dbaeumer Let me restate the previous question: If the client does not support `CodeActionKind` and the server sees this but it does support `CodeActionKind` is the intent that the server then changes it's caps to return `codeActionProvider: true` so that the client knows that it has that capability? Is that the intent with all server capabilities that return `bool | SomethingElse`?

**Comment by dbaeumer** [comment]
@kjeremy yes but the correct property to test on is `codeActionLiteralSupport`. Server can only provide `SomethingElse` if that property is there.

**Comment by kjeremy** [comment]
@dbaeumer I don't think that's entirely clear in the spec. It may be worth adding text for each case where the server is required to fall back based on the presence of client capabilities.

BTW I've implemented this for rust-analyzer here: https://github.com/rust-analyzer/rust-analyzer/pull/4516

**Comment by dbaeumer** [comment]
@kjeremy any suggestion around the working. PR would be welcome :-)
