### ISSUE TITLE
CodeActionKind for adding functions?

### ISSUE THREAD

**Issue by kjeremy** [microsoft/language-server-protocol#966]
We have assists for things like: "add function" and I can't decide which `CodeActionKind` fits better. I am wondering if there should be an explicit "insert".

**Comment by dbaeumer** [comment]
I would rather opt for `create`. But why do you need to distinguish this?

**Comment by kjeremy** [comment]
I am trying to categorize all of the actions we provide and it seems like
"insert something" is a very common action.

**Comment by kjeremy** [comment]
I'm getting back to this and am going with `generate`: https://github.com/rust-analyzer/rust-analyzer/pull/5116#discussion_r447095013

**Comment by dbaeumer** [comment]
@kjeremy I am closing this issue because of house keeping. If you think I should add something to the spec please ping with a proposal.
