### ISSUE TITLE
Is the client supposed to support all TextDocumentSyncKind variants?

### ISSUE THREAD

**Issue by kjeremy** [microsoft/language-server-protocol#967]
I am not seeing anywhere that the `TextDocumentSyncKind` is negotiated between the client and the server. It looks like the server simply announces which one it supports and that any client must support all three. Is that correct?

**Comment by dbaeumer** [comment]
Yes, this is correct. Reason is that this was in the first version of the spec which didn't have any capability support.

**Comment by kjeremy** [comment]
Thanks! It may be worth explicitly stating that in the docs.
