### ISSUE TITLE
VersionedTextDocumentIdentifier version=null behavior

### ISSUE THREAD

**Issue by dantleech** [microsoft/language-server-protocol#969]
Hi,

https://microsoft.github.io/language-server-protocol/specification#versionedTextDocumentIdentifier

> If a versioned text document identifier
> is sent from the server to the client and the file is not open in the editor
> (the server has not received an open notification before) the server can send
> `null` to indicate that the version is known and the content on disk is the
> master (as speced with document content ownership).

Is there a typo here? should it be `... that the version is not known ...`

Is the implication that the server should reload from the disk, or that the incoming update should be authoritative?

**Comment by dantleech** [comment]
Ah no makes sense, rubber duck ...

**Comment by dantleech** [comment]
Saying that - what should the behavior of the _server_ be if the client sends `null`? (assuming that the client is authoritative in that case)

**Comment by dbaeumer** [comment]
@dantleech in which scenario?

**Comment by dantleech** [comment]
no particular scenario that I can think of - but it's a nullable field so the client could send it, and the server should handle that in some way.

**Comment by dbaeumer** [comment]
The client does send it on open and change events.
