### ISSUE TITLE
Semantic Highlighting API token edit seems to be needlessly complex

### ISSUE THREAD

**Issue by etc0de** [microsoft/language-server-protocol#979]
(I made this ticket to elaborate on my point in [my comment here](https://github.com/microsoft/language-server-protocol/issues/18#issuecomment-619946698) and to allow more discussion)

Currently, the semantic highlighting API appears to specify this mechanism for token editing:

```
/**
		 * A file can contain many tokens, perhaps even hundreds of thousands of tokens. Therefore, to improve
		 * the memory consumption around describing semantic tokens, we have decided to avoid allocating an object
		 * for each token and we represent tokens from a file as an array of integers. Furthermore, the position
		 * of each token is expressed relative to the token before it because most tokens remain stable relative to
		 * each other when edits are made in a file.
		 *
          	 * Here is an example for encoding a file with 3 tokens in a uint32 array:
		 * ```
		 *    { line: 2, startChar:  5, length: 3, tokenType: "properties", tokenModifiers: ["private", "static"] },
		 *    { line: 2, startChar: 10, length: 4, tokenType: "types",      tokenModifiers: [] },
		 *    { line: 5, startChar:  2, length: 7, tokenType: "classes",    tokenModifiers: [] }
**** LEFT OUT VERY OVER THE TOP ENCODING SPEC HERE ***
		 *    // 1st token,  2nd token,  3rd token
		 *    [  2,5,3,0,3,  0,5,4,1,0,  3,2,7,2,0 ]
		 *     It is possible to express these new tokens in terms of an edit applied to the previous tokens:
		 *    [  2,5,3,0,3,  0,5,4,1,0,  3,2,7,2,0 ] // old tokens
		 *    [  3,5,3,0,3,  0,5,4,1,0,  3,2,7,2,0 ] // new tokens
		 *
		 *    edit: { start:  0, deleteCount: 1, data: [3] } // replace integer at offset 0 with 3
```
I think this design looks unnecessarily overcomplicated.

I would suggest something like the following instead:

**1. Specifying edits in simple ranges:** I would propose this edit event to describe the same operation as given as example above:

`{rangeStart: 0, rangeLen: 3, property: "line", valueShift: 1}` (to move tokens 0,1,2 down by one line)

In general, `valueShift` would be relative(!) numeric value applied to the given "line" property for every token in the range. I also suggest a `valueSet` which applies an absolute value, and also allows strings to e.g. change the "tokenType" of a range in bulk.

**2. Remove the integer encoding from the spec.**

I am suggesting this because I just don't understand why it is currently spec'ed out this way. I find this reasoning particularly a bit odd: `A file can contain many tokens, perhaps even hundreds of thousands of tokens. Therefore, to improve the memory consumption around describing semantic tokens, we have decided to avoid allocating an object for each token ` - it's nice VS Code does that, but why does it have to be used for the edit ranges in that way? It feels to me like it should remain an implementation detail to VS Code, not something that leaks into the protocol like this.

**Comment by dbaeumer** [comment]
1.) the advantage (and that is why we went down that path after trying quite some other formats) of the current delta encoding is that the diff can be computed by taking two sematic token number arrays and simply creating a number diff. There is no need that that algorithm understand that the number are actually encode anything. The idea is also that if we need to do comparable thing in the future we will use the same number diffing. 

2.) it is a payload problem. The JSON with property names and strings for semantic tokens and modifiers can be very big for large files. It also produces quite some GC garbage on the client side. Having a builder that does that on the server side seemed relatively easy.

**Comment by etc0de** [comment]
@dbaeumer interesting points, thanks for responding so quickly!

Regarding 1, it sounds a bit nebulous. Is this just some anticipation for the future? It seems like this alone may not be enough to make it worth adding, although I understand that is a consideration.

Regarding 2, but the edit payload would usually be rather low, right? (If you look at my syntax again, you can easily shift 1K+ tokens with a trivially short line if they all shift uniformly, which is usually the **only** way it happens if you type in the middle of the file.) And for new tokens all data would be streamed fully anyway, wouldn't it? Or is it giving any advantage for *new* tokens outside of edits?

If this really gives a transfer benefit then seeing some numbers would be nice. GC garbage sounds like it possibly, maybe(? BIG quesiton mark) might be worth assuming the implementing coders should if in doubt embed native code to optimize it, rather than make it a pain to use for everyone else who uses implementations in languages not suffering from this problem. I don't know, I'm just throwing that view out there, I know many will disagree. But if this is really worth optimizing in the protocol, numbers would be nice.

**Comment by dbaeumer** [comment]
I will close the issue. I think we had quite some discussions about this in other issues and parts of your concerns got addressed in the spec.
