### ISSUE TITLE
How to set cursor position for completion when snippet template is not supported

### ISSUE THREAD

**Issue by SLdragon** [microsoft/language-server-protocol#981]
Hi, team,
I am using LSP for auto-completion and diagnostic for the Visual Studio. however, from the "ClientCapabilities" it shows that Visual Studio do not support snippet template.

```
{
    "textDocument": {
        "completion": {
            "completionItem": {
                "snippetSupport": false,
            },
        },
...
}
```

I want to change the cursor position after user selecting the complete item, 

when snippet template is supported, I can use the templete as below:
```
"name": "$1"

```

However, snippet template is not supported in VS, are there any other ways to achieve this?

**Comment by rcjsuen** [comment]
> However, snippet template is not supported in VS, are there any other ways to achieve this?

@SLdragon Unfortunately, no. You don't have any options here.

**Comment by dbaeumer** [comment]
@rcjsuen thanks for your answer. It is correct.

I will close the issue as a question.
