### ISSUE TITLE
[website] use sticky table headers 

### ISSUE THREAD

**Issue by SKalt** [microsoft/language-server-protocol#985]
#### The problem
When I visit https://microsoft.github.io/language-server-protocol/implementors/servers/ to check the implementation table, I often have to scroll back up to the top of the table to check the headers.  If I'm checking an implementation low on the table, I'll see something like 

```
| ... 
+------------+--------+-------+------------+
| a language | a name | a url | a language |
+------------+--------+-------+------------+
| ...
```

which hides which column represents what.  Since there's no natural order to the list of features implemented, I'm unlikely to remember the column order.
#### Proposed solution
Use a `position: sticky` header on the `<thead>`s of the large tables.

Similar to https://github.com/langserver/langserver.github.io/issues/160.

**Comment by dbaeumer** [comment]
Good idea. However the document is markdown. Anyone want to provide a PR for this?

**Comment by SKalt** [comment]
I should be able to get to the fix within a week.  It looks like the place to add scss/css would be https://github.com/microsoft/language-server-protocol/blob/gh-pages/_layouts/implementors.html or https://github.com/microsoft/language-server-protocol/blob/gh-pages/css/main.scss

**Comment by dbaeumer** [comment]
@SKalt thanks for locking into it. And yes, the places are correct.

**Comment by SKalt** [comment]
status update: I got the site to build in a docker container, then failed to get sticky headers to stick due to something in the bootstrap css, likely `.table-responsive`, something about the flex, or an `overflow: hidden` somewhere.

**Comment by dbaeumer** [comment]
Closing, PR merged
