### ISSUE TITLE
Header part specifics

### ISSUE THREAD

**Issue by daurnimator** [microsoft/language-server-protocol#986]
Reading https://microsoft.github.io/language-server-protocol/specifications/specification-current/#headerPart I instantly had a few questions:

  - Are header field names case sensitive?
  - Is exactly one space after the colon permitted? Is 0 allowed? If there is more than one is that considered part of the value?
  - Is any other whitespace permitted around the header field name?

**Comment by dbaeumer** [comment]
The semantic of the header fields are like in HTTP. See https://tools.ietf.org/html/rfc7230#section-3.2
