### ISSUE TITLE
DocumentOnTypeFormattingOptions doesn't extend WorkDoneProgressOptions

### ISSUE THREAD

**Issue by bubba** [microsoft/language-server-protocol#987]
In 3.15 and 3.16 of the specification, `DocumentOnTypeFormattingOptions` doesn't extend `WorkDoneProgressOptions`. I thought this was odd, since its counterparts `DocumentFormattingOptions` and `DocumentRangeFormattingOptions` also extend it. Is this an oversight?

**Comment by dbaeumer** [comment]
No, the reason behind this is that onType formatting should be super fast and hence should never require to report progress. TO indicate that it doesn't extend `WorkDoneProgressOptions`.

Closing the issue. Please ping if you disagree.
