### ISSUE TITLE
How to pass extra options from UI into a language service?

### ISSUE THREAD

**Issue by chengtie** [microsoft/language-server-protocol#990]
I'm building a web page using React. The web page (component `Playground`) contains a Monaco Editor, behind which there is a language server conforming to language server protocol. At the moment the editor provides especially the feature of formatting.

Here is `our-language-server.js`, it calls the `formatCode` function developed in OCaml and transformed to JavaScript. 

```
    import {TextEdit, Position} from 'vscode-languageserver-protocol'; 
    
    export class OurLanguageService {
        format (document, range, option) {
            let edits = [];
            edits.push(TextEdit.del(range));
            //@ts-ignore
            let t = formatCode(document.getText(), <parameters>);
            edits.push(TextEdit.insert(Position.create(0, 0), t));
            return edits;
        }
    }
```

In the react component `ResizableMonacoEditor`, we have for example:

```
    monaco.languages.register({
      id: LANGUAGE_ID,
      extensions: [],
      aliases: [],
      mimetypes: [],
    });
        
    const m2p = new MonacoToProtocolConverter();
    const p2m = new ProtocolToMonacoConverter();
    let ourLanguageService = new OurLanguageService();
    
    function createDocument (model) {
      return TextDocument.create(MODEL_URI, model.getModeId(), model.getVersionId(), model.getValue());
    }

    monaco.languages.registerDocumentRangeFormattingEditProvider(LANGUAGE_ID, {
      provideDocumentRangeFormattingEdits (model, range, options, token) {
        const document = createDocument(model);
        const edits = ourLanguageService.format(document, m2p.asRange(range), m2p.asFormattingOptions(options));
        return p2m.asTextEdits(edits)
      }
    });

    const monacoOurModel = monaco.editor.createModel(value, LANGUAGE_ID, MONACO_URI);

    class ResizableMonacoEditor extends React.Component {
    
      _handleEditorDidMount (editor, monaco) {
        this.editor = editor;
        this.editor.setModel(monacoOurModel);
        this.forceUpdate();
        this.handleResize();
    
        if (this.props.editorDidMount) {
          this.props.editorDidMount(editor, monaco);
        }
      }
    
      render () {
        let _handleEditorDidMount = this._handleEditorDidMount.bind(this)
        return <Suspense fallback={<div>Loading</div>}>
          <MonacoEditor {...this.props} editorDidMount={_handleEditorDidMount} />
        </Suspense>
      }
      ... ...
```

In React component `Playground`, we have 

```
    _handleEditorDidMount (editor, monaco) {
      this.editor = editor;
      this.formatAction = this.editor.getAction('editor.action.formatDocument');
    }
       
    runFormat () {
      clearTimeout(this.timeout);
    
      this.timeout = setTimeout(() => {
        this.editor.getModel().updateOptions({ ... ... })
        this.formatAction.run();
      }, 300);
    }
     
    inputChange (event) {
      let value = event.target.value;
      this.setState((s) => ({ code: value }));
      this.runFormat();
    }

     return (
       ... ...
       <ResizableMonacoEditor value={this.state.code} editorDidMount={_handleEditorDidMount} height="100%" options={monacoOptions} />
```

In the web page, users will be able to tune several parameters about the formatting of the code, for example `ribbonWidth`, which indicates the maximum number of non-indentation characters that should appear on a line; and `limitWidth`, which indicates the maximum number of characters that should appear on a line. I want to pass all these parameters via components and finally to `formatCode(document.getText(), <parameters>`, but I don't know how.

It seems that we could use [these options](https://microsoft.github.io/monaco-editor/api/classes/monaco.editor.textmodelresolvedoptions.html) to pass values, but none of them is equivalent to my `ribbonWidth` or `limitWidth`.

Does anyone have any idea?

**Comment by rcjsuen** [comment]
> In the web page, users will be able to tune several parameters about the formatting of the code, for example `ribbonWidth`, which indicates the maximum number of non-indentation characters that should appear on a line; and `limitWidth`, which indicates the maximum number of characters that should appear on a line.

@chengtie `ribbonWidth` and `limitWidth` are not defined in the [protocol](https://github.com/microsoft/language-server-protocol/blob/ebe54d8f3b62f2dce308b6c940aeb54c54886a0d/_specifications/specification-3-15.md) for `FormattingOptions`. You should not expect these options to be respected by a language server (I guess there are some out there that expects these options?). I presume you are okay with this and that the OCaml language server supports these options...?

> I want to pass all these parameters via components and finally to `formatCode(document.getText(), <parameters>`, but I don't know how.

This sounds more like a generic question related to React and/or the Monaco Editor than the LSP.

**Comment by dbaeumer** [comment]
@rcjsuen is correct. The LSP only defines formatting options that are language independent. Language specific formatting options can be passed but are subject to the client and server.

**Comment by dbaeumer** [comment]
Objections to close the issue?

**Comment by chengtie** [comment]
If you know, please give me some hints about how "language specific formatting options can be passed"...

**Comment by kdvolder** [comment]
@chengtie Not 100% sure what you need/want, but I think probably you should use the 'configuration' pieces of the protocol.

Either this: (older and somewhat deprecated)
https://microsoft.github.io/language-server-protocol/specifications/specification-current/#workspace_didChangeConfiguration

Or this: (intended to replace the older part of the protocol)

https://microsoft.github.io/language-server-protocol/specifications/specification-current/#workspace_configuration

**Comment by dbaeumer** [comment]
@chengtie I answered on the issue you created in the vscoe-languageserver-node repository

**Comment by dbaeumer** [comment]
@kdvolder thanks for the pointers !

Another one is: `[key: string]: boolean | number | string;` here: https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_formatting
