### ISSUE TITLE
Diagnostic Range Update

### ISSUE THREAD

**Issue by afonsojramos** [microsoft/language-server-protocol#993]
While developing an extension using this protocol, I came up with some issues with Diagnostics and CodeActions. Some have been fixed, others are still a very open issue, namely the Diagnostics update.

Initially, I was sending one diagnostic at a time, but then it only showed the last one, therefore I started keeping a Map of Diagnostic Arrays per Document and such issue was fixed.

Now the problem that I face is if the user makes changes to the file after I have provided the diagnostics. Is there a way for me to easily update the diagnostics range?

**Comment by rcjsuen** [comment]
> Now the problem that I face is if the user makes changes to the file after I have provided the diagnostics. Is there a way for me to easily update the diagnostics range?

@afonsojramos You can't update individual diagnostics. You always send the whole set of diagnostics that pertain to a URI.

**Comment by afonsojramos** [comment]
Yeah, I've come to that conclusion, which is why I'm using the Diagnostic Array Map. 

How would I update the ranges of all the diagnostics based on changes by the user without recalculating them from scratch (as this is heavy on resources process)

**Comment by dbaeumer** [comment]
You can't just update the ranges since diagnostics have no identity. This is how the protocol is defined today.

**Comment by afonsojramos** [comment]
Okay, it seems that updating the ranges is not the best option in that case. 

How should I tackle the problem then @dbaeumer @rcjsuen ? The problem that I am facing is that, if the user updates the file and the text segment in question changes place, the diagnostic appears in the same location, even though the text segment it belongs to is no longer there.

**Comment by rcjsuen** [comment]
> Bear in mind that I have a Diagnostic Array saved in the extension which I can update and then send again to the client.

If you offset your diagnostics based on what the user typed and send it back to the client, what happens?

**Comment by afonsojramos** [comment]
Well, for the past day I have been trying to implement such thing, but even though (on verbose mode) the client is sending the message `Sending notification 'textDocument/didChange'.`, it is not triggering the function `connection.onDidChangeTextDocument` on the server.

**Comment by afonsojramos** [comment]
@rcjsuen @dbaeumer Just discovered that neither `connection.onDidChangeTextDocument`, `connection.onDidCloseTextDocument`, nor `connection.onDidOpenTextDocument` are being run when a notification is sent. Do you have any idea on why this might be happening? `connection.onCodeAction`, `connection.onDidChangeConfiguration` and `connection.onInitialize` are all working!

**Comment by rcjsuen** [comment]
@afonsojramos Please open a ticket in the relevant LSP client/server library that you are using. I assume you are using [microsoft/vscode-languageserver-node](https://github.com/microsoft/vscode-languageserver-node) but I could be wrong.

**Comment by dbaeumer** [comment]
I commented on the corresponding issues in the other repositories.
