### ISSUE TITLE
client->server request: matching brace

### ISSUE THREAD

**Issue by matklad** [microsoft/language-server-protocol#999]
Another request from rust-analyzer

## Matching Brace

**Server Capability:** `{ "matchingBrace": boolean }`

This request is send from client to server to handle "Matching Brace" editor action.

**Method:** `experimental/matchingBrace`

**Request:**

```typescript
interface MatchingBraceParams {
    textDocument: TextDocumentIdentifier,
    /// Position for each cursor
    positions: Position[],
}
```

**Response:**

```typescript
Position[]
```

### Example

```rust
fn main() {
    let x: Vec<()>/*cursor here*/ = vec![]
}
```

`experimental/matchingBrace` yields the position of `<`.
In many cases, matching braces can be handled by the editor.
However, some cases (like disambiguating between generics and comparison operations) need a real parser.
Moreover, it would be cool if editors didn't need to implement even basic language parsing

### Unresolved Question

* Should we return a a nested brace structure, to allow paredit-like actions of jump *out* of the current brace pair?
  This is how `SelectionRange` request works.
* Alternatively, should we perhaps flag certain `SelectionRange`s as being brace pairs?

**Comment by matklad** [comment]
This basically documents what rust-analyzer is doing today, but now I lean towards the last alternative for the general protocol -- just stuffing info about braces into `SelectionRange` request.

**Comment by dbaeumer** [comment]
@jrieken FYI.

**Comment by dbaeumer** [comment]
Dups #672.
